### ISSUE TITLE
Option to sign into other domain

### ISSUE THREAD

**Issue by tomassommar** [raelgc/scudcloud#101]
Upon starting ScudCloud for the first time, and mistakenly misspelling the slack domain you want to join into, there seem to be no option to sign into another domain. This renders ScudCloud unusable. It would be nice with an option to sign into other domain.

**Comment by raelgc** [comment]
Hi @tomassommar, thank you for reporting this issue.

You can change the default domain deleting or editing `~/.config/scudcloud/scudcloud.cfg`.

And if you want multiple domains, you can open menu `File` > `Sign in To Another Team`.

**Comment by tomassommar** [comment]
Thanks!
