### ISSUE TITLE
Working behind a proxy

### ISSUE THREAD

**Issue by fjmartinez** [raelgc/scudcloud#102]
Would be possible the option to configure a proxy?
I'm using Ubuntu 14.04 with unity, maybe the qt libs not working fine with the environments configurations vars?
The screen holds in white waiting a connection or something.

**Comment by Lauxtermann** [comment]
Install proxychains (sudo apt-get install)

Edit /etc/proxychains.conf (tab separated values)
[ProxyList]
http    proxy-ip    8080    domain\username   password
https  proxy-ip    8080    domain\username   password

Edit: /usr/share/applications

#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Categories=Network;Chat;
Name=ScudCloud
Comment=ScudCloud is an open-source client for Slack
Keywords=slack;chat;instant-messaging;collaboration;
Exec=proxychains /opt/scudcloud/scudcloud 
Icon=/home/username/Documents/Icons/Slack.png

execution uses proxychains to open a connection!

Goodluck!

**Comment by raelgc** [comment]
Please, see #115.
