### ISSUE TITLE
Zoom not preserved across sessions for multiple Slacks

### ISSUE THREAD

**Issue by alehandrof** [raelgc/scudcloud#103]
I have two Slacks open. The zoom setting is preserved for the 1st one, but it occasionally resets (not sure what triggers it) for the 2nd one.

**Comment by raelgc** [comment]
Hi @alehandrof, thanks for reporting this issue!

Are you on Ubuntu with Unity 14.04?

**Comment by alehandrof** [comment]
Yes; sorry for not being more precise.

**Comment by raelgc** [comment]
No problem, if not `precise` (12.04), at least you're `trusty` :P

**Comment by alehandrof** [comment]
But probably not `wily` :)

**Comment by raelgc** [comment]
Hope you're not pressing `Ctrl`+`0` while trying to switch between teams. This will reset the zoom :)

**Comment by alehandrof** [comment]
Nope. I had a look again. I can replicate the behavior by exiting the app and opening it again. At which point, the 2nd Slack has its zoom level reset. I use "Close to tray", but I here mean exiting the app fully.

**Comment by michaelherold** [comment]
So it sounds like you'd like zoom level to persist between two sessions? i.e. that it should be persisted to the configuration?

**Comment by raelgc** [comment]
@michaelherold It's persisted. But I think the second team is not receiving the default zoom level from config.

**Comment by alehandrof** [comment]
Yes, @raelgc has an accurate description of what's happening now. Sorry for the shoddy original issue.

**Comment by raelgc** [comment]
@alehandrof I just published the fix! Please, update and upgrade!

**Comment by alehandrof** [comment]
Thanks @raelgc for the incredibly fast fix -- to say nothing of the puns :)
