### ISSUE TITLE
Trying to run on Fedora, getting a useless empty window

### ISSUE THREAD

**Issue by syskill** [raelgc/scudcloud#105]
I'm trying to run scudcloud on my Fedora 20 laptop. I have the python3-PyQt4 and qtwebkit packages installed. When I run scudcloud, this thing appears:
![screenshot-scudcloud](https://cloud.githubusercontent.com/assets/93612/7595313/4b81ae78-f8b4-11e4-8b09-8deb255ff045.png)

Under the file menu I see items called "Preferences" and "Sign in to Another Team" that I suspect could be useful, but they are grayed out.

AFAICT the only thing that is displayed or logged at all is an error message in the terminal where I ran it: [**ETA:** same behavior when running with `--debug=True`]

```
thinkpad:~$ scudcloud --debug=True
ERROR:root:Could not find any typelib for Unity
loaded the Generic plugin 
```

Of course I'd expect a message like this while running on Fedora. It doesn't sound like a fatal error. Is it?

**Comment by syskill** [comment]
Update: I installed the libunity package from [here](https://launchpad.net/libunity). That changed the output in the terminal but did not restore any of scudcloud's functionality:

```
thinkpad:~$ scudcloud
loaded the Generic plugin 
```

**Comment by raelgc** [comment]
@syskill Which qtwebkit version? Additionally, maybe you can try install [python3-gobject](https://apps.fedoraproject.org/packages/python3-gobject).

**Comment by syskill** [comment]
@raelgc Here are the installed packages:
python3-3.4.1-16.fc21.x86_64
python3-PyQt4-4.11.3-1.fc21.x86_64
python3-gobject-3.14.0-1.fc21.x86_64
qt-4.8.6-28.fc21.x86_64
qtwebkit-2.3.4-6.fc21.x86_64

I upgraded to Fedora 21 last night, partly in hope of resolving this issue and partly because it was long overdue anyway. No change in scudcloud's behavior.

**Comment by syskill** [comment]
@raelgc Any other suggestions? I'd appreciate if you could tell me how I might get a useful error message -- anything other than a completely blank window would probably help us track down the problem.

**Comment by raelgc** [comment]
@syskill you can try start with: `scudcloud --debug=True` - this will enable the web Console.

Then you can right click and select `Inspect element`. Then, go to `Console` and check if any error (in red) is displayed.

Anyway, I'll try download and install Fedora in a VM to help on that!

**Comment by syskill** [comment]
@raelgc Aha, finally some useful information:
![screenshot-web inspector -](https://cloud.githubusercontent.com/assets/93612/7659956/f5b1f072-fb13-11e4-93ea-5840447836b4.png)

I realized that I didn't have the python3-pyOpenSSL package installed, so I installed that (version 0.13.1). However, that error message persists.

My guess is that a deprecated version of SSL is being used for some reason. I'll run a few more tests...

**Comment by syskill** [comment]
Update: I tried adding this to the __init__ method of class ScudCloud:

``` python
        sslcfg = QSslConfiguration.defaultConfiguration()
        sslcfg.setProtocol(QSsl.TlsV1)
        QSslConfiguration.setDefaultConfiguration(sslcfg)
```

Still getting the same error.

**Comment by syskill** [comment]
Wait, how'd this get closed???

**Comment by syskill** [comment]
Well, this is awkward... the problem turned out to be a stray certificate in my otherwise empty /etc/pki/tls/certs directory, which I had configured as trusted to work out a client's issue several months ago. While that cert was there, qtwebkit would fail to connect to any HTTPS URL. Now that it's gone everything works fine.

**Comment by raelgc** [comment]
@syskill I'm very glad you got it working!
Keep an eye on #113 issue too :)

**Comment by RobertAtomic** [comment]
I'm having the same issue in CentOS 6.5 .  I don't have any extra certs or anything unusual on /etc/pki though.  Any suggestions?

**Comment by moonwolf-github** [comment]
@RobertAtomic where did you get python3 for CentOS6 from?
