### ISSUE TITLE
No tray icon Ubuntu 15.04

### ISSUE THREAD

**Issue by nazar-pc** [raelgc/scudcloud#106]
Ubuntu 15.04 x64, works fine, but no tray icon.
When choosing "Close to tray" and closing I can't use it until I kill it and restart.

**Comment by raelgc** [comment]
Hi @nazar-pc, thanks for reporting this issue!

Can you, please, run scudcloud from the command line and post the output?

**Comment by nazar-pc** [comment]
```
nazar-pc@nazar-pc ~> scudcloud 
NOT SANDBOXED
[fresh] [warning] ppb_var_var_to_utf8, 'var' is not a string, (0)
[fresh  3351] not implemented: PPB_OpenGLES2DrawBuffers(Dev);1.0
[fresh  3351] [PPB] {fake} ppb_video_capture_enumerate_devices
[fresh  3351] [PPB] {zilch} ppb_network_monitor_update_network_list
[fresh  3351] [PPB] {zilch} ppb_flash_set_instance_always_on_top instance=10, on_top=1
[fresh  3351] [PPB] {fake} ppb_video_capture_close
SpellCheck: Language = "uk_UA" 
```

**Comment by raelgc** [comment]
Until this point, everything ok. And when you close to tray (and the app freezes), anything different?

**Comment by nazar-pc** [comment]
I'm not sure whether it freezes, likely it works fine, but I can't reach it because there is no tray icon.
When I'm opening new instance it reasonable says "The program is already running", but I'd prefer to open existing instance at this point instead.

**Comment by sudhirkhanger** [comment]
There is no system tray icon for KDE either. Plasma 5 uses KStatusNotifierItems for system tray.

**Comment by raelgc** [comment]
I'll download 15.04 to investigate all issues related to it.

**Comment by raelgc** [comment]
According [this blog](blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/), qt4 should works with tray icons in Plasma 5, just requiring the `sni-qt` package installed.

Can you guys try install `sni-qt` package, if available?

**Comment by raelgc** [comment]
If this works, I'll include `sni-qt` in the recommended packages to get installed by default when available in the Debian derived distro.

**Comment by nazar-pc** [comment]
I have `sni-qt:i386` already installed because it is used by Skype,
After installation `sni-qt` (which is amd64 version) icon appeared in tray and works as expected, so, yes, add it to dependencies, please.

**Comment by raelgc** [comment]
New package published with the fix. Please, update and upgrade.

**Comment by nazar-pc** [comment]
Thanks!
