### ISSUE TITLE
Spell check not marking misspelled words red

### ISSUE THREAD

**Issue by coliver** [raelgc/scudcloud#110]
Incorrectly spelled words not being marked red (I know it doesn't auto correct or suggest).

Linux Mint 17 Qiana x86_64 (Ubuntu 14.04 Compatible repository)
hunspell-en-us at version: 20070829-4ubuntu3

Other than running `sudo apt-get install hunspell-en-us` is there anything else I need to do to enable spell check?

Thanks

**Comment by raelgc** [comment]
Hi @coliver, thanks for reporting this issue.

Can you confirm if `libqtwebkit-qupzillaplugins - 1.0-1` package is installed?

**Comment by coliver** [comment]
It was not.  Installing that and rebooting did the trick. Thanks.
