### ISSUE TITLE
Gentoo: segmentation fault

### ISSUE THREAD

**Issue by rburcham** [raelgc/scudcloud#111]
I have performed a manual install and I believe the dependencies are in place.  However:

$ /opt/scudcloud/scudcloud
No bp log location saved, using default.
[000:000] Cpu: 6.58.9, x8, 2701Mhz, 16023MB
[000:000] Computer model: Not available
[000:000] Browser XEmbed support present: 1
[000:000] Browser toolkit is not Gtk2 (0).
[000:002] Using Xt toolkit
No bp log location saved, using default.
[000:000] Cpu: 6.58.9, x8, 2701Mhz, 16023MB
[000:000] Computer model: Not available
/opt/scudcloud/scudcloud:36: Warning: cannot register existing type 'GdkDisplayManager'
  sys.exit(app.exec_())
/opt/scudcloud/scudcloud:36: Warning: g_once_init_leave: assertion 'result != 0' failed
  sys.exit(app.exec_())
/opt/scudcloud/scudcloud:36: Warning: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
  sys.exit(app.exec_())
/opt/scudcloud/scudcloud:36: Warning: invalid (NULL) pointer instance
  sys.exit(app.exec_())
/opt/scudcloud/scudcloud:36: Warning: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
  sys.exit(app.exec_())
/opt/scudcloud/scudcloud:36: Warning: cannot register existing type 'GdkDisplay'
  sys.exit(app.exec_())
/opt/scudcloud/scudcloud:36: Warning: g_type_register_static: assertion 'parent_type > 0' failed
  sys.exit(app.exec_())
Segmentation fault

I'm going to guess there some sort of gtk2 dependency that remains unsatisfied?  What do?

**Comment by raelgc** [comment]
Hi @rburcham, thank you for reporting this issue!

After some investigation of similar issues, appears that the flash plugin can be the root cause of this.

Can you, please, edit `/opt/scudcloud/lib/wrapper.py` close to the line `27` and disable (inserting `#` at the beginning of the line) to make it like this?

```
#  QWebSettings.globalSettings().setAttribute(QWebSettings.PluginsEnabled, True)
```

Then restart ScudCloud.

**Comment by rburcham** [comment]
Well that has moved the ball as it were... I now get the login page and supply my credentials, and it appears to authenticate.  But the page never advances beyond the "Loading..." view.

Thanks, I'll search the other tix to see if this has been encountered before.  If not I'll open another.

**Comment by raelgc** [comment]
@rburcham I remember this issue in Ubuntu 12.04, exactly in #20, when we saw that the `libqtwebkit4` provide in Ubuntu 12.04 was old (update it to more recent version solved the problem).
