### ISSUE TITLE
Ubuntu: The program is already running.

### ISSUE THREAD

**Issue by roelvanduijnhoven** [raelgc/scudcloud#114]
Really love this client. Most painful downside is that I cannot easily open the client again.

Steps to reproduce:
1. Open ScudCloud app
2. Enable `close to gray`
3. Exit (keeps running in background)
4. Click Desktop shortcut (see screenshot)
5. Warning is shown (see screenshot).

![desktop-icon](https://cloud.githubusercontent.com/assets/91910/7678330/9d89fc0e-fd53-11e4-9ab7-5187a8fd4365.png)
![error](https://cloud.githubusercontent.com/assets/91910/7678292/5ec16ff2-fd53-11e4-9bb1-b7868841cee4.png)

**Comment by raelgc** [comment]
Hi @roelvanduijnhoven, thanks for reporting this issue.

When `Close to Tray` is enabled, there is `Close` (which closes the window but keep ScudCloud running in tray) and `Quit` (which will really finish the program execution),

Can you make sure you clicked in `Quit`? So, if program is still running even after `Quit`, yes, this is a bug.

**Comment by roelvanduijnhoven** [comment]
Oh sorry, I use `close` to close the application. _Not_ the `exit` menu item.

So I do want to keep the program running in the background (such that I can receive messages). However while the programming is running in the background I would like the desktop icon to reopen the app again. Instead I get the previously shown error.

**Comment by raelgc** [comment]
Right. So, for that improvement, we have #66.

**Comment by roelvanduijnhoven** [comment]
Sorry!
