### ISSUE TITLE
After authentication, page does not advance past the "Loading ..." view

### ISSUE THREAD

**Issue by rburcham** [raelgc/scudcloud#116]
![Uploading scudcloud-post-login.png…]()

I tried to attach an image but it seems to not want to.  I successfully have supplied my team domain and my credentials, and it seems to have authenticated through, however the view remains stuck on the first page after the authentication, with the "Loading ..." and the random pleasant expression e.g. "Always get plenty of sleep, if you can."

**Comment by rburcham** [comment]
libQtwebkit version is 

/usr/lib64/qt4/libQtWebKit.so.4.9.4

It appears I could upgrade to 5.4, I'll investigate this path.

**Comment by rburcham** [comment]
![scudcloud-post-login-debug](https://cloud.githubusercontent.com/assets/11066282/7687088/51291cd4-fd60-11e4-97ce-9b8f06c26620.png)

I've updated my qtwebkit, but I suspect the root cause might be different from ticket #20.  I have enabled debug with 

scudcloud --debug=True

and examined the javascript console, and there appears to be a "failed to load resource:  SSL handshake failed" error when retrieving a script library from mixpanel?  Again I have tried to attach a screen shot but in case it fails I have also attached it here:

http://i.imgur.com/gXSepP5.png

**Comment by rburcham** [comment]
I take it back, it's exactly the same as #20.

TypeError: 'undefined' is not a function (evaluating 'this._onElClick.bind(this)')

I can see from #20 that immerrr was able to backport qtwebkit4 for Ubuntu, but it isn't clear which revision of what package he landed on.  If I knew that I could apply proper masks and get portage to build a good PyQT and qtwebkit combo.

**Comment by raelgc** [comment]
@rburcham I think [this package](https://launchpad.net/ubuntu/trusty/+source/qtwebkit-source) was the source.

Additionally, I just checked the installed `libQtWebKit` here:

```
/usr/lib/x86_64-linux-gnu/libQtWebKit.so.4.10.2
```

**Comment by rburcham** [comment]
Okay the libQtWebKit.so.4.10.2 lib is not part of the stock QtWebKit packaging.  It appears to be packaged with the independent QtWebKit-2.3, which is available to Gentoo through the "qt" portage overlay.  I used layman to add the qt overlay:

# layman -a qt

And then built dev-qt/qtwebkit23.  When it merges it will have files that collide with the stock qtwebkit (obviously), so they must be bypassed, so:

# FEATURES="-collision-detect -protect-owned" emerge dev-qt/qtwebkit23 -v

After that the lib has been upgraded:

# ls -la /usr/lib64/qt4/libQtWebKit.so
lrwxrwxrwx 1 root root 21 May 20 08:55 /usr/lib64/qt4/libQtWebKit.so -> libQtWebKit.so.4.10.4

And scudcloud works great.  Thanks for the hints raelgc!

**Comment by raelgc** [comment]
@rburcham, I'm glad you solved this problem and documented the process here! For sure this will be helpful for others with the same problem!
