### ISSUE TITLE
Scudcloud hangs on bootup

### ISSUE THREAD

**Issue by dgikiller** [raelgc/scudcloud#119]
Hi,

I'm trying to get this program working on Sabayon/Gentoo and I created an ebuild following your README install procedure.
The program starts but freezes just after launch like this:
![Screen Freeze](http://i.imgur.com/u2RkQT1.png)

![Kill required](http://i.imgur.com/sxWG6C5.png)

Giving me only the following output even with --debug=True:

```
No bp log location saved, using default.
[000:000] Cpu: 6.60.3, x8, 3400Mhz, 15967MB
[000:001] Computer model: Not available
[000:001] Browser XEmbed support present: 1
[000:001] Browser toolkit is not Gtk2 (0).
[000:001] Using Xt toolkit
No bp log location saved, using default.
[000:000] Cpu: 6.60.3, x8, 3400Mhz, 15967MB
[000:000] Computer model: Not available

(python3:11549): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'

(python3:11549): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(python3:11549): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
[1]    11549 killed     scudcloud
```

This cause the gnome shell 3.14 crash sometimes.
Here you are my  installed packages:

```
dev-python/dbus-python-1.2.0-r1
dev-python/PyQt4-4.11.3
dev-lang/python-3.3.5-r1
dev-lang/python-3.4.3 
```

Anyway thank you for your work, hope we could fix this. :+1:

**Comment by raelgc** [comment]
Please, check #111

**Comment by dgikiller** [comment]
Yes that's exact the same issue, now the program hangs on login.
I have installed this libraries:  

```
dev-qt/qtwebkit-5.4.1
dev-qt/qtwebkit-4.8.6-r1
```

are those dependencies?
How could I fix that?

**Comment by raelgc** [comment]
Now, probably just some linking. A most complete solution is on #116.
