### ISSUE TITLE
Miminize on start

### ISSUE THREAD

**Issue by nazar-pc** [raelgc/scudcloud#122]
I'd like to put ScrudCloud into autostart, but there is no option to start it minimized to tray.

**Comment by raelgc** [comment]
@nazar-pc, I've implemented this option. Start with `scudcloud --minimized=True` to start ScudCloud minimized.

If it works as expected, please, close this issue.

Of course, first run `sudo apt-get update && sudo apt-get upgrade`.

**Comment by nazar-pc** [comment]
Thanks!
