### ISSUE TITLE
Share Snippet Shortcut (Shift+Ctrl+V) not working

### ISSUE THREAD

**Issue by mnl-zmr** [raelgc/scudcloud#124]
The shortcut for sharing a snippet is not working in scudcloud. 

When using the web ui from Chrome, you can quickly share a snippet with ctrl+shift+v (opens a new modal), when using scudcloud this is not working / nothing happens...

**Comment by raelgc** [comment]
Hi @der-tale, thanks for reporting this issue. I'll take a look during my weekend.

Reminder to myself: maybe this is related to the multi team switcher shortcuts interception.

**Comment by raelgc** [comment]
Fix published in Ubuntu repos.
