### ISSUE TITLE
Cannot access preferences

### ISSUE THREAD

**Issue by WolfangAukang** [raelgc/scudcloud#125]
Hello,

From a Manjaro (Arch-based distro) with XFCE 4.12, I cannot access the Preferences. They can't be selected (the option text is greyed).

Using Xubuntu with the XFCE 4.10 I can access it without any problems.

**Comment by michaelherold** [comment]
This occurs for me initially upon loading scudcloud, but as soon as I click around in the app (change a channel or interact with a timeline) Preferences becomes available. @WolfangAukang is it still disabled for you if you change the active channel?

**Comment by WolfangAukang** [comment]
@michaelherold  Strangely, now I turned on the computer (with Manjaro) and it worked just when I opened it. And the notifications are working (they weren't working before).

In case the problem repeats, I will try it again.

**Comment by raelgc** [comment]
`Preferences` (and other account entries) are enabled only when the Slack JavaScript receives the connection signal.

**Comment by raelgc** [comment]
Please, upgrade and test. Re-open the issue if not fixed.
