### ISSUE TITLE
Feature Request: Support mouse forward/back navigation

### ISSUE THREAD

**Issue by Aaron3** [raelgc/scudcloud#128]
On a many buttoned mouse in a browser, you usually have 2 buttons that work with browsers as forward and back (emulating Alt+[left/right arrow] keys). When managing a lot of chats or switching between rooms to grab a link, then back to another chat, these buttons are extremely helpful.

These are usually buttons 8 (back) and 9 (forward).

(Supporting  Alt+[left/right arrow] keys would also be nice.)

**Comment by raelgc** [comment]
Hi @Aaron3, thanks for reporting this.

One question: enable `Alt`+`left arrow` and `Alt`+`right arrow` will be enough?

**Comment by Aaron3** [comment]
But, fancy mouse buttons? :sob:

**Comment by raelgc** [comment]
Just to learn more about what you need: Is this directly supported by browsers? Are we talking about page navigation back and forward? Because they're not that much useful in Slack.

**Comment by Aaron3** [comment]
Yes it is. All browsers support it. And yes, it is page navigation back and forth. 

When moving between a lot of chat rooms with simultaneous chats, it is extremely useful.

**Comment by raelgc** [comment]
Aaron, in a first moment, what comes to my mind is: if you press back and forward in Slack, you'll get previous and next pages in browser history, not switch between rooms.

Or Slack, in browser, work differently? I mean, if you press back, instead of get previous browser history, you'll switch between Slack channels?

Sorry to ask so many details, I'm just trying to understand to implement this.

**Comment by Aaron3** [comment]
Yes, when using it in the browser it navigates between channels.

**Comment by raelgc** [comment]
@Aaron3 I took a look in Slack documentation: the shortcut to switch channels is `Alt`+`Up arrow` or `Alt`+`Down arrow`, and they works in ScudCloud.

Not related to Navigation History shortcuts ( `Alt`+`Left arrow` or `Alt`+`Right arrow`).

**Comment by Aaron3** [comment]
Alt+left/right was just explaining how the mouse buttons work in a browser.
Mouse navigation is the issue not keyboard.

**Comment by raelgc** [comment]
Hi @Aaron3, sorry for the late response. I was trying catch up with some major issues.

Back to this... and sorry to ask you again: you need that buttons 8 and 9 from your mouse browse between signed teams, is that?

**Comment by thepaul** [comment]
For what it's worth, Slack does explicitly support alt-leftarrow and alt-rightarrow as navigating back and forth in the history of visited channels, and not just as browser navigation. It works that way in the mac desktop app, for example, and is listed on https://slack.zendesk.com/hc/en-us/articles/201374536-Slack-keyboard-shortcuts

**Comment by raelgc** [comment]
Thank you, @thepaul

**Comment by kurtwheeler** [comment]
Was this closed as a Won't Fix? This is something that regularly bugs me.

**Comment by raelgc** [comment]
Hi @kurtwheeler and thanks for giving your feedback on this.

Can you tell me which keys are returned by your mouse? Button 8 and 9 for up/down?

**Comment by kurtwheeler** [comment]
The forward mouse button returns Button 9 and backwards mouse button returns Button 8.

**Comment by raelgc** [comment]
@kurtwheeler I'm taking a look on this now and sounds easy to fix.

But, just to check: 8 for history back and 9 for history forward? Why not to use this to switch between teams?

**Comment by kurtwheeler** [comment]
Well personally I don't ever switch teams, so that would be way less useful. However personal preferences aside I think those functions are appropriate for those buttons because that's what they default to in every other situation I've see them supported by default (other examples of this include Chrome, Firefox, and even file managers, both Ubuntu and windows). If I'm am trying a new app of any sort for the first time and I think it might support those buttons I expect their functions to be the most direct translation of "forwards" and "backwards" that makes sense for that app. Even if I did switch teams I'm not sure that I would think of moving "forwards" and "backwards" through my team list, that would be rather surprising behavior.

**Comment by raelgc** [comment]
Right, thanks for the @kurtwheeler!

**Comment by raelgc** [comment]
@kurtwheeler which distro are you using? You know where ScudCloud files are located? (In Ubuntu, at `/usr/lib/python3/dist-packages/scudcloud`).

I'm asking because I'll paste a code here and ask you to test it, as I don't have a mouse with those buttons.

**Comment by kurtwheeler** [comment]
Yep I'm using Ubuntu and I checked and that file is in fact there.

**Comment by raelgc** [comment]
@kurtwheeler Please:
1. open file `/usr/lib/python3/dist-packages/scudcloud/wrapper.py` using `sudo`
2. after method `loadStarted` (i.e, after line `110`) add this method:
   
   ``` python
       def mousePressEvent(self, event):
           if 8 == event.button():
               self.back()
           elif 9 == event.button():
               self.forward()
           super(Wrapper, self).mousePressEvent(event)
   ```
3. save and close file
4. restart ScudCloud
5. test mouse buttons `8` and `9`

**Comment by kurtwheeler** [comment]
Hey @raelgc. I tried what you suggested and the back button works great but the forward button doesn't do anything. Please let me know if there's anything else I can do to help test this. I really appreciate your efforts here!

**Comment by raelgc** [comment]
Thank you @kurtwheeler!

Let's, then, print the mouse button number to see if it's different then expected.

Please, change the method to:

``` python
    def mousePressEvent(self, event):
        print("Button {}".format(event.button()))
        if 8 == event.button():
            self.back()
        elif 9 == event.button():
            self.forward()
        super(Wrapper, self).mousePressEvent(event)
```

Then start ScudCloud from the command line with:

```
scudcloud &
```

**Comment by kurtwheeler** [comment]
Ah perfect, that worked well. Turns out my forward button is being recognized as 16. I'm not sure why that doesn't match the output of `xev`:

```
ButtonRelease event, serial 37, synthetic NO, window 0x6800001,
    root 0x9c, subw 0x6800002, time 2857496809, (28,35), root:(899,510),
    state 0x10, button 9, same_screen YES
```

but I tried changing forward to 16 and it worked for me!

**Comment by raelgc** [comment]
@kurtwheeler This is now published and available in latest ScudCloud. Can you run a `sudo apt-get update && sudo apt-get upgrade` to double check if it's working fine?

**Comment by kurtwheeler** [comment]
Yep, it's working great. Thanks so much for adding this!

**Comment by raelgc** [comment]
You're welcome! Thank you for your time requesting attention for this issue and helping with debug/testing.
