### ISSUE TITLE
Feature Request: Fullscreen support

### ISSUE THREAD

**Issue by theanine** [raelgc/scudcloud#129]
Fullscreen should hide the menu and title bar.

**Comment by raelgc** [comment]
Published in Ubuntu repositories. Please, update/upgrade and re-open this issue if not properly working.

**Comment by theanine** [comment]
The title bar is hidden properly, but the menu bar is not.  I'm on Ubuntu 14.04 LTS.

Also, the menu item says "Toogle" instead of "Toggle".

**Comment by raelgc** [comment]
@ComtriS I've updated one version today, and aside the typo (thank you!), it's working fine for me on Unity under 14.04 LTS. Are you using Unity too?

**Comment by theanine** [comment]
I'm using Gnome.

**Comment by raelgc** [comment]
Appears to be a bug in GTK3: https://bugs.launchpad.net/qemu/+bug/1294898

As Unity do not uses the default menu bar (and uses it in the window bar), this is not an issue.

I tried to just hides the menu bar, but when it's hidden, a lot of shortcuts stops to works, including the one to toggle the fullscreen mode.

And according the same bug, resize the menubar in GTK3 do not works as expected.

I'm open to any ideas here.

**Comment by theanine** [comment]
No ideas.  I can live with the menu bar for now.  Full screen works pretty well.  Thanks.
