### ISSUE TITLE
Feature request: taskbar flash notification

### ISSUE THREAD

**Issue by derekn** [raelgc/scudcloud#130]
It would be nice to have the window flash in the taskbar (i.e. Gnome panel) for new message notifications (a la Thunderbird)

**Comment by raelgc** [comment]
@derekn, thanks for reporting this feature request.

This feature is present only for Unity: it was for all, but in KDE it was stealing focus :(

**Comment by derekn** [comment]
could it be a preference option?

**Comment by raelgc** [comment]
Other possible solution can be avoid flash just under KDE/Cinnamon, etc. Or support only GTK environments.

Reminder to myself: flash was removed in #22

**Comment by raelgc** [comment]
Hi @derekn,

After some investigation in the code, I found that the flash notification is supported only under Unity (but probably can be extended to Gnome, and like mentioned, it was removed due Qt DE users reporting a but that flash was stealing focus).

Which DE are you using?

**Comment by derekn** [comment]
I'm using Cinnamon which is a fork of Gnome 3

**Comment by raelgc** [comment]
@derekn, can you test this please? Last time we've checked in Cinnamon, the flash was stealing focus (the reason why it was removed from non Unity environments).

Please, using `sudo` or `root`, edit `/opt/scudcloud/lib/launcher.py` and replace the content with the following:

``` python
from PyQt4.Qt import QApplication

class DummyLauncher:
    def __init__(self, parent):
        self.parent = parent
    def set_property(self, name, value):
        if "urgent" == name and True == value:
            QApplication.alert(self.parent)
```

Of course, exit and restart the app.

**Comment by coliver** [comment]
I know I'm not @derekn but I also want this feature.  Using the code you pasted on Cinnamon 2.2.16 it does indeed steal focus.

**Comment by raelgc** [comment]
Sounds like a bug on related Qt4 version or a Cinnamon issue. The description of this method (`QApplication.alert`) is:

> Causes an alert to be shown for widget if the window is not the active window. 
> 
> On Mac OS X, this works more at the application level and will cause the application icon to bounce in the dock.
> 
> On Windows, this causes the window's taskbar entry to flash for a time.
> 
>  On X11, this will cause the window to be marked as "demands attention", the window must not be hidden (i.e. not have hide() called on it, but be visible in some sort of way) in order for this to work.

The interesting is: only Cinnamon users reported it to steal focus.

**Comment by raelgc** [comment]
@kaleissin (or anyone here), are you running KDE5, right? Can you try that change that I suggested in Sep 10, and check if the app is flashed-but-without-steal-focus?

My idea is to enable this again in Qt environments other then Cinnamon.

**Comment by raelgc** [comment]
This was workarounded by #353 as Cinnamon will not work with taskbar flash notification.
