### ISSUE TITLE
Monospaced fonts appear as typical serif font

### ISSUE THREAD

**Issue by mgallagher** [raelgc/scudcloud#133]
This very well might be a problem on my end (Arch + GNOME), but here's what I get in scudcloud when I type out a code block or preformatted text:

![image](https://cloud.githubusercontent.com/assets/1775621/7947509/d0b00e3c-093a-11e5-9852-cb474d2b50ea.png)

And here it is Chromium:

![image](https://cloud.githubusercontent.com/assets/1775621/7947502/bd4daaac-093a-11e5-9833-f8a2e4c8fc2a.png)

Anything I should check for? It doesn't seem like it is using the default monospaced font I've selected in GNOME. 

Edit: Topic title updated.

**Comment by michaelherold** [comment]
Interestingly, mine uses sans-serif fonts:

![Image of Scudcloud](http://i.imgur.com/cRtN92U.png)

I have enabled the "use Lato 2.0" option in Preferences and have installed `ttf-lato` from the AUR.

That being said, by using `scudcloud --debug=True` I was able to determine that the font stack for monospaced fonts is `font-family: Monaco, Menlo, Consolas, 'Courier New', monospace;` which doesn't involve Lato. :smile:

I have both Consolas and Courier New installed (verified by running `fc-list` in a shell) so it seems like they should be picked up. I'm guessing QtWebView might use a different font cache or something. :frowning:

**Comment by raelgc** [comment]
Usually installing any package with `Courier New` (like `mscore-fonts` or `ttf-mscorefonts-installer`) solves the problem.

**Comment by raelgc** [comment]
@mgallagher Can you try the above suggestion and give us a feedback, please?

**Comment by pospi** [comment]
I have `ttf-mscorefonts-installer` installed and I get this font issue. Running Ubuntu 15.04 + Unity 7.3.2

**Comment by jprupp** [comment]
pospi, I have an idea what may be going on. Install `ttf-mscorefonts-installer` from the command line instead:

``` sh
sudo apt-get purge ttf-mscorefonts-installer
sudo apt-get install -y ttf-mscorefonts-installer
```

The installer requires the acceptance of some sort of agreement I promptly dismissed. You may not be able to accept such agreement from the graphical installation.

**Comment by pospi** [comment]
@xenog that was exactly it! I configured this workstation with a silent bootstrapping script and I guess that suppressed the licence dialog from the MS font installer. Thanks :D

**Comment by raelgc** [comment]
I'm glad you found the reason and now serif font is properly displayed! :)
