### ISSUE TITLE
keep connect does not works

### ISSUE THREAD

**Issue by throrin19** [raelgc/scudcloud#134]
Hi, If I exit the app and relanch it, my connection is closed but, in the last logIn, I check the keep connect button. It's normal ?

**Comment by throrin19** [comment]
bump

**Comment by raelgc** [comment]
Hi @throrin19 and sorry for my late response.

Where is this button? (Sorry, I still didn't saw it).

And, I think this option is to not disconnect after a timeout while away from the desktop (the default Slack behaviour). Not to keep connection after close the app (what is, in theory, impossible).

**Comment by throrin19** [comment]
Ok, It's a shame that it is impossible to keep the connection and information after leaving the application. The browser gets there yet though. thank you

**Comment by raelgc** [comment]
@throrin19 Are you talking about the `Keep me signed in` displayed during login?

**Comment by throrin19** [comment]
Yes, I talking about this checkbox. I can't see other `keep me signed in` in other place :(. It's not possible to store information in localstorage or other secure storage ?

**Comment by raelgc** [comment]
Sorry, in a first moment I was not realizing you were talking about this checkbox.

It must works and store you info at `~/.config/scudcloud/`. Can you close ScudCloud and try create that folder manually?

**Comment by throrin19** [comment]
THe folder was created and now it works fine. Thanks
