### ISSUE TITLE
User Styles/Scripts

### ISSUE THREAD

**Issue by aikar** [raelgc/scudcloud#141]
Styles mostly, but can we have a way to load user styles and scripts?

See: https://userstyles.org/styles/browse/slack

Would love to apply them to the ScudCloud client.

**Comment by epzee** [comment]
:+1:

**Comment by raelgc** [comment]
Indeed, I was checking this site, and all styles can be downloaded as a JS file too (GreaseMonkey script). Maybe it'll be not hard to allow a `js` folder in user configuration folder with customized JS scripts.

**Comment by aikar** [comment]
CSS is just as if not more important than JS. Please support both.
I'm currently using chrome as a 2nd app type version just so I can have a custom theme, but would love to not use chrome for it anymore.

**Comment by raelgc** [comment]
But @aikar, the site you've pointed offers the option to download the CSS theme as a JS file.

**Comment by LoLei** [comment]
I too would love this, since I'm used to using the dark theme in the web browser. :+1:

**Comment by rickisen** [comment]
I would also love this. Or at least a dark mode in preferences or something.

**Comment by mxxivcz** [comment]
@aikar It's actually quite easy to customize styles. There's an existing CSS file loaded into the UI. Its full path is `/opt/scudcloud/resources/resources.css` in my case. I use it to make fonts smaller in the left column.

Maybe it would be enough to have a similar CSS file in the user's config directory to solve this issue.

**Comment by raelgc** [comment]
While anyone can edit the `resources.css` file, I'm afraid we'll not implement an official way to change Slack themes.

The reason is: Slack has support for pre-built themes and few customizations. While it's limited, they have a reason for it: users can, accidentally, break the UI, removing or misplacing important actions/buttons/links.

I'd love more customization options too, like font size or a Night mode (indeed, I've opened a Slack support ticket for it, and they've said this will be available in the future).

So, the way to request a different style is to open a Slack ticket directly or hack `resources.css` with extreme caution (and use `dpkg-divert` on Ubuntu/Debian to preserve changes).

**Comment by vlatkoB** [comment]
Would be nice to be able to scale fonts. On 4K monitor fonts look really tiny. On Arch, CSS file is at:
`/usr/lib/python3.6/site-packages/scudcloud/resources/resources.css`

**Comment by raelgc** [comment]
@vlatkoB Use zoom: press <kbd>Ctrl Shift +</kbd>

**Comment by vlatkoB** [comment]
It doesn't work. Checked keyboard shortcuts. Maybe because I'm on Cinnamon.
I manually updated resources.css, but next update will probably overwrite it.

There would be no problem if ScudCloud could use font sizes defined in system.

**Comment by raelgc** [comment]
@vlatkoB Zoom works using the Qt shortcut for zoom, which is **not** <kbd>Ctrl +</kbd> but <kbd>Ctrl =</kbd>, which usually is fired in most of keyboards using <kbd>Ctrl Shift +</kbd> pressed at the same time.

Scudcloud uses fonts defined by Slack.

You can overwrite `resources.css` and keep changes using `dpkg-divert`. Let me know if you don't know how to use it.

**Comment by vlatkoB** [comment]
Qt zoom doesn't work with any of those keys.
`dpkg-divert` doesn't work on Arch, using pacman.
I tried to change Qt prefs in .config/Trolltech.conf, but no changes on ScudCloud. Also tried Qt CleanLooks theme.

I'll stick with resources.css patch for now. Have to change it on only two places.
Thanks for help.

**Comment by karlyeurl** [comment]
Hi. It's 2017, and Slack still does not have a proper night mode. Any chance of theming for ScudCloud? For now, I'd rather use the website in conjunction with the Dark Reader extension, but if ScudCloud made it easy enough to have an interface actually usable while coding, I'd use it.

**Comment by raelgc** [comment]
Indeed, @karlyeurl. I even asked them too, back in the earlier days.

I'll start in a simple way to support this: a file with custom CSS that will be loaded if present.

Then later, we can improve this, like offer an "official" night mode, based on daily time, etc.
