### ISSUE TITLE
Integration prompt inside chat → ScudCloud breaks

### ISSUE THREAD

**Issue by lalomartins** [raelgc/scudcloud#143]
So I'm in a new team where I hadn't so far configured Google Docs/Drive/etc integration. I pasted a link to a GDoc. Slack shows me the message offering to integrate. I clicked the link to allow it. That replaces the whole page with a Google authentication screen… and I couldn't get out of it.

(Might have been possible with alt-left, or using my keyboard or mouse's special back key/button, but I didn't remember to try. Might also have fixed itself if I did log in, but I couldn't try that because it offered me the wrong account, and the “sign in with a different account” link was non-responsive. And anyway, after doing all that again in the regular browser, I rather suspect it wouldn't, since, after authenticating, it dropped me in the integrations page, not back in the chat.)

**Comment by raelgc** [comment]
I suspect that ScudCloud is trying to browse to the URL due the Google Auth support. Can you, please, paste the file link URL? (Of course, you can replace any sensitive IDs in the URL).

**Comment by lalomartins** [comment]
Sorry, since I already authorized it, I have no idea how to reproduce it again :smile_cat: 

Ooh, maybe it would make sense for us to create a ScudCloud team in Slack? Too meta?

**Comment by lalomartins** [comment]
although we'd have to keep #81 in mind

**Comment by raelgc** [comment]
I like the idea of a Slack team, just thinking if that will not cause too much noise in the daily work.

About the issue: I'm adding Back and Forward browsing (with shortcuts), so probably this will avoid this kind of issue.

**Comment by lalomartins** [comment]
ok, moved the tangential discussion to its own ticket

**Comment by lalomartins** [comment]
![screenshot from 2015-06-18 16 16 45](https://cloud.githubusercontent.com/assets/1211455/8233244/77660334-15d5-11e5-9eed-972a3a5ccb0b.png)
The links are:
[Yes](https://accounts.google.com/o/oauth2/auth?response_type=code&redirect_uri=https%3A%2F%2Fslack.com%2Fservices%2Fauth%2Fgoogle&client_id=[removed]&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.readonly+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&access_type=offline&approval_prompt=force&state=[removed]&include_granted_scopes=true)
[Just this once](https://accounts.google.com/o/oauth2/auth?response_type=code&redirect_uri=https%3A%2F%2Fslack.com%2Fservices%2Fauth%2Fgoogle&client_id=[removed]&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.readonly+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&access_type=offline&approval_prompt=force&state=[removed]&include_granted_scopes=true)
“Not now” and “Never” aren't real links, they probably just trigger JS events.
