### ISSUE TITLE
ScudCloud is stuck on slack status page

### ISSUE THREAD

**Issue by sarovios** [raelgc/scudcloud#147]
I had some connection issues and I pressed to open the slack status (https://status.slack.com/) page from ScudCloud. From this time I am stuck in this page and I can't go back to the main page. I tried to re-open and re-install but nothing seems to work.

**Comment by raelgc** [comment]
Hi @sarovios, thank you for reporting this issue.

Well, probably if I add buttons to `Back` and `Forward` navigation, this will be avoided.

For now, please, remove this file: `~/.config/scudcloud/scudcloud.cfg`.

Dumb question: what to press in order to open the Slack status page?

**Comment by sarovios** [comment]
Thanks, config file removal worked. Back/Forward buttons should be fine to solve this issue.

**Comment by raelgc** [comment]
Published in Ubuntu repositories. Please, update/upgrade and re-open this issue if not properly working.
