### ISSUE TITLE
Idea: a ScudCloud team on Slack

### ISSUE THREAD

**Issue by lalomartins** [raelgc/scudcloud#149]
Idea raised in #143: create a Slack team for ScudCloud, for coordinating and mainly for testing.

To avoid noise, we should set some rules. Here's what I propose:
- Only post in _general_ if it's really important.
- On days you can't handle noise, leave _random_. Or, conversely, leave it when you join the team, and only join it when you have free time to chat.
- Posting to _random_ is not restricted, with the caveat that there might not be anyone in the forest to hear your tree fall.
- There will be a _testing_ channel which you should **not** be in unless you're in the process of testing something.
- You should only test things on _testing_ or on the private chat to slackbot. (Or, if you need test something more complex related to private chat, schedule it with someone else in advance.)

**Comment by michaelherold** [comment]
:+1:

**Comment by raelgc** [comment]
Please, send your emails to me: rael.gc@gmail.com
