### ISSUE TITLE
Add keyboard customizations (feature request)

### ISSUE THREAD

**Issue by svpcom** [raelgc/scudcloud#15]
Add option to swap Ctrl-Enter and Enter - i.e. send message by Ctrl-Enter and new line by Enter.

**Comment by raelgc** [comment]
Hi @svpcom, thank you for the feedback!

Indeed, you can create a multi-line message in Slack if you surround your message with ```

In fact, this sounds like a Slack internal feature, and while (in theory) I can try to change it, my idea is try to keep ScudCloud with a minimum interference in the Slack UI. I.e., keep the Slack UI as it is.

So, in a first moment, we should open this as a request for the Slack team itself before try to implement in ScudCloud.

So, please, create this Help Request: at ScudCloud, press F1, then click on `Send Us a Help Request`. 

Then let me know their answer.

**Comment by advancingu** [comment]
Shift+Enter lets me write multiline messages with Slack under Firefox. Wouldn't this work with Scudcloud if it's just a web view?

**Comment by raelgc** [comment]
Yes, it works in the same way.
