### ISSUE TITLE
Scudcloud crashes upon start

### ISSUE THREAD

**Issue by syphernl** [raelgc/scudcloud#155]
Scudcloud crashes during load, most likely due to the fact that Chrome's Pepperflash was updated:

```
NOT SANDBOXED
libva info: VA-API version 0.37.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_0_35
libva info: va_openDriver() returns 0
[ERROR:flash/platform/pepper/common/pep_process.cpp(19)] CHECK(g_process_type == PROCESS_TYPE_UNKNOWN) failed
[1]    4994 abort      scudcloud
```

Slack in Chrome works just fine though.

```
ii  scudcloud                                                   1.0-45                                     all          ScudCloud is a non official desktop client for Slack
```

Specs: Ubuntu 15.04 LTS amd64 with Cinnamon 2.6

**Comment by moritzheiber** [comment]
Same happens for me. Why does Scudcloud even need a flash plugin?

**Comment by raelgc** [comment]
@syphernl and @moritzheiber: thank you for reporting this issue.

Flash is required due embedded video playback, like Youtube, and the fact that Qt4 does not support HTML5 videos.

A proper way to solve this can be add a command line argument to disable plugins. Like `--plugins=False`.

**Comment by graywolf-theheathen** [comment]
Same issue here.

scudcloud --debug DEBUG
NOT SANDBOXED
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
[ERROR:flash/platform/pepper/common/pep_process.cpp(19)] CHECK(g_process_type == PROCESS_TYPE_UNKNOWN) failed
Aborted

**Comment by graywolf-theheathen** [comment]
Tried the plugins=false thing two ways and neither worked. Suggestions?

scudcloud --plugins=False
usage: scudcloud [-h] [--confdir dir] [--debug DEBUG] [--minimized MINIMIZED]
scudcloud: error: unrecognized arguments: --plugins=False

scudcloud --plugins FALSE
usage: scudcloud [-h] [--confdir dir] [--debug DEBUG] [--minimized MINIMIZED]
scudcloud: error: unrecognized arguments: --plugins FALSE

**Comment by raelgc** [comment]
@graywolf-theheathen I'm working to add this parameter now, ScudCloud still doesn't support it.

**Comment by graywolf-theheathen** [comment]
That sir is a good reason it didn't work, lol.

**Comment by raelgc** [comment]
God, python `ArgumentParser` just sucks... it says to support `bool`, but it doesn't properly. I'll need to add it as `no_plugins` to keep the arguments compatible with existing ones.

**Comment by ajithrn** [comment]
NOT SANDBOXED
[ERROR:flash/platform/pepper/common/pep_process.cpp(19)] CHECK(g_process_type == PROCESS_TYPE_UNKNOWN) failed

Got the same issue, elementary OS Freya

**Comment by graywolf-theheathen** [comment]
Added  --no_plugins NO_PLUGINS to my launcher and it is working now. Thank you sir. Any idea on if/when the flash issue will be resolved? If it can.

**Comment by moritzheiber** [comment]
:+1: Works for me now. Thanks!

**Comment by graywolf-theheathen** [comment]
Update;

Pepperflash just updated on my Linux Mint box. Scudcloud now runs with Plugins.

**Comment by raelgc** [comment]
Thank you for sharing this @graywolf-theheathen! :)
