### ISSUE TITLE
Doesn't keep my user and pass on a seccond slack account

### ISSUE THREAD

**Issue by ldimitroff** [raelgc/scudcloud#156]
I have two slack accounts, and I have both logged in the first time. Everytime I reboot my computer, the second account asks me for the user and password again.

**Comment by michaelherold** [comment]
Out of curiosity, did you check "remember me" on the second team?

**Comment by ldimitroff** [comment]
Yes, of course, on both accounts.

**Comment by oliverbienert** [comment]
It's the same with me.  I established my second account a couple of weeks later than the first. However, after every reboot, I have to login again into my second account. And yes, I've checked the 'Remember me' checkbox.

**Comment by m4gzus** [comment]
I have the same problem too, but I have single account logged in. And after reboot I have to login again.
'Remember me' checkbox is checked.

**Comment by raelgc** [comment]
This was fixed on #199 a month ago. If you're not using the latest version, please, update.

**Comment by oliverbienert** [comment]
Cool, thank you!

Seems to work perfectly.

Oliver
