### ISSUE TITLE
Caps Lock as Ctrl-L seems to cause highlighted text to become unhighlighted

### ISSUE THREAD

**Issue by solarce** [raelgc/scudcloud#159]
First, I am super happy for scudcloud, so thank you for all your hard work.

I am not sure if this is a scudcloud issue or an interaction with PyQT and my Cinnamon Desktop or what, but I wanted to file an issue to see what feedback you might have.

I  am running the latest stable release of scudcloud via AUR:

```
~ ys scudcloud
aur/scudcloud 1.0.36-1 [installed] (10)
```

I have Caps Lock remapped to Ctrl-L in Cinnamon and I find that when I highlight text in scudcloud with the mouse and then press Caps Lock is causes the highlighting to disappear. The same thing does not happen with the regular Ctrl-L and Ctrl-R keys though.

It's a little annoying because it doesn't happen in the other GUI apps I use regularly, but they are all GTK apps. scudcloud is the only QT one.

Any thoughts?

**Comment by raelgc** [comment]
Hi @solarce, thank you for reporting this.

QT and GTK uses different keybinding configs. A similar raised issue is #62.

I don't know how exactly to set the keybindings for QT in a GTK environment, so the only possible solutions is this SuperUser question: http://superuser.com/questions/171925/enable-emacs-like-keybindings-scheme-for-all-qt-applications

**Comment by raelgc** [comment]
@solarce I tested this in Slack in Firefox, and I can see the same behaviour. So, this is not related directly to ScudCloud.
