### ISSUE TITLE
Segmentation fault.

### ISSUE THREAD

**Issue by Gibol** [raelgc/scudcloud#161]
![zrzut ekranu z 2015-06-22 10 30 50](https://cloud.githubusercontent.com/assets/5168262/8278265/40bf0cc0-18ca-11e5-8404-8a8e0ab9e129.png)
![zrzut ekranu z 2015-06-22 10 32 32](https://cloud.githubusercontent.com/assets/5168262/8278266/40c5db04-18ca-11e5-8d58-c3f5d42f65e8.png)
![zrzut ekranu z 2015-06-22 10 32 56](https://cloud.githubusercontent.com/assets/5168262/8278268/40c784cc-18ca-11e5-9530-408dcad45f9b.png)
![zrzut ekranu z 2015-06-22 10 33 22](https://cloud.githubusercontent.com/assets/5168262/8278267/40c6ffac-18ca-11e5-955b-0c8380069338.png)

**Comment by raelgc** [comment]
Hi @Gibol, thank you for reporting this issue.

Can you tell me if this is related to #155?

**Comment by Gibol** [comment]
I don't think so.
It was just a random crash, i think it was in tray or i was on another
desktop when it happend.
It seems to have something to do with dbus (stack trace clearly shows where
that happend )

2015-06-22 14:01 GMT+02:00 Rael Gugelmin Cunha notifications@github.com:
