### ISSUE TITLE
High DPI support

### ISSUE THREAD

**Issue by larsnystrom** [raelgc/scudcloud#162]
Everything is tiny on a high resolution screen. It would be really nice if you could scale the UI somehow.

On Unity 7 you can get the default scaling factor with this script:

```
#!/bin/sh

command -v gsettings >/dev/null 2>&1 || { echo >&2 "gsettings not found."; exit 1; }

SCALING_FACTOR=`gsettings get org.gnome.desktop.interface scaling-factor | cut -c7-`
TEXT_SCALING_FACTOR=`gsettings get org.gnome.desktop.interface text-scaling-factor`

[ -z "$SCALING_FACTOR" ] && { echo >&2 "could not get scaling-factor."; exit 1; }
[ -z "$TEXT_SCALING_FACTOR" ] && { echo >&2 "could not get text-scaling-factor."; exit 1; }

FACTOR=`echo "$SCALING_FACTOR * $TEXT_SCALING_FACTOR" | bc -l`

echo -n "$FACTOR"
exit 0
```

I figured this out by trial and error, so it might be wrong, but it seems to be the way Unity calculates the scaling in Ubuntu 14.04.

**Comment by raelgc** [comment]
Hi @larsnystrom and thanks for reporting this issue.

As an alternative, ScudCloud offers zoom support. 

You can increase zoom pressing `Ctrl`+`+` (usually fired with `Ctrl`+`Shift`+`=`) and decrease with `Ctrl`+`-`. Reset it with `Ctrl`+`0`.
