### ISSUE TITLE
Keeps on prompting to enable desktop notifications

### ISSUE THREAD

**Issue by nafg** [raelgc/scudcloud#163]
Every so often a panel appears at the top of slack saying desktop notifications need to be reenabled.

**Comment by moonwolf-github** [comment]
With 1.0.46 (and earlier versions) it happens every time program starts. I'll check 1.0.48 in a minute.

**Comment by moonwolf-github** [comment]
Same for 1.0.48.

**Comment by FatCache** [comment]
Not sure which version I have as scudcloud --version isn't supported, but I'm having the same issue.

**Comment by mreq** [comment]
Same.

**Comment by soundslocke** [comment]
Also experiencing this issue here.

**Comment by stieg** [comment]
I am also seeing this too using top of tree 1.0.55

**Comment by raelgc** [comment]
This is a known issue, indeed, we discussed a lot in the past. Basically: Slack team will force a page reload, when they need all clients reloading their JavaScript changes.

ScudCloud do not pay attention to page reloads, only to URL changes.

I'm working on this, but trying to not break existing features.

Sorry, for now, we have only the workaround to click in another group/room to re-enable the notifications.

**Comment by stieg** [comment]
Alright.  Thanks for the update.  Keep us posted and let us know if there
is anything we could do to help.

On Mon, Aug 10, 2015 at 10:52 AM, Rael Gugelmin Cunha <
notifications@github.com> wrote:

> This is a known issue, indeed, we discussed a lot in the past. Basically:
> Slack team will force a page reload, when they need all clients reloading
> their JavaScript changes.
> 
> ScudCloud do not pay attention to page reloads, only to URL changes.
> 
> I'm working on this, but trying to not break existing features.
> 
> Sorry, for now, we have only the workaround to click in another group/room
> to re-enable the notifications.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/raelgc/scudcloud/issues/163#issuecomment-129524736.

## 

Andrew AV. Stiegmann

**Comment by raelgc** [comment]
If someone is still facing this issue, please re-open it.
