### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by moonwolf-github** [raelgc/scudcloud#164]
After upgrade to 1.0.48 i noticed notifications behave very strangely. Sound plays even when application has focus (when i'm talking with somebody on private). Second thing - icon on taskbar receiving number of unread messages and it keeps displaying it (can't test it further at the moment, don't know on what circumstances numbers disappear eventually, but it lasts some time).

**Comment by raelgc** [comment]
Hi @moonwolf-github, thanks for reporting this issue.

About the sound: sound is not handled by ScudCloud, it's played directly by Slack. Sometimes I can see a delay, but few occasions.

I'm trying a fix to try to make the count get updated more often. I did a different approach with notifications in 1.0.46 to make ScudCloud use less CPU.

**Comment by nargiza-sarkulova** [comment]
Hi @raelgc,
I can confirm I'm having the same issue with unread messages number: even after reading the message number doesn't disappear. It disappears after quite some time or if you switch channel/person. Don't remember in which version this behavior started but now I have the latest version (1.0.52) and it's still there. Very annoying indeed. I wouldn't mind using more CPU if there was quick fix actually.

**Comment by raelgc** [comment]
Hi @nargiza-sarkulova, yes, that due the change I did to use less CPU (I got a bunch of people complaining about this), and there is only one case where the notifications are still not properly decreasing: when you receives a direct message in the current channel.

I'll work in a simple fix, test it, and later deploy. Not sure if today, but it's my next task in ScudCloud.

**Comment by raelgc** [comment]
@nargiza-sarkulova and @moonwolf-github: the new fix is deployed. And it'll continue using low CPU :)

Sorry for the inconvenience!

**Comment by nargiza-sarkulova** [comment]
Seems to be working now :) Thank you for your hard work, I really appreciate your quick assistance @raelgc
