### ISSUE TITLE
Linux Mint Cinnamon - tray icon sometimes does not display

### ISSUE THREAD

**Issue by edmundcraske** [raelgc/scudcloud#169]
Sometimes, for a reason I can't establish, ScudCloud's tray icon does not display. Not sure if this is fundamentally a Linux Mint / Cinnamon bug or something else.

I've got ScudCloud configured to close to tray, and so there's no way of getting the window back when the tray icon has disappeared. If I try to launch ScudCloud from the Menu, it gives an error saying it's already running - is it possible to instead make it reopen the window for the existing instance? It would also be good if it could reinitialise the tray icon in the hope of making it visible again. Currently I have to go find the process and kill it and then restart it to get ScudCloud back.

**Comment by derekn** [comment]
This is an issue in Cinnamon. I experience it a lot with other apps, particularly Pidgin and Thunderbird.

**Comment by raelgc** [comment]
Fixed in #192
