### ISSUE TITLE
open ScudCloud when (double)-clicking on tray icon (feature request)

### ISSUE THREAD

**Issue by Shohou** [raelgc/scudcloud#17]
When I click (or double-click) on tray icon ScudCloud window should open. Now this happens when I right-click and choose Show, make this default action on simple click

**Comment by syphernl** [comment]
@Shohou What are you using on your desktop? 
I'm using Cinnamon (Ubuntu 14.10).

**Comment by Shohou** [comment]
I'm using LinuxMint 17.1 with Cinnamon, it's based on Ubuntu 14.04 I think

**Comment by syphernl** [comment]
Sounds like a Cinnamon issue, but perhaps others (e.g. Unity or Gnome-shell users) are experiencing the same. I've seen it before with other apps which needed a little tweaking also to get it to work fine in Cinnamon.

# 

Scroll would also be nice. Scroll up: show, Scroll down: hide.

**Comment by Shohou** [comment]
Thanks for implementing this so fast!

It's still not perfect. If ScudCloud window is open (in background) and some other window is in foreground clicking on tray icon closes ScudCloud instead of bringing it to foreground. I need to click twice to get it to foreground

**Comment by raelgc** [comment]
Please, update and test again. I think it's fixed now.

**Comment by Shohou** [comment]
Yep, works perfect. Thank you!

**Comment by amitz** [comment]
Is it possible this gone back to being broken? I'm using Mint 17.3 with Cinamon and a single click seems to just open the menu.

**Comment by toshe** [comment]
@amitz same behaviour with wingpanel on elementary os. Single click opens the menu. Double click doesn't open the window. Which version did you use? maybe we can backport this
