### ISSUE TITLE
Cannot sign into more than two accounts

### ISSUE THREAD

**Issue by davereid** [raelgc/scudcloud#170]
I added two Slack team accounts successfully, but when I went to use 'Sign in to Another Team', it just does nothing.

**Comment by davereid** [comment]
Hrm, this seemed to have resolved it today after the update.

**Comment by metadan** [comment]
I'm having this problem today. Installed fresh today. 14.04 fully updated/upgraded and installed as recommended on install guide with apt.

**Comment by trichner** [comment]
Can confirm, same problem. Ubuntu 14.04 LTS, installed from PPA.

I would post the version of scudcloud but I could not find it. The 'About' leads to the github repo, the commandline has no '-v' or '--version' option and the 'Help & Feedback' did absolutely nothing.
Even starting from the commandline never shows the version, did my eyes miss it somewhere in the UI?

**Comment by raelgc** [comment]
New version released with contributed fixes. Please, re-test.

**Comment by trichner** [comment]
Ok, did a quick smoke test. Seems to be fixed now. Thanks a lot :)

**Comment by davereid** [comment]
Going to close.
