### ISSUE TITLE
scudcloud doesn't show new messages

### ISSUE THREAD

**Issue by 0xd3adsh3ll** [raelgc/scudcloud#172]
Hello, I faced with problem, when scudcloud in tray and I get a new message but scudcloud doesn't show new messages I mean scudcloud doesn't highlights users which with new direct messages in main window. I have version 1.0-50 on linux mint cinnamon. 
P.S. When I use older version I have no problems.
Thanks.

**Comment by raelgc** [comment]
Fixed in #164
