### ISSUE TITLE
HiDPI Support

### ISSUE THREAD

**Issue by Nek-** [raelgc/scudcloud#173]
Hello,

Thank you for scudcloud, that's awesome :) . But I have an issue with my hidpi computer (my resolution is 4K):

![](https://sc-cdn.scaleengine.net/i/4bc0b9f4607ac5f441ddc84d85719fae2.png)

The app is not really readable.

Well, currently I have a dualscreen and so no problem for me as the second screen is only fullhd. But careful with this feature: the dpi should apply when the app is switched between screens...
(this behavior should be supported by Ubuntu as Chromium do it like a boss)

**Comment by aikikode** [comment]
Scudcloud has zoom support which can help for now: 'Ctrl +' and 'Ctrl -'.

**Comment by kaimast** [comment]
Ctrl + helps. But detecting the dpi should would be very helpful for me too.

**Comment by Nek-** [comment]
CTRL+ is broken. This is not an hidpi support at all.

**Comment by raelgc** [comment]
@Nek- It's not broken. Usually you need to press `Ctrl` `Shift` `=`, because `+` is `=` on Caps. And this will zoom in and out. While it's not a real HiDPI support, it helps.

**Comment by raelgc** [comment]
And, to try to help: Slack told me they released a beta Linux client. They're searching for beta testers. Maybe it has better HiDPI support: https://docs.google.com/forms/d/1uOlDiuT9XMEGijhXicsOasJv3Nxvt5Azvd9OIIS61Sk/viewform

**Comment by raelgc** [comment]
Just to make clear: there is no (official) support for HiDPI on Qt4. And people is still discussing about it on Qt5.

**Comment by Nek-** [comment]
IDK how but ubuntu fixed it for a while.

**Comment by raelgc** [comment]
@Nek- Thank you for the feedback! :)
