### ISSUE TITLE
spellcheck not working Mint 17.1 64-bit

### ISSUE THREAD

**Issue by zeeshanikram** [raelgc/scudcloud#174]
I have installed the application and also hunspell-en-us dictionary but my input box does not display any misspelled words, neither it highlights anything.

**Comment by rsyring** [comment]
Ditto on Ubuntu 14.04.

**Comment by rsyring** [comment]
related to #55 - tried the solution on #55 to install libqtwebkit-qupzillaplugins_1.0-1_amd64.deb but that doesn't seem to have resolved anything for me.

**Comment by rsyring** [comment]
I take the above comment back...after I restarted my machine, spelling highlights for misspelled words are now working.

**Comment by raelgc** [comment]
You're required to install these packages:
- `libqtwebkit-qupzillaplugins`
- the HunSpell dictionary for your language
- and `python3-hunspell` if you're using ScudCloud `1.0.68` and want to see suggestions in right click context.
