### ISSUE TITLE
Feature request: Clicking on tray icon should show/minimise scudcloud from/to the tray

### ISSUE THREAD

**Issue by DenisBY** [raelgc/scudcloud#176]
I mean if it's minimized to the tray, clicking once should show it and if I click again on the tray icon, scudcloud should be minimized to the tray again. Right/Left/Middle click, once/twice, whatever.

**Comment by rsyring** [comment]
I agree that the primary click (usually left) should show/hide by default.  Secondary click (right by default) should show the current menu for preferences, quit, etc.

**Comment by collinpeters** [comment]
+1

**Comment by triplepointfive** [comment]
+1

**Comment by binarysource** [comment]
+1

**Comment by grinderX19** [comment]
+1

**Comment by raelgc** [comment]
Just a friendly reminder that it's not possible under Unity (or other environments using the same notification scheme) run actions while clicking in the systray icon (it allows only display a menu).

**Comment by edmundcraske** [comment]
This works as expected in Linux Mint Cinnamon...
