### ISSUE TITLE
Notification issue on Fedora - url truncated

### ISSUE THREAD

**Issue by paoloantinori** [raelgc/scudcloud#178]
Hi, I have just spotted this issue on Fedora22

Someone posted this link in a room:

https://www.google.co.uk/search?q=famous&ie=utf-8&oe=utf-8&gws_rd=cr&ei=zjmeVbbDA8yxsAG2taTYDg#q=famous+traduzione

I have clicked on the Notification popup, integrated with the operating system, but I was sent to

https://www.google.co.uk/search?q=famo

something that suggests the url has been truncated in the notification and only that part has been used.

**Comment by raelgc** [comment]
Hi @paoloantinori, and sorry for the late response.

This was truncated by the system notification engine, not by ScudCloud.

I guess you're using Gnome 3, right? Because Unity do not allow links in the notifications :(
