### ISSUE TITLE
"python3" may not be the system python (with PyQt installed)

### ISSUE THREAD

**Issue by rsyring** [raelgc/scudcloud#180]
I'm a python dev and in my environment, "python3" from my path points to a python3.4 install that I have setup for my user.  In that case, scudcloud fails to start:

```
rsyring@loftex:~$ scudcloud 
Traceback (most recent call last):
  File "/usr/bin/scudcloud", line 6, in <module>
    from PyQt4 import QtGui
ImportError: cannot import name QtGui
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 20, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ImportError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/scudcloud", line 6, in <module>
    from PyQt4 import QtGui
ImportError: cannot import name QtGui
```

I have a workaround in place currently so it's not an issue for me.  But, is this something scudcloud wants to deal with as it moves forward?

**Comment by aikikode** [comment]
I don't think it's the app responsibility to detect 'real' system python if the user altered his system.
'python3' by default points to system python.

Anyway it should not be an issue when https://github.com/raelgc/scudcloud/issues/85 is resolved and this app is installed via setuptools.

**Comment by andresgaragiola** [comment]
I have the same problem. Can you share your workarround rsyring?

Regards

**Comment by rsyring** [comment]
@andresgaragiola I actually decided to let python3 point to the system python3 and I now use a command that modifies my paths when I want a terminal session with a custom python3.  

The other option would be to setup a bash script that adjusts paths and points `python3` to the system python3 and then start scud cloud from that script.

**Comment by moonwolf-github** [comment]
Another option is to use virtualenv, should do the trick.

**Comment by raelgc** [comment]
@rsyring If you can create that script and send a pull request, that would be awesome!

**Comment by rsyring** [comment]
@raelgc I'm sorry, I actually misspoke in my comment above. I actually just install the custom python version (3.4.x) into /opt and then symlink the bin as `python3.4`:

```
ls -lh /usr/local/bin/python*
lrwxrwxrwx 1 root root 27 Jul 16 11:38 /usr/local/bin/python3.4 -> /opt/python34/bin/python3.4
```

So, if I want the system python 3, then I just use `python3` binary.  If I want the custom built version, I know I have to use `python3.4` binary.

**Comment by rsyring** [comment]
pyenv is also an option: https://github.com/yyuu/pyenv

**Comment by raelgc** [comment]
Interesting, I was not aware of `pyenv`, thanks for sharing this @rsyring
