### ISSUE TITLE
Mousing over "reaction" emojis does not show contributing team members popup

### ISSUE THREAD

**Issue by thepaul** [raelgc/scudcloud#181]
Regarding the new feature as described at: https://slack.zendesk.com/hc/en-us/articles/206870317-Emoji-reactions

It mostly works just fine already in Scudcloud. The only shortcoming, as far as I can tell, is there isn't a way to see who attached each reaction emoji without going into the web client.

**Comment by moonwolf-github** [comment]
Works for me.

**Comment by thepaul** [comment]
It now works for me too. Probably a change on their end.
