### ISSUE TITLE
Emoji artifacting

### ISSUE THREAD

**Issue by dom0do** [raelgc/scudcloud#182]
My emoji are rendering pretty terribly in ScudCloud on my Ubuntu PC, like so:
![selection_145](https://cloud.githubusercontent.com/assets/758181/8728722/6e8a27ee-2bac-11e5-8d08-62c2c902504d.png)

But they render just fine in the Slack web interface in Firefox on the same system:
![selection_146](https://cloud.githubusercontent.com/assets/758181/8728794/e8d4d8be-2bac-11e5-8a36-0b6e3bfdae54.png)

Clearly this isn't a widespread issue as I don't see an existing issue for this. My colleague's Debian system renders correctly:
![screenshot_2015-07-16_11-00-24](https://cloud.githubusercontent.com/assets/758181/8728740/8b1ca418-2bac-11e5-8359-38efdc55a7aa.png)

My system is an Asus NV56Z laptop with dual IntelHD/nVidia graphics, running Ubuntu 14.04 with GNOME Shell 3.12.2 using default MESA 10.1.3 driver . I tried running Scudcloud on the nVidia (with optimus) but nothing changed.

**Comment by bkconrad** [comment]
Same issue here on Ubuntu Vivid:

```
kaen@kaen-desktop:~$ lsb_release -c
Codename:   vivid
kaen@kaen-desktop:~$ glxinfo | grep vendor
server glx vendor string: NVIDIA Corporation
client glx vendor string: NVIDIA Corporation
OpenGL vendor string: NVIDIA Corporation
kaen@kaen-desktop:~$ apt-cache policy nvidia-346
nvidia-346:
  Installed: 346.59-0ubuntu1
  Candidate: 346.59-0ubuntu1
  Version table:
 *** 346.59-0ubuntu1 0
        500 http://us.archive.ubuntu.com/ubuntu/ vivid/restricted amd64 Packages
        100 /var/lib/dpkg/status
kaen@kaen-desktop:~$ sudo lshw -C display
[sudo] password for kaen: 
  *-display               
       description: VGA compatible controller
       product: GK104 [GeForce GTX 760]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:48 memory:fd000000-fdffffff memory:f0000000-f7ffffff memory:f8000000-f9ffffff ioport:e000(size=128) memory:fe000000-fe07ffff
```

I took a crack at this today, but setting the various Antialiasing hints as mentioned [in the docs](http://doc.qt.io/qt-4.8/qpainter.html#RenderHint-enum) had no effect. It's possible this is a bug with Qt4's WebView or Painter

**Comment by raelgc** [comment]
Indeed, very bad rendering. And probably @bkconrad it's right: related to Qt4 QWebView. Hope we can improve this in a Qt5 version.

**Comment by raelgc** [comment]
This will be fixed in future Qt upgrades.
