### ISSUE TITLE
Slack needs your permission to enable desktop notifications

### ISSUE THREAD

**Issue by chrisvdb** [raelgc/scudcloud#183]
Slack shows a "Slack needs your permission to enable desktop notifications" banner in Scudcloud. Clicking on "enable desktop notifications" and enabling them temporarily removes the banner but it reappears sometime later. The banner shows on all/most different slack teams.

Is there a way to get rid of this banner permanently? Can Scudcloud suppress the banner?

**Comment by michaelherold** [comment]
Duplicate of #163.

**Comment by chrisvdb** [comment]
Sorry, had missed that issue. Will close this one.
