### ISSUE TITLE
"Sign with Google" issue

### ISSUE THREAD

**Issue by dburm** [raelgc/scudcloud#185]
For some reason I've changed my internal Slack account to Google one.
And now scudcloud requires two-factor authentication on each start.

> $ lsb_release -a
> Distributor ID: LinuxMint
> Description:    Linux Mint 17.2 Rafaela
> Release:    17.2
> Codename:   rafaela
> 
> $ apt-cache policy scudcloud
> scudcloud:
>   Installed: 1.0-50
>   Candidate: 1.0-50
>   Version table:
>  **\* 1.0-50 0
>         500 http://ppa.launchpad.net/rael-gc/scudcloud/ubuntu/ trusty/main amd64

**Comment by dburm** [comment]
Fixed by removing old ~/.scudcloud config file. Sorry for bothering you.

**Comment by raelgc** [comment]
No bother at all. Glad to hear you found a way to fix it.
