### ISSUE TITLE
Display Scudcloud version

### ISSUE THREAD

**Issue by trichner** [raelgc/scudcloud#186]
I wanted to post the version of scudcloud for another issue but I could not find it. The 'About' leads to the github repo, the commandline has no '-v' or '--version' option and the 'Help & Feedback' did absolutely nothing.
Even starting from the commandline never shows the version, did my eyes miss it somewhere in the UI?

**Comment by raelgc** [comment]
Hi @trichner, thank you for reporting this.

You're not missing anything, actually the only way to check version is checking in your package manager.

But I like your suggestion to just print using `--version` :)

I'll implement this during my weekend.

**Comment by trichner** [comment]
awesome :)

**Comment by alexander-jiang** [comment]
@raelgc Mind if I tackle this? I'm pretty new to open-source contributions and would like to take on (what seems to be) a smaller task.

**Comment by raelgc** [comment]
Hi @alexander-jiang!

I'm glad to hear you want to help on this! Please, go ahead! Just don't forget to read the [contribution guide](https://github.com/raelgc/scudcloud/blob/master/CONTRIBUTING.md).

And, welcome aboard!
