### ISSUE TITLE
Send message by ctrl enter

### ISSUE THREAD

**Issue by ANtlord** [raelgc/scudcloud#188]
Is it possible to make customization of hotkeys? For example I need send message by ctrl+enter instead enter. And by enter got to new line. Can I add this feature to client? Or is it impossible. Thanks.

**Comment by raelgc** [comment]
Hi @ANtlord, thanks for reporting this issue.

Unfortunately, we're not touching any Slack internal look and feel. Our idea is to keep the ScudCloud as client simple as possible.

You should request this customization option to the Slack team.
