### ISSUE TITLE
Tray icon not visible in Mint Cinnamon 17.2

### ISSUE THREAD

**Issue by souvikonline** [raelgc/scudcloud#192]
I am using the Void (http://cinnamon-spices.linuxmint.com/uploads/themes/C7AR-WYUC-R6K0.png) 
![screenshot from 2015-08-04 10 35 34](https://cloud.githubusercontent.com/assets/570124/9053648/5eb23724-3a95-11e5-8b6a-2e3a35f205eb.png)
theme for Cinnamon in Linux Mint 17.2. The tray icon is not visible. Please see the screenshot.

**Comment by gmorten1** [comment]
i have the same or similar problem in ubuntu 14.04 (trusty) with the Mate desktop (gnome-based desktop similar to cinnamon). i have the latest scudcloud 1.0-53 from the repo. i didn't have this problem with the previous version

specifically, the panel icon disappears when i have a pending notification. i see the normal empty cloud icon when nothing is pending, 
![screenshot from 2015-08-04 08 56 33](https://cloud.githubusercontent.com/assets/383842/9061061/23b73cd6-3a87-11e5-89ed-d56570defaae.png)

but when a DM comes in the icon first flashes the blue cloud icon (no number) and then disappears completely except for a black underline
![screenshot from 2015-08-04 08 58 38](https://cloud.githubusercontent.com/assets/383842/9061066/28d11a84-3a87-11e5-82e7-634fde136464.png)

the icon files (e.g.  scudcloud-attention-1.svg) look ok if i open them in an external viewer

**Comment by gmorten1** [comment]
incidentally, looking at souvik's screenshot i think he has a different problem (which i also encountered before) -- the pale color of the transparent "empty cloud" icon scudcloud.svg is almost an exact match for the default panel background color. i "fixed" this by changing my panel background.

**Comment by 0xd3adsh3ll** [comment]
![_003](https://cloud.githubusercontent.com/assets/4302413/9081431/ecb87e46-3b64-11e5-814b-98191c0491c8.jpg)
![_002](https://cloud.githubusercontent.com/assets/4302413/9081432/ed00a1c6-3b64-11e5-99b9-ce0b9f955f61.jpg)

@gmorten1 I have the same problem as yours.
linux mint 17.2

**Comment by roman-kiselenko** [comment]
![same](https://cloud.githubusercontent.com/assets/3471384/9092453/fc78c79c-3bae-11e5-8ad6-e0e16eed1eb7.png)
![other](https://cloud.githubusercontent.com/assets/3471384/9092513/525d3a76-3baf-11e5-96b1-130a2a968b01.png)
-  +1 Ubuntu 14.04. Gnome fallback
  No icon for a new message

**Comment by sergey-sukiyazov** [comment]
Hi
I found cause of this problem. It happens for me under Ubuntu 14.04 LTS too.
Problem is in file systray.py at line 38:

```
    def setCounter(self, i):
        print( "i =", i)
        print( "scudcloud-attention-"+str(int(i)))
        if 0 == i:
            if True == self.urgent:
                self.setIcon(QtGui.QIcon.fromTheme("scudcloud-attention"))
            else:
                self.setIcon(QtGui.QIcon.fromTheme("scudcloud"))
        elif i > 0 and i < 10:
            self.setIcon(QtGui.QIcon.fromTheme("scudcloud-attention-"+str(i)))
        elif i > 9:
            self.setIcon(QtGui.QIcon.fromTheme("scudcloud-attention-9-plus"))
```

there is code

```
self.setIcon(QtGui.QIcon.fromTheme("scudcloud-attention-"+str(i)))
```

but value of `i` became as float, i.e. we got `2.0` instead of `2` and we have wrong name for icon. So, we need to convert float to integer before call `str(...)`, i.e.:

```
self.setIcon(QtGui.QIcon.fromTheme("scudcloud-attention-"+str(int(i))))
```

this solve the problem.

**Comment by raelgc** [comment]
Thank you for the investigation and fix @fishbullet !

**Comment by gmorten1** [comment]
awesome guys, just updated to 1.0-55 and my issue is fixed. thanks! 
![image](https://cloud.githubusercontent.com/assets/383842/9114797/b3629792-3c29-11e5-9c80-f5f83273495d.png)

as i mentioned previously, i now think that the original issue reported by souvik is a different problem -- the "empty cloud" icon in the hicolor icon theme doesn't have enough contrast on the light gray default panel background color on some gnome-based desktops. if you zoom on his original screenshot it's evident that the icon is actually there, but it's nearly invisible due to lack of contrast.

**Comment by roman-kiselenko** [comment]
Thanks @sergey-sukiyazov for the investigation, i just make a fast PR.

**Comment by raelgc** [comment]
Well, nice team work :)

**Comment by msaggiorato** [comment]
Hey guys, i'm getting this in MATE too, not sure if this was already pushed to the repository that we use to install the app.

Also, it would be great to be able to change the tray icon like it's possible to change the app icon.

**Comment by grinderX19** [comment]
Confirming the same for Xfce4.

**Comment by raelgc** [comment]
@msaggiorato But you can do the same as the for app icon. Just remember to use `dpkg-divert` to keep your changes between updates.

For some reason, under Xfce4, Qt is using the icon for dark themes, located at `/usr/share/icons/ubuntu-mono-dark/scalable/apps/scudcloud.svg` and should be using `/usr/share/icons/ubuntu-mono-light/scalable/apps/scudcloud.svg`.

If someone play with the code under Xfce4, the file is [systray.py](https://github.com/raelgc/scudcloud/blob/master/scudcloud-1.0/lib/systray.py#36) and this is the line: 

``` python
 self.setIcon(QtGui.QIcon.fromTheme("scudcloud"))
```

**Comment by pescobar** [comment]
I am getting the same problem in Linux Mint 17.2 with MATE using scudcloud 1.1-1. I have checked that the patch in systray.py which is mentioned in previous comments is applied.

When opening scudcloud from the shell I get this message which I don't know if could be related:

```
"sni-qt/6099" WARN  10:46:34.586 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
No bp log location saved, using default.
[000:000] Cpu: 6.69.1, x4, 2600Mhz, 7927MB
[000:000] Computer model: Not available
[000:000] Browser XEmbed support present: 1
[000:000] Browser toolkit is not Gtk2 (0).
[000:000] Using Xt toolkit
No bp log location saved, using default.
[000:000] Cpu: 6.69.1, x4, 2600Mhz, 7927MB
[000:000] Computer model: Not available
java version "1.7.0_85"
OpenJDK Runtime Environment (IcedTea 2.6.1) (7u85-2.6.1-5ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)
```

UPDATE: When I get a notification I can see something:
![systray](https://cloud.githubusercontent.com/assets/103797/11364351/37d7aacc-92a0-11e5-8187-2750b2f38460.png)

maybe the default icon is not visible with my theme?

**Comment by pescobar** [comment]
after reading this issue https://github.com/raelgc/scudcloud/issues/229 I found a workaround doing this:

```
sudo cp /usr/share/icons/hicolor/scalable/apps/scudcloud.svg /usr/share/icons/hicolor/scalable/apps/scudcloud.svg.backup

sudo cp /usr/share/icons/ubuntu-mono-light/scalable/apps/scudcloud.svg /usr/share/icons/hicolor/scalable/apps/scudcloud.svg
```

Now it's not perfect but at least I see something in the systray:

![systray2](https://cloud.githubusercontent.com/assets/103797/11399257/68f6b454-9386-11e5-83ae-427c6b032abc.png)
