### ISSUE TITLE
Cannot activate desktop notifications

### ISSUE THREAD

**Issue by mbootsman** [raelgc/scudcloud#194]
I keep getting the message "Slack needs your permission to enable desktop notifications"

When clicking the message and activating Desktop notifications, I do not get a the message indicsted by this notice: "Your browser should now be presenting you with the option to enable notifications, probably at the top or bottom of this window. Click Enable or Allow or Yes or OK or whatever the right button is!"

Using the latest ppa version.

**Comment by Slater91** [comment]
Have you tried switching to another channel or conversation? It always works when I do.

**Comment by mbootsman** [comment]
Hmm, that seemd to have helped. I get desktop notifications now. But with code in them, as reported in another issue.
