### ISSUE TITLE
Notification showing JavaScript instead of the message

### ISSUE THREAD

**Issue by davereid** [raelgc/scudcloud#197]
I'm seeing this for my notifications today:

![workspace 1_277](https://cloud.githubusercontent.com/assets/62967/9114876/beeff382-3c21-11e5-9563-6af330e3dbe4.png)

**Comment by shadefinale** [comment]
I also am having this issue.

If I try sudo apt-get update and then sudo apt-get upgrade it says that it's on the latest version already.

I'm on ubuntu gnome 14.10.

**Comment by roman-kiselenko** [comment]
Look this https://github.com/raelgc/scudcloud/issues/195

**Comment by shadefinale** [comment]
I've seen it and I'm unable to figure out how to update to 1.0-54.

I've tried sudo apt-get update && sudo apt-get upgrade

I've also tried uninstalling and reinstalling the package, both keep me at 1.0-50

EDIT:
sudo apt-get install scudcloud=1.0-54
and/or (I've seen it typed both ways in #195)
sudo apt-get install scudcloud=1.0.54

Give me an error like the following:
E: Version '1.0.54' for 'scudcloud' was not found

**Comment by lube8uy** [comment]
I'm on ubuntu 14.04 and could upgrade to 1.0-55, the upgrade fixed the error.

**Comment by raelgc** [comment]
@shadefinale If you're using `Utopic`, you should manually download the `.deb` file for other version from [Launchpad](https://launchpad.net/~rael-gc/+archive/ubuntu/scudcloud/+files/scudcloud_1.0-55_all.deb) and manually install it.

Canonical Launchpad doesn't allow me anymore to upload packages for Utopic, as it's no more supported.

**Comment by shadefinale** [comment]
@raelgc That's exactly what I needed to do, I'm on 1.0-55 now. 

Thank you very much!
