### ISSUE TITLE
TypeError: 'undefined' (evaluating 'this._onElClick.bind(this)') on rollup-core_required.js

### ISSUE THREAD

**Issue by GrandadEvans** [raelgc/scudcloud#198]
Hi,

I have forked the project but it appears that the fault in question

```
TypeError: 'undefined' is not a function (evaluating 'this._onElClick.bind(this)')
```

is in a remote file rollup-core_required.js at line 15023

I am not sure as to whether this has anything to do with flash etc as to get to this stage I had to run

``` bash
scudcloud --debug=True --no_plugins=True
```

otherwise I get

```
/usr/bin/scudcloud:32: Warning: cannot register existing type 'GdkDisplayManager'
  sys.exit(app.exec_())
/usr/bin/scudcloud:32: Warning: g_once_init_leave: assertion 'result != 0' failed
  sys.exit(app.exec_())
/usr/bin/scudcloud:32: Warning: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
  sys.exit(app.exec_())
Killed
```

Any help in fixing this is obviously appreciated...so thanks in advance.
![screenshot from 2015-08-06 23-27-45](https://cloud.githubusercontent.com/assets/896346/9125023/22718570-3c94-11e5-9394-be18e9130bf6.png)

**Comment by raelgc** [comment]
Hi @GrandadEvans, 

Which distro are you using? Can be related to the `qtwebkit` version.

**Comment by raelgc** [comment]
@GrandadEvans Please, see #20 for `qtwebkit` version.
