### ISSUE TITLE
scudcloud package doesn't seem to work on Ubuntu 12.04

### ISSUE THREAD

**Issue by immerrr** [raelgc/scudcloud#20]
Is Ubuntu 12.04 supported by scudcloud? I see the package in PPA, but it doesn't seem to work.

After the recent change when `pyc` files started being generated by system-wide `python3`, having installed a missing dependency `python3-dbus`, and having downloaded `fonts-lato` package from a newer distribution, scudcloud finally started up, which is great. But unfortunately after logging in it is only showing load screen and ends up [looking like this](http://i.imgur.com/L3sDq8v.png)

**Comment by raelgc** [comment]
@immerrr Thanks for reporting this issue.

So, these are the problems in 12.04?
1. `python3-dbus` missing as required package;
2. `fonts-lato` is not present in 12.04;
3. the left pane appears to not work (as the right pane appears to be ok).

Can you confirm that?

**Comment by immerrr** [comment]
@raelgc I can confirm the first two.

As for the third, it seems that the whole start up procedure hangs, but now paying closer attention to how a successful startup goes on in Chrome, I see that the right pane is populated only when something happens in the left one, so it may very well be like you say.

**Comment by immerrr** [comment]
Thanks for the prompt response, btw :) It's always amazing when unofficial solutions emerging from scratching an itch become better than their official counterparts. :+1:

**Comment by raelgc** [comment]
Thanks @immerrr :)

For the first issue, if I just add the missing dependency to the package will be enough.

For the second, I can try include the `fonts-lato` package using the [sources in Launchpad](https://launchpad.net/ubuntu/+source/fonts-lato/1.104-2).

For the third: I think it's something related to the webkit version it's installed in Precise. There is a PPA that install newest versions of Python (3.4.0) in Precise and others: http://linuxg.net/how-to-install-python-3-4-on-ubuntu-13-1012-1012-04-linux-mint-161413-and-elementary-os-0-2/

If you try the PPA, maybe you'll need to remove ScudCloud and install it again (to recompile the `.pyc` files).

**Comment by immerrr** [comment]
I know about deadsnakes PPA, but unfortunately it won't help in presence of third-party compiled python packages (like PyQt4): they should be built against specific version of python and the `python-pyqt4` package in 12.04 is built against 3.2.

If scudcloud had a more conventional package structure, I could install it with pip into a virtualenv, but there's no setup.py and akin. Is there a reason for that?

**Comment by raelgc** [comment]
@immerrr Yes, the reason is: I learned python, webkit and all related stuff just to build ScudCloud, so I was not aware about it :)

Can you help me with that?

My first question: can a pip package be installed in `/opt`?

**Comment by immerrr** [comment]
Yes, it can, it's somewhat unconventional, but [happens in the wild](https://graphite.readthedocs.org/en/0.9.10/install.html#default-installation-layout).

**Comment by raelgc** [comment]
Cool!

So, if we use a `pip` package, newer version of PyQt4 can be installed?

**Comment by immerrr** [comment]
To upgrade PyQt4 one also has to upgrade system-wide libqt packages, so it is not _that simple_ (python binary packages were always somewhat complicated), but yes, it is doable.

**Comment by raelgc** [comment]
@immerrr What appears to fail is something related to JavaScript.

You can enable JavaScript console in ScudCloud running in terminal:
    scudcloud --debug=True

Then you can right click in any place in the window and select `Inspect`. Then go to `Console` and see if some error is displayed in the console.

**Comment by immerrr** [comment]
Here's what I see in the console:

```
rollup-core_required.js:10881      2015/3/10 9:1:8.864 booted! pri:0
rollup-secondary_required.js:8290  browser not recognized, defaulting to restrictive referrer policy
rollup-core_required.js:10881      2015/3/10 9:1:8.907 onDOMReady
rollup-core_required.js:10881      2015/3/10 9:1:8.907 calling didStartLoading 
rollup-core_required.js:10881      2015/3/10 9:1:8.907 soundManager.setup called 
rollup-core_required.js:10881      2015/3/10 9:1:9.134 soundManager.onready called 
rollup-core_required.js:10883      2015/3/10 9:1:9.717 6809ms from first html to calling onStarts() 
rollup-core_required.js:10881      2015/3/10 9:1:9.717 TS.storage.disabled:true 
rollup-core_required.js:10881      2015/3/10 9:1:9.717 TS.storage.disabled:true 
rollup-core_required.js:10883      2015/3/10 9:1:9.724 #menu_space_action_items_template has no html 
rollup-core_required.js:10881      2015/3/10 9:1:9.726 4ms spent compiling templates 
rollup-core_required.js:14205      TypeError: 'undefined' is not a function (evaluating 'this._onElClick.bind(this)')
```

**Comment by raelgc** [comment]
@immerrr Ok, I've added `python3-dbus` to dependencies and uploaded a `fonts-lato` package for Precise in Launchpad.

About the JS error: this is sad. My hope was that my JS insertion was causing the failure. Appears that our only solution will be upgrade PyQt4.

**Comment by raelgc** [comment]
Appears that you can build a newer PyQt4 using SIP: http://movingthelamppost.com/blog/html/2013/07/12/installing_pyqt____because_it_s_too_good_for_pip_or_easy_install_.html

**Comment by immerrr** [comment]
I have recently been using [miniconda](http://conda.pydata.org/miniconda.html), it makes working with binary packages a lot easier and it already has fresh qt4 & pyqt4 packages. However, dbus & gi-related packages are missing there, I'll try to build them tomorrow and see if it will help to fix the issue.

**Comment by raelgc** [comment]
@immerrr You cannot keep the defaults `python3-gi` and `python3-dbus` ones?

**Comment by immerrr** [comment]
That's the downside of conda: its virtualenvs don't use system-wide python packages.

**Comment by raelgc** [comment]
@immerrr One idea: if we can track files installed by conda, maybe we can create a `.deb` package with that and place files overriding Ubuntu ones.

**Comment by raelgc** [comment]
@immerrr I can see the following Python packages in the Conda installer: 
- python-3.4.2-0
- conda-env-2.1.3-py34_0
- openssl-1.0.1k-0
- pycosat-0.6.1-py34_0
- pyyaml-3.11-py34_0
- readline-6.2-2
- requests-2.5.3-py34_0
- sqlite-3.8.4.1-0
- system-5.8-1
- tk-8.5.15-0
- xz-5.0.5-0
- yaml-0.1.4-0
- zlib-1.2.8-0
- conda-3.9.1-py34_0

Are you sure Qt is included?

**Comment by immerrr** [comment]
They are probably not installed by default, but they are available via the official conda distribution channel (aka `defaults`):

```
$ conda search 'qt$'
Fetching package metadata: ......
pyqt                      .  4.10.4                   py34_0  defaults        
                             4.10.4                   py33_0  defaults        
                          .  4.10.4                   py27_0  defaults        
                             4.10.4                   py26_0  defaults        
qt                           4.7.4                         0  defaults        
                          .  4.8.5                         0  defaults      
```

**Comment by raelgc** [comment]
I've downloaded the full AnaConda and appears there is no `dbus` package on it (for `python3-dbus`).

**Comment by immerrr** [comment]
I have mocked up a version that starts up and doesn't load slack page, but loads plain-http pages. It cannot be so easy, can it? Apparently, qt & pyqt conda packages are built without ssl support.

**Comment by raelgc** [comment]
And if we try with `pip` or `sip`?

**Comment by immerrr** [comment]
pyqt has its own pip-incompatible installers, so pip won't help with it either.

I rebuilt pyqt=4.10.4 under conda and got scudcloud running there under py2, but unfortunately it exhibits the same behaviour. The next step is to try and upgrade qt itself.

**Comment by immerrr** [comment]
I have brought up a VM with ubuntu 14.04 and installed xfce with python-qt4 examples, one of examples is fancybrowser implemented with QtWebkit and it fails in the same manner.

**Comment by immerrr** [comment]
While installing into a fresh ubuntu-server distro I have also found that you need to require `xdg-utils` package to use `xdg-icon-resource` in postinst scripts.

**Comment by immerrr** [comment]
But scudcloud unlike fancybrowser actually works when installed from the package.

**Comment by raelgc** [comment]
I saw that the error displayed in 12.04 is related to `jquery-ui-widget`. If we were able to find a working version of `jquery-ui`, maybe we can inject it into ScudCloud. What is the exact `qtwebkit` version included in 12.04? Then we can try search something related in the web.

**Comment by immerrr** [comment]
The exact version of libqt4-webkit is 4.8.1[*](http://packages.ubuntu.com/libqt4-webkit) and libqtwebkit4 (which seems to provide the actual libQtWebkit.so file) is 2.2.1[*](http://packages.ubuntu.com/libqtwebkit4).

**Comment by immerrr** [comment]
Just finished rebuilding fresher qt in conda and it doesn't seem to help.

**Comment by raelgc** [comment]
And how if we use the deadsnakes PPA, and over it we add 14.04 qtwebkit packages?

**Comment by garagatyi** [comment]
I've faced with this problem too. ScudCloud hangs on load screen.

**Comment by raelgc** [comment]
Hi @garagatyi!

Yeap, unfortunately, the packaged version of qtwebkit in Precise is displaying some JavaScript issues with the `jquery ui widget` plugin that are preventing Slack to be loaded inside ScudCloud.

We're trying to find ways to get an updated version ot qtwebkit in Precise, but appears to be not easy.

**Comment by immerrr** [comment]
I have backported qtwebkit4 package using hybrid precise/trusty system and it seems to fix this issue. It doesn't work on my computer because I have skype which depends on i386 version of qtwebkit4 and it has to be backported as well (which I don't have time for now), but it works on a clean 12.04 vm.

I'm uploading them to dropbox and will post links as soon as they are up. I didn't care about giving them meaningful package revision strings, so they will conflict with the packages from trusty (use with care).

**Comment by immerrr** [comment]
Here's the folder: https://www.dropbox.com/sh/8pq1gxo3jgtrpvv/AAA-tLoUua_AcxbgEkUusMZRa?dl=0:
- `liborc` is a vanilla trusty package (can be downloaded from there)
- gstreamer\* packages were rebuilt without package source modifications
- libqtwebkit4 package omits `qt4-default` dependency (which is absent in precise and is not necessary as there's no qt5 in the first place) but otherwise is unchanged

I hope I'll find time at the weekend to write an unattended backport script so that everyone else doesn't have to trust me.

**Comment by raelgc** [comment]
@immerrr This is awesome! And it the trusty ones are working, I can back-port them to Precise. Let me take a look... but in advance: this is really awesome!

**Comment by raelgc** [comment]
@immerrr If you can send me the `libqtwebkit4` source package, I can upload it to the PPA for Precise.

**Comment by immerrr** [comment]
There's not much to add: I simply downloaded the offical trusty's qtwebkit-source and deleted `qt4-default` from build dependencies.

**Comment by raelgc** [comment]
@immerrr cool!

I'll follow your comments and build them all for Precise! :clap:

**Comment by raelgc** [comment]
@immerrr Just to double check: with Precise vanilla `python3`, right?

**Comment by immerrr** [comment]
Yup, the only extra thing I required was `xdg-utils`, but I have reported it somewhere before.

**Comment by raelgc** [comment]
@garagatyi Please, try install the `.deb` files from @immerrr dropbox: https://www.dropbox.com/sh/8pq1gxo3jgtrpvv/AAA-tLoUua_AcxbgEkUusMZRa?dl=0

**Comment by garagatyi** [comment]
I have skype too

**Comment by raelgc** [comment]
@immerrr Do you mind in generate a i386 package for `libqtwebkit4` too? I'll include them in this repo.

**Comment by immerrr** [comment]
Yup, I have rebuilt the packages and dropbox should sync their new versions in about 30 minutes.

However there is a deeper problem: I have built a total of 43 packages, and some of those depend on specific version of each other, i.e. if one wants, say, to install `libqtwebkit4-dev` that package has to be of the same version as `libqtwebkit4`. Hence the PPA has to provide all of those.

I think it would be better to put those online via another precise-only (since it's a precise-only issue) PPA and then see if these new webkit packages can get through [ubuntu backport process](https://wiki.ubuntu.com/UbuntuBackports). I'll try doing that within the next few days.

**Comment by immerrr** [comment]
Okay, I have found [ppa:gstreamer-developers/ppa](https://launchpad.net/~gstreamer-developers/+archive/ubuntu/ppa) which provides most of the packages. It was interesting to start using PPA for me, so I have gone through creating [ppa:immerrr-k/qtwebkit4-backport](https://launchpad.net/~immerrr-k/+archive/ubuntu/qtwebkit4-backport), but for simplicity I think it is useful to have the package in scudcloud repo.

Here's what you can use to create a source package signed by your signature: https://gist.github.com/immerrr/41fe9b8e33b4a92381e4

**Comment by raelgc** [comment]
@immerrr Loved it! I think it's not a problem people get using these PPAs, as a updated `qtwebkit` is really useful for other different goals.

I'll update instructions on README for Precise.
