### ISSUE TITLE
Commandline Parameter should work from .cfg file too

### ISSUE THREAD

**Issue by githubrsys** [raelgc/scudcloud#205]
## Summary

On linux standard .desktop files come without cli parameters like --no_plugins=True etc. These Parameters should work from the ~/.config/scudcloud/scudcloud.cfg file too and should be maintainable through the GUI.

Because once you manipulated the origin .desktop file it is overwritten on next update. Especially on gnome it is unhandy because the applist will rely on /usr/share/applications and gives ~/.local/share/applications not the favour.

**Comment by raelgc** [comment]
Hi @githubrsys, sorry for my late response.

You're right, and this is a good idea for improvement.

In this meanwhile, you can use `dkpg divert` to keep make your `.desktop` file survive between updates. See a quick usage here: http://unix.stackexchange.com/questions/107704/debian-keep-custom-changes-in-initscript
