### ISSUE TITLE
Last signed in Slack account does not persist

### ISSUE THREAD

**Issue by davereid** [raelgc/scudcloud#206]
I keep having to sign into fourth Slack account. Whenever I restart the application the fourth account never persists. I do have the 'Remember me' checked when I sign in every time.

**Comment by davereid** [comment]
Hrm, this seems to be happening to whatever Slack account I signed into _last_. It never persists beyond my current application session.

**Comment by raelgc** [comment]
Hi @davereid, thanks for reporting this issue.

I'm trying to wonder the reason for this. ScudCloud persists the browser session in config files. Maybe there is a limit for this.

Do you mind to delete your `~/.config/scudcloud` folder and try again?

Hope we can find the reason for this problem and fix it! :)

**Comment by davereid** [comment]
I'll give that a try starting next week since I'm not looking forward to having to re-auth 5 different accounts with TFA on a Friday. :)

**Comment by RoverWire** [comment]
Hey, this is a workaround that seems to work https://github.com/raelgc/scudcloud/issues/199#issuecomment-132975073

**Comment by raelgc** [comment]
Duplicate of #199
