### ISSUE TITLE
Fedora repo linked in readme nonfunctional in F22

### ISSUE THREAD

**Issue by CBJamo** [raelgc/scudcloud#207]
Just installing the repo and package with dnf on F22 gives this error when running scudcloud: 

```
[cbjamo@localhost ~]$ scudcloud --debug=True
loaded the Generic plugin 
/usr/bin/scudcloud:32: Warning: cannot register existing type 'GdkDisplayManager'
  sys.exit(app.exec_())
/usr/bin/scudcloud:32: Warning: g_once_init_leave: assertion 'result != 0' failed
  sys.exit(app.exec_())
/usr/bin/scudcloud:32: Warning: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
  sys.exit(app.exec_())
```

I then tried the package provided by this: https://copr.fedoraproject.org/coprs/jsbillings/scudcloud/ copr repo, and it worked flawlessly. There is a patch that references issue #111.

**Comment by raelgc** [comment]
You can now start the program disabling plugins using:

```
scudcloud --no_plugins=True
```
