### ISSUE TITLE
Allow for selecting of profiles when using Chrome as the web browser

### ISSUE THREAD

**Issue by MakotoTheKnight** [raelgc/scudcloud#209]
My workflow with Slack mandates that I keep my work profile and my personal Chrome profiles separate.  This helps for things like company-only conference calls or links that really shouldn't be opened by my personal profile.

I'm firstly wondering how feasible this is, and secondly if this would be a useful feature to others.  I may wind up forking a copy of the repo to take a stab at this.

**Comment by raelgc** [comment]
Hi @MakotoTheKnight,

The main problem is: ScudCloud just uses `xdg-open` to open URLs and others. So, users can run which browser, image-viewer, etc, they want.
