### ISSUE TITLE
Custom CSS injection

### ISSUE THREAD

**Issue by syphernl** [raelgc/scudcloud#21]
It would be nice if we could somehow inject custom CSS into the webview. 

The use case for this to flip the colors in the content area. Slack allows customization of the sidebar but not the content area which is extremely white and really needs some tweaking.

**Comment by raelgc** [comment]
@syphernl, you can inject custom CSS tweaking `/opt/scudcloud/resources/login.css`.

And if you want to always keep your changes (i.e., avoid `apt` overriding your changes on system update), you can use `dpkg-divert`:

```
sudo dpkg-divert --add --rename --divert /opt/scudcloud/resources/login.css.real /opt/scudcloud/resources/login.css
sudo cp /opt/scudcloud/resources/login.css.real /opt/scudcloud/resources/login.css
```

Now `apt` will always update `login.css.real`, while you can work on `login.css`.
