### ISSUE TITLE
Support Wily in PPA

### ISSUE THREAD

**Issue by yoasif** [raelgc/scudcloud#210]
I believe the [Scudcloud PPA](https://launchpad.net/~rael-gc/+archive/ubuntu/scudcloud) is maintained by Rael. 

It'd be nice if it supported Wily 15.10 by default -- currently, I am using the Vivid version, which happens to work fine.

**Comment by raelgc** [comment]
Hi @yoasif, thank for reporting this.

Indeed, I'm responsible for the PPA too.

Can you tell me if `fonts-lato - 2.0-1` package is already present in Wily?

**Comment by yoasif** [comment]
Yes, it is available in Wily:

apt-cache policy fonts-lato
fonts-lato:
  Installed: 2.0-1
  Candidate: 2.0-1
  Version table:
 **\* 2.0-1 0
        500 http://us.archive.ubuntu.com/ubuntu/ wily/main amd64 Packages
        100 /var/lib/dpkg/status

https://launchpad.net/ubuntu/wily/+package/fonts-lato

On Mon, Aug 17, 2015 at 3:45 PM, Rael Gugelmin Cunha <
notifications@github.com> wrote:

> Hi @yoasif https://github.com/yoasif, thank for reporting this.
> 
> Indeed, I'm responsible for the PPA too.
> 
> Can you tell me if fonts-lato - 2.0-1 package is already present in Wily?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/raelgc/scudcloud/issues/210#issuecomment-131940441.

## 

Asif Youssuff
http://quippd.com

**Comment by raelgc** [comment]
I've published version for Willy :)
