### ISSUE TITLE
Install failed on mscorefonts

### ISSUE THREAD

**Issue by FastandBulbous** [raelgc/scudcloud#216]
Tried to install with apt-get on a fresh Ubuntu 14.04 without mscorefonts 
The installation tries to install the fonts and hangs at the T&Cs acceptance dialog

Install the fonts through Settings/Color/Calibrate to get going again

**Comment by raelgc** [comment]
Hi @FastandBulbous and thanks for reporting this issue and the workaround.

In fresh 14.04, some weird issues happens, most due the not updated system.

I'll add instructions to people always perform first an `apt-get update && apt-get upgrade` to make sure they're with correct dependencies.
