### ISSUE TITLE
team selector disappeared

### ISSUE THREAD

**Issue by ildella** [raelgc/scudcloud#217]
Hi. This morning, I started ScudCloud as any day, but there is no more Team selector on the left. Just disappeared, no way to have it back. 
Using it on Ubuntu 15.04. What can I try? What additional info can I provide to help debugging? Thanks.

**Comment by raelgc** [comment]
Hi @ildella, thanks for reporting this issue.

The team selector is displayed only when more then one team is detected. Maybe, for some reason, ScudCloud was not able to correctly save the session.

One workaround will be add the other team again.
