### ISSUE TITLE
How to remove a team?

### ISSUE THREAD

**Issue by markmandel** [raelgc/scudcloud#218]
So I can't seem to remove a team from scudcloud.

If I sign out of it, it stays in the list, but with a login screen.

If I then restart scudcloud, it won't let me access any of my other teams until I sign into the one I just signed out of.

I really don't want to delete my scudcloud.cfg and start again - I'm signed into about 8 teams right now.

Not sure what is going on?

**Comment by raelgc** [comment]
Hi @markmandel and thanks for reporting this issue.

In theory, if you sign out of a team, and restart the app, the team will be no more displayed in the left pane.

Is this not happening?

**Comment by markmandel** [comment]
Aha, I think I worked out the bug!

If I sign out of a team, and leave that team as the active team - then quit scudcloud, when I next open the application, it gives me the login screen for that team that I just quit.

Interestingly, to get around it, I just click one of the links to the other teams I am signed into.

I'll leave it up to you if you want to close the issue - it has a decent workaround.

**Comment by raelgc** [comment]
Glad to hear you found a workaround @markmandel!

And thank you for sharing the workaround! It'll be really useful for future references.

**Comment by davidcortesortuno** [comment]
I had the same problem in Ubuntu 14.04. I solved it by going to `~/.config/scudcloud/scudcloud.cfg` and removing the team address in the `Domain=` field, so I don't get the login page from the team I signed out, anymore. I saw this was closed but I think this can be helpful to someone else

**Comment by raelgc** [comment]
Thank you for your feedback, @davidcortesortuno!

**Comment by keevitaja** [comment]
It seems that, in case you log out from the multiple accounts, then only the least team will be removed as @markmandel described above. 

But in both cases this is a clear bug.

using 1.30

edit: to remove the other accounts, you just need to login and logout as you did the first time.

**Comment by raelgc** [comment]
Hi @keevitaja. Yes, unfortunately, for now, you have to manually exclude the team from the config file.

**Comment by stratigos** [comment]
Unfortunately this is also a bug if you are kicked from a team or if the owner of the team deletes the channel. There is no UI option to switch teams/channels, only the loading interface to rejoin the same channel that has recently been deleted. My project manager recently deleted a channel to create to a new Slack channel, and Ive been stuck outside of it for a few days not knowing what happened until someone emailed me. 

Deleting the value for `Domain=` breaks ScudCloud (in Ubuntu 14.04) such that when you reload the application, you just get a grey screen with no interface at all (as per @davidcortesortuno suggestion). The entire line must be deleted to restore the interface and log into a different channel.

**Comment by meshy** [comment]
I have closed the app, gone into `~/.config/scudcloud/scudcloud.cfg`, and deleted the bad domain from the list. When I open the app again, the domain is still in the list, and is saved back into the config file.

Presumably it's being cached somewhere?

Is there a new solution to this? If not, should the issue be re-opened?

**Comment by raelgc** [comment]
@meshy The first step should be logoff from the target team, then close the app, then remove from config file.

**Comment by meshy** [comment]
@raelgc sorry, I didn't make it clear that I had already logged out of the team.

**Comment by raelgc** [comment]
Just to double check (and sorry to ask this): the app was really quit, not just closed/minimized to tray, right?

**Comment by meshy** [comment]
I think so, but best if I double-check `;)`

**Comment by meshy** [comment]
Yes, confirmed, the app was closed before removing the domain from the file. Upon re-opening, I am presented with the "log in to team" page.

**Comment by arku31** [comment]
I confirm the bug. I have to edit config to remove old team and this is abnormal. I guest the best way is making additional button - "Delete this team" near "Signout".

**Comment by raelgc** [comment]
@arku31 I agree this is bug, and it's odd. Really sorry for this.

But for now, I have more critical issues to dedicate my free time. As soon as possible, I'll take a look on this one.

I'd love help on this too, if someone can take a look.

**Comment by arku31** [comment]
@raelgc never ever write on python but if you suggest where to look - I can give a try :)

**Comment by raelgc** [comment]
@arku31 The logic happens here: https://github.com/raelgc/scudcloud/blob/master/scudcloud/scudcloud.py#L314

In that code, `teams` is the team list stored in Slack saved session. And `domains` is the list of domains saved in the config file.

This method is confuse and ugly. It tries to load the teams in session, but respecting the order from the domains file. If a new team is detected, it must be stored in the config file.

Probably a better way to fix it is start the method from the ground. Break it in smaller methods if you want. The goal is always to have a clear code :)

**Comment by yxhuvud** [comment]
What worked for me was to delete the domain from BOTH scudcloud.cfg and from scudcloud_qt5.cfg

**Comment by AVGP** [comment]
I wonder what the expected behaviour is when a team is in the stored Slack session but not in the domains list.

Right now it adds any team that is in the Slack session to the list of teams in Scudcloud ([See here](https://github.com/raelgc/scudcloud/blob/f9ae6fac6e7245b855e78b9b57d806a70c885e8e/scudcloud/scudcloud.py#L343-L346)).

Once I comment those lines out, I can remove a team by changing the domains in the config file.

**Comment by raelgc** [comment]
@AVGP The expected behaviour is that Slack remove it from session. And, any team on session get added to ScudCloud.

Anyway, this code section deserves a rework from the ground. Starting by discussing how it should behave and all edge cases.
