### ISSUE TITLE
Scudcloud doesn't start. Can't import PyQt4 module.

### ISSUE THREAD

**Issue by abhyuditjain** [raelgc/scudcloud#220]
I have an issue on my Ubuntu 14.04 LTS. Whenever I try to run scudcloud it gives the following traceback:

Traceback (most recent call last):
  File "/usr/bin/scudcloud", line 4, in <module>
    from PyQt4 import QtGui
ImportError: No module named 'PyQt4'

But I can import that module everywhere else.

My python version: 3.4.3 (/usr/local/bin/python)

EDIT: python3-pyqt4 is also installed and nothing works

**Comment by raelgc** [comment]
Hi @abhyuditjain, thanks for reporting this issue.

Can you try again after perform a system update running in the terminal `sudo apt-get update && sudo apt-get dist-upgrade` ?

**Comment by ghost** [comment]
Hi, it is the same thing for me and I tried to run `sudo apt-get update && sudo apt-get dist-upgrade`
I'm with DEBIAN
thanks

**Comment by raelgc** [comment]
Guys, not sure if you're adding the PPA to get the automatic updates or not. 

Case not, use a tool like `aptitude` to solve the dependencies.

In case you're using the PPA, let me know what package `apt` is reporting as missing.

**Comment by sdwvit** [comment]
sudo apt-get remove scudcloud && sudo apt-get update && sudo apt-get install scudcloud helped for me

**Comment by vpatras** [comment]
today I tried to install in Debian stretch/sid (testing) and also the same problem - after installation, when I tried to run application I received:

...
File "/usr/lib/python3/dist-packages/scudcloud/leftpane.py", line 5, in <module>
    from PyQt4.QtWebKit import QWebView, QWebSettings
ImportError: No module named 'PyQt4.QtWebKit'

because QtWebKit is now missing in Package: python-qt4 (was till "jessie") and I can't find another package with it

**Comment by raelgc** [comment]
Hi @vpatras, the missing package is [python3-pyqt4](https://packages.debian.org/jessie/python3-pyqt4).

**Comment by vpatras** [comment]
Dear Rael,

unfortunatelly not - I have it, currently installed version 
4.11.4+dfsg-2 on Debian GNU/Linux testing (stretch).

Problem is, that till "jessie" (stable) release there was it, but 
currently (testing) there is missing 
(https://packages.debian.org/stretch/python3-pyqt4)...

Best regards,

Viktor

**Comment by TravellingGuy** [comment]
The latest release of the python3-pyqt4 package (4.11.4+dfsg-2) on Debian sid (and probably testing) removed support for the WebKit module (http://metadata.ftp-master.debian.org/changelogs//main/p/python-qt4/python-qt4_4.11.4+dfsg-2_changelog).

Looks like QT4WebKit is essentially dead in the water (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784513;msg=7, https://lists.debian.org/debian-devel-announce/2015/05/msg00001.html), everything is migrating to QT5.

**Comment by raelgc** [comment]
@TravellingGuy thank you for sharing this info! Sounds like a hard movement to exclude (instead of keep the current) Qt4Webkit. Probably Ubuntu will follow this in next releases too.

Time to put more focus in the qt5 branch.

**Comment by JumpingSpottedTiger** [comment]
@raelgc Just wanted to let you know that this morning the python-pyqt4 package in Archlinux has now dropped webkit support.

**Comment by raelgc** [comment]
@JumpingSpottedTiger Thanks for sharing this important notice!

How about `python-pyqt5`?

**Comment by JumpingSpottedTiger** [comment]
It works well enough in my testing that I've decided update the AUR package to use it.

**Comment by ghost** [comment]
I'm the above poster. Looks like Arch has reverted this change, so I've in turn reverted the AUR package. I guess let this be a testament that, other than the channel close button being masked by the scroll bar, it worked really well with qt5.

**Comment by raelgc** [comment]
Thanks for the keeping us updated, @ainola. This is a sign that we should promote the qt5 version everywhere.

**Comment by ghost** [comment]
@raelgc Because I know you want to keep getting bothered with this, it looks like they just reversed the decision to reverse the decision. The bindings have been dropped again.

**Comment by raelgc** [comment]
@ainola People raised an issue for this: #520
