### ISSUE TITLE
Slack official client Beta

### ISSUE THREAD

**Issue by raelgc** [raelgc/scudcloud#221]
For everyone following this repo.

Slack team is now working in a Linux client, in beta for now.

Anyone that want to test and provide feedback in the official client, please, signup in this form: https://docs.google.com/forms/d/1uOlDiuT9XMEGijhXicsOasJv3Nxvt5Azvd9OIIS61Sk/viewform

**Comment by raelgc** [comment]
@bkconrad @dgikiller @djsiddz @fishbullet @immerrr @janeklb @jshawl @markmandel @mbajor @moonwolf-github @padraic7a @StenSoft @syphernl

Probably you'll be interested on this (read above).

**Comment by moonwolf-github** [comment]
Thanks for info.

**Comment by janeklb** [comment]
@raelgc thanks indeed

**Comment by markmandel** [comment]
I signed up - curious to see how/when people get accepted.

**Comment by dgikiller** [comment]
thanks @raelgc

**Comment by raelgc** [comment]
Someone got the download links?

**Comment by markmandel** [comment]
Never heard a thing... anyone else, or is it all fight club?

**Comment by padraic7a** [comment]
Downloads available here: https://www.reddit.com/r/linux/comments/3deva4/slack_chat_beta_now_available_for_linux/

**Comment by raelgc** [comment]
Thank you @padraic7a

**Comment by markmandel** [comment]
Thanks! I also found this repo, by decompressing the .deb http://packagecloud.io/slacktechnologies/slack/debian/

I'll give it a spin at some point. Curious to see if I like scudcloud better, mainly because it's open source, and I can hack it to suit my needs. We shall see!

**Comment by raelgc** [comment]
@markmandel Browsing in the URL you sent, I can see RPMs too in the files list: https://packagecloud.io/slacktechnologies/slack/

**Comment by porjo** [comment]
@raelgc I've tried installing the RPMs without any luck. The RPM links on that page you referenced direct you to another page which describes setting up an RPM repo (by piping a shell script to `sudo`!!!). Unfortunately that repo appears to be either empty or not configured properly. 

Has anyone else got RPMs working? If so, please post direct links to the RPM download, thanks!

**Comment by raelgc** [comment]
@porjo I have this link sent by them on Sep 2: https://slack-ssb-updates.global.ssl.fastly.net/linux_releases/slack-1.2.0-0.1.fc21.x86_64.rpm

**Comment by porjo** [comment]
Thanks. FYI, 1.2.2 is also available from that location: https://slack-ssb-updates.global.ssl.fastly.net/linux_releases/slack-1.2.2-0.1.fc21.x86_64.rpm

I've installed that package onto Fedora 23 and seems to work OK. Here's a screenshot showing signed-in to multiple teams:

![slack_linux](https://cloud.githubusercontent.com/assets/1296987/10064134/a55b8b58-62b8-11e5-9e1d-633e0855126c.jpg)

**Comment by janeklb** [comment]
It's now available officially from https://slack.com/apps

**Comment by raelgc** [comment]
Thank you for the update, @janeklb!

**Comment by raelgc** [comment]
It makes sense for us continue this work now that there is an official Linux app?

**Comment by moonwolf-github** [comment]
@raelgc that's a good question. I'm today testing it and it works fine. I don't think we will be able to make better app - anyway it's build around www content.

**Comment by raelgc** [comment]
Even the Mac OSX client is built around the web app.

**Comment by raelgc** [comment]
Just one important point to remember, as we're talking about a program running in our machines: ScudCloud was built with community effort and it's open source in the pure meaning (as it's Python, you can see the program source installed in your machine).

The official client is a closed source binary running and it spawns several process in the machine.

**Comment by moonwolf-github** [comment]
I would go with scudcloud. As the user and as the developer too (i love Python and Qt (:) ). But would anyone else?

**Comment by raelgc** [comment]
That's the question :)

Wondering if we have a way to measure that other then the Google results.

**Comment by moonwolf-github** [comment]
Official client gives me "maximum number of clients reached” error for other applications  which prevents them from working (even the screensaver). Maybe there is a future for scudcloud? (;)

**Comment by syphernl** [comment]
I'm having the same issue with the official client as @moonwolf-github so I'm back at Scudcloud as well ;-)

**Comment by roman-kiselenko** [comment]
> I'm having the same issue with the official client 

+1

**Comment by immerrr** [comment]
FTR, they seem to have fixed it (answer from a support request from couple days ago):

> We've actually fixed the X client leak and it'll be in the next release - we also hack-patched it in the latest version of 1.2.2, so if you uninstall it, then redownload a new copy from the apps page (yes, I know this is dumb and weird, sorry), the X client leak should be fixed.

**Comment by ivesa** [comment]
Discovered ScudCloud because I'm also being hit by that X client leak. Let's see if I prefer the open-source version :-)

**Comment by raelgc** [comment]
Welcome @ivesa! Please, remember to report any issue or missing feature :)

This leak issue affects Ubuntu and Fedora official clients?

**Comment by raelgc** [comment]
This leak issue affects Ubuntu and Fedora official clients?

**Comment by ivesa** [comment]
@raelgc I'm only running the Ubuntu client, no idea what the Fedora one does.

**Comment by urkle** [comment]
@raelgc FYI I prefer scudcloud as it uses half the RAM over the "official" client from slack.

**Comment by porjo** [comment]
FYI, a new version (`1.2.3`) of the official client has been released for Linux which apparently fixes the X client leak issue - unfortunately, appears to only be available for Ubuntu at this stage. https://slack.com/apps

**Comment by brad** [comment]
Personally, I would much rather use an open source alternative and would be sad if work stopped on this project.

**Comment by markmandel** [comment]
I loved scudcloud - but I have to admit, I've switched over to using the official client full time now :(

**Comment by fooblahblah** [comment]
I prefer SC simply because it works great on NixOS and the official doesn't :)

**Comment by burabure** [comment]
now the download is at https://slack.com/downloads
