### ISSUE TITLE
Scudcloud is removed from Unity launcher on upgrade

### ISSUE THREAD

**Issue by nazar-pc** [raelgc/scudcloud#222]
If Scudcloud is pinned on Ubuntu Unity launcher - it is unpinned on upgrade.
Weird, there is no such issue with any other app.
Ubuntu 15.10

**Comment by raelgc** [comment]
Hi @nazar-pc, thanks for reporting this issue.

Weird, there is no specific commands related to this in the `.deb` package.

It happens during any upgrade?

**Comment by nazar-pc** [comment]
Only during Scudcloud update and only relates to Scudcloud icon.
There are some pre- and post- install triggers, I guess during one of them there is a check for executable existence and if not - icon is removed (I've seen some compilation step at late stage of Scudcloud update/installation).

**Comment by raelgc** [comment]
Yeap, it's just a post installation step to compile the ScudCloud python libraries files into byte code to improve startup time.

**Comment by raelgc** [comment]
@nazar-pc I just tried this (with ScudCloud opened) and cannot reproduce (it got still locked to Launcher).

Anyway, I'm on 14.04. I need to try on 15.10.

**Comment by nazar-pc** [comment]
Just happened the same thing once to Firefox & Firefox trunk.
I remember there was also something similar on 15.04 when Gedit was updated from 3.10 or 3.12 to 3.14.
There should be some connection in those events.

**Comment by raelgc** [comment]
In 14.04, ScudCloud is really crazy when I try to pin it to launcher... sometimes it opens 2 icons in launcher, etc :(

**Comment by nazar-pc** [comment]
They have few thousands of bugs for Unity/Compiz and trying to figure out what to do for 16.04 LTS: https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-16.04-Unity-Bugs
So yes, it might be Unity problem indeed.

**Comment by raelgc** [comment]
Thank you for sharing this, @nazar-pc! I'll keep an eye on this!

**Comment by nazar-pc** [comment]
Just got Unity update that mentines https://bugs.launchpad.net/unity/+bug/1498106 to be fixed.
So, this issue should be resolved, I'll reopen it when issue will repeat on next update.
