### ISSUE TITLE
scudcloud tray icon always uses hicolor in LM17.2 cinnamon

### ISSUE THREAD

**Issue by Beefalo** [raelgc/scudcloud#229]
Scudcloud seems to ignore ubuntu-mono-dark and ubuntu-mono-light. Testet by replacing icons in hiclor. They are always used.

Linux Mint 17.2,  Cinnamon, Scudcloud 1.0-67

edit:
forgot to mention, tested gtk-update-icon-cache, but it did not fix the issue.

~$ sudo gtk-update-icon-cache --force /usr/share/icons/hicolor
gtk-update-icon-cache: Cache file created successfully.
~$ sudo gtk-update-icon-cache --force /usr/share/icons/ubuntu-mono-light
gtk-update-icon-cache: Cache file created successfully.
~$ sudo gtk-update-icon-cache --force /usr/share/icons/ubuntu-mono-dark 
gtk-update-icon-cache: Cache file created successfully.

**Comment by raelgc** [comment]
Cinnamon uses `hicolor` ScudCloud icons, as expected.
