### ISSUE TITLE
Feature request: ROOM integration

### ISSUE THREAD

**Issue by iddqdidkfa** [raelgc/scudcloud#230]
My team using Slack integration with [ROOM](https://room.co/#/) service for voice and video communication. It will be awesome to open **ROOM** links in ScudCloud popup window (with ability to specify pulseaudio SINK and SOURCE).
Or maybe ScudCloud could support plugins someday.

**Comment by raelgc** [comment]
Hi @iddqdidkfa,

What is the URL when you click in a ROOM link? It's opened in the external browser?

**Comment by iddqdidkfa** [comment]
@raelgc yes, it's opened in default browser.
Link looks like https://room.co/#/Slack-VwABxad4hgd839K6

**Comment by raelgc** [comment]
A way to change this should be ask ROOM to generate URLs like this: `room://Slack-VwABxad4hgd839K6`

So ScudCloud will pass it to system `xdg-open`.

**Comment by iddqdidkfa** [comment]
@raelgc We can't ask ROOM to generate different URLs. Actually it's not even ROOM generating this URL, you can use any combination after `/#/` to create new room (or join existing)

I just though ScudCloud could capture link click event and if it's domain matches `room.co` use `xdg-open`
I'm not python specialist, sorry

**Comment by iddqdidkfa** [comment]
I guess there is no point to do some voice/video communication services integration since Slack will provide integrated feature soon
https://softcommerce.slack.com/screenhero
