### ISSUE TITLE
/me text not shown in italics (minor style bug)

### ISSUE THREAD

**Issue by ckortekaas** [raelgc/scudcloud#232]
I'm on Fedora 22 using 1.0.67.

In the web client the styling for /me puts the text in italics. Doesn't seem to be doing this on scudcloud.

Really really minor bug, but wondering if its a quick style css fix.. or something about scudcloud on Fedora 22.

**Comment by raelgc** [comment]
Hi @ckortekaas, thanks for reporting this issue.

Probably it's a missing font. We need to discover which one.

**Comment by ckortekaas** [comment]
In the web gui, inspecting the element seems to give a font-family of "Lato,appleLogo,sans-serif"

**Comment by raelgc** [comment]
Right. On Ubuntu there is a package called `fonts-lato`. On Fedora, it's called `lato-fonts`.

**Comment by moonwolf-github** [comment]
Maybe it's worth to add dependency for Fedora RPM...

**Comment by raelgc** [comment]
It'd be great!

**Comment by ckortekaas** [comment]
Unfortunately after adding lato-fonts and rebooting the problem persists. I have to run scudcloud with noplugins=true due to the libqtwebkit4 incompatibility but I doubt fonts are affected.

**Comment by MeanderingCode** [comment]
Same issue on Debian testing with fonts-lato package installed

**Comment by raelgc** [comment]
I've made a quick fix yesterday for fonts. Please, upgrade to the newest version.
