### ISSUE TITLE
Code snippets make app slow and twitchy

### ISSUE THREAD

**Issue by laenco** [raelgc/scudcloud#238]
Hello!

Any code snippet on screen (and in current chat) makes app very slow and twitchy, either input becomes very laggy.
The longer code snippet is on screen leads to the greater lag between action and app reaction.
Scudcloud is started with --no_plugins=True and there is high cpu usage.

**Comment by moonwolf-github** [comment]
I think it's a duplicate of #140.

**Comment by laenco** [comment]
Yes, it is. Sorry, didn't find that.

**Comment by raelgc** [comment]
Hi @laenco, no problem. Unfortunately, the performance is ordered by QtWebKit. Maybe if we upgrade from Qt4 to Qt5, we'll see a performance improvement related to code snippet and files.

**Comment by raelgc** [comment]
I just release a new version with an option to disable snippets (they'll be viewable in browser after click).

After upgrade, open your config file located at `~/.config/scudcloud/scudcloud.cfg` and add the following line:

```
Snippets=False
```
