### ISSUE TITLE
KDE Message Notification Displays Javascript Code

### ISSUE THREAD

**Issue by brownslink** [raelgc/scudcloud#243]
PPA is deb http://ppa.launchpad.net/rael-gc/scudcloud/ubuntu utopic main.

This is displayed within the notification box when running with Kubuntu 14.10 instead of the message itself.

function () {if(model_ob.is_im){TS.ims.startImByMemberId(model_ob.user)}else{TS.mpims.displayMpim(model_ob.id)}}

**Comment by raelgc** [comment]
Utopic is no more supported by Canonical, so I'm blocked to upload a new version for it.

Please, manually download the version for Trusty or Vivid from the PPA: https://launchpad.net/~rael-gc/+archive/ubuntu/scudcloud/+packages

**Comment by brownslink** [comment]
Hmm - It is less than a year old so it should be supported.  In fact, that
is the last official KDE release for Plasma 4 so many will stick with it
until Plasma 5 becomes more mature.

**Comment by raelgc** [comment]
@brownslink, unfortunately, I really have no way to upload a version to Utopic.

But you can edit your PPA config to use Vivid (the package requirements are the same), like suggest in this [AskUbuntu question](http://askubuntu.com/questions/293203/how-can-i-add-a-ppa-from-a-previous-release). 

Sad to hear that Utopic was the latest Plasma 4 release. It was rock solid stable.

**Comment by raelgc** [comment]
About the Utopic end of life: https://lists.ubuntu.com/archives/ubuntu-announce/2015-July/000197.html

As a non LTS version, just 9 months of support.

If you have plans to keep using KDE 4, probably the best idea is to downgrade to 14.04 and add the KDE 4 backports PPA (which offers the latest fixes and improvements).

**Comment by brownslink** [comment]
OMG - 9 months? - I am never installing one of those again.

Downgrading looks hard too.  It may be easier to just reinstall LTS and go
from there.

**Comment by raelgc** [comment]
Well, now you can get 15.10 and then when 16.04 arrives, upgrade to it. And then stay in the LTS.

**Comment by brownslink** [comment]
I ended up taking your original advice and going with a Kubuntu 14.04
reinstall and then installing the Kubuntu backports ppa.

I will have to learn Plasma 5 in a vm before I feel comfortable switching
to in.  And even then, that won't be until an LTS comes along.

Thanks for the help.

**Comment by raelgc** [comment]
Your welcome!

I'm not comfortable with Plasma 5 yet too!

**Comment by brownslink** [comment]
I played with Kubuntu 15.10 in a VM and it is almost tolerable.  They
managed to get a normal KDE3 style start menu and some of the widgets like
System Load are almost ready.  Many feature are actually superior to Plasma
4 like System Tray icon control.  The Aya desktop theme is now available
(with Slim Glow task items).  Once you get a nice rainy day color scheme
and the wallpapers removed, you can stand to look at it.  I guess I should
publish my own theme.  VirtualBox extensions loaded automatically.  I will
likely move to Plasma 5 at the next LTS.

Cheers

Your welcome!

I'm not comfortable with Plasma 5 yet too!

**Comment by raelgc** [comment]
How I miss KDE2 and 3 :(
