### ISSUE TITLE
Context menu doesn't work on openSUSE Thumbleweed

### ISSUE THREAD

**Issue by mbajor** [raelgc/scudcloud#244]
System openSUSE Thumbleweed, qt: 4.8.7.

RMB click in the middle of a word causes error:

Traceback (most recent call last):
  File "/opt/scudcloud/lib/wrapper.py", line 67, in contextMenuEvent
    self.window.speller.populateContextMenu(menu, element)
  File "/opt/scudcloud/lib/speller.py", line 83, in populateContextMenu
    action = QtGui.QAction(suggests[i], self)
TypeError: arguments did not match any overloaded call:
  QAction(QObject): argument 1 has unexpected type 'bytes'
  QAction(str, QObject): argument 1 has unexpected type 'bytes'
  QAction(QIcon, str, QObject): argument 1 has unexpected type 'bytes'

**Comment by raelgc** [comment]
@mbajor, thank you for reporting this issue.

In the line 83, we're creating the `QAction` with, in theory, a `str` and a `QObject`. Not `bytes`.

Can you open the file `/opt/scudcloud/lib/speller.py` and change the following:

``` python
for i in range(0, count):
                action = QtGui.QAction(suggests[i], self)
```

And change like below?

``` python
for i in range(0, count):
                action = QtGui.QAction(str(suggests[i]), self)
```

Of course, restart ScudCloud.

**Comment by mbajor** [comment]
@raelgc This change fixes the issue
