### ISSUE TITLE
icon disappears after update thorught ppa (Ubuntu 14.04 LTS/15.04)

### ISSUE THREAD

**Issue by w4rrendev** [raelgc/scudcloud#246]
icon disappears after update thorught ppa (Ubuntu 14.04 LTS/15.04)

I always change the default icon with sudo nautilus /usr/share/applications/scudcloud.desktop and change the icon.
this line: Icon=/home/username/Pictures/new_icon_image.png

after update, I have to change it again.
is there way to persist it?

thank you

**Comment by raelgc** [comment]
Yes, it's describe right below the install instructions.

Save the new icon as `scudcloud.png` at your home.

The run the following commands:

```
sudo dpkg-divert --add --rename --divert /opt/scudcloud/resources/scudcloud.png.real /opt/scudcloud/resources/scudcloud.png
sudo cp ~/scudcloud.png /opt/scudcloud/resources/
sudo chmod +r /opt/scudcloud/resources/scudcloud.png
```
