### ISSUE TITLE
Font Ubuntu Family has changed after latest update (Ubuntu 14.04LTS/15.04)

### ISSUE THREAD

**Issue by w4rrendev** [raelgc/scudcloud#247]
After the latest update, I noticed that the font are diffent and i can't change it.
The default font before the latest update is Ubuntu (family).

**Comment by raelgc** [comment]
Hi @filipeguarino, thank you for reporting this issue.

Yes, we've made a change to fix the font loading and use the Slack default font, `Lato`. That's how Slack is supposed to be displayed.

You can change it editing the `/opt/scudcloud/resources/resources.css` file, but remember to use `dpkg-divert` to preserve your changes.

**Comment by filipeguarino** [comment]
hello @raelgc thanks for reply..
the file /opt/scudcloud/resources/resources.css isn't exists
Can you verify, please? 
What about the next update? Will it be like before? using Ubuntu systems font?
thank you very much.

**Comment by raelgc** [comment]
Yes, I just verified, and this file exists in the update published yesterday.

**Comment by raelgc** [comment]
The plan is to do not change Slack expected behavior. Which means keep their font.
