### ISSUE TITLE
When signed into multiple teams there is no way to see if there are unread  messages in the inactive team(s)

### ISSUE THREAD

**Issue by urkle** [raelgc/scudcloud#248]
My suggestion would be to show a badge on the team icon showing that messages are waiting to be read. and possibly a number for important messages?

**Comment by raelgc** [comment]
Hi @urkle and thank you for reporting this issue.

If you have a direct message (aka important message), the team icon will display a red right border.

**Comment by urkle** [comment]
so, I see the slight red right border now. However it doesn't reliably show up.  As I switch teams and it goes away and then shows back up after a second or two.   

I guess what I am more so wanting (which may not easily be possible) is to know the direct messages/channel message as well as knowing if there are messages in my starred channels, and then lastly that there are messages in the channels I am a member of.   The more imporrant being direct & starred channel messages.

**Comment by raelgc** [comment]
When you click in the channel, yes, it'll take 2 seconds to become red again.

The red mark is displayed every time you got a Slack notification. It relies in your Slack notification configuration (global, per team or per channel).
