### ISSUE TITLE
Slack logo images with random filenames stored in /tmp

### ISSUE THREAD

**Issue by lots0logs** [raelgc/scudcloud#249]
I think a picture will explain it best:
![2015-10- 5_03-55-33-am](https://cloud.githubusercontent.com/assets/4675662/10276596/0604ff7e-6b16-11e5-9aa0-4d814ecfc026.png)
I have a total of 123 of them right now. That's after running the app for about 24 hours. Let me know if there's any other info I can provide that would help resolve the issue. Cheers!

**Comment by raelgc** [comment]
This is effect of using teams icons for notifications. Slack changes the icon URL each session for a random string (probably for security reasons).

While this is not a huge disk usage (`123 * 8.4Kb = 1033.2Kb`), and files are deleted after few days of usage, I think we should fix this.

I'll work on this.

Reminder to myself: fix the `populate` method.

**Comment by raelgc** [comment]
Fixed in commit 85535c412a

Please, upgrade!

**Comment by lots0logs** [comment]
Thanks!! :+1:

**Comment by raelgc** [comment]
Welcome and thank you for reporting this! 
It'd be impossible to fix without someone with eagle eyes reporting this!
