### ISSUE TITLE
Receiving "Error listening the socket" on launch

### ISSUE THREAD

**Issue by jnankin** [raelgc/scudcloud#25]
When I launch scudcloud I get a dialog that pops up and says "error listening the socket".  Then, when I try to log in, it never loads slack and just says "Loading..."

**Comment by raelgc** [comment]
Hi @jnankin, thank you for reporting this issue.

Which distro are you using? Do you have any other ScudCloud instance minimized to systray?

**Comment by jnankin** [comment]
ubuntu 14.04, and this happens as soon as I launch the app.  It shows up in
the systray, and the main app launches and just says "Loading"

**Comment by raelgc** [comment]
@jnankin Can you, please, perform a `sudo apt-get update && sudo apt-get dist-upgrade` to make sure all python packages are updated?

Because yesterday I tested in a vanilla Trusty, and only after update system it worked fine.

**Comment by jnankin** [comment]
Yes that definitely fixed the dialog problem for me.  But slack still isn't
loading.  When I launch scudcloud from the cli I get:

"sni-qt/5637" WARN  15:45:14.872 void
StatusNotifierItemFactory::connectToSnw()
Invalid interface to SNW_SERVICE
No bp log location saved, using default.
[000:000] Cpu: 16.2.3, x4, 2200Mhz, 5842MB
[000:001] Computer model: Not available
[000:001] Browser XEmbed support present: 1
[000:001] Browser toolkit is not Gtk2 (0).
[000:001] Using Xt toolkit
No bp log location saved, using default.
[000:000] Cpu: 16.2.3, x4, 2200Mhz, 5842MB
[000:000] Computer model: Not available

**Comment by jnankin** [comment]
I just see the attached screen.

**Comment by jnankin** [comment]
I just see this screen
![screenshot from 2015-03-12 15 46 44](https://cloud.githubusercontent.com/assets/541969/6627843/26e7eb1e-c8cf-11e4-9962-dd88b90d7367.png)

**Comment by raelgc** [comment]
@jnankin Can you, please, close ScudCloud, then:

1 - Start it from the terminal this way: `scudcloud --debug=True`
2 - Right click in ScudCloud window and select `Inspect`.
3 - Maximize the Inspector and select `Console` at top.
4 - Watch for JavaScript errors.

There is people reporting JS errors on 12.04 (Issue #20) due old webkit included with PyQt, but still not 14.04.

**Comment by jnankin** [comment]
Yes, I see JS errors.  See attached.
![screenshot from 2015-03-12 16 44 36](https://cloud.githubusercontent.com/assets/541969/6628881/1f594f02-c8d7-11e4-9a57-2591937f9579.png)

**Comment by jnankin** [comment]
looks the same as on #20

**Comment by jnankin** [comment]
oops, and I actually am running on 12.04.  Sorry about that.  We can close and mark this as a dup then.
