### ISSUE TITLE
Hidden menubar appears again after restart

### ISSUE THREAD

**Issue by ssergiienko** [raelgc/scudcloud#251]
It would be nice to remember show/hidden state between restarts.

**Comment by anhskohbo** [comment]
+1

**Comment by raelgc** [comment]
I just published an attempt to solve this. Can you guys, please, test and close this issue if working? If not, post a comment and I'll try to solve.

**Comment by ssergiienko** [comment]
@raelgc In version 84 it not works for me. (

**Comment by neokore** [comment]
It doesn't work for me neither. It also happen that the menu entry for hidding menubar doesn't appear, but F12 shortcut works.
Could it be that the keyboard shortcut doesn't save the menubar status?
I'm using v84 with KDE Plasma 5.3 on Kubuntu 15.04 if it's useful.

**Comment by raelgc** [comment]
Sorry for the not working fix, guys.

I need to download a Qt based DE and test this a VM.
