### ISSUE TITLE
Large pasted text file brings Scudcloud down.

### ISSUE THREAD

**Issue by cdysthe** [raelgc/scudcloud#253]
A colleague was pasting a large text file, a 512 line changelog, in Slack as a message to me. When I try to open the post Scudcloud grinds to a halt. I am able to see it in the web version of Slack in my browser.

**Comment by moonwolf-github** [comment]
See #140.

**Comment by cdysthe** [comment]
Thanks, That's it.

**Comment by raelgc** [comment]
I just release a new version with an option to disable snippets (they'll be viewable in browser after click).

After upgrade, open your config file located at `~/.config/scudcloud/scudcloud.cfg` and add the following line:

```
Snippets=False
```
