### ISSUE TITLE
Icon not shown in systray at all in KDE5 (scudcloud 1.0-78)

### ISSUE THREAD

**Issue by kaleissin** [raelgc/scudcloud#255]
I'm running KDE5 on Ubuntu 15.04 and the icon doesn't turn up in the systray at all. (Exceedingly common problem, bah.) Scudcloud was installed from the ppa.

**Comment by raelgc** [comment]
Hi @kaleissin, thank you for reporting this issue.

Can you just double check if it's not really displaying the icon at all or if it's displaying the gray icon close to the KDE panel color? (Please, check #77 and #192).

**Comment by raelgc** [comment]
I checked here, and `Icon.fromTheme` is really inconsistent across DEs. It has a fallback icon to set. I'll try this.

**Comment by raelgc** [comment]
No, properly being loaded. Do you have the `sni-qt` package installed?

**Comment by raelgc** [comment]
Systray app icons with Qt5 (used by KDE5) appears to be really broken for now, unfortunately.

**Comment by kaleissin** [comment]
Whoa, I didn't expect such a quick turnaround! You on European time? Take care not to burn out or somethin'!

I do have sni-qt, and there's no invisible icon. The only icons in the tray are for KDE5's own stuff, which is rather telling, no? Firefox can't talk with it either so slack in browser also have no noitifications. I could get used to this non-blinking, unchanging silence ;)

**Comment by raelgc** [comment]
I'm trying some workarounds to see if it's possible to get it working.

**Comment by kaleissin** [comment]
I upgraded with a ppa (**ppa:kubuntu-ppa/backports**) to the newest kde and the scudcloud icon just pops in place. It's where it should be and it works. Plasma 5.3.2, Qt: 5.4.1. So you can close this issue if you like. I assume 15.10 will use the same or a newer version. Now for the interesting test: will plasma still restart roughly every 10 minutes?

**Comment by raelgc** [comment]
Good to hear it's working now!
