### ISSUE TITLE
Can't use PPA on Debian

### ISSUE THREAD

**Issue by Rudloff** [raelgc/scudcloud#262]
The README says that the PPA can be used on Debian, but it does not seem to work:

```
http://ppa.launchpad.net/rael-gc/scudcloud/ubuntu/dists/jessie/main/binary-i386/Packages  404  Not Found
```

**Comment by raelgc** [comment]
Hi @Rudloff, thanks for reporting this issue.

You're right, the instructions should be more clear.

After add the `ppa`, please run this command:

```
sudo sed -i 's/jessie/trusty/g' /etc/apt/sources.list.d/scudcloud.list
```

Let me know if this works and then I'll update the `README.md` file.

**Comment by Rudloff** [comment]
I had to use a different path:

```
sudo sed -i 's/jessie/trusty/g' /etc/apt/sources.list.d/rael-gc-scudcloud-jessie.list
```

But then, it installs correctly. Thanks!
