### ISSUE TITLE
Jump to conversation shortcut does not work after switching team

### ISSUE THREAD

**Issue by alfredopalhares** [raelgc/scudcloud#268]
So after switching team with with mouse, you cannot use `Ctrtl + K` (jump to conversation) to be able to type you need to click on the "slack" area to do anything. Even if you then use `Ctrl + <number>` to switch teams.

Runing on Arch Linux (Up to date) and using scudcloud version **1.0.84**

This is a bit of a edge case, but worth to mention.

**Comment by raelgc** [comment]
Hi @masterkorp and thank you for reporting this issue.

I tried to investigate the reason, and it appears to be trivial: after switch the team, the mouse focus is in the left panel. If you click in any place of the Slack panel itself (i.e., not in the left pane), the shortcut will work again.

My proposed solution: after switch team, put the keyboard focus in the Slack pane.

**Comment by raelgc** [comment]
Fix published for Ubuntu. Now, please wait until Arch version got updated.
