### ISSUE TITLE
Packages don't work on debian

### ISSUE THREAD

**Issue by white-gecko** [raelgc/scudcloud#27]
I'm trying to install scudcloud on a debian jessie and added the ppa as `utopic` and also tried `trusty` but there are unmet dependencies:

```
The following packages have unmet dependencies:
 scudcloud : Depends: python3-pyqt4 but it is not going to be installed
             Depends: libunity9 but it is not installable
             Depends: gir1.2-unity-5.0 but it is not installable
             Depends: libqtwebkit-qupzillaplugins but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Do you plan to also support debian? It shouldn't be to complicated, since ubuntu is based on debian. But you might have to remove the `libunity9` dependency, is only in experimental so far (https://packages.debian.org/experimental/libunity9).

**Comment by white-gecko** [comment]
I've tried to build the package with `dpkg-buildpackage` but still have the same dependency issues. While `python3-pyqt4` can be resolved and I would try to ignore the unity dependency, since you write in the README : “channels quicklist (Unity only)”, so I guess this can be deactivated. But what is `libqtwebkit-qupzillaplugins`? I can't even find it in the [ubuntu packages](http://packages.ubuntu.com/search?section=all&arch=any&keywords=libqtwebkit-qupzillaplugins&searchon=names).

**Comment by white-gecko** [comment]
Removing the unity dependencies and `libqtwebkit-qupzillaplugins` lets me atleast install the package and it also seams to run.

**Comment by raelgc** [comment]
Hi @white-gecko, thanks for reporting this issue!

Cool you're trying to make it run on Debian. Debian was the responsible to make me see how nice the Linux world can be.

The `libqtwebkit-qupzillaplugins` package I've created just for ScudCloud: the goal is to add the spell checker. I.e, to make a red sub mark in words that are not in `hunspell` dictionary. I've built this package based on webit plugins from `QupZilla`: https://github.com/QupZilla/qtwebkit-plugins.

I have the source if you need it too.

**Comment by NyanSten** [comment]
Why are `libunity9` and `gir1.2-unity-5.0` required? I haven't find either used anywhere in the sources. Also, `libqtwebkit-qupzillaplugins` seems not to be required so I would suggest moving it to Recommends instead.

**Comment by white-gecko** [comment]
Isn't there a spellchecker in webkit already? Firefox has something like that.

**Comment by raelgc** [comment]
@StenSoft `libunity9` is required by Unity class. `gir1.2.-unity-5.0` is required for Gi, i.e., Unity too. So, for Debian both are not required, as `libunity` can be dropped in this case.

@white-gecko Spell checker is not built in in webkit. I had to add a webkit plugin for it (it's not related to browser plugins). It's not required, of course, but it's easy to rebuild the package for Debian (it it's not working).

**Comment by NyanSten** [comment]
@raelgc Oh, I see now. I would suggest instead of `"ubuntu"==os.environ.get('DESKTOP_SESSION')` to do autodetection:

```
try:
    from gi.repository import Unity
except ImportError:
    Unity = None
    from launcher import Launcher

try:
    from gi.repository import Dbusmenu
except ImportError:
    Dbusmenu = None
```

and then in `__init__`:

```
if Unity is not None:
    self.launcher = Unity.LauncherEntry.get_for_desktop_id("scudcloud.desktop")
else:
    self.launcher = Launcher(self)
```

and in `quicklist`:

```
if Dbusmenu is not None:
    ql = Dbusmenu.Menuitem.new()
    # and so on
```

Then, you can move `libunity9` and `gir1.2.-unity-5.0` to Recommends.

**Comment by raelgc** [comment]
@StenSoft I like your suggestions! Are you able to create a pull-request with these changes?

**Comment by NyanSten** [comment]
@raelgc I will, during the weekend

**Comment by raelgc** [comment]
@StenSoft Great, I'll upload the package in few hours. Any special instruction that I should add to the README to get it working on Debian? (Maybe to skip the `recommends`?)

**Comment by NyanSten** [comment]
Not really. Recommends mean that it is nice to have but not necessary so when the packages are not available, they will be just skipped by Apt.
