### ISSUE TITLE
Scudcloud doesn't use the icon theme icon in Ubuntu 15.10

### ISSUE THREAD

**Issue by cdysthe** [raelgc/scudcloud#270]
Hi,

I am using the Numix icon theme in Unity on Ubuntu 15.10. Numix contains a Scudcloud icon but it is not being used since I updated to Ubuntu 15.10. The default icon is used in the launcher while all other applications I use get icons from the Numix theme. I have noticed that the icon in use is /opt/scudcloud/resources/scudcloud.png. Is there a way to have Scudcloud use the icon theme icon instead of the default like other applications do?

**Comment by raelgc** [comment]
Hi @cdysthe,

By default, ScudCloud supports the dark/light humanity themes. If those themes are not used, then the hicolor icon will be used, as it should be.

Additional themes will be supported only by user contribution. If you want to help and support Numix theme, send the icons and the related path to be included in the `/debian/install` file.
