### ISSUE TITLE
Second icon in Ubuntu launcher

### ISSUE THREAD

**Issue by cdysthe** [raelgc/scudcloud#273]
Hi,

I lock Scudlcoud to the launcher in Ubuntu 15.10 and can open Scudcloud with it. However it creates a second icon in Scudcloud so I have two as long as Scudcloud is open. If if I unlock the first icon and lock the new one I still get a second one next time I open Scudcloud. There's also the issue with adhering to the set icon pack issue #270.

**Comment by raelgc** [comment]
Hi @cdysthe and thank you for reporting this issue. 

**Please**, on reporting issues, don't use generic text as `Another icon issue` as title.

I can see this issue too (not only for ScudCloud, but for other apps, like Chrome, usually after an upgrade), and it's really annoying. Usually it disappears after a reboot.

Are you using Unity too? 

I tried to investigate this in the code, and was not able to see problems in ScudCloud itself (of course, if someone is reading this and disagree, post a comment).

It appears to be more related to Unity issues, as reported by other users. Anyway, I'll keep an eye on this and try few code changes to see if this will disappear.

**Comment by raelgc** [comment]
@cdysthe Just to share with you: in Unity under Ubuntu 14.04, I faced this double entry in Launcher for several programs.

I got a new machine with 15.10, and this behavior is no more present.

**Comment by cdysthe** [comment]
@raelgc I have looked at this some more. The reason the issue was present in 15.10 was that I had manually changed the icon to Numix (who has a Scudcloud icon). When I did that and clicked the launcher in Unity a second default Scudcloud icon appears in the menu. The real problem here is that Scudcloud doesn't fully adhere to the icon theme set. The launcher icon is correct, but the task icon is default. That is unusual behavior. And if I want to lock the icon to the launcher I get the default icon, not the one set in the icon pack, in my case Numix. An easy way to reproduce this is to apply an icon theme which includes a custom Scudcloud icon like Numix does. Drag the icon from the menu to the launcher. Then click the icon in the launcher and you will get a second default Scudcloud icon representing the task. The Numix icon stays in the menu. See the two screenshot with Numix icon in the menu and default icon in the launcher. 

Yes, I know this is cosmetic, but to me that is important too! :)

![scudcloudmenu](https://cloud.githubusercontent.com/assets/1281031/11398823/301a1494-9351-11e5-8db0-5125cb48648d.png)

![scudcloudlauncher](https://cloud.githubusercontent.com/assets/1281031/11398835/36a26fdc-9351-11e5-8707-9e5cdb1d3e09.png)

**Comment by raelgc** [comment]
@cdysthe Sorry for the long time to answer this.

Numix icon should replace the icon used in the `.desktop` file. This icon is located at: `/usr/share/pixmaps/scudcloud.png`.

**Comment by immerrr** [comment]
Hey, I realized I experience this issue on my 12.04, and to the best of my knowledge I don't have any custom themes installed.

@raelgc, any suggestions on how to debug it?

**Comment by raelgc** [comment]
@immerrr Unfortunately this is a Unity issue with non GTK toolkits. I faced a lot during 12.04, a bit during 14.04 (mostly with Chrome and ScudCloud), and until now 0 times in 16.04.

**Comment by cdysthe** [comment]
I'm now on 16.04 and it doesn't seem to be a problem anymore.

**Comment by raelgc** [comment]
16.04 is so great!

**Comment by immerrr** [comment]
I'm still postponing the migration to 16.04, so no luck on this side. But it seems that `unity --reset-icons` helped, with the disclaimer that it resets the "hud" panel to post-installation state. After re-locking and re-ordering all my icons as I like them to be, it worked.
