### ISSUE TITLE
Desktop notifications are disabled after suspending

### ISSUE THREAD

**Issue by JanChec** [raelgc/scudcloud#274]
Every day I run my PC from suspended state I have to enable ScudCloud's desktop notifications. Top bar appears asking about them.

**Comment by raelgc** [comment]
Hi @Kern3l and thank you for reporting this issue.

Yes, this is a pain. I tried to add some code in the past to try to override notifications after resume, but this added some CPU usage additionally to the Slack reconnect actions (which is already heavy), so I removed it.

I'll try some other fixes to try to solve this.

**Comment by JanChec** [comment]
Awesome, can't wait for it! ;]

**Comment by raelgc** [comment]
Just one note: as a workaround for now, just press <kbd>Ctrl+R</kbd> to reload the team.

**Comment by raelgc** [comment]
No notification today after resume. If you face this again, please, reopen.

**Comment by JanChec** [comment]
This is awesome! Just updated, thanks!

**Comment by raelgc** [comment]
Well, today I face this again. But now, at least, you can click in the yellow banner and the allow notifications button will work while ScudCloud is opened.

**Comment by JanChec** [comment]
Fixed for me so far. I have ScudCloud in background and I suspend. Previously I had to enable notifications every day, but not anymore.
