### ISSUE TITLE
Window half gray on startup, then fully gray

### ISSUE THREAD

**Issue by LoLei** [raelgc/scudcloud#276]
![0xobg8n](https://cloud.githubusercontent.com/assets/9076894/10815655/bd268536-7e2d-11e5-8710-e8813622acfd.png)
![scudcloud2](https://cloud.githubusercontent.com/assets/9076894/10815656/bd4b9470-7e2d-11e5-9bd7-82ee116939af.png)

Cannot click on anything or close it without 10 second delay.

OS: Arch Linux
DE: Xfce4
WM: i3
Latest release of scudcloud from yaourt.

Gray is the color of my GTK theme.

Not a duplicate of #158, since I am online at all times.

**Comment by JumpingSpottedTiger** [comment]
I'll just chime in that I'm on Gnome 3.18 with Arch as well, running the same package. No issues from me.

**Comment by LoLei** [comment]
Update: It seems fixed after a reboot. But it still happens occasionally after other reboots.

I'll update DE and WM in the OP.

**Comment by raelgc** [comment]
If this became an issue again, please, re-open.
