### ISSUE TITLE
Cannot invite members to private channels

### ISSUE THREAD

**Issue by alfredopalhares** [raelgc/scudcloud#280]
![2015-11-02-143837_1235x671_scrot](https://cloud.githubusercontent.com/assets/223763/10884410/d5a135b2-816f-11e5-85c0-101a33a1e68a.png)

The list of members never updates.

Using Arch Linux up to date and scudcloud version 1.0.89-1 from the AUR.

**Comment by raelgc** [comment]
I tested and can see the same on Ubuntu 14.04. Works on browser.
I need to check if it works on qt5.

**Comment by raelgc** [comment]
Thank you @masterkorp for reporting it!
