### ISSUE TITLE
Provide ability to mark messages unread

### ISSUE THREAD

**Issue by colans** [raelgc/scudcloud#281]
It would be great if it were possible to mark messages as being unread.

This doesn't work on Ubuntu/Chromium (probably due to Unity), but it does work on the Android client.

Thanks for all of your work on this project.

**Comment by raelgc** [comment]
Hi @colans and thanks for reporting this issue.

ScudCloud just wraps the web version of Slack. This feature is missing in the web client. So, you should open a Slack support request - press F1 - for it (if it doesn't exist).
