### ISSUE TITLE
Great stuff. Fedora 23 ?

### ISSUE THREAD

**Issue by james-gonzalez** [raelgc/scudcloud#284]
Hi

I've just tried to install ScudCloud on my Fedora 23 installation, I simply used the Fedora 22 repo and it installed just fine. Problem is, it doesn't work. It runs and then just crashes.

**Comment by raelgc** [comment]
Please, start it disabling the plugins:

```
scudcloud --no_plugins=True &
```

**Comment by mbajor** [comment]
@cultavix I've added Fedora 23 repo. libqt4-webkit-qupzillaplugins package is unavailable yet, because of unresolved dependencies. I think deploy of Fedora 23 on OBS is in progress.

Note that Fedora 23 repo is available on OBS we use, but not announced officially.

**Comment by james-gonzalez** [comment]
Thanks guys, I've installed it via the Fedora 23 repo now. It still has the same problem, it runs,  but then just crashes, nothing ever comes up on screen. As soon as I disable the plugins as suggested by @raelgc, it works fine. What am I missing out on?

**Comment by taz77** [comment]
Just an FYI. The only way I have gotten Scudcloud to work on Fedora 23 is to use the no_plugins flag.

**Comment by stieg** [comment]
@taz77 I'm using a modified branch of scudcloud on Fedora23 currently.  @raelgc is in the process of reviewing and merging but you are welcome to try it if you like.  https://github.com/stieg/scudcloud/tree/fedora23_working

I run it from the dev tree by running `python3 -m scudcloud` in the top of the tree.

**Comment by raelgc** [comment]
I think we can just remove Flash/plugins support in the next version (the _pythonic_ one). A lot of users complained about this issue, and it's too easy to click and open videos in the browser.

**Comment by stieg** [comment]
Anything that puts one more scoop of dirt on top of Flash's grave is a
great thing in my book :D.

On Wed, Jan 13, 2016 at 2:16 PM, Rael Gugelmin Cunha <
notifications@github.com> wrote:

> I think we can just remove Flash/plugins support in the next version (the
> _pythonic_ one). A lot of users complained about this issue, and it's too
> easy to click and open videos in the browser.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/raelgc/scudcloud/issues/284#issuecomment-171420284.

## 

Andrew AV. Stiegmann

**Comment by taz77** [comment]
LOL. Yeah good ole flash. It's survived for so long. The death of it will be when Chrome drops their plugin.
