### ISSUE TITLE
Hangs on "Loading slack..."

### ISSUE THREAD

**Issue by imunhatep** [raelgc/scudcloud#285]
Application starts, but hangs without response.
Fedora 22, gnome-shell 3.16.4

**Comment by immerrr** [comment]
This might be related to https://status.slack.com/2015-11/15406af52d7fd9c2. I had the same problem with scudcloud and went to double check that the web version experienced the same problem.

**Comment by imunhatep** [comment]
Than you, but no, that is not the case, cause web and mobile versions work fine.
Issue repeats every time I open ScudCloud.

**Comment by raelgc** [comment]
Usually this is due a old qtwebkit version. Can you tell me which version of qt4 and qtwebkit are you using on Fedora 22?

**Comment by imunhatep** [comment]
It seems I have only qt5 (5.5.0)

qt5-qtbase.x86_64                           5.5.0-18.fc22
qt5-qtbase-common.noarch             5.5.0-18.fc22
qt5-qtbase-gui.x86_64                     5.5.0-18.fc22
qt5-qtwebkit.i686                              5.5.0-4.fc22

qtwebkit.i686   2.3.4

**Comment by james-gonzalez** [comment]
I've got the same problem. To solve it, I just disabled the plugins via the --no_plugins=True option

**Comment by imunhatep** [comment]
Indeed, that helped. Thanks.

**Comment by tchwpkgorg** [comment]
It hangs for me with "Loading... Be cool. But also be warm.".

Starting with --no_plugins=True option does not help.

Running scudcloud 1.0-67 on Ubuntu 15.10, 64 bit.

**Comment by raelgc** [comment]
Hi @tchwpkgorg, thank you for reporting this.

`1.0-67` is pretty old. Can you try update? If not working, I heard people saying to, on 15.10, to remove the PPA and add again.

Probably you're facing the same issue described on #294, but it's fixed in new version.

**Comment by tchwpkgorg** [comment]
Indeed, upgrading to the latest one fixed it. Thanks!
