### ISSUE TITLE
Credentials not stored

### ISSUE THREAD

**Issue by cheskos** [raelgc/scudcloud#286]
Hello.

I have to enter all of my credentials every time I start the client, even though the Remember me? checkbox is checked. Please let me know if further evidence is required.

Thanks

**Comment by james-gonzalez** [comment]
Same here. Though I'm using Fedora 23, which means I can't run it without disabling the plugins.

**Comment by raelgc** [comment]
Can you try manually create the folder `~/.config/scudcloud/` ?

**Comment by james-gonzalez** [comment]
The folder is already there?

**Comment by moesch** [comment]
Same here (debian/jessie)

```
thomas@drusus:~/.config/scudcloud$ ls -l
insgesamt 12
drwxr-xr-x 18 thomas thomas 4096 Nov 15 09:52 data7
drwxr-xr-x  2 thomas thomas 4096 Nov 18 09:02 prepared
-rw-r--r--  1 thomas thomas 1077 Nov 18 09:00 scudcloud.cfg
```

**Comment by cheskos** [comment]
for me, it somehow fixed itself. At the fix time the folder is there already. Thanks!

**Comment by cheskos** [comment]
Now the application won't go further than showing "Loading..."

I ran a self-test and everything is green

**Comment by raelgc** [comment]
Hi @cheskos, please see #294.

**Comment by moesch** [comment]
After update to 1.1 (from current source) the credentials are stored! :-)  
debian/jessie

**Comment by cheskos** [comment]
Fixed! Thanks so much @raelgc

**Comment by cheskos** [comment]
Hi again.

My .config files are there, I updated to the newest version on Friday or Thursday and was working fine, but today is stuck on "Loading..." again :(

**Comment by raelgc** [comment]
Hi @cheskos, you need to update again. New version released during the weekend.

Sorry for the inconvenience.
