### ISSUE TITLE
No notifications

### ISSUE THREAD

**Issue by oblitum** [raelgc/scudcloud#287]
I've installed it through the standard ppa method from README on Ubuntu 15.04 and I'm not getting any desktop notifications.

**Comment by raelgc** [comment]
Hi @oblitum and thanks for reporting this issue.

Are you still facing this in the latest version (`1.1.1`)?

Case yes, which DE are you using?

**Comment by oblitum** [comment]
@raelgc Hi, I'll close this one. I've realized this is related to running in fullscreen mode, and notifications are not working for any application running in fullscreen mode. I'm running Gnome 3 on Archlinux. I think this Ubuntu issue is related: https://bugs.launchpad.net/ubuntu/+source/notify-osd/+bug/550566.

But, if you could help me on this one I'd be glad:
- https://github.com/raelgc/scudcloud/issues/288#issuecomment-158825064

I'm not using scudcloud because of that.
