### ISSUE TITLE
scudcloud changes my volume

### ISSUE THREAD

**Issue by rvandegrift** [raelgc/scudcloud#289]
Today I tried scudcloud, but somehow my volume keeps being set to 100%.  If I lower it, after two notification sounds, it's back at 100%.  I'm using scudcloud from git on Debian Jessie. Slack in iceweasel has never touched the volume.

**Comment by raelgc** [comment]
Hi @rvandegrift and thank you for reporting this issue.

This is not directly related to ScudCloud. Please, see #31
