### ISSUE TITLE
fonts-lato package is old and doesn't render cyrillic

### ISSUE THREAD

**Issue by immerrr** [raelgc/scudcloud#29]
This is what I see with the currently available `fonts-lato` package:
![lato-cyrillic](https://cloud.githubusercontent.com/assets/579798/6655806/1e72eed8-cb0f-11e4-8d56-457530a2740c.png)

According to http://www.latofonts.com/lato-free-fonts/, 2.0 version includes cyrillic glyphs and should fix this issue. `fonts-lato=2.0-1` is [available in utopic without any dependencies](http://packages.ubuntu.com/utopic/fonts-lato), so it should be straightforward to backport.

**Comment by raelgc** [comment]
Reminder to myself: See http://pyqt.sourceforge.net/Docs/PyQt4/qwebview.html#setZoomFactor

**Comment by raelgc** [comment]
@immerrr Thanks for investigate this, man!
`fonts-lato_2.0-1` published for Trusty and Precise.
