### ISSUE TITLE
No scrolling in channel list and member list

### ISSUE THREAD

**Issue by luftigdev** [raelgc/scudcloud#291]
In both, the channel list and the member list, I cannot scroll. On the website, there is a scrollbar that allows me to see all channels and members. Inside Scudcloud I can only see the top channels and members without being able to scroll down.

I'm using Ubuntu 15.04

**Comment by raelgc** [comment]
Hi @rafaroca and thank you for reporting this issue.

In 14.04, I can see the scrollbar only when required. I need to check in 15.04.

**Comment by adamatom** [comment]
I'm also seeing this behavior on Debian Sid.

**Comment by ghost** [comment]
We have the same problem on OpenSuSE 13.2.

BTW I tried to do 'scudcloud --version' but that fails:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/scudcloud/VERSION'

The version is the latest one-click ...

**Comment by raelgc** [comment]
@ahbril This should not happens. (I've checked in Ubuntu the output of `scudcloud --version` and it worked fine). Is the `/opt/scudcloud/VERSION` file present?

Maybe I should install OpenSUSE and Debian in a VM and try to debug in the HTML inspector to see if I can force the scrollbar.

**Comment by ghost** [comment]
@raelgc indeed, there is no such file:

ls -CF /opt/scudcloud/
lib/  LICENSE  resources/  scudcloud*

A scrollbar would be really nice!

**Comment by raelgc** [comment]
@rafaroca Are you talking about the channel list displayed in the left pane, or when you click in Channels? I mean, any chance this is same as #309?

**Comment by raelgc** [comment]
@ahbril Is there any place you can open an issue for the missing `VERSION` file in the openSUSE package?

**Comment by ghost** [comment]
@raelgc: Yes, I think this is a duplicate of #309 (or rather #309 seems to be a duplicate of #291) ...

**Comment by ghost** [comment]
@raelgc I hope you meant opening an issue here ... otherwise ... you can delete that one.

I would not know at all how to request it at OpenSuSE, let alone the fact that I would not know what _should_ be there in the first place. Maybe it's an optional thing, or ... I simply have no clue about it. YOU on the other hand have made scudcloud ...

**Comment by luftigdev** [comment]
@raelgc @ahbril Yes, this was the same issue as #309. Today I got the new release via the repo and it's fixed. Thanks a lot!

**Comment by raelgc** [comment]
@rafaroca Thank you for reporting it! And nice avatar!
