### ISSUE TITLE
Unable to start scudcloud

### ISSUE THREAD

**Issue by ghost** [raelgc/scudcloud#295]
```
Traceback (most recent call last):
    File "/usr/bin/scudcloud", line 3, in <module>  from PyQt4 import QtGui, QtCore
ImportError: /usr/lib/python3.5/site-packages/PyQt4/QtGui.so: undefined symbol: _ZTI19QGraphicsLayoutItem
```

**Comment by raelgc** [comment]
Hi @edvinasme, thank you for reporting this issue.

Can you give us more details, like which distro, desktop environment, etc?

**Comment by dorian-marchal** [comment]
_comment moved in the right issue → https://github.com/raelgc/scudcloud/issues/294#issuecomment-157985571_

**Comment by ghost** [comment]
I am not sure why this got closed, as I do get an error message (contrary to what is happening in #294 ). Also, this started happening few weeks ago.

I am running python 3.5 on ArchLinux. WM is bspwm.

I do not get any windows popping up or anything, it just fails with the error.

**Comment by raelgc** [comment]
Sorry @edvinasme, just re-opened.

**Comment by raelgc** [comment]
I can see this issue in comments in AUR page: https://aur.archlinux.org/packages/scudcloud/

Anything there can help you?

**Comment by ghost** [comment]
@raelgc the comment that you mention is made 1 day ago and it's the last comment without any replies. That was the first thing that I have cheked before making an issue here.

I don't know if this might be same issue as #180 ?

**Comment by auscompgeek** [comment]
Looks like you have a broken partial upgrade. `scudcloud` starts fine for me on Arch Linux. You should run `pacman -Syu`.

**Comment by ghost** [comment]
I did try that. As I said this has been broken for more than a few weeks. During this time scudcloud client was updated a few times which did not fix the problem.

Just today I updated to 1.1.1. I also re-install dependencies: `python-dbus-1.2.0-5  python-pyqt4-4.11.4-2`

Still getting same error.

Running scudcloud as another user also brings the same error message.

**Comment by auscompgeek** [comment]
What version of `qt4` do you have installed?

**Comment by ghost** [comment]
```
pacman -Qs qt4
local/lib32-qt4 4.8.7-2
    A cross-platform application and UI framework (32-bit)
local/liblastfm 1.0.9-1
    A Qt4 C++ library for the Last.fm webservices
local/pyqt4-common 4.11.4-2
    Common PyQt files shared between python-pyqt4 and python2-pyqt4
local/python-pyqt4 4.11.4-2
    A set of Python 3.x bindings for the Qt toolkit
local/qca-qt4 2.1.1-1
    Qt Cryptographic Architecture
local/qt4 4.8.7-3
    A cross-platform application and UI framework
```

**Comment by ghost** [comment]
Additionally, I have reinstalled scudcloud completely, but I still get same error (`pacman -Rcsn scudcloud` & `yaourt -S scudcloud`)

Looking for any pointers on how I can debug this further.

**Comment by auscompgeek** [comment]
Have you tried reinstalling qt4 yet?

If that doesn't work, check that `ldd /usr/lib/python3.5/site-packages/PyQt4/QtGui.so 2>/dev/null` has `libQtGui.so.4 => /usr/lib/libQtGui.so.4` and that `objdump -T libQtGui.so.4 | grep _ZTI19QGraphicsLayoutItem` produces output.

**Comment by ghost** [comment]
@auscompgeek Thanks for your help. I have fixed the issue.

Some info:

```
ldd /usr/lib/python3.5/site-packages/PyQt4/QtGui.so 2>/dev/null | grep libQtGui
libQtGui.so.4 => /usr/lib64/eToken/libQtGui.so.4 (0x00007f7b5ef8c000)
```

I have noticed that libQtGui was not from Qt package but from `safenet-authentication-client` package installed from AUR. After removing this package, the `ldd` command's output is as following:

```
ldd /usr/lib/python3.5/site-packages/PyQt4/QtGui.so 2>/dev/null|grep QtGui                                                                                                  
    libQtGui.so.4 => /usr/lib/libQtGui.so.4 (0x00007effc100a000)
```

I am also able to start scudcloud. Thanks for your help again.

**Comment by raelgc** [comment]
Thank you @auscompgeek for all the help and thank you @edvinasme for give all the details.
