### ISSUE TITLE
Multiroom is broken

### ISSUE THREAD

**Issue by paoloantinori** [raelgc/scudcloud#305]
Fedora 23

``` bash
rpm -qa | ag scud
scudcloud-1.1.6-1.1.noarch
```

I am connected to 2 chats, but I can only see a single one. I'm no longer able to switch to the other.

**Comment by raelgc** [comment]
Hi @paoloantinori, thanks for raising this issue.

If you start scudcloud from the terminal, can you see any output error?

**Comment by paoloantinori** [comment]
Hi, nothing logged. 

```
12:15 $ scudcloud --debug DEBUG --no_plugins NO_PLUGINS
/opt/scudcloud/lib/notifier.py:3: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
loaded the Generic plugin 

```

Only the left side button changes but nothing in the main frame

**Comment by raelgc** [comment]
Right. So, can you please, perform these steps:
1. Open `/opt/scudcloud/lib/leftpane.py`, go to the bottom and comment these lines like below:

``` python
#    def contextMenuEvent(self, event):
#        pass
```
1. Start again scudcloud with debug options:

``` term
scudcloud --debug=True &
```
1. In the left pane, right click and select `Inspect`. Maximize the inspeclet window and click in `Console` tab. Paste errors here, please.

**Comment by paoloantinori** [comment]
https://gist.github.com/paoloantinori/ba2ded98252e12635f0a

But no new entries when I click around

**Comment by raelgc** [comment]
This is the output of the main pane. 

Is the left pane, the one with the 2 teams switcher, displayed to you?

**Comment by paoloantinori** [comment]
Sorry, the left panel is displayed but there is no entry at all in console.

**Comment by raelgc** [comment]
Right. And if you click in the menu `File` > `Sign in To Another Team` and complete the process? Still the same?

**Comment by paoloantinori** [comment]
I've tried to log in and out a couple of time but no error or logs traced.

**Comment by paoloantinori** [comment]
I've tried to log in and out a couple of time but no error or logs traced.

**Comment by paoloantinori** [comment]
I have noticed that the team links, in the main page are inverted. A sends me to B while B sends me to A. I wonder if that has to do with the issue.

**Comment by raelgc** [comment]
@paoloantinori Can you backup the `~/.config/scudcloud/scudcloud.cfg` file, delete the original and start all the process again?

This is really weird. Hope we can find the root cause and fix it.

**Comment by paoloantinori** [comment]
It worked! It must have been a somehow corrupted .cfg file.

Thanks for support!

**Comment by raelgc** [comment]
Team links? When you mention "team links", in my mind, these are the links in the left pane.

**Comment by paoloantinori** [comment]
on the bottom side of the main panel there are also the links of the team you are already logged in. They were bringing me to the wrong chat.

**Comment by raelgc** [comment]
Oh, I'm glad it worked!

Sorry for the inconvenience, @paoloantinori!
