### ISSUE TITLE
assertion 'G_TYPE_IS_OBJECT (object_type)' failed

### ISSUE THREAD

**Issue by candrews** [raelgc/scudcloud#307]
I'm trying to run Scudcloud on Fedora 23. I installed it using [these instructions](http://software.opensuse.org/download.html?project=home%3Amoonwolf%3Ascudcloud&package=scudcloud) linked from README.md, then ran scudcloud.

Here's the console output:

```
$ scudcloud 
/opt/scudcloud/lib/notifier.py:3: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
loaded the Generic plugin 
No bp log location saved, using default.
[000:000] Cpu: 6.69.1, x4, 3300Mhz, 15954MB
[000:000] Computer model: Not available
[000:000] Browser XEmbed support present: 1
[000:000] Browser toolkit is not Gtk2 (0).
[000:000] Using Xt toolkit
No bp log location saved, using default.
[000:000] Cpu: 6.69.1, x4, 3300Mhz, 15954MB
[000:000] Computer model: Not available
Vector smash protection is enabled.
/usr/bin/scudcloud:48: Warning: cannot register existing type 'GdkDisplayManager'
  sys.exit(app.exec_())
/usr/bin/scudcloud:48: Warning: g_once_init_leave: assertion 'result != 0' failed
  sys.exit(app.exec_())
/usr/bin/scudcloud:48: Warning: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
  sys.exit(app.exec_())
```

The window is shown, but it's blank white with a menu bar.

**Comment by raelgc** [comment]
Hi @candrews and thanks for raising this issue.

Start it with:

```
scudcloud --no_plugins=True
```

If it works, please, close this issue.

**Comment by candrews** [comment]
@raelgc that does allow scudcoud to start and it works - but that seems more like a workaround than a fix. Shouldn't this issue stay open until this workaround is not necessary?

And what does that command line option do?

**Comment by raelgc** [comment]
@candrews It disables Flash.

It's a recurrent issue here. I think package for Fedora 23 should have it disabled by default.

Or, better than that, always disabled in any platform. Less memory consumption and less issues here. The only cons: user clicking in a video you'll be redirected to the system browser.

**Comment by candrews** [comment]
@raelgc I still don't understand why you closed the issue... the issue exists, occurs for other users, and has not been fixed. Should not this issue remain open until a fix is made (which may be to disable it by default, or at least for Fedora)?

**Comment by raelgc** [comment]
It should be a Fedora 23 package issue. But you're right, I'll keep it opened until it got fixed.

**Comment by raelgc** [comment]
Flash was gone since 1.2.
