### ISSUE TITLE
scudcloud --version does not work on OpenSuSE 13.2

### ISSUE THREAD

**Issue by ghost** [raelgc/scudcloud#311]
I tried to do 'scudcloud --version' but that fails:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/scudcloud/VERSION'

**Comment by raelgc** [comment]
According you, the `VERSION` file is missing in this package, right?

**Comment by ghost** [comment]
I can only come to that conclusion, yes. I mean I never removed the file and I guess files don;t get lost by themselves ...

**Comment by raelgc** [comment]
Thank you for all the info, @ahbril!

**Comment by raelgc** [comment]
@mbajor, can you investigate this?

**Comment by mbajor** [comment]
@ahbril @raelgc Fixed, repository has been updated

**Comment by raelgc** [comment]
Nice team work, guys!

**Comment by ghost** [comment]
Lol all I did was complain :) Anyway, tested it, and it works now!

**Comment by raelgc** [comment]
@ahbril but without this, how will we know about the issue? :)
