### ISSUE TITLE
scudcloud prevents computer shutdown

### ISSUE THREAD

**Issue by Rudloff** [raelgc/scudcloud#314]
I am using scudcloud 1.1-7 on Debian 8.2.
When scudcloud is running and I try to shutdown my computer, scudcloud window is closed but the program keeps running in the background. This seems to cancel the shutdown and I have to redo it in order to really shutdown the computer.
The console does not output any error.

**Comment by raelgc** [comment]
Hi @Rudloff, thanks for reporting this issue.

ScudCloud is programmed to answer to shutdown or single cancel, like <kbd>Ctrl+C</kbd> commands, but that can be a bug.

Can you, please, provide more details? Like any screenshot or screencast or power log details?

**Comment by Rudloff** [comment]
Here is a screencast that shows the problem: https://www.youtube.com/watch?v=-J1uouN2rmw&feature=youtu.be
When I use Xfce shutdown button, scudcloud is only closed to tray and then seems to freeze (I can't exit with Ctrl+C anymore).
If I use `sudo poweroff` instead of Xfce's GUI, it closes correctly.

**Comment by raelgc** [comment]
For some reason, Xfce is just closing the window instead of call exit.

**Comment by t-st** [comment]
I have the same issue on kubuntu 15.04 and 15.10.
When the Scudcloud Window is open, it just closes it to Tray and aborts the Shutdown/Reboot/Logout. ~/.xsession-errors shows: "ksmserver: Client  "/usr/bin/scudcloud"  ( 1081832d31000144959479100000044470008 ) canceled shutdown."

When the Scudcloud Window is already closed to Tray when I press Shutdown/Reboot/Logout, it does not cancel the command and the shutdown finishes.

I also tried the Beta Slack Linux client. Slack also has a "Close to Tray" Option. There it does not cancel Shutdown/Reboot/Logout. But I would rather use Scudcloud tbh.

**Comment by raelgc** [comment]
Thank you guys for all the info.

I'll try fix this in the next days.

Reminder to myself: probably non Gnome environments are closing the app in a different way. Take a look at [`abouToQuit`](http://pyqt.sourceforge.net/Docs/PyQt4/qcoreapplication.html#aboutToQuit).

**Comment by raelgc** [comment]
@t-st and @Rudloff, can you guys test this solution for me, please?

Open `/opt/scudcloud/scudcloud` and go to line 20, where we have the `signal.signal` line:

``` python
    signal.signal(signal.SIGINT, exit)
```

Add a new line with `signal.signal(signal.SIGTERM, exit)` like below:

``` python
    signal.signal(signal.SIGINT, exit)
    signal.signal(signal.SIGTERM, exit)
```

Save and close. Of course, if ScudCloud is opened, quit and start it again.

Let me know if it works as expected.

**Comment by t-st** [comment]
sry, doesn't seem to change anything for me.

**Comment by raelgc** [comment]
No sorry and thanks for the quick reply, @t-st!

Don't worry, we'll try until we get it fixed!

**Comment by raelgc** [comment]
@t-st and @Rudloff Please, can you test a new attempt?

In file `/opt/scudcloud/scudcloud`, we have this close to line `30`:

``` python
    app = QtGui.QApplication(sys.argv)
    app.setApplicationName(Resources.APP_NAME)
```

Add a new line (the third line in the below code):

``` python
    app = QtGui.QApplication(sys.argv)
    app.setApplicationName(Resources.APP_NAME)
    app.aboutToQuit.connect(exit)
```

Of course, save file, exist, restart ScudCloud and them try a system shutdown.

**Comment by Rudloff** [comment]
It still does not work, sorry.

**Comment by raelgc** [comment]
What happens when you get the ScudCloud process id (i.e., the `<pid>`) and run:

```
kill -TERM <pid>
```

**Comment by Rudloff** [comment]
It seems to kill it correctly.
scudcloud outputs `Terminated`.

**Comment by raelgc** [comment]
So, ScudCloud is answering SIGINT and SIGTERM signals. But, while KDE, Gnome, Cinnamon, Unity and others sends these signs to programs, Xfce appears to act in different way.

Wondering if you guys (or your Xfce) are trying to use scripts like [this](https://forum.xfce.org/viewtopic.php?pid=39710) to solve this program and are facing this as side effect.

**Comment by jayme-github** [comment]
I do see the same here running KDE4 on Debian Jessie (scudcloud package from ppa).
Connecting to `SIGTERM`  and the `aboutToQuit` signal does not help.

It only happens when `Close to tray` is enabled.

**Comment by raelgc** [comment]
New version published with a fix provided by @jayme-github!
