### ISSUE TITLE
Crash on every startup, slash in team name

### ISSUE THREAD

**Issue by davidwindell** [raelgc/scudcloud#315]
Whenever our team loads scudcloud, we get an error which may be related to our team name utilising a forward slash (outer/edge).

```
scudcloud crashed with FileNotFoundError in urlretrieve(): [Errno 2] No such file or directory: '/tmp/outer/edge.png'
```

**Comment by raelgc** [comment]
Hi @davidwindell, thanks for reporting this issue!

Indeed, it's related to this. I'll fix it.

**Comment by davidwindell** [comment]
:+1: wow, thanks for the quick response!

**Comment by raelgc** [comment]
@davidwindell I'm just waiting answer in other fixes. Then I'll publish a new version.

**Comment by raelgc** [comment]
In this meanwhile, you can apply the [changes](https://github.com/raelgc/scudcloud/pull/316/files) manually to fix it until the update.

**Comment by raelgc** [comment]
Fixed and published. Please upgrade.
