### ISSUE TITLE
Scudcloud seems to disregard "notification snooze" mode

### ISSUE THREAD

**Issue by immerrr** [raelgc/scudcloud#325]
I had this "notification snooze" mode enabled today when a private message arrived and scudcloud squiggled in the unity panel. My colleague swears that he didn't override the "notification snooze" mode, so it might be that scudcloud disregards that setting.

**Comment by raelgc** [comment]
Hi Dennis,

ScudCloud will wobble only when a notification is raised by Slack. Slack control itself the notifications. 

ScudCloud has zero lines about notification configurations. 

Where the snooze mode was activated?

**Comment by immerrr** [comment]
It's a "bell" icon in the top left, as described in http://slackhq.com/post/135387122640/do-not-disturb

**Comment by immerrr** [comment]
yep, it's reproduceable with `/remind me` command to slack bot, and i think you're right: chromium tab gets the "attention" modifier in DnD mode, it's just that it's a lot less intrusive than the wobbling.

**Comment by raelgc** [comment]
Thanks for sharing and investigate this, Dennis.

So, the notification is not displayed in system, but the icon is wobbling, right?

**Comment by immerrr** [comment]
yes, no notification, wobbling icon. feel free to close this if you don't see an easy solution, i think i can live with it.
