### ISSUE TITLE
Click on tray icon opens menu instead of opening application window (Linux Mint 17.3)

### ISSUE THREAD

**Issue by 2128506** [raelgc/scudcloud#326]
At some point (most likely after upgrade from Mint 17.2 to Mint 17.3, but I'm not absolutely sure) behaviour of left click on tray icon changed - now it shows menu instead of opening application window. This is very annoying as you need two clicks to open it - on icon and then on "Show" menu item. It will be great to return old behaviour or made it configurable.

**Comment by dthorell** [comment]
That's a Mint 17.3 feature, disable "Enable support for indicators" in System Settings -> General to go back to old behaviour

**Comment by 2128506** [comment]
Yes, that solved the issue. Thank you!

**Comment by raelgc** [comment]
Maybe we should add an entry in Troubleshooting section for it!
