### ISSUE TITLE
URLs seem to break at the first '&'

### ISSUE THREAD

**Issue by rolfkleef** [raelgc/scudcloud#330]
It seems that a URL with an & is displayed correctly, but the actual link when clicked is missing everything from the & onward:

Displayed is `http://www.example.com?abc=def&xyz=123`, click goes to `http://www.example.com?abc=def`

Running 1.1-11 as package on Ubuntu 14.04. The link works correctly in both the web view and Slack's own Ubuntu client.

**Comment by raelgc** [comment]
Hi @rolfkleef, thanks for reporting this issue!

@immerrr Can you take a look if this is related to change we've made regarding link copy?

**Comment by immerrr** [comment]
@raelgc, it could very well be, let me see.

**Comment by immerrr** [comment]
it's weird though, the changes about link copy should only affect copying, not the normal left-clicking

**Comment by immerrr** [comment]
ah, i see, it's the same problem (`_linkClicked` method uses the same `QUrl.toString` method that loses percent-encoding), but i don't understand why has it not occurred before (or why has no one reported this so far)

**Comment by immerrr** [comment]
I've created #331 to fix this.

**Comment by rolfkleef** [comment]
that was quick :smile:
