### ISSUE TITLE
LeftPanel alert for unread messages

### ISSUE THREAD

**Issue by mynameisfiber** [raelgc/scudcloud#333]
Right now leftpanel team icons get the `alert` class when I have a direct mention.  I'd love a secondary class for icons so I know there are generally unread messages.  Even better would be an icon overlay with the number of unread messages.

**Comment by shevek** [comment]
+1

**Comment by raelgc** [comment]
My proposed solution: a blue border in the team icon to indicate unread messages. And an small red circled overlay with the numbers of direct mentions.

**Comment by mynameisfiber** [comment]
@raelgc that sounds perfect
