### ISSUE TITLE
Feature request: persistent notification

### ISSUE THREAD

**Issue by tylercollier** [raelgc/scudcloud#334]
Would it be possible to change the title bar of the app to have an asterisk (star) in it if I have an unread message? That way, when I return from lunch, I can know that I should go look for new messages, or if I needn't bother. That's how Skype works. My MinuteDock web app works the same way, it shows an asterisk if the timer is on, and not if it's off.

The asterisk itself isn't super important, rather just some way for me to know. Thanks!

**Comment by raelgc** [comment]
Hi @tylercollier, thanks for raising this improvement.

Can you provide a sample of app title when there is a new message?

**Comment by tylercollier** [comment]
Sure! "\* Scudcloud"

Generally applications put it on the left (it would be opposite for right-to-left languages). That way, even if a user has many windows open and their window switcher bar is crowded, such that their is not much room for the titles, the user can still tell there is a notification.

I've attached a picture of my Ubuntu window switcher bar, but it'd be the same idea for Windows. In this example, you can see my MinuteDock timer running in Firefox, and you know it's running because of the asterisk. You can also see that I have a message in Skype. I forgot, they don't use an asterisk, but instead bold the title and put a number within brackets to indicate the number of chat sessions with unread messages (so if you had 3 messages from one person, and 4 messages from another person, the number in the title bar would be 2, because it's 2 chat sessions with unread messages). I suppose that idea is even better than asterisks.

![Image of window switcher bar](http://i.imgur.com/8TpouDU.png)

**Comment by raelgc** [comment]
Thank you for the additional info, @tylercollier!

Slack usually provides the number of unread direct messages/mentions. Maybe we can use it.

**Comment by tylercollier** [comment]
I just noticed that when using the slack web browser client, it shows me a bang (!) if there is a direct message (I believe that is what you call it when someone uses the at sign @ and your name). So if someone messages in the #general channel, and then someone uses @tylercollier to message me in the #general channel as well, my slack browser title bar might read:

> ! \* general | My Slack Project - Google Chrome

**Comment by raelgc** [comment]
Hi @tylercollier, I've made a simple attempt to address this.

Can you, please, test the fix?

If yes, overwrite `scudcloud.py` file replacing the content with [this version](https://raw.githubusercontent.com/raelgc/scudcloud/334-title-notification/scudcloud/scudcloud.py)?

**Comment by tylercollier** [comment]
Sure thing. I'm trying it right now. Do you know of a way to test messages from someone else? All I can think of is to ask someone else to message me. The slackbot doesn't trigger responses consistently, so I don't think I can talk to it.

**Comment by raelgc** [comment]
Yes, I know how: send me your email to `rael.gc@gmail.com`, then I'll add you to a simple test team we've created for this purpose! :)
