### ISSUE TITLE
I'm able to run any number of scudcloud instances. Bug ? Feature ?

### ISSUE THREAD

**Issue by zerthimon** [raelgc/scudcloud#337]
Expected behavior would be poping up the running instance ?
![screenshot1](https://cloud.githubusercontent.com/assets/746367/12379147/f56dfd90-bd64-11e5-8df5-3c006e595f3a.png)
![screenshot2](https://cloud.githubusercontent.com/assets/746367/12379146/f56c625a-bd64-11e5-903f-2dc3a98ba242.png)

**Comment by chrismshelton** [comment]
I've noticed this too. I upgraded from 1.1.8 to 1.1.12 on Friday and I believe that's when it started (ubuntu 15.04)

**Comment by raelgc** [comment]
It's a bug.

Thank you for reporting this, @zerthimon and @chrismshelton!

**Comment by raelgc** [comment]
It appears to be fixed to me in latest version (`1.2`). Let me know if still an issue.
