### ISSUE TITLE
Back and Forward keyboard shortcuts no longer work after hiding the menu

### ISSUE THREAD

**Issue by marius-bica** [raelgc/scudcloud#338]
Problem: after hiding the menu using F12, the keyboard shortcuts for back (Alt + left arrow) and forward (Alt + right arrow) no longer work.

ScudCloud version: 1.1.12
OS: Kubuntu 14.04
Python version: 2.7.6
Architecture: x86_64

Steps to reproduce:
1. Click on some of the channels to make sure there is something in the history
2. Press F12 to hide the menu
3. Try Alt + left arrow to go back. Nothing happens
4. Re-enable the menu using F12. Notice how the keyboard shortcuts are working again.

**Comment by raelgc** [comment]
Hi @marius-bica and thanks for reporting this issue!

The custom shortcuts for ScudCloud are registered twice to avoid this known behavior (in fullscreen, shortcuts do not works). But the qwebkit default ones (like reload, backward, forward) are not. 

The fix will consist in register them again against the main window.

**Comment by raelgc** [comment]
@marius-bica Do you mind to test a possible fix for this?

Please, edit file `scudcloud.py` and **append** the following code to the `updateEditMenu` method:

``` python
        # Now register the same actions in the Window itself, to avoid lose them in full screen (#338)
        self.addAction(self.menus["edit"]["undo"])
        self.addAction(self.menus["edit"]["redo"])
        self.addAction(self.menus["edit"]["cut"])
        self.addAction(self.menus["edit"]["copy"])
        self.addAction(self.menus["edit"]["paste"])
        self.addAction(self.menus["edit"]["back"])
        self.addAction(self.menus["edit"]["forward"])
        self.addAction(self.menus["edit"]["reload"])
```

Then go to fullscreen and test it. Remember to switch between teams too while testing.

**Comment by marius-bica** [comment]
Yes, this solves my problem :) 
Note that my original issue did not involve full screen, just toggling the menu with F12. I tested with fullscreen anyways and it works there also.

> Remember to switch between teams too while testing.

Unfortunately I only have 1 team in my slack, but is there a reason to believe this won't work when switching between teams?

**Comment by raelgc** [comment]
We have a simple team to test, give me your email (send to rael.gc@gmail.com) and I can invite you.

Yes, on multiple teams, every time you switch between the teams, we need to update the shortcuts in main window.

Another stuff to test: while NOT in fullscreen or hidden menus, check if the shortcuts are not firing the actions twice.

**Comment by marius-bica** [comment]
Email sent.

> Another stuff to test: while NOT in fullscreen or hidden menus, check if the shortcuts are not firing the actions twice.

Tested, the actions are not firing twice.

**Comment by marius-bica** [comment]
Tested the shortcuts with multiple teams - back and forward shortcuts don't work at all, all other shortcuts are functional. Toggling the menu and/or full screen makes no difference.

**Comment by raelgc** [comment]
Reload works?

**Comment by marius-bica** [comment]
No, reload has no effect either.

**Comment by raelgc** [comment]
@marius-bica Can you try this new attempt? Please, replace the entire `scudcloud.py` with [this one](https://raw.githubusercontent.com/raelgc/scudcloud/338-wrapper-shortcuts-not-working-in-fullscreen/scudcloud/scudcloud.py).

**Comment by marius-bica** [comment]
Yep, that one works. Tested with menu toggling, team switching and fullscreen. The back and forward shortcuts are there.
