### ISSUE TITLE
Feature Request: Support for Night Mode

### ISSUE THREAD

**Issue by SenorFusion** [raelgc/scudcloud#339]
This blog post by the maintainer of the Slack Night Mode style says it all: http://blog.lacour.me/making-slack-night-mode

tl;dr - He ported it to the Slack Desktop apps, any chance we could get this in ScudCloud?

Also, Thanks to raelgc and the other maintainers of this project - It's 10x faster than the default slack client for me. Excellent work - it's much appreciated!

**Comment by raelgc** [comment]
I've sent a similar request to Slack team directly (as we can customize the sidebar). 

Their answer:

> This is a feature request we receive often and something we are looking into hopefully providing in the future.
> 
> I'll be sure to add your vote regarding a night mode for Slack to the UX/UI team.

**Comment by raelgc** [comment]
Please, see #141
