### ISSUE TITLE
transparent icon in tray

### ISSUE THREAD

**Issue by 0xd3adsh3ll** [raelgc/scudcloud#345]
Hello, after upgrade the tray icon became is transparent
Distributor ID: LinuxMint
Description:    Linux Mint 17.2 Rafaela
Release:    17.2
Codename:   rafaela
scudcloud --version
ScudCloud 1.2.0
![screenshot_007](https://cloud.githubusercontent.com/assets/4302413/12552994/f5abf484-c385-11e5-9c77-a582998ff6b0.png)

It's like seem as issue https://github.com/raelgc/scudcloud/issues/192

**Comment by raelgc** [comment]
It's not transparent, it's using a color too close to the systray color.

This sounds like a problem in Mint. When it's too bright, people is complaining about not visible in bright colors. Now under dark.

In default Ubuntu (with Unity), we're placing icons under `/usr/share/icons/ubuntu-mono-dark` and `/usr/share/icons/ubuntu-mono-light`, so Qt will detect automatically.

Is there something similar for Mint?

**Comment by 0xd3adsh3ll** [comment]
Hello, @raelgc. Sorry for my mistake.

> Is there something similar for Mint?
> hell hellname # ls -l /usr/share/icons/ubuntu-mono-light
> итого 20
> drwxr-xr-x 3 root root 4096 сент. 10 11:12 16x16
> drwxr-xr-x 3 root root 4096 сент. 10 11:12 22x22
> drwxr-xr-x 3 root root 4096 сент. 10 11:12 24x24
> drwxr-xr-x 3 root root 4096 июля  21  2015 scalable
> drwxr-xr-x 5 root root 4096 июля  28 09:25 status
> hell hellname # ls -l /usr/share/icons/ubuntu-mono-dark
> итого 16
> drwxr-xr-x 3 root root 4096 сент. 10 11:12 16x16
> drwxr-xr-x 3 root root 4096 сент. 10 11:12 22x22
> drwxr-xr-x 3 root root 4096 сент. 10 11:12 24x24
> drwxr-xr-x 3 root root 4096 июля  21  2015 scalable

**Comment by raelgc** [comment]
@0xd3adsh3ll, np.

I think those 2 folder were installed by ScudCloud.

Wondering which theme Mint uses by default, if there are something similar to the 2 Ubuntu light/dark themes.

**Comment by raelgc** [comment]
Maybe we use a colored (purple) icon, like the program icon, so we can avoid this problem in Mint. What do you think, @0xd3adsh3ll?

**Comment by panzerdp** [comment]
Hi @raelgc 
First of all thanks for the application, I'm using it every day :).

I have the same problem with the icon. The issue appeared after latest update.
Thanks.

![680526](https://cloud.githubusercontent.com/assets/1078719/12573724/0a1e2c32-c405-11e5-9a0a-e04fd7834004.png)

**Comment by alsar** [comment]
The same problem is on Ubuntu. On the default theme the displayed icon is ok, but if you use any custom theme you always have the black icon.
I didn't have any problems until the update.

**Comment by raelgc** [comment]
I'll change the `hicolor` icon to be a colored one. So we can avoid users with non-default dark themes complaining about dark icon, and users with non-default light themes complaining about the light icon.

**Comment by panzerdp** [comment]
@raelgc Sounds good. The active icon is blue anyway, but the default could be green for example.

**Comment by raelgc** [comment]
Can you try, please:
1. Remove the svg running: `sudo rm /usr/share/icons/hicolor/scalable/apps/scudcloud.svg`
2. Copy the colored icon running: `sudo cp /usr/share/pixmaps/scudcloud.png /usr/share/icons/hicolor/128x128/apps/`
3. Update icons database running: `sudo gtk-update-icon-cache /usr/share/icons/hicolor`
4. Quit ScudCloud and open it again.

To revert: 
1. `sudo rm /usr/share/icons/hicolor/128x128/apps/scudcloud.png`
2. `sudo apt-get install --reinstall scudcloud`

**Comment by panzerdp** [comment]
@raelgc After executing command 1, I have this error:
`rm: cannot remove ‘/usr/share/icons/hicolor/scudcloud.svg’: No such file or directory`
I'm using Mint 17.2 with Cinnamon.

**Comment by raelgc** [comment]
Oops, should be in `/usr/share/icons/hicolor/scalable/apps/`

**Comment by raelgc** [comment]
I've udpated the commands.

**Comment by panzerdp** [comment]
Yes, looks better now. The icon looks a bit weird because it's png, but as temporary solution will work.
Thanks.
![27323c](https://cloud.githubusercontent.com/assets/1078719/12580147/d01a5016-c435-11e5-8f70-0df2d2a23816.png)

**Comment by raelgc** [comment]
@panzerdp Ugly as hell!

Can you try, please:
1. Revert steps using the instructions I've pasted above
2. Open [this link](https://github.com/raelgc/scudcloud/blob/345-no-trayicon-contrast-in-hicolor/share/icons/hicolor/scudcloud.svg), save in your homefolder and replace the `/usr/share/icons/hicolor/scalable/apps/scudcloud.svg` with this new one (using `sudo`)?

It's not a perfect SVG (I'm really newbie in Inkscape), so if someone can improve it, we'll be really glad!

**Comment by panzerdp** [comment]
Thanks @raelgc, it does look better now.

![d28537](https://cloud.githubusercontent.com/assets/1078719/12580889/d34dda40-c43b-11e5-82f2-d6449cb7c115.png)

**Comment by raelgc** [comment]
Thanks for the long testing, @panzerdp!

The fix is merged and I'll deploy today after test other minor fixes!

**Comment by panzerdp** [comment]
Great! Thanks for the quick fix @raelgc.

**Comment by 0xd3adsh3ll** [comment]
@raelgc thanks for fix!

**Comment by raelgc** [comment]
I'm glad it worked, @0xd3adsh3ll! Thanks for your patience!
