### ISSUE TITLE
Incorrect package dependency in fedora

### ISSUE THREAD

**Issue by liam-raymond-brightpearl** [raelgc/scudcloud#348]
The fedora package for scudcloud 1.2/1.3 requires dbus-1-python3, which is not present in fedora, the equivalent package is python3-dbus. Upgrading via rpm --nodeps results in a working scudcloud installation, so the package is otherwise sound (tested on fedora 23).

**Comment by raelgc** [comment]
Hi @liam-raymond-brightpearl and thanks for reporting this issue!

@mbajor Please, can you take a look on this?

**Comment by mbajor** [comment]
@liam-raymond-brightpearl @raelgc 
Repository has been updated. Build in progress...

**Comment by raelgc** [comment]
Thank you, good sir!
