### ISSUE TITLE
[ENH] Local logs

### ISSUE THREAD

**Issue by paoloantinori** [raelgc/scudcloud#349]
This request is a little in contrast with _Slack_ client-server idea, but having the capability to produce a local copy of chat logs, just plain IRC could be an interesting feature.

In particular I have just been bitten by the 10k messages limit of the free offering, that made me realize the important of a local copy of my own data.

**Comment by raelgc** [comment]
Hi @paoloantinori and thanks for reporting this issue!

I can realize how bad is to hit the 10k messages limit of the free offering.

But I'm afraid that if we implement this, we'll be creating a workaround to break Slack business model. Which probably will lead them to block our client in the future.

So far, Slack team has been really gentle with us, even commenting in this repo.

Our rule is keep ScudCloud a simple wrapper for Slack internal engine, and never touch the internal client.

I'm really sorry for the inconvenience, but I'll have to say **No** for this enhancement.
