### ISSUE TITLE
Multi team unread notification indicator disappears when clicking on another team

### ISSUE THREAD

**Issue by edmundcraske** [raelgc/scudcloud#354]
I'm using ScudCloud signed into multiple teams. If I get a notification from a team other than the one I'm looking at, a red line appears down the edge of that team icon in the team bar on the left. If I then click a team other than the team for which I have a notification, the team list seems to get redrawn, and no longer indicates that there's an unread notification, although I've not looked at it yet.

Hopefully I've explained it well enough!

**Comment by edmundcraske** [comment]
Might go hand in hand with #333 :)

**Comment by raelgc** [comment]
Fixed in #360
