### ISSUE TITLE
Team icons that aren't set show as generic Slack logo rather than initials on coloured background

### ISSUE THREAD

**Issue by edmundcraske** [raelgc/scudcloud#355]
I'm signed into multiple teams, and in the team list on the left, only an icon for each team is shown, and not always in the same order. If a specific icon has not been set for a team, although the Slack team settings shows a custom icon with some background colour and the initials of the team name, ScudCloud only shows a generic Slack logo, so there is no way to differentiate between teams that do not have custom logos set.

**Comment by raelgc** [comment]
Hi @edmundcraske and thanks for reporting this issue.

Two improvements to address here.

First: when the default team is loaded, ScudCloud query Slack about additional teams, and for some reason, they're returned in a random order. So, we should work to have a way to save/config team loading order (probably just save order in the config file).

And second improvement: add the team initials to the icon when default icon is used.

**Comment by raelgc** [comment]
@edmundcraske In a first moment, I'll fix the loading order (and enable users to change it in the config file).

A friendly reminder that you can put your mouse over the team icon to see the team name.
