### ISSUE TITLE
Multiple Teams

### ISSUE THREAD

**Issue by ghost** [raelgc/scudcloud#356]
Is it somehow possible to open more than one team at startup?

**Comment by raelgc** [comment]
Hi @kampdomoj.

Yes, you should be able to click on menu `File` > `Sign in to Another Team`.

After finish to add the other team, ScudCloud will persist your team after close the application.

**Comment by ghost** [comment]
Awesome. Thanks!

**Comment by raelgc** [comment]
You're welcome!

Feel free to raise any issues you face! :)

**Comment by vlatkoB** [comment]
I can log to another team, but ScudCloud does not persist that connection. After startup, I must manually log in to another team every time.
Check config and see the domain is filled:
`Domain=https://workinghaskell.slack.com/, https://zoomin-dev.slack.com/`

ArchLinux, ScudCloud 1.37-2

**Comment by vlatkoB** [comment]
It works now.
Seems after logging to another team one must manually close ScudCloud (Ctrl+Q) and than it remembers. If ScudCloud is closed by the system on shutdown, it doesn't remember it.

**Comment by raelgc** [comment]
@vlatkoB It's watching for system shutdown, but some systems (or desktop environments) make this call in a different way.

**Comment by vlatkoB** [comment]
If someone has the same issue, this is the solution. :-)

**Comment by vlatkoB** [comment]
On Linux, the easiest solution to scaling is to run it with ENV var set to some value, like this:
`QT_AUTO_SCREEN_SCALE_FACTOR=2 scudcloud `

See [QT high DPI](https://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/)
