### ISSUE TITLE
Few account switching problem

### ISSUE THREAD

**Issue by DmitriyBaklikov** [raelgc/scudcloud#36]
Hi @raelgc. 
I'm using two Slack accounts and after I added second one, I've gotten an issue with team labels at the left sidebar:

![Problem with team switching](http://i.imgur.com/pBNQWXL.png)

I'm unable to switch teams using this panel. My system: Ubuntu 14.10/Unity

**Comment by raelgc** [comment]
Hi @ch1m1d, thanks for reporting this issue!

Just to try to isolate this problem: the issue (not listing the other team) persists even after a close/restart?

**Comment by DmitriyBaklikov** [comment]
yes, even rebooted once to be definitely sure :)

**Comment by raelgc** [comment]
Right. Thanks for checking that.

I'll download a 14.10 image and test.

**Comment by raelgc** [comment]
@ch1m1d I just downloaded the 14.10 iso, installed in a VM, then installed ScudCloud, and it worked fine.

![essgxd1](https://cloud.githubusercontent.com/assets/263302/6720945/08596196-cda7-11e4-8246-39f770350a85.png)

Can you try delete your `~/.scudcloud` file and restart the program again, please?

If this do not works, start scudcloud with: `scudcloud --debug=True`.

Then, right click over the left team switcher and select `Inspect`. Then go to `Console` and check if there is JavaScript error there. If yes, paste them here, please.

**Comment by DmitriyBaklikov** [comment]
@raelgc just tried and team switcher bar is inaccessible by inspector.

**Comment by raelgc** [comment]
@ch1m1d My bad!

Please, using `sudo`, edit file `/opt/scudcloud/lib/leftpane.py` and comment these lines like below:

``` python
    #def contextMenuEvent(self, event):
        #pass
```

Then try again run as `scudcloud --debug=True` and then right click in the left pane, open the `Inspect` > `Console` to find JS errors.

**Comment by DmitriyBaklikov** [comment]
@raelgc 

```
SyntaxError: Expected token ')'
```

and

```
TypeError: 'null' is not an object (evaluating 'document.getElementById(team).classList')
```

**Comment by raelgc** [comment]
@ch1m1d This persists after a system update? 

In the console, there is the info about the lines where the first error happened? (Usually in the right side of the line where the error is displayed)

**Comment by raelgc** [comment]
Closing by inactivity. Please, re-open if required.
