### ISSUE TITLE
Enhancement request: non-direct-mention indicator

### ISSUE THREAD

**Issue by tylercollier** [raelgc/scudcloud#362]
I'd like to know if there are unread messages in Scudcloud. In issue #334, the fix provided shows digits in brackets for the number of unread _direct-mentions_, but does not indicate non-direct-messages in any way.

The Slack web browser client indicates that there are unread non-direct-messages using an asterisk in the browser tab title. E.g., it might show `* general | My Slack Project`. I think Scudcloud should behave the same way. The asterisk and direct-message count are unrelated, so both can be present at the same time, indicating different pieces of information. E.g. if you had some number of unread non-direct-messages, and 3 unread direct-messages, you might see `* [3] general | My Slack Project`.

**Comment by raelgc** [comment]
@tylercollier I've made it, but the only difference about your request: when direct mentions are present, asterisk will be not present.

So you'll see:

`ScudCloud` for no unreads or direct messages;
`[3]ScudCloud` for 3 direct messages (with or without unreads);
`*ScudCloud` for unread messages but not direct mentions.

I.e., direct mentions will always have precedence over unreads.

**Comment by tylercollier** [comment]
Works for me. Thanks!
