### ISSUE TITLE
[mate] no scudcloud icon in notification area

### ISSUE THREAD

**Issue by yermulnik** [raelgc/scudcloud#363]
I've got Linux Mint 17.1 Rebecca with Mate window manager and there's no Scudcloud icon in notification area (where all other app icons reside). Scudcloud version is latest (1.5), installed from http://ppa.launchpad.net/rael-gc/scudcloud/ubuntu/, but issue has been present with older versions. Is there a way to debug this or anything else?

**Comment by raelgc** [comment]
Hi @yermulnik. I'm sorry to hear about this issue!

Can you please, capture a screenshot of the notification area?

And additionally, any idea about which is the icon theme used by default by Mate?

**Comment by yermulnik** [comment]
> Can you please, capture a screenshot of the notification area?

![scudcloud](https://cloud.githubusercontent.com/assets/1274789/12662174/198762c8-c627-11e5-9a9d-67ba45c48e3c.png)
licq, yakyak (google hangouts client), skype, pidgin and others. I've got similar issue with viber: it occasionally shows its icon after startup, but at most it is a little black dot, that you can see between separator next to netspeed applet on the left side and licq "flower" icon on the right side (can't imagine what influences that behavior: sometimes it shows up after viber startup and another time it's a black dot).

> And additionally, any idea about which is the icon theme used by default by Mate?

Honestly, I don't really know %-\ Does it really matter? Doesn't sculdcloud have its own icon, independent from the desktop theme?

**Comment by raelgc** [comment]
@yermulnik, thank you for the screenshot.

> Does it really matter? 

Yes. The Desktop Environments will search icon folders in a preference order. Anyway, `hicolor` appears to be the used icon for ScudCloud in Mate.

So, can you, please:
1. Close ScudCloud.
2. Download [this improved icon](https://github.com/raelgc/scudcloud/blob/363-no-notification-area-icon-in-mate/share/icons/hicolor/scudcloud.svg).
3. Using `sudo`, replace `/usr/share/icons/hicolor/scalable/apps/scudcloud.svg`
4. Update icons database: `sudo gtk-update-icon-cache /usr/share/icons/hicolor`

Re-open ScudCloud.

**Comment by yermulnik** [comment]
No luck =(
FYI: as I don't have `gtk-update-icon-cache` I ran `update-icon-caches /usr/share/icons/hicolor`

Found such settings `org.gnome.desktop.interface icon-theme 'Mint-X'` and `org.mate.interface icon-theme 'gnome'` and updated icons in those themes - still no scudcloud icon in notification area =(

**Comment by raelgc** [comment]
Just to double check: you've mentioned that, sometimes, the icons appears, right?

**Comment by yermulnik** [comment]
Viber's icon. Most of the time after restart it's a black dot, but sometimes icon show up as it should be. But Scudcloud's icon doesn't appear in notification area at all, even as a black dot =(

**Comment by raelgc** [comment]
Right.

Is there any folder named `Mint-X` in `/usr/share/icons/`? Do you mind to run a `ls` on `/usr/share/icons/` folder and paste here?

**Comment by yermulnik** [comment]
> Is there any folder named Mint-X in /usr/share/icons/?

Yep. And as I wrote before I had copied icon there too (`cp /usr/share/icons/hicolor/scalable/apps/scudcloud* /usr/share/icons/Mint-X/apps/scalable/`) and updated icon cache.

> Do you mind to run a ls on /usr/share/icons/ folder and paste here?

```
14:23:06 [yz@local][w:1][j:0][~]> ls /usr/share/icons/
cab_extract.png        Faenza               locolor       Mint-X-Dark    Mint-X-Yellow
cab_view.png           gnome                LoginIcons    Mint-X-Grey    ubuntu-mono-dark
default                gnome-colors-common  mate          Mint-X-Orange  ubuntu-mono-light
DMZ-Black              gnome-wise           menta         Mint-X-Pink    unity-icon-theme
DMZ-White              hicolor              Mint-X        Mint-X-Purple  unity-webapps-applications
elementary             HighContrast         Mint-X-Aqua   Mint-X-Red
elementary-monochrome  Humanity             Mint-X-Blue   Mint-X-Sand
elementary-mono-dark   Humanity-Dark        Mint-X-Brown  Mint-X-Teal
```

**Comment by raelgc** [comment]
We're not the only with problems with SVG icons in Mate: http://forums.mate-desktop.org/viewtopic.php?f=2&t=3194

Maybe if we try convert to PNG and place in `Mint-X` folder.

**Comment by yermulnik** [comment]
I've got a bunch of Scudcloud icons:

```
scudcloud-attention-1.svg
scudcloud-attention-2.svg
scudcloud-attention-3.svg
scudcloud-attention-4.svg
scudcloud-attention-5.svg
scudcloud-attention-6.svg
scudcloud-attention-7.svg
scudcloud-attention-8.svg
scudcloud-attention-9-plus.svg
scudcloud-attention-9.svg
scudcloud-attention.svg
scudcloud.svg
```

Should I try to convert all of them?

**Comment by raelgc** [comment]
@yermulnik Yes, please.

Few notes on it:
1. Use [this scudcloud.svg icon](https://github.com/raelgc/scudcloud/blob/363-no-notification-area-icon-in-mate/share/icons/hicolor/scudcloud.svg) instead of the one you already have. Others are fine to use.
2. Put PNG icons inside this folder `/usr/share/icons/Mint-X/22x22/apps/`.
3. Update icons cache.
4. Restart ScudCloud.

**Comment by yermulnik** [comment]
Nothing changed =(

```
/usr/share/icons/Mint-X/apps/22/scudcloud-attention-1.png:      PNG image data, 22 x 22, 8-bit colormap, non-interlaced
/usr/share/icons/Mint-X/apps/22/scudcloud-attention-2.png:      PNG image data, 22 x 22, 8-bit colormap, non-interlaced
/usr/share/icons/Mint-X/apps/22/scudcloud-attention-3.png:      PNG image data, 22 x 22, 8-bit colormap, non-interlaced
/usr/share/icons/Mint-X/apps/22/scudcloud-attention-4.png:      PNG image data, 22 x 22, 8-bit colormap, non-interlaced
/usr/share/icons/Mint-X/apps/22/scudcloud-attention-5.png:      PNG image data, 22 x 22, 8-bit colormap, non-interlaced
/usr/share/icons/Mint-X/apps/22/scudcloud-attention-6.png:      PNG image data, 22 x 22, 8-bit colormap, non-interlaced
/usr/share/icons/Mint-X/apps/22/scudcloud-attention-7.png:      PNG image data, 22 x 22, 8-bit colormap, non-interlaced
/usr/share/icons/Mint-X/apps/22/scudcloud-attention-8.png:      PNG image data, 22 x 22, 8-bit colormap, non-interlaced
/usr/share/icons/Mint-X/apps/22/scudcloud-attention-9-plus.png: PNG image data, 22 x 22, 8-bit colormap, non-interlaced
/usr/share/icons/Mint-X/apps/22/scudcloud-attention-9.png:      PNG image data, 22 x 22, 8-bit colormap, non-interlaced
/usr/share/icons/Mint-X/apps/22/scudcloud-attention.png:        PNG image data, 22 x 22, 8-bit colormap, non-interlaced
/usr/share/icons/Mint-X/apps/22/scudcloud.png:                  PNG image data, 22 x 22, 8-bit colormap, non-interlaced
```

I also made 24px icons as my mate-panel is 24px and copied those 22px and 24px icons into hicolor theme folder and updated icon cache: `-rw-r--r-- 1 root root 15541324 Jan 29 17:42 /usr/share/icons/Mint-X/icon-theme.cache` (did for hicolor icon cache too).

**Comment by raelgc** [comment]
The last idea that came to my mind: try copy to the `gnome` folder too and update icons cache.

**Comment by yermulnik** [comment]
Already did that. And even tried to change icon themes via Mate's GUI to make it reread settings in its "natural" way. Still no luck =( Guess the problem is deeper than we think of it.
Than for ideas and trying to help.

**Comment by raelgc** [comment]
If **licq** icon is properly displayed, let's try mimic it:
1. Go to `/usr/share/icons` folder
2. Run `find -name licq*`

Then we should try change (or remove) **licq** icons, one by one, to see which of the results icon is really used.

If success on this, we can try mimic **licq** icons type and placement.

**Comment by yermulnik** [comment]
Licq has no icons in `/usr/share/icons` directory at all, so I experimented with Pidgin. But removing icons from `/usr/share/icons` influenced only menus, but not notification area icons %-\

JFYI: I've googled (https://www.dropboxforum.com/hc/en-us/community/posts/201545695?page=2#comments) that running Viber under `strace` fixes the icon appearance problem. I tried. And it's true: running Viber under `strace` makes icon in notification area appear every time Viber is started. But it doesn't work with Scudcloud =(

**Comment by raelgc** [comment]
Nice finding, @yermulnik.

And if you search for Viber icons?

**Comment by yermulnik** [comment]
Same as with Pidgin's icons: icon disappeared from panel menus, but shows in notification area. Seems that mate's notification area uses icons from some other place than `/usr/share/icons/`.

**Comment by raelgc** [comment]
Just to double check: `File` >`Close to Tray` is activated right?
Em 29/01/2016 21:33, "George L. Yermulnik" notifications@github.com
escreveu:

**Comment by yermulnik** [comment]
WOW! That wasn't obvious to me %-\ Thanx!!! And sorry for the noise =)
I'm closing this issue! Thanx again!

**Comment by raelgc** [comment]
No problem, @yermulnik! I'm glad it worked! Have a great weekend! :)

**Comment by yermulnik** [comment]
Thanx! You too! =)

By the way, maybe some comment on that option would help dummies like me to understand that tray icon only shows when option is turned on =)
