### ISSUE TITLE
Please, bring back b&w tray icon.

### ISSUE THREAD

**Issue by artyomxx** [raelgc/scudcloud#369]
Or at least make it an option.

This looks ridiculous:
![image](https://cloud.githubusercontent.com/assets/888428/12685407/3ea5b47a-c6d5-11e5-935d-bae3c27fa3aa.png)

**Comment by drohm** [comment]
I would like this as well.  It would match darker themes better.

**Comment by raelgc** [comment]
Which DE are you using and which is the used icon theme?

**Comment by artyomxx** [comment]
Elementary OS, Pantheon desktop environment, stock theme.

**Comment by raelgc** [comment]
Which is the folder for Pantheon icons theme? Usually a sub-folder for `/usr/share/icons/`.

**Comment by artyomxx** [comment]
Um... I'm not sure I understand what are you talking about.
But... There's a folder `/usr/share/icons/elementary` and there is a lot of other folders inside. I guess, they use `/usr/share/icons/elementary/panel` for icons in tray. There again are two folders inside: `16` and `24`.

Hope this helps.

**Comment by raelgc** [comment]
@lolwhoami Yes, this works, but we still have some work to do.

So, please:
1. Copy all ScudCloud light icons into elementary scalable icons folder: `sudo cp /usr/share/icons/ubuntu-mono-dark/scalable/apps/scudcloud* /usr/share/icons/elementary/scalable/apps/` (if these sub folders `scalabable/apps` do not exists, create them).
2. Update Elementary theme icon cache: `sudo gtk-update-icon-cache /usr/share/icons/elementary`.
3. Close ScudCloud and re-open.

**Comment by raelgc** [comment]
Let me know if it works or not :)

**Comment by artyomxx** [comment]
Yes, it works. Thanks. But is seems like it may be lost with OS upgrade, right?

**Comment by raelgc** [comment]
Yes it'll, but it was a test. My plan is to include official support.

Thanks for verify!

**Comment by raelgc** [comment]
@lolwhoami Can you tell me if Elementary uses a totally white color for icons?
