### ISSUE TITLE
Package for Arch Linux AUR

### ISSUE THREAD

**Issue by topher1kenobe** [raelgc/scudcloud#37]
I'd love to see a packager for the AUR.  Thanks!

**Comment by raelgc** [comment]
@topher1kenobe Can you run, please, a test for me?

Can you check if this [tool](https://bbs.archlinux.org/viewtopic.php?id=187558) works to convert the packages?

The debian packages are located here (you need just the `.deb` files): https://launchpad.net/~rael-gc/+archive/ubuntu/scudcloud/+packages

Trusty is the current Ubuntu version. Short explanation of the packages: 
- `scudcloud` is the program itself
- `libqtwebkit-qupzillaplugins` is just a recommended package that will provide spell checker. 
- `fonts-lato` is just the package (recommended too) with the font family used by Slack.

**Comment by raelgc** [comment]
@topher1kenobe Can you try with the following instructions?

First: you'll need this package (linked here to `64bits`): https://www.archlinux.org/packages/extra/x86_64/python-pyqt4/

Then run in term:

``` bash
wget https://github.com/raelgc/scudcloud/archive/v1.0.21.tar.gz
tar -xvf v1.0.21.tar.gz
cd scudcloud-1.0.21
SOURCE="scudcloud-1.0"
INSTALL="/opt/scudcloud"
sudo mkdir -p $INSTALL/lib
sudo mkdir -p $INSTALL/resources
sudo cp $SOURCE/lib/*.py $INSTALL/lib
sudo cp $SOURCE/resources/* $INSTALL/resources
sudo cp $SOURCE/scudcloud $INSTALL
sudo cp $SOURCE/LICENSE $INSTALL
sudo cp $SOURCE/scudcloud.desktop usr/share/applications
sudo cp $SOURCE/systray/hicolor/* usr/share/icons/hicolor/scalable/apps
sudo ln -sf $INSTALL/scudcloud /usr/bin/scudcloud
```

**Comment by michaelherold** [comment]
@topher1kenobe I've created an Arch PKGBUILD and [put it on the AUR](https://aur.archlinux.org/packages/scudcloud/). If you have issues, please let me know [at my Github repository](https://github.com/michaelherold/PKGBUILDs).

@raelgc Would you be interested in a PR adding this package to the readme?

**Comment by raelgc** [comment]
@michaelherold I'd love it! :)
Additionally, are you aware if there is a way I can create the Arch package under Ubuntu?

**Comment by michaelherold** [comment]
Cool, I'll write up something and send you a PR soon.

Arch is very different from Ubuntu, in that any user-distributed packages are distributed as scripts (called PKGBUILDs) that are built from source. As such, there isn't a way to "create" the Arch package under Ubuntu since the package isn't distributed. If you would like to know more about the Arch Build System, you can read about it at the Arch wiki; I'd suggest checking out [the article on PKGBUILD](https://wiki.archlinux.org/index.php/PKGBUILD), the one on the [Arch User Repository](https://wiki.archlinux.org/index.php/Arch_User_Repository), and [the one on creating packages](https://wiki.archlinux.org/index.php/Creating_packages)

I'm happy to maintain the Arch package, since I'm using it for my work chat. I'm planning to put together a scudcloud-git package as well, which will allow people to build your master branch at any time.

**Comment by topher1kenobe** [comment]
Whoa, I didn't see any of the previous posts for me!  I'm really sorry folks.

I installed from AUR and it installed fine, but doesn't want to run:

```
$ scudcloud 
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.4/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.4/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.Notifications': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/scudcloud", line 18, in <module>
    main = ScudCloud()
  File "/opt/scudcloud/lib/scudcloud.py", line 34, in __init__
    notify2.init(self.APP_NAME)
  File "/opt/scudcloud/lib/notify2.py", line 96, in init
    '/org/freedesktop/Notifications')
  File "/usr/lib/python3.4/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.4/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.4/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.4/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.4/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
```

I'll try some of the other stuff and get back to you.

**Comment by topher1kenobe** [comment]
@raelgc I tried the instructions you mentioned, and I got the same result as my above post.

**Comment by raelgc** [comment]
@topher1kenobe I think you need a `python3-dbus` package. Is [this one](https://www.archlinux.org/packages/extra/i686/python-dbus/files/)?

**Comment by michaelherold** [comment]
Yep, looks like there's a missing dependency. @topher1kenobe I've updated the PKGBUILDs, let me know if they help.

**Comment by topher1kenobe** [comment]
@michaelherold I get the same error just installing scudcloud.  

Then I installed python-dbus and still got the same error.  :(

**Comment by michaelherold** [comment]
Following up in michaelherold/PKGBUILDs#1

**Comment by topher1kenobe** [comment]
The package for Arch works now.  It requires a notification daemon to be set up in dbus.

**Comment by raelgc** [comment]
I'm glad you got it working @topher1kenobe!

**Comment by michaelherold** [comment]
@raelgc I'm putting together a patch that would make a notification daemon optional. Would you be interested in such a thing?

**Comment by raelgc** [comment]
@michaelherold I'm always interested in making the program easy to run :)
What will be the effect when this daemon is not available?

**Comment by michaelherold** [comment]
I'm planning to just have [notify](https://github.com/raelgc/scudcloud/blob/master/scudcloud-1.0/lib/scudcloud.py#L256) silently return unless it's configured.

**Comment by raelgc** [comment]
Just out of curiosity: is hard to get the notifications configured by the package?

**Comment by michaelherold** [comment]
Arch is a build-it-yourself OS, where nothing is installed by default. There are at least 7 notification daemons and 5 desktop environments that can provide the functionality. I'm not sure of a way to say "I depend on a service" in a PKGBUILD, though that's something I'm looking into.

Really though, we should rescue this exception since it's a bad user experience to give the cryptic error message that Topher was experiencing.

**Comment by raelgc** [comment]
@michaelherold Got it, thanks for the explanation!

So, additionally, can you please add the info in your package instructions that if user wants notification he/she needs to install any notification daemon?

**Comment by michaelherold** [comment]
I'll add it in the PR for optional notifications.

**Comment by beeender** [comment]
Any way to make the spell checker work in Arch Linux? Arch doesn't have libqtwebkit-qupzillaplugins pgk now...

**Comment by michaelherold** [comment]
@beeender I'm not sure. I tried working with the qtwebkit-plugins-git package, but wasn't able to get it to link.

A better place for this discussion would be [the AUR](https://aur4.archlinux.org/packages/scudcloud/), since everyone there is an Arch user.
