### ISSUE TITLE
Fedora 22 install issue

### ISSUE THREAD

**Issue by imunhatep** [raelgc/scudcloud#371]
# dnf install  scudcloud -b --allowerasing

Last metadata expiration check performed 0:47:45 ago on Tue Feb  2 11:13:49 2016.
Error: nothing provides /bin/python3 needed by scudcloud-1.5.0-1.1.noarch

Probably resolved: https://ask.fedoraproject.org/en/question/77243/nothing-provides-binpython3/

**Comment by raelgc** [comment]
Hi @Imunhatep, thanks for raising and pointing the direction.

Can you then, please, create a pull request with the correct `.spec` file?

**Comment by raelgc** [comment]
Thank you @Imunhatep!
