### ISSUE TITLE
Cannot switch to n-th team using keyboard

### ISSUE THREAD

**Issue by Slater91** [raelgc/scudcloud#374]
Since I updated to version 1.5.0 I can no longer switch to a specific team (the second out of three) using the keyboard shortcut ctrl+tab. I currently have three teams set up.
One curious bit is that I can't switch using ctrl+tab, but I usually can using shift+ctrl+tab. It's as if there was some kind of "wall" which separates the teams in a circular order, so you have to go back to get to the ones on the other side. Alternating the two ways of switching back and forth you get to select the appropriate team, but it's obviously not the way it is meant to work.

Using Scudcloud 1.7 on Linux Mint 17.3 64-bit.

**Comment by raelgc** [comment]
Indeed @Slater91, the <kbd>Ctrl+Tab</kbd> is not working as expected. Just the <kbd>Ctrl+[number]</kbd> shortcut is working.

**Comment by raelgc** [comment]
@Slater91 For some reason, when I've restarted the app to test with debug enabled, the issue disappeared... Can you check if the same happens to you?

**Comment by raelgc** [comment]
Well, it works for some minutes, then got broken again. I'm debugging and it appears to be broken in LeftPane JS.

**Comment by raelgc** [comment]
Ok, found the issue. Fixing.
