### ISSUE TITLE
Channel list does not display more than 10 channels

### ISSUE THREAD

**Issue by edmundcraske** [raelgc/scudcloud#376]
Have just joined an existing team with a large number of channels (more than 10), and although the list is now scrollable (as per #309 ) and appears to have the right size for all of the channels, only the first 10 alphabetically appear to be shown.

**Comment by edmundcraske** [comment]
This also applies to the list of users you get when you click on Direct Messages - not sure if the same solution applies?

**Comment by raelgc** [comment]
Hi @edmundcraske and thanks for reporting this issue!

This is, indeed, a nice catch!

I've made a deep investigation on this, and noticed that this is a Slack internal behaviour: the number of returned channels in the list depends on the window resolution.

If I resize ScudCloud window and then click on channels, the number of returned teams will change.

I.e, unfortunately, this is not something that we can change or fix with CSS like #309.

**Comment by edmundcraske** [comment]
Is this functionality implemented differently to the slack web ui?

**Comment by raelgc** [comment]
This functionality is internal to Slack, we don't touch it. 

But Slack engine is aware it's running inside a desktop client, so it behaves differently then while inside a browser.

**Comment by raelgc** [comment]
To illustrate this, I'm adding screenshots of the channel list dialog under the inspelect.

Current team have 14 channels.

In a **big** resolution, all teams displayed:
![big_resolution](https://cloud.githubusercontent.com/assets/263302/12833130/ba4ef2b2-cb85-11e5-9da0-d94585de791a.png)

In a **small** resolution, only 10 teams displayed:
![small_resolution](https://cloud.githubusercontent.com/assets/263302/12833134/c4f8fb0e-cb85-11e5-804e-919b885cac70.png)

**Comment by edmundcraske** [comment]
Is there a way to make it paginate? Presumably that's what other clients do?

**Comment by raelgc** [comment]
The team list display is made by Slack itself, not by ScudCloud, like other clients do, including the official app.

The only UI we have control is over the leftpane.
