### ISSUE TITLE
Newly added team is sometimes forgotten

### ISSUE THREAD

**Issue by edmundcraske** [raelgc/scudcloud#378]
Sorry, found yet another bug! Not so obvious this one...

If I add a new team to Scudcloud, it works whilst the app is open, but the next time I start the app, it may or may not remember the new team.

I initially believed that this was related to a difference in the way that the app was closed down if I shut down my machine whilst it was still running, compared to manually quitting Scudcloud first (My system is Linux Mint Cinnamon 'Rebecca' 17.1 amd64). However, I added a team, and then manually quit, and it seemed to remember it when I started up, but has since forgotten it again.

In case it is relevant, this newly added team is the 5th one I have signed into.

**Comment by raelgc** [comment]
Hi again @edmundcraske!

No sorry, it's good we have all bugs listed here!

My guess this is related how the logic to load teams is handled.

Can you tell me if the newly team is listed in the config file? (In the `Domain` variable).

**Comment by raelgc** [comment]
Do you mind to send me your email (send to rael.gc@gmail.com)? This way I can add you in the ScudCloud Slack team and we can discuss in a faster way.

**Comment by edmundcraske** [comment]
Does seem to be, for now...

**Comment by raelgc** [comment]
Thanks for the feedback. I'll close this for now. If it get back, please, reopen.
