### ISSUE TITLE
Why I should use ScudCloud?

### ISSUE THREAD

**Issue by irfanfadilah** [raelgc/scudcloud#379]
Hello, I'm an Ubuntu user and really interested in this unofficial app..

But I have question, why I should use this app instead of the web version..?

Thanks,

**Comment by raelgc** [comment]
Hi @irfanfadilah, how are you?

Benefits of ScudCloud over using Slack in a browser:
- multiple teams support in one window with quick team switch,
- native system notifications,
- it'll follow your desktop activity (if correct packages are installed) and will keep online while you're logged in, like the OSX version),
- count of unread direct mentions at launcher/sytray icon,
- alert/wobbling on new messages,
- channels quicklist (Unity only),
- optional tray notifications and "Close to Tray".

Additionally, if for some reason ScudCloud do not met your expectations, you can try:
- [plaidchat](https://github.com/plaidchat/plaidchat): another open source client;
- [the official app](https://slack.com/downloads): supports Ubuntu and Fedora.

**Comment by irfanfadilah** [comment]
Hi @raelgc, thanks for your explanation.. :+1:

**Comment by raelgc** [comment]
You're welcome, @irfanfadilah! Feel free to ask any question!

**Comment by damianalvarez** [comment]
Hi, why I should use this app instead of the official beta version? (https://slack.com/downloads)

Thanks!

**Comment by raelgc** [comment]
Hi @damianalvarez, how are you?

ScudCloud was started in a time where Slack has no support for Linux. Today we have the official app, and it works very well.

Later, ScudCloud was continued due 3 benefits: 
- users claiming to continue due to general smaller memory footprint;
- support for more distros;
- better Unity integration.

**Comment by raelgc** [comment]
@damianalvarez Let me know if I can help you with any additional info :)
