### ISSUE TITLE
Email addresses in code blocks are not displayed with a mono spaced font

### ISSUE THREAD

**Issue by brad** [raelgc/scudcloud#387]
When I write a code block that contains an email address, it gets converted to a link and a non-mono spaced font. I checked in the slack web app and there the email does not get converted to a link, which avoids the problem.

**Comment by raelgc** [comment]
Hi @brad and thanks for reporting this issue.

While this is annoying, I'm afraid we don't have any control over it. ScudCloud is just a simple wrapper for Slack: we provide few callbacks to Slack call ScudCloud for notifications and other few interactions.

So, Slack just detects it's a desktop client and automatically turns emails in links.

You can see this in the official client too.
