### ISSUE TITLE
Unmet python3 dependency on ubuntu 12.04

### ISSUE THREAD

**Issue by agustinh17** [raelgc/scudcloud#388]
Hello! I'm having an issue while trying to install on ubuntu 12.04

The error message I get is:

```
The following packages have unmet dependencies:
 scudcloud : Depends: python3 (>= 3.4) but 3.2.3-0ubuntu1.2 is installed.
             Depends: python3-dbus but it is not going to be installed.
             Depends: python3-dbus.mainloop.qt but it is not going to be installed.
             Depends: python3-notify2 but it is not going to be installed.
             Depends: python3-pyqt4 but it is not going to be installed.

```

Already tried installing python3.4 and it didn't help since the dependency is python3 >=3.4 but I have python3=3.2.3-0ubuntu1.2 and python3.4 instead.

Any help would be appreciated!

(I've already considered the libqtwebkit4 backport mentioned in the Readme)

**Comment by raelgc** [comment]
Hi @agustinh17,

Like stated in the `README` file, for Ubuntu 12.04 (Precise Pangolin), **additionally** you'll need to update `qtwebkit`: Slack is not compatible with `libqtwebkit4` package shipped with 12.04, hanging in the `Loading` screen.

Please add the following PPAs (for updated `qtwebkit`):

``` term
sudo add-apt-repository -y ppa:immerrr-k/qtwebkit4-backport
sudo apt-get update
```

**Comment by agustinh17** [comment]
@raelgc I've done this already - and I made it clear at the end of my message :)

**Comment by raelgc** [comment]
Can you try add the `deadsnakes` PPA too?

```
sudo add-apt-repository ppa:fkrull/deadsnakes
sudo apt-get update
sudo apt-get install python3.4
```

**Comment by raelgc** [comment]
I think in the past we had not specified any python 3 specific version.

**Comment by agustinh17** [comment]
Thanks @raelgc I tried that as well but I'm still getting an error because the unmet dependency is python3 >=3.4 but I have python3=3.2.3-0ubuntu1.2 and python3.4 instead.

Anything else I could try?

**Comment by raelgc** [comment]
Sorry @agustinh17, but it's not clear to me: do you have `3.2.3` or `3.4` installed?

**Comment by agustinh17** [comment]
@raelgc 

python3 version 3.2.3-0ubuntu1.2
AND
python3.4 version 3.4.4-1+precise1

**Comment by raelgc** [comment]
This is weird. In theory, `3.4` should replace `3.2.3`. Or at least, makes ScudCloud works. I'll download a 12.04 ISO and try something to help you.

**Comment by raelgc** [comment]
Ok, after play a bit on 12.04, I got it working, using the `python setup` process, over the system python3.

The `deadsnakes` PPA was not required, and for some weird reason, their python3.4 do not replaces system python3.2.

So I'll change the package to require just `python3`. It was this way, but in the transition to the proper python package, I think `stdeb` (the tool to generate a debian package using a python package) suggested to be `>=3.4` and I kept this way.

Give me few minutes and I'll upload a new package. For now, remove the `deadsnakes` PPA and `python3.4` and `python3.4-minimal`.

**Comment by raelgc** [comment]
I'm facing a curious situation: the package display errors while building for Precise. And if I build it for Trusty then backport, it'll still require a python greater then installed one.

I got ScudCloud working only installing as a python package (after clone the repo, run `sudo python3 setup install --record install.txt`).

**Comment by raelgc** [comment]
@immerrr Any ideas?

**Comment by immerrr** [comment]
@raelgc: yep, I have run into the same problem, but backporting python proved a tad more difficult than I thought. The problem is that there are a few scudcloud dependencies that are binary libs that themselves depend on the major version of python they were built for. E.g. precise packages will depend on `python (>= 3.2), python (<< 3.3)`, so they are incompatible with the fresher python version and you have to backport all of them. You must also backport all binary python3 libraries you're going to install in the future, because of the same incompatibility.

Also, does scudcloud really need `python3` or would `python3-minimal` be enough? That would simplify backporting a bit, as `python3` also brings in `python3-tk` and the like to the table.

**Comment by immerrr** [comment]
As for the build error, if you mean the error you see in https://launchpadlibrarian.net/238041857/buildlog_ubuntu-precise-i386.scudcloud_1.11-1_BUILDING.txt.gz, it should be fixable by adding `dh-python` to `Build-Depends`.

Or is it any other error?

**Comment by immerrr** [comment]
> I got ScudCloud working only installing as a python package (after clone the repo, run sudo python3 setup install --record install.txt).

That's great news, meaning that the scudcloud source supports 3.2 (I was afraid it would not after the "upgrade") and fixing the build procedure will work eventually without any other backports.

**Comment by raelgc** [comment]
@immerrr Exactly this error. Searching throw Internet, I found that `dh-python` is not available on 12.04 (the tool used to build the `.deb` package based in the `setup.py` file).

Anyway, to get it working on 12.04, I've installed `python3`, `python3-setuptools`, `python3-dbus`, `python3-qt4` and `python3-dbus.mainloop.qt`.

**Comment by raelgc** [comment]
In theory, a package for 12.04 could be generated using the old model: in the `/debian` folder, a `install` file telling where to install files. But I'm not willed to create a separate branch only for 12.04 and maintain it.

My suggestion is to update the `README.md` file changing 12.04 instructions to use the python `setup`.

**Comment by agustinh17** [comment]
@raelgc I can confirm that after installing the suggested packages and running `python setup.py`  everything works! Updating the readme instead of maintaining a different branch makes total sense.

Just a minor comment, it should be `python3-pyqt4` instead of `python3-qt4`

Thanks a lot for your help!

**Comment by raelgc** [comment]
Thank you for the correction, @agustinh17!

**Comment by raelgc** [comment]
@agustinh17 After a huge help from @immerrr, package for 12.04 got fixed. Now you can install using `apt`!

**Comment by agustinh17** [comment]
@immerrr @raelgc Thanks a lot, you guys rock!
