### ISSUE TITLE
Profile display does not work when clicking on user name.

### ISSUE THREAD

**Issue by bstein-clever** [raelgc/scudcloud#396]
When I'm in the official Slack client (or the web one), I get a display of the user's profile picture and name, like this:
![image](https://cloud.githubusercontent.com/assets/11928921/13089438/6548866a-d4a5-11e5-8a10-7ea9adf0cfe6.png)

However, in scudcloud, these do not display. Instead I just get a white box, like so:
![image](https://cloud.githubusercontent.com/assets/11928921/13089334/fd1c067a-d4a4-11e5-97e9-21e6f5ee4f1b.png)

It would be great to get a picture, or at least a visible name.

Thanks!

**Comment by raelgc** [comment]
Hi @bstein-clever and thanks for reporting this issue!

I'm inspecting and it appears to be a limitation of webkit version included in ScudCloud. The profile background is using this style:

``` css
background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0) 34%, rgba(0,0,0,0.2) 66%, rgba(0,0,0,0.2) 83%, rgba(0,0,0,0.6)), url('https://secure.gravatar.com/avatar/<id>.jpg?s=512&d=https%3A%2F%2Fslack.global.ssl.fastly.net%2F7fa9%2Fimg%2Favatars%2Fava_0005-512.png'), url('https://secure.gravatar.com/avatar/<id>.jpg?s=48&d=https%3A%2F%2Fslack.global.ssl.fastly.net%2F66f9%2Fimg%2Favatars%2Fava_0005-48.png');
```

And qtwebkit is displaying this as `Invalid property value`.

As a workaround for now: you can click again in the profile picture, then it'll be opened in the right pane (this time, properly displayed).

**Comment by raelgc** [comment]
More exactly, this is the CSS property not accepted: 

```
linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0) 34%, rgba(0,0,0,0.2) 66%, rgba(0,0,0,0.2) 83%, rgba(0,0,0,0.6))
```

**Comment by raelgc** [comment]
Probably we can solve it using `-webkit-linear-gradient`.

**Comment by raelgc** [comment]
It'll be a bit more complicated. We'll need to watch when user click in a profile and then apply this.

I'm able to do this with:

``` javascript
$('body').delegate(
    $("a[href^='/team']"), 
    'click', 
    function(){ 
        var obj = $('.member_preview_link.member_image.thumb_512');
        if(obj.length > 0){
            var style = obj.attr('style').replace('linear-gradient', '-webkit-linear-gradient'); 
            obj.attr('style', style);
        }
    }
);
```

**Comment by bstein-clever** [comment]
Interesting. Thanks for the info and fast responses!
That's a nice workaround, I'd previously been using a Ctrl-K to open up the switcher and then jumping to the user to see their profile.

I'm fine with whatever solution you think is best - I just find it frustrating that I can't click a username to get more info.

**Comment by bstein-clever** [comment]
Confirmed working. Thanks for the super-fast turnaround!

**Comment by raelgc** [comment]
Welcome! Thank you for reporting this!

**Comment by bstein-clever** [comment]
This seems to be happening again - I think probably for a bit, but I don't normally look at people's profiles.
Thanks!

**Comment by bstein-clever** [comment]
(I can't find a way to reopen - let me know if I should create a new issue.)

**Comment by raelgc** [comment]
Re-opened!
