### ISSUE TITLE
Unable to drag and drop attachments

### ISSUE THREAD

**Issue by justin8** [raelgc/scudcloud#399]
When opened in a browser I can drag and drop a file and click upload, or hold shift while dragging and have it instantly upload. Dragging an image for example in to scudcloud results in it opening the image instead of the slack app.

Running on Arch linux, using Gnome 3

**Comment by raelgc** [comment]
Hi @justin8 and thanks for reporting this issue!

Sounds like an issue between Qt clipboard and integration with your desktop environment.

In my case, I'm using Ubuntu/Unity with default clipboard manager:

http://www.screencast.com/t/7I6JddeSwgCn

1 - Which desktop environment are you using?
2 - Are you using a different clipboard manager?
3 - Can you try drop the image exactly inside the Slack message text input?

**Comment by justin8** [comment]
1. I'm using gnome 3
2. I'm using clipit
3. Apparently I can no longer replicate the problem; dragging and dropping it now works as expected, with the exception that shift+drop doesn't instantly upload it, it has the pop up as though shift wasn't being held down.

Thanks for the quick response though.

**Comment by raelgc** [comment]
I'm glad it worked!

In case you start to face this issue again, feel free to re-open! :)
