### ISSUE TITLE
No module named 'setuptools'

### ISSUE THREAD

**Issue by slashinfty** [raelgc/scudcloud#402]
Running BunsenLabs Linux (based on Debian Jessie), and attempted the manual install.

`matt@debian:~/Downloads/scudcloud-1.16$ sudo python3 setup.py install

Traceback (most recent call last):

  File "setup.py", line 3, in <module>
    from setuptools import setup

ImportError: No module named 'setuptools'
`

I'm unsure if this is an installation error, or a distribution error.

**Comment by stieg** [comment]
Do you have the python3 setuptools package installed locally?  Sometimes it doesn't come with the system by default.  In example, on my fedora 23 system the package that provides that functionality is `
python3-setuptools-18.0.1-2.fc23.noarch`

**Comment by raelgc** [comment]
@stieg is right. I'll update `README` to include this info.

@mathbraddock, on Debian/Ubuntu, the package is `python3-setuptools`.
