### ISSUE TITLE
Notification icon cannot be loaded with dunst

### ISSUE THREAD

**Issue by blueyed** [raelgc/scudcloud#404]
I use [dunst](https://github.com/knopwob/dunst) for displaying notifications, and it fails to display the icon with messages from scudcloud:

> Could not load icon: '/tmp/scudcloud_U096BTFNX.png'

This is because this `.png` file is a jpeg image.
Converting it to png fixes it.

This might be related to the packaging - I am using https://aur.archlinux.org/packages/scudcloud/.

**Comment by raelgc** [comment]
Hi @blueyed and thanks for reporting this issue!

I've fixed this and published new GitHub release and Ubuntu packages.

Sorry for the inconvenience!
