### ISSUE TITLE
Hide Menu Bar

### ISSUE THREAD

**Issue by janickm** [raelgc/scudcloud#406]
Would it be possible to add a (GUI) switch to hide the menu bar (`File` / `Edit` / ...) in the `View` menu item, such that the bar is not shown anymore, but the items can be accessed with `Alt+F` / `Alt+E` / ... ?

**Comment by raelgc** [comment]
Hi @ph03,

This was implemented on #233. But this option is visible only when environment is not Unity.

**Comment by janickm** [comment]
Ok - so I'm running GNOME Shell 3.10.4 on Ubuntu 14.04 and the "hide" menubar option is not shown in the `View` item

**Comment by raelgc** [comment]
Right, thank you for the feedback. The solution will be make this menu entry always available.

While this is not fixed, you can edit file `/usr/lib/python3/dist-packages/scudcloud/scudcloud.py` and edit lines `268/269`.

Actually they're like this:

``` python
        if Unity is None:
            viewMenu.addAction(self.menus["view"]["hidemenu"])
```

Change to this:

``` python
        viewMenu.addAction(self.menus["view"]["hidemenu"])
```

Save, and restart ScudCloud.

**Comment by janickm** [comment]
Thanks, working great! :) Will you add this into the next release?

The bar can be toggled with `F12`, however, when it's hidden, also the `Alt+x` accelerators do not work. Is it possible to make these available with a hidden bar as well?
