### ISSUE TITLE
Giant system tray icon in Cinnamon.

### ISSUE THREAD

**Issue by cdysthe** [raelgc/scudcloud#410]
The system tray icon when running Scudcloud on Cinnamon is far too big. In Unity it has the correct size. See screenshot.

![screenshot from 2016-03-07 09 03 29](https://cloud.githubusercontent.com/assets/1281031/13571719/b572a676-e444-11e5-807d-c877c00db1ea.png)

**Comment by raelgc** [comment]
Hi @cdysthe, thanks for reporting this issue.

What is the expected tray icon size in Cinnamon?

**Comment by cdysthe** [comment]
The expected size is the same as the other system tray icons. I think it's 16x16 pixels. You can see the size of the other icons in the screenshot. Skype has the correct size when I run it, but Scudcloud does not.

**Comment by raelgc** [comment]
Thank you for the answer, @cdysthe!

Please, can you additionally tell which version are you using?

The approach we've tried was to place a SVG, so the DEs can resize it to required dimension. But some DEs will just prefer a fixed size PNG.

It's no clear to me if Cinnamon is trying to use a PNG or is picking the SVG without resize.

First step will be identify which file it's using.

I'll need to install Cinnamon in a VM and play with it a bit. 

If you someone help with this: we'll need to play with the `/usr/share/icons` folder, re-generate the icon cache and probably restart Cinnamon to check if it's working.

**Comment by cdysthe** [comment]
Sorry about that. Here goes.

Scudcloud 1.18-1
Cinnamon 2.8.6 on Linux Mint 17.3 

I will see if I can make sense of the icons, but I do not know how to re-generate the icon cache. I'm just a user trying to have all our employees on Scudcloud at all times :)

**Comment by raelgc** [comment]
@cdysthe Thank you for the update!

And no sorry, you already reported a lot of useful issues here! Thank YOU for spend your time helping to improve ScudCloud!

The command in Unity is `sudo update-icon-cache` and in Gnome is `sudo gtk-update-icon-cache`. But you need to run in the folder where the icons are located.

But I hope today at my night I'll have sometime to investigate this.

**Comment by edmundcraske** [comment]
I'm not seeing this issue on Linux Mint 17.1 (Cinnamon version 2.4.8) but I guess there could be some changes in Cinnamon between 2.4 and 2.8 that might explain it?

**Comment by raelgc** [comment]
@cdysthe Are you still facing this issue?
