### ISSUE TITLE
Sound notification not working when switching active sound device

### ISSUE THREAD

**Issue by oblitum** [raelgc/scudcloud#418]
This is the only issue I have with this awesome client. It should probably be related with #120, but for me, no-sound is happening in specific situations.

These are the situations that I get no notification sound and how I fix it, which is kind of annoying since
I have to do this frequently:
- When I start the application, I have to check whether notification sounds are working by going to the notification sound configurations and switching between the several kind of sounds. What's very common to happen is that, for some unknown reason, the sound I last configured will not work just after starting the application, nor will it make any sound when I go to the configuration pane and click on it, it gets muted, and so, I have to chose another random sound (it seems there's some kind of delay to download these sounds when clicking) and it will work. When I start the application again there will be a chance this new configured sound will not work, nor will it make any sound on the configuration pane too, so I have to chose another one, even the former one that didn't work now does some noise.
- When I turn my bluetooth headphones, or generally when switching the sound device, I have to do the same process as before because notifications are muted.

System:
- Arch Linux with Gnome 3.

**Comment by oblitum** [comment]
I'm on a slow network on purpose, and clicking the several sound options frequently just gives no sound at all when selecting. My feeling is that this has to do with the fact that these sound notifications have to be downloaded instead of obtained from cache and this may fail/timeout silently.

**Comment by raelgc** [comment]
Hi @oblitum and thanks for reporting this issue!

In few days I'll be switching to Ubuntu 16.04, so probably I'll face the sound issues again.

About the cache: there is a configured cache saved at `~/.config/scudcloud/data7`. Anyway, like you said, the sound appears to be played always online.

I saw that always when Slack sends a notification to ScudCloud, it send info about a sound to play. If I find a way to avoid play the web sounds, maybe we could include sounds at the install and them play them offline.

**Comment by oblitum** [comment]
That would be cool, this sure relates with having to download them all the time, and should be more issue prone upon start.

**Comment by raelgc** [comment]
@oblitum One stuff that I've noticed (in Ubuntu 14.04) is that sometimes the sound is played in the old active device. Can you check this, please?

**Comment by oblitum** [comment]
@raelgc yes, this happened to me too if I recall correctly, but I think, in my system, only with scudcloud

**Comment by oblitum** [comment]
May be related: https://unix.stackexchange.com/questions/362223.

Closing as I'm not using the application anymore, nor the system I was in to reproduce the issue.

**Comment by raelgc** [comment]
Thank you for the updates, @oblitum!
