### ISSUE TITLE
scudcloud never loading, 100% CPU usage

### ISSUE THREAD

**Issue by tchwpkgorg** [raelgc/scudcloud#419]
Since yesterday, scudcloud won't load for me.

In the interface it just shows "Loading ..."; in top, I can see it's using 100% CPU.

Version 1.20-1 on Ubuntu 15.10, 64 bit.

**Comment by raelgc** [comment]
Hi @tchwpkgorg and thanks for reporting this issue.

What if you start ScudCloud by command line?

Start it with debug enabled:

```
scudcloud --debug=True &
```

**Comment by tchwpkgorg** [comment]
Hmm, not that much happening:

```
$ scudcloud --debug=True
URL Changed: https://staffdotcom.slack.com/messages
```

And that's it.

**Comment by raelgc** [comment]
Any chance you're behind a proxy or something like that blocking Internet for ScudCloud?

**Comment by tchwpkgorg** [comment]
Nope, no proxy between me and the internet.

**Comment by tchwpkgorg** [comment]
BTW, the official Slack client work fine.

**Comment by raelgc** [comment]
Nice to hear that at least you're able to run the official app! This way you'll have a way to connect to Slack other then the browser! :)

Well, tomorrow with the beta release for 16.04 I'll install it and check it out.

**Comment by raelgc** [comment]
@tchwpkgorg Installed 16.04 today, and I cannot see this issue. 

If you remove your config file at `~/.config/scudcloud/`, still the same result?
