### ISSUE TITLE
Strip redirection code when copying links 

### ISSUE THREAD

**Issue by immerrr** [raelgc/scudcloud#42]
Right now if you type `www.google.com` into the chat window and copy the resulting link, it looks like the following: `https://slack-redir.net/link?url=http%3A%2F%2Fwww.google.com&v=3`

Would be nice to strip all but the url part.

**Comment by raelgc** [comment]
Well, I think we can try to improve this in one side, but in other try to keep the original behaviour.

I.e.: if the user directly click in the link, we keep the original behaviour: the URL will be redirected by `slack-redir.net`.

If the user right click and copy the link, then we can skip the redirect engine.

How about it?

**Comment by immerrr** [comment]
Yup, this is exactly what I have asked :)

**Comment by michaeldye** [comment]
I'd like this adjustment too.

**Comment by raelgc** [comment]
Appears that Slack team fixed this :)

**Comment by raelgc** [comment]
This is back and I'm working to fix it.

**Comment by raelgc** [comment]
Fixed and published. Please upgrade.
