### ISSUE TITLE
Cannot input spanish characters like í á é

### ISSUE THREAD

**Issue by elpraga** [raelgc/scudcloud#431]
They get inserted always like 'i 'a 'e
on Ubuntu 14.04 using the latest build April 15 2016 - 1.22-2

**Comment by raelgc** [comment]
Hi @elpraga and thanks for reporting this issue.

Which is your keyboard layout? 

This happens only on ScudCloud or any oher Qt program too?

**Comment by elpraga** [comment]
I guess It is es. I use setxkbmap es to se it. It works fine with other apps. Like firefox and chromium.

**Comment by elpraga** [comment]
I use fluxbox and some loose apps, but I cannot remember any app where it is not working. Can you give me an example on an broadly used qt app to try it? :D

**Comment by elpraga** [comment]
I can use czech characters like ěščřáž without problems, but when I want to include the spanish ones, I first have to press the accute and then the charater. Might that be an issue?

**Comment by elpraga** [comment]
Ok, I just installed JuffEd and tea. They are both simple editors build upon  Qt4 and they both have the same issue. Is there some other app I can try it with?

**Comment by raelgc** [comment]
Can you try this?

Open a terminal and run at home folder:

```
wget https://raw.githubusercontent.com/raelgc/win_us_intl/master/.XCompose
sudo apt-get -y install uim
im-config -n uim
```

Logout and login.

If **no** success, remove the `.XCompose` from your home folder and logout/login again.

**Comment by elpraga** [comment]
It is working now. I did not try to delete the  .XCompose file. any idea why it was not working with ibus?

**Comment by raelgc** [comment]
ibus doesn't support `.XCompose` file. I use a international keyboard, and my native language is brazilian portuguese, so I faced this issue too :)

**Comment by elpraga** [comment]
I moved .XCompose file to another directory and it still seems to be working fine using uim even without .XCompose file.

But it is really bothersome that it does not work by default in ibus. 

Is there a place to report it directly to ibus guys? As it affects every QT4 app?

**Comment by elpraga** [comment]
By the way.. 

Thanks for such a speedy reply @raelgc !! :smile:

**Comment by raelgc** [comment]
You're welcome! I'm glad to hear it worked!
