### ISSUE TITLE
Add another team without function

### ISSUE THREAD

**Issue by hekele** [raelgc/scudcloud#433]
Hi there, I tried to add another team, but the link "Sign in to another team" is without function. I tried it on two different machines. On one with three teams present and one with four teams... On both machines no reaction.

**Comment by cirelli94** [comment]
This is happening even to me. I'm unable to login to a team.

**Comment by raelgc** [comment]
Hi @hekele and @cirelli94, sorry about this.

Can you, please, start ScudCloud by the command line and see what is the output when you click to add another team?

Are you clicking in `File` -> `Sign in to Another team`?

**Comment by hekele** [comment]
Hi Rael, there is no output in the terminal, when I click on the link. 
It's not File > Sign in to another team. It's the link the drop down 
when you click on the name of the current team.

File > Sign in to another team is working fine :) Many thanks! That 
saved my day!

**Comment by raelgc** [comment]
Thank you for the feedback @hekele. Indeed, they improved the team menu some time ago, and the webkit version used in ScudCloud is missing the click action. I'll commit a fix to force catch the click.

**Comment by cirelli94** [comment]
I was already in a team, and the `File -> Sign in to Another team` doesn't work to me!

From the terminal:

```
cirelli@asus:~$ scudcloud &
[1] 8957
cirelli@asus:~$ /usr/lib/python3/dist-packages/scudcloud/notifier.py:3: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python3/dist-packages/scudcloud/scudcloud.py:27: PyGIWarning: Unity was imported without specifying a version first. Use gi.require_version('Unity', '7.0') before import to ensure that the right version gets loaded.
  from gi.repository import Unity, Dbusmenu
"sni-qt/8957" WARN  10:25:16.803 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
SpellCheck: Language = "it_IT" 

```

**Comment by cirelli94** [comment]
I solved doing: 
rm -rf ./.config/scudcloud
