### ISSUE TITLE
Long team names overflow

### ISSUE THREAD

**Issue by Brottweiler** [raelgc/scudcloud#437]
# Native browser client

![](https://i.imgur.com/lQmlQZb.png)
# Scudcloud

![](https://i.imgur.com/H3Fbjtf.png)

As you can see, if the team name is long enough it will go outside the boundary and overflow.

---

**Distro**: Archlinux

**Comment by raelgc** [comment]
This is an interesting one. We have absolutely no controle over this. I'll check if maybe it's a custom CSS rule getting ignored by the used webkit version.

Maybe it's time to change to a new engine.
