### ISSUE TITLE
Fonts differ from browser

### ISSUE THREAD

**Issue by Brottweiler** [raelgc/scudcloud#440]
I am not sure what the case is in the official slack desktop app, but I noticed from Chrome the fonts do differ, and they look uglier in Scudcloud. I do have [lato](https://aur.archlinux.org/packages/ttf-google-fonts-git/) installed.

First screenshot is browser, second is client.

![](https://i.imgur.com/pM9Uvxv.png)

![](https://i.imgur.com/BlKZyJa.png)

The browser font look better than the client font.

---

**Distro**: Archlinux

**Comment by raelgc** [comment]
Hi @Brottweiler and thanks for raising this issue.

Font is the same.

Unfortunately, it's just the webkit version used in ScudCloud that renders everything a bit uglier. Similar to #182

**Comment by Brottweiler** [comment]
Sounds like this is not an issue.
