### ISSUE TITLE
Rearrange teams in sidebar

### ISSUE THREAD

**Issue by Brottweiler** [raelgc/scudcloud#441]
In the official client you can click and drag the team icons to the left, and rearrange them. In scudcloud, this is not possible. They seem to be ordered in the way you log in to them, so to rearrange them you have to log out of them and login in the order you want them.

---

**Distro**: Archlinux

**Comment by raelgc** [comment]
Hi Brottweiler and thank you for raising this issue.

You can edit the config file (`~/.config/scudcloud/scudcloud.cfg`) and edit the `Domains` line to define the order of loading teams.

In the past I tried to add support to drag and drop, but this will required more loaded JS libraries, so more RAM usage.

**Comment by Brottweiler** [comment]
Thank you, then this seems fine. 

It's not like I would need to rearrange them every now and then anyway, it would be a one time thing if I add a new team and I just want to move it to a different place.
