### ISSUE TITLE
Clicking on link for browser fill up RAM

### ISSUE THREAD

**Issue by Hydhen** [raelgc/scudcloud#445]
I don't really know where is the issue but since it's `scudcloud` processes that grows up I post it here

When I have a link on Slack which I click on, it should open in a web browser

I got `google-chrome-stable` installed and it seem to be set as default web browser

When I open any link, `scudcloud` creates some kinds of fork and it fills my RAM by 300mb for each instances, until my PC freeze

EDIT :
I just re-configured my `xdg-open` settings, still have the same issue
`$ xdg-open https://archlinux.org` creates a new tab in my chrome session

I'm on Manjaro Linux 16

**Comment by raelgc** [comment]
Unfortunately this is the way Chrome works. Every new tab is a new process.
