### ISSUE TITLE
Multi-user chats (with unread messages) don't show usernames.

### ISSUE THREAD

**Issue by bstein-clever** [raelgc/scudcloud#449]
Multi-user chats that have unread messages don't always show usernames properly, like so:

![image](https://cloud.githubusercontent.com/assets/11928921/15491905/4bf4f352-212a-11e6-8f96-d3f6c86c02a5.png)

(note how none appear).

It does sometimes work, but I haven't done enough testing to figure out the rhyme or reason.
This specific chat displays fine if there are no unread messages. (So no badge is displayed).

It works fine inside a chrome browser.

Thanks!

**Comment by raelgc** [comment]
Hi @bstein-clever, thanks for raising this issue.

Is the username too long when this happen?

**Comment by bstein-clever** [comment]
It's not just one username, this happens when it's a group direct message.(https://get.slack.help/hc/en-us/articles/212281468-Direct-messages-and-group-DMs)

It is the case that the entire list of names is too long, though no individual user's is too long.

I'm not sure if a single user having a name too long would have the same effect, it's difficult for me to test that. But I do notice that it works fine for channels where the name is too long:
![image](https://cloud.githubusercontent.com/assets/11928921/15513504/bb9be20a-2199-11e6-8c4d-fbb38cc13f37.png)

**Comment by raelgc** [comment]
@bstein-clever This issue was fixed and published for Ubuntu.
