### ISSUE TITLE
scudcloud @ qt5

### ISSUE THREAD

**Issue by rburcham** [raelgc/scudcloud#452]
After upgrading my gentoo to plasma5/qt5 my scudcloud main branch no longer would load.  I read the thread/issue in which @raelgc started a port to qt5, and pulled that branch.  After installing that version I now show this stack basis:

$ scudcloud --version
ScudCloud 1.16
Python 3.4.3
Qt 5.6.0
PyQt 5.6.1.dev1604271126
SIP 4.18

My observation is that while this version functional there are some nagging problems.  
1.  Remember me / save password functionality doesn't work.
2.  Scudcloud will not reconnect after a network outage is restored.  Despite going through the motions of the general Slack reconnect behavior, the connection is never restored and the app must be shutdown ad restarted.

Am I using the correct version for qt5?  I am using the build scudcloud-254-port-to-qt5.

**Comment by raelgc** [comment]
Hi @rburcham. Unfortunately, the way qt5 saves configuration is different than qt4.

Try remove the entire config folder and run it again.

Anyway, this reminded me that I need to merge latest changes in qt5 branch.

**Comment by rburcham** [comment]
Yes I saw that in the original thread too.  I gave that a try and it does reset everything about the app to defaults (size, position, groupname, etc.).  However after re-configuring and logging in, it still doesn't seem to want to retain the remember password function.

**Comment by rburcham** [comment]
Also for what it is worth, right clicking on anything seems to crash the app.

**Comment by raelgc** [comment]
Nice list of issues, @rburcham, thank you!

I'll try to take a look on those.

**Comment by raelgc** [comment]
@rburcham I fixed the username/password.

But I didn't face the right clicking crash.

**Comment by rburcham** [comment]
Thanks @raelgc I'll take a look.

BTW has the qt5 port been merged to the main yet?

**Comment by boltronics** [comment]
I didn't see a crash by right clicking either. Will try to test these changes later in the week. Thanks for working on it!

**Comment by rburcham** [comment]
The latest 254-port-to-qt5 looks good.  Remember me is working and reconnect appears to work as expected.  Right clicking on embedded objects doesn't crash the app any longer.  Looks good!

**Comment by raelgc** [comment]
I'll close this for now. We should continue talking in #254 (issue) or in #474 (the pull request).
