### ISSUE TITLE
Message editing is broken

### ISSUE THREAD

**Issue by Grief** [raelgc/scudcloud#459]
## ScudCloud Version

```
/usr/lib/python3/dist-packages/scudcloud/scudcloud.py:27: PyGIWarning: Unity was imported without specifying a version first. Use gi.require_version('Unity', '7.0') before import to ensure that the right version gets loaded.
  from gi.repository import Unity, Dbusmenu
ScudCloud 1.26
Python 3.5.1+
Qt 4.8.7
PyQt 4.11.4
SIP 4.17
```
## Distro and Desktop info
- Distribution: kubuntu
- Version/Release: 16.04
- Desktop environment: kde

Message editing doesn't work. After you enter it, for example, by pressing up arrow, buttons Cancel and Save Changes will not work and you will have no ability to dismiss editing dialog.

**Comment by pdecat** [comment]
I've got the same issue but how can it be related to the Chrome update as scudcloud relies on QtWebKit?

There must have been a change on slack's end...

**Comment by Grief** [comment]
@pdecat you are right. I have Qt components updated as well to the latest ones. And everything is just fine in chrome, but not in scudcloud. So the issue is somewhere between the scudcloud and Qt

**Comment by loonies** [comment]
I'm also affected, but I'm not sure if this is Qt related as I didn't
update Qt4 recently.

**Comment by cromega** [comment]
+1

**Comment by raelgc** [comment]
Qt were not updated in Ubuntu these days. I just restarted this (to reload Slack) and started to face this issue too.

Sounds like Slack changed something in their end. Usually this will be fixed automatically by them.

**Comment by Grief** [comment]
@raelgc Sorry, seems that my guess module is broken. I started to observe that issue right after system upgrade (I use beta channels and ppa's with the most fresh software, including chrome, qt, kde etc), so maybe you are right and this is just a coincidence. But I don't see the same behavior in browsers though.

**Comment by raelgc** [comment]
No problem, @Grief, thank you for reporting this issue! Indeed, if it wasn't your report, I would be not aware of it.

My guess: probably they changed this in Slack itself (now I can see the edit is in the message place), and as we're using a old webkit, this got broken just for us.

**Comment by Grief** [comment]
@raelgc that basically means that the fix is required from scudcloud team, right?

**Comment by Yoshiitsune** [comment]
+1 
Same issue on ArchLinux up to date.
ScudCloud 1.25
Python 3.5.1
Qt 4.8.7
PyQt 4.11.4
SIP 4.18

**Comment by bstein-clever** [comment]
I'm also experiencing this since the end of last week. Ubuntu Xenial with the latest scudcloud. My current workaround is to just delete the message and re-send it, assuming no one else has said anything yet. :(

**Comment by immerrr** [comment]
Same here, editing is broken. Worth noting that in Chrome it works OK.

```
ScudCloud 1.26
Python 3.5.1+
Qt 4.8.7
PyQt 4.11.4
SIP 4.17
```

**Comment by boltronics** [comment]
I'm seeing this on Debian Jessie also.

**Comment by igorp1024** [comment]
Same on ubuntu 16.04 (installed from the scratch). I may be wrong, but this might has been working on 15.10 a couple of days ago.

```
python:3.5.1
qt:4.8.7 and 5.5.1
python3-pyqt4:4.11.4
python3-sip:4.17
scudcloud: latest from the ppa - 1.26
```

**Comment by raelgc** [comment]
@igorp1024 this started few days ago, it'll happen in any distro.

**Comment by frontierpsycho** [comment]
I'm on Debian and using the ppa to install scudcloud. I checked to see all the available versions, to downgrade, and it seems only the latest one is available:

> $ apt-cache madison scudcloud
> 
>  scudcloud |     1.26-2 | http://ppa.launchpad.net/rael-gc/scudcloud/ubuntu/ trusty/main amd64 Packages

Is it possible to make the previous version available until this is fixed?

**Comment by Grief** [comment]
@frontierpsycho this bug doesn't seem like a regression so there is near no chance to get it working just with a downgrade.

**Comment by frontierpsycho** [comment]
I'm confused. It was working a few days ago, before I upgraded scudcloud. I guess something changed on the Slack side, then?

**Comment by Lisio** [comment]
Same problem. Advanced Options tab is also broken after last updates.

**Comment by eyalzek** [comment]
+1

**Comment by Yoshiitsune** [comment]
@frontierpsycho Yes seems to come from an update on the Slack side, so downgrading will not help you.

**Comment by arroo** [comment]
mine seems to be a bit behind:
$ scudcloud --version
ScudCloud 1.20
Python 3.4.3
Qt 4.8.6
PyQt 4.10.4
SIP 4.15.5

so this seems to be server-side?

**Comment by cajogos** [comment]
Can confirm I am still having this same issue on Ubuntu 14.04.

Can't edit messages and Preferences -> Advanced Options does not work either.

```
$ scudcloud --version
ScudCloud 1.27
Python 3.4.3
Qt 4.8.6
PyQt 4.10.4
SIP 4.15.5
```

**Comment by Lisio** [comment]
Nothing is fixed, message editing doesn't work.

```
# apt --installed list | grep scudcloud
scudcloud/xenial,xenial,now 1.27-2 all [installed]
```

**Comment by raelgc** [comment]
Please, update (if in Ubuntu and Debian). Other distros will wait until maintainer update packages.

**Comment by Lisio** [comment]
Looks like ubuntu repos not updated yet. After manual js replacement editing is working.

```
wget https://raw.githubusercontent.com/raelgc/scudcloud/ff8a97765548b31b45a7258136ede5739b2caadd/scudcloud/resources/scudcloud.js -O /usr/lib/python3/dist-packages/scudcloud/resources/scudcloud.js
```

However, Advanced Options tab still not working. Need to create separate issue?

**Comment by raelgc** [comment]
@Lisio Yes, please! About the message editing: Launchpad is still building packages. They'll be ready in few minutes.

**Comment by ilyail3** [comment]
Works well for me, thanks for the fix

**Comment by Enefrius** [comment]
Fixed on Arch:
`wget https://raw.githubusercontent.com/raelgc/scudcloud/ff8a97765548b31b45a7258136ede5739b2caadd/scudcloud/resources/scudcloud.js -O /usr/lib/python3.5/site-packages/scudcloud/resources/scudcloud.js`
