### ISSUE TITLE
How to enable autologin

### ISSUE THREAD

**Issue by ghost** [raelgc/scudcloud#46]
Each time i start my system, i have to login, again..
Is there a way to make scudcloud auto-login in to account?

**Comment by raelgc** [comment]
Hi @ExClouds, thanks for reporting this issue.

This is really weird. Your domain and cookies should be saved in your home directory as `~/.scudcloud`.

**Comment by roberthawdon** [comment]
It's even worse when using Two Factor Authentication. Without it, I needed to select the my company to sign in. With 2FA, I need to type my company name, then sign in, then get the 2FA code. On the official slack client (for Mac), it remembers I'm already authenticated.

**Comment by raelgc** [comment]
@roberthawdon But this is the expected behaviour (keep authenticated). Can you check if your domain is saved in `~/scudcloud`? Anyway, this will be saved in window close event, so, if for some reason, the app is killed, this will be not saved.

**Comment by roberthawdon** [comment]
Scudcloud always crashes when I close the window. I don't see my domain in `.scudcloud` Though there is an entry in the `Cookies` section.

**Comment by raelgc** [comment]
@roberthawdon Right. Can you paste the stack details when the app crashes?

**Comment by roberthawdon** [comment]
Actually, ignore me, automatic updates hadn't run for a few days. A new build (with a clean `.scudcloud` file) has resolved the issue.

**Comment by raelgc** [comment]
Good to hear that @roberthawdon! Let me know if you find new issues!

**Comment by vlatkoB** [comment]
Maybe after first login there could be a message that you have to "properly" close the app? 
I ran it first time, logged in and left it in the tray, but seems like shutting down OS doesn't trigger saving login info (Arch+Cinnamon). 
All working fine after I closed the app manually on time, config filled and autologin works.

**Comment by manicmarvin** [comment]
This issue is still painful. I think Scudcloud needs to save the login information ON logging in not on exit. If it can't be triggered by a in-webapp event, perhaps it can be timed (very very ineffectual) to autosave login info every hour or so?
