### ISSUE TITLE
Wrong counts in unread badges that disappear on channel select.

### ISSUE THREAD

**Issue by bstein-clever** [raelgc/scudcloud#463]
## ScudCloud Version

Paste the output for `scudcloud --version` below:
`
ScudCloud 1.26
Python 3.5.1+
Qt 4.8.7
PyQt 4.11.4
SIP 4.17
`
## Distro and Desktop info
- Distribution: Ubuntu
- Version/Release: Xenial
- Desktop environment: Unity
## Expected behavior

Channels with unread messages show correct @-mention counts as a number.
## Actual behavior

Many channels with unread marks will show a number that is too high (usually 9+) when slack is reloaded. Immediately viewing the channel will reset this number to the correct value, even if the unread mark is higher in history, and so doesn't get cleared.

The web slack client doesn't seem to do this, though it also doesn't happen 100% of the time in scudcloud.
## Steps to reproduce
1.  Close Slack
2.  Reopen it.
3. Notice several channels that have 9+ messages notified.
4. Open channel (say, one that has several pages of unread messages).
5. Observe the 9+ badge disappear instantly, though the normal white "unread" color remains.

**Comment by bstein-clever** [comment]
False alarm here. After a bit more poking, I discovered that:
1) The important step to reproducing is sleeping/waking the computer.
and, more importantly
2) It also happens in the Slack web client, so it's a bug on their end. I'll report it to them.

**Comment by raelgc** [comment]
Thank you for all job here (create, investigate and close), @bstein-clever! I'm sure Slack team will be happy to fix this issue!

**Comment by benjiwheeler** [comment]
@bstein-clever, I'd love to know where your Slack bug report lives!

**Comment by raelgc** [comment]
@benjiwheeler You can use https://get.slack.help/hc/en-us

**Comment by bstein-clever** [comment]
The bug report is in a support ticket, not in the community forums, so I can't send you a link.
I don't believe it's been fixed yet, but the workaround suggested had to do with changing the `mark as read` settings in your preferences.

It didn't work for me, since I wanted to leave unseen messages as unread, but it might be sufficient for you.
