### ISSUE TITLE
Cannot see channel

### ISSUE THREAD

**Issue by Slater91** [raelgc/scudcloud#466]
## ScudCloud Version

http://www.tuttowindows.net/news/surface-book-e-surface-pro-4-disponibili-nuovi-mercati-57523/
## Distro and Desktop info
- Distribution: Linux Mint
- Version/Release: 17.3
- Desktop environment: Cinnamon
## Expected behavior

All channels should be visible in the left sidebar.
## Actual behavior

One channel is not actually visible. I can only access it by clicking on a link (e.g. "#channel").
## Steps to reproduce
1. Open Scudcloud
2. The desired channel is not visible
3. ???
4. No profit.

**Comment by raelgc** [comment]
Hi @Slater91 and thanks for reporting this issue.

This is a duplicate of #454.

**Comment by Slater91** [comment]
Sorry for the duplicate. I looked for the issue and did not find it, so I opened a new thread.
