### ISSUE TITLE
Edit message doesn't seem to work

### ISSUE THREAD

**Issue by rburcham** [raelgc/scudcloud#477]
## ScudCloud Version

$ scudcloud --version
/usr/lib64/python3.4/site-packages/scudcloud-1.30-py3.4.egg/scudcloud/notifier.py:3: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
ScudCloud 1.30
Python 3.4.4
Qt 5.6.0
PyQt 5.6.1.dev1604271126
SIP 4.18
## Distro and Desktop info
- Distribution: gentoo
- Version/Release: up-to-date
- Desktop environment: kde/qt/plasma/5
## Expected behavior

After hitting Save Changes the edited post should display 
## Actual behavior

After hitting Save Changes the original unedited post displays
## Steps to reproduce
1.  post something 
2.  mouse over the text, click the ... icon, select edit message
3.  make some changes in the edit message UI, click Save Changes

**Comment by rburcham** [comment]
Delete message works.  Add reaction works.

**Comment by raelgc** [comment]
Sorry @rburcham, but I tested here and it's working fine. Can you, please, test this again?
