### ISSUE TITLE
Debian QtWebKit dependencies are wrong for qt5

### ISSUE THREAD

**Issue by onitake** [raelgc/scudcloud#478]
## ScudCloud Version

```
ScudCloud 1.30
Python 3.5.2
Qt 5.6.1
PyQt 5.6
SIP 4.18
```
## Distro and Desktop info
- Distribution: Debian
- Version/Release: stretch (testing)
- Desktop environment: Plasma 5
## Expected behavior

The Qt5 branch of ScudCloud has incorrect QtWebKit dependencies in debian/control.

It points to python3-pyqt4, but that should be python3-pyqt5.qtsvg and python3-pyqt5.qtwebkit.

A patch is included below.
## Patch

```
From b732d12c755473214509982bc0cac9fbc63979b4 Mon Sep 17 00:00:00 2001
From: Gregor Riepl <onitake@gmail.com>
Date: Wed, 13 Jul 2016 14:52:58 +0200
Subject: [PATCH] Fixed Debian package dependencies for Qt5

---
 debian/control | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/debian/control b/debian/control
index 748f260..10e97ce 100644
--- a/debian/control
+++ b/debian/control
@@ -13,7 +13,8 @@ Depends: libqtwebkit4 (>= 2.3.2),
          python3-setuptools,
          python3-dbus,
          python3-dbus.mainloop.qt,
-         python3-pyqt4,
+         python3-pyqt5.qtsvg,
+         python3-pyqt5.qtwebkit,
          xdg-utils,
          ${misc:Depends}, 
          ${python3:Depends}
-- 
2.8.1
```

**Comment by raelgc** [comment]
Hi @onitake and thank you for reporting this!

Do you mind if I add you as contributor so you can work directly on this branch?

**Comment by onitake** [comment]
I don't think that's really necessary - unless I find more bugs later. ;)

Just wanted to drop this quick fix so the right dependencies get pulled in when installing from the Debian package. I had to install a few Linux desktops lately and was bitten by the missing modules every time.

The Qt5 port is working great, by the way. I'm using it on a daily basis without any major issues so far.
