### ISSUE TITLE
feature request: client-side logging

### ISSUE THREAD

**Issue by rsrchboy** [raelgc/scudcloud#483]
(Apologies if this is already present, and I just haven't managed to find the "on" button yet.)

It would be useful to store chat logs locally, much as many clients for other protocols do.  I haven't dug into the code yet, but would it be possible to add a "log conversations locally" option?

Thanks!

**Comment by raelgc** [comment]
Hi @RsrchBoy and sorry for my delay in answer this.

I can realize how bad is to hit the 10k messages limit of the free offering.

But I'm afraid that if we implement this, we'll be creating a workaround to break Slack business model. Which probably will lead them to block our client in the future.

So far, Slack team has been really gentle with us, even commenting in this repo.

Our rule is keep ScudCloud a simple wrapper as possible for Slack internal engine, and never touch the internal client.

I'm really sorry for the inconvenience, but I'll have to say No for this enhancement.
