### ISSUE TITLE
Preserve Single Instance when launch under Xmonad

### ISSUE THREAD

**Issue by riaqn** [raelgc/scudcloud#484]
## ScudCloud Version

Paste the output for `scudcloud --version` below:

```
ScudCloud 1.31
Python 3.5.2
Qt 4.8.7
PyQt 4.11.4
SIP 4.18
```
## Distro and Desktop info
- Distribution: Archlinux
- Version/Release: Rolling
- Desktop environment: Xmonad
## Expected behavior

When launching a new process of scudcloud, it should detect the running instance and, instead of starting a new instance, the existing one should pop up. (The behaviour of official client)
## Actual behavior

When launching a new process, a new instance is created.
## Steps to reproduce
1. execute "scudcloud"
2.  close the window
3.  re-execute "scudcloud"

**Comment by raelgc** [comment]
Hi @riaqn and thank you for raising this issue.

In fact, this is the current behavior on Unity. Probably we'll need someone contributing to fix this under Xmonad. I've changed this issue title to reflect this.

**Comment by riaqn** [comment]
@raelgc 
It's strange that today scudcloud pops up the existing instance instead of starting a new one. As I don't know how it works, I'm afraid I can't do much except closing this issue.

**Comment by raelgc** [comment]
@riaqn Thank you for the feedback. If you find a consistent way to reproduce this, please, feel free to re-open this issue.
