### ISSUE TITLE
"Create new channel" button is in wrong position. 

### ISSUE THREAD

**Issue by ankworld** [raelgc/scudcloud#495]
## ScudCloud Version

Paste the output for `scudcloud --version` below:
`/usr/lib/python3.5/site-packages/scudcloud/notifier.py:3: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
ScudCloud 1.31
Python 3.5.2
Qt 4.8.7
PyQt 4.11.4
SIP 4.18.1
`
## Distro and Desktop info
- Distribution: Arch Linux
- Version/Release: 4.7.6-1-ARCH
- Desktop environment: Gnome [3.20]
## Expected behavior
1. "Create new channel" button at right position
## Actual behavior

![screenshot from 2016-10-06 21-15-18](https://cloud.githubusercontent.com/assets/10556919/19156038/b469ff90-8c0a-11e6-8461-e0a5b8fb09ce.png)

**Comment by raelgc** [comment]
Hi @ankworld, thanks for raising this and sorry for my late reply.

My client was opened for more than a week (and I was not seeing this issue). I restarte it now and now I can see it.

Sounds like a CSS change in the Slack side not supported by webkit version we use. Anyway, probably just a simple CSS fix.
