### ISSUE TITLE
Bug: cached team icons int /tmp are public-viewable

### ISSUE THREAD

**Issue by anatolyborodin** [raelgc/scudcloud#497]
## ScudCloud Version

```
/usr/lib/python3/dist-packages/scudcloud/notifier.py:3: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
ScudCloud 1.33
Python 3.5.2
Qt 4.8.7
PyQt 4.11.4
SIP 4.17
```
## Distro and Desktop info

Ubuntu 16.04, KDE
## Expected behavior

Many programs create temporary files and folders in `/tmp`, but set the mode to `0600` or `0700`. Examples are: mc, skype, kde, mozilla. There could be some security and privacy concerns.
## Actual behavior

`scudcloud` creates files with names like `/tmp/scudcloud_U02HC3ZL4.jpg` and modes `0644`. These files contain icons of teams the user has logged into. But a user may not want to show other local users that some particular slack team is logged in.
## Steps to reproduce
1. Run scudcloud
2. Log in into a team
3. `ls -l /tmp/scudcloud*`

**Comment by raelgc** [comment]
Nice catch @anatolyborodin!

I was using a python library to take care of this. 

I'll check if we can set permissions or replace it by manual code.

**Comment by raelgc** [comment]
It'll require a replacement of the `urlib.request.urlretrieve` library for a manual code, as it doesn't have a permission parameter.

**Comment by raelgc** [comment]
KISS solution will be use a user folder, like `$XDG_CACHE_HOME`.

**Comment by anatolyborodin** [comment]
I see no reason why `$XDG_CACHE_HOME` couldn't be used.

**Comment by anatolyborodin** [comment]
Thanks! :)
