### ISSUE TITLE
ScudClound needs package gir1.2-notify-0.7, but doesn't install it

### ISSUE THREAD

**Issue by paol** [raelgc/scudcloud#498]
## ScudCloud Version

Paste the output for `scudcloud --version` below:
`ScudCloud 1.32
Python 3.5.2+
Qt 5.6.1
PyQt 5.7
SIP 4.18.1`
## Distro and Desktop info
- Distribution: Kubuntu
- Version/Release: 16.10
- Desktop environment: KDE
## Actual behavior

On a clean install from the PPA on Kubuntu 16.10 scudcloud fails to start due to a missing dependency.
The following package is needed but is not listed in scudcloud's dependencies:

gir1.2-notify-0.7

**Comment by raelgc** [comment]
Hi @paol. I can see this package in the `debian/control` file. Are you installing this by `apt` or throw `python`?

**Comment by paol** [comment]
Here's the package installed on my system, installed with apt from the yakkety PPA:

```
$ apt-cache show scudcloud 
Package: scudcloud
Priority: optional
Section: python
Installed-Size: 374
Maintainer: Rael Gugelmin Cunha <rael.gc@gmail.com>
Architecture: all
Version: 1.32-2
Recommends: sni-qt, fonts-lato, gir1.2-unity-5.0, libqtwebkit-qupzillaplugins, python3-hunspell, python3-notify2, python3-gi, ttf-mscorefonts-installer
Depends: python3, python3-setuptools, python3-dbus, python3-dbus.mainloop.qt, python3-pyqt5, python3-pyqt5.qtsvg, python3-pyqt5.qtwebkit, xdg-utils, python3:any (>= 3.3.2-2~)
Filename: pool/main/s/scudcloud/scudcloud_1.32-2_all.deb
Size: 42330
MD5sum: 7fa674344a5120961d1acfe96af4b667
SHA1: 4e3722d62c8b8dd07d0cbf6c3186fb8d8d2bd71c
SHA256: 107fa31f7e32e71d72b8eb93823af4d473664b7f08fbcda78479fc3773c3d2bf
Description-en: ScudCloud is a non official desktop client for Slack
 ScudCloud is a non official desktop client for Slack.
 Slack (http://slack.com) is a platform for team communication.
Description-md5: 186d8ab2e71fece379e71251cb5519f0
```

gir1.2-notify doesn't appear anywhere in Depends or Recommends (not that it should be in Recommends, since it's not optional).

**Comment by paol** [comment]
Speaking of Recommends, taking a look at that list again it seems a little suspicious that stuff like python3-gi is really optional. Are you sure some of those shouldn't be in Depends?

**Comment by raelgc** [comment]
`python3-gi` is not really required and in a previous PR people move it to Recommends, because in some Debian version it was not present.

You're right about `gir1.2-notify`. I'll fix it. Thanks for your time explaining and patience.

**Comment by raelgc** [comment]
@paol New Yakkety package released, including other fixes/improvements. Please, update and re-open this issue if required.
