### ISSUE TITLE
never stays logged in

### ISSUE THREAD

**Issue by srw2d** [raelgc/scudcloud#50]
Thanks for the great work on this!

One issue I have, it never saves my login details. Is this a known issue or a bug? I am using this in elementary OS 0.3 Freya (64-bit)  

Thanks!

**Comment by raelgc** [comment]
Hi @srw2d, thank you for the compliments and thank you for creating this issue.

ScudCloud will save your info only when properly closed. If some crash happens, then it'll be not saved.

Usually this is fixed after a system update, like described in #46

**Comment by srw2d** [comment]
Thanks! fast reply as well...That worked, to fix it all I needed to do was to login, logout. Then I tried logging out of my desktop session, logged back in and started it up and it all worked. Thanks!

**Comment by raelgc** [comment]
Good to hear it worked :)

**Comment by manicmarvin** [comment]
@raelgc As I mentioned  in #46, this _intentional_ behaviour is flawed. New users will never know that they have to close Scudcloud manually the first time. 

I think Scudcloud needs to save the login information ON logging in not on exit. If it can't be triggered by a in-webapp event, perhaps it can be timed (very very ineffectual) to autosave login info every hour or so?

**Comment by raelgc** [comment]
@manicmarvin This is old info. Scudcloud now saves after fetch all teams, on manual exit and on system shutdown sign (but few DEs don't send this last signal properly). 

It's a bug in the retrieve team logic, but I'm not able to reproduce. I need to see the command line output when this happen. The ideal would be have the same config file, but this will be a privacy concern.

**Comment by manicmarvin** [comment]
@raelgc Thanks for the update. So LXDE doesn't send the required signal obviously, because that's where I'm facing the problem. Can I help reproduce the bug? I must warn you, I will need some hand-holding to figure out how to do record the bug.
