### ISSUE TITLE
scudcloud installation error - seemingly requires python2 for gi

### ISSUE THREAD

**Issue by eiso** [raelgc/scudcloud#502]
## ScudCloud Version

 1.34-1  (https://aur.archlinux.org/packages/scudcloud/)
## Distro and Desktop info
- Distribution: Arch Linux package manager
- Version/Release: latest release of Arch
- Desktop environment: x with i3 
## Expected behavior

After installing scudcloud from the package manager using yaourt I expected to be able to run the application when calling "scudcloud" via CLI.

I also tried installing scudcloud directly from this repo not using AUR and had the same error.
## Actual behavior

Instead the following error arrived:

```
mthek@blackmirror ~> scudcloud -h
Traceback (most recent call last):
  File "/usr/bin/scudcloud", line 11, in <module>
    load_entry_point('scudcloud==1.34', 'gui_scripts', 'scudcloud')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2608, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2268, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2274, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/scudcloud/__main__.py", line 16, in <module>
    import scudcloud.scudcloud as sca
  File "/usr/lib/python3.5/site-packages/scudcloud/scudcloud.py", line 3, in <module>
    from scudcloud.notifier import Notifier
  File "/usr/lib/python3.5/site-packages/scudcloud/notifier.py", line 3, in <module>
    from gi.repository import Notify
  File "/usr/lib/python3.5/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'
```

This looks like classic python 2 vs. python 3 problem. However I noticed that scudcloud itself is written in Python3 by checking setup.py which starts with:

```
#!/usr/bin/env python3
```

As you can see I am running python 3.5.2 (locally, in shell and globally)

```
mthek@blackmirror ~> python -V
Python 3.5.2
```

It seems like an error with gi that is required.
## Steps to reproduce
1. yaourt scudcloud
2. scudcloud

**Comment by raelgc** [comment]
Hi @eiso and thanks for reporting this.

You're right: this sounds like a python 2 syntax in a python 3 package.

The problem is: `gi` is an external package and we don't have control over it.

I can see [several similar results](https://www.google.com.br/search?client=ubuntu&channel=fs&q=%22File+%22%2Fusr%2Flib%2Fpython3.5%2Fsite-packages%2Fgi%2F__init__.py%22%2C+line+39%22&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=4VMgWOPxEO6w8wegoaOgBA) in Google. The first one said this:

> I installed python-keyring pygobject-devel python-crypto python-gobject and now it works.

Other answer is saying...

> to install the package python3-gi and symlink the gi directory to the lib/python3.4/site-packages directory of your self-compiled python.

**Comment by eiso** [comment]
Thank you.  I managed to get it working after manually removing the gi package (sudo rm -R /usr/lib/python3.5/site-packages/gi) and installing it again using Arch's package manager (sudo pacman -S python-gobject). Now it works!

**Comment by raelgc** [comment]
I'm glad it worked, @eiso ! Thank you for posting your solution! It'd be useful for something facing the same issue!
