### ISSUE TITLE
Crash when right-clicking

### ISSUE THREAD

**Issue by hackel** [raelgc/scudcloud#503]
## ScudCloud Version
`ScudCloud 1.35
Python 3.5.2+
Qt 5.6.1
PyQt 5.7
SIP 4.18.1`

## Distro and Desktop info

  - Distribution: Ubuntu
  - Version/Release: 16.10
  - Desktop environment: Unity 7.5.0

## Expected behavior
Context menu with typical cut/copy/paste options.

## Actual behavior
Scudcloud stayed running, but I got a crash dialogue with the following:

Scudcloud crashed with AttributeError in contextMenuEvent(): module 'PyQt5.QtGui' has no attribute 'QAction'

Traceback:
   File "/usr/lib/python3/dist-packages/scudcloud/wrapper.py", line 76, in contextMenuEvent
     action = QtGui.QAction('Copy Quoted', self)
 AttributeError: module 'PyQt5.QtGui' has no attribute 'QAction'

## Steps to reproduce
Have not been able to reproduce yet.

**Comment by raelgc** [comment]
Hi @hackel. Thanks for raising this issue.

I just fixed this issue (after your report). Please, upgrade and test. Re-open the issue it not properly fixed.
