### ISSUE TITLE
Webkit Network Disk Cache Location

### ISSUE THREAD

**Issue by myroslav** [raelgc/scudcloud#505]
According to https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html:

> `$XDG_CACHE_HOME` defines the base directory relative to which user specific non-essential data files should be stored. If `$XDG_CACHE_HOME` is either not set or empty, a default equal to `$HOME/.cache` should be used. 

However in https://github.com/raelgc/scudcloud/blob/67adddbfe1485af83e86dc2443a41d0981743c64/scudcloud/scudcloud.py#L136 there is:

    self.diskCache.setCacheDirectory(self.settings_path)

ignoring the recommendation and "polluting" the `$XDG_CONFIG_HOME` (`$HOME/.config/scudcloud`), it would be good to have it improved.

**Comment by raelgc** [comment]
Hi @myroslav. Indeed, this is a nice improvement! Thank you for reporting this and provide all info!

**Comment by selurvedu** [comment]
Awesome, thanks!
