### ISSUE TITLE
Scudcloud becomes invisible and unresponsive after resume.

### ISSUE THREAD

**Issue by cdysthe** [raelgc/scudcloud#51]
Hi,

I use ScudCloud on a few laptops (Thinkpads). When I suspend the laptop and then resume ScudCloud is invisible and can not be revived with the system tray icon. I have to close the application from the system try icon and restart it.

**Comment by raelgc** [comment]
Hi @cdysthe, thank you for reporting this issue.

Can you, please, give me the following info:

1 - Which distro and version are you using?

2 - It has all updates? (I have seen crashes in vanilla Ubuntus fixed after system updates);

3 - If you have an updated system, can you, please, open ScudCloud from terminal, then suspend/resume and paste here the errors displayed in terminal? If you can paste the errors, probably I can find a solution.

Thank you!

**Comment by cdysthe** [comment]
On 04/04/2015 05:01 PM, Rael Gugelmin Cunha wrote:

> Hi @cdysthe https://github.com/cdysthe, thank you for reporting this 
> issue.
> 
> Can you, please, give me the following info:
> 
> 1 - Which distro and version are you using?
> 
> Ubuntu 15.04 x64
> 
> 2 - It has all updates? (I have seen crashes in vanilla Ubuntus fixed 
> after system updates);
> 
> Fully updated.
> 
> 3 - If you have an updated system, can you, please, open ScudCloud 
> from terminal, then suspend/resume and paste here the errors displayed 
> in terminal? If you can paste the errors, probably I can find a solution.
> 
> I am not able to reliably reproduce this problems. I have found out it 
> doesn't happen all the time. As soon as I have some more time I will try 
> to find a way to reproduce it and follow your debugging instructions.
> 
> Thank you!

Thank you! :)

> —
> Reply to this email directly or view it on GitHub 
> https://github.com/raelgc/scudcloud/issues/51#issuecomment-89667302.

## 

//Christian

Dropbox. Your files from anywhere: http://db.tt/U8MqkVR

**Comment by raelgc** [comment]
Thank you @cdysthe to provide all this useful info!

The use of 15.04 is really the new info here. I still didn't test it there.

Hope you can find an easy way to reproduce this issue. Anyway, as soon 15.04 get released, probably more people will report this issue too.

**Comment by raelgc** [comment]
@cdysthe Still an issue in 15.04?

**Comment by cdysthe** [comment]
I just got a new laptop and on on that one it's not happening. On the old one it still is. I find it hard to understand how it can be a hardware p problem.

**Comment by raelgc** [comment]
Indeed, a real mystery. Is 15.04 updated in the old one?

**Comment by cdysthe** [comment]
Yes, they are on the exact same Ubuntu install fully updated. One is a Thinkpad T430s, the new one in a Thinkpad X1 Carbon. I'll do some more research on it. It could maybe be TLP which isn't fully implemented in the new X1 Carbon

**Comment by NyanSten** [comment]
When you suspend the laptop and then resume it, is the monitor configuration the same? It may be ScudCloud is displayed on a disconnected monitor by accident.

**Comment by raelgc** [comment]
Hi @cdysthe, any update on this? I mean, still facing the same issue?
