### ISSUE TITLE
Scudcloud Eating up Stupid Amounts of RAM

### ISSUE THREAD

**Issue by stieg** [raelgc/scudcloud#511]
## ScudCloud Version
Tested on official package and top of dev tree
* v1.37-3-gcbe15de
* scudcloud-1.37-1.fc25.noarch

## Distro and Desktop info
  - Distribution: Fedora 25
  - Version/Release: scudcloud-1.37-1.fc25.noarch
  - Desktop environment: Gnome 3.22

## Expected behavior
Scudcloud should not be a memory piggy

## Actual behavior
Scudcloud is a memory piggy.  See following PS info after startup:

```
$ ps -o command,vsize,rss,%mem,size 24034
COMMAND                        VSZ   RSS %MEM  SIZE
python3 -m scudcloud        3962112 1194328  7.3 2344188
```
The process is chewing up 3.9G of virtual mem, and has 1.19G resident!

## Steps to reproduce
 1. Start scudcloud
 2. Get process id
 3. run `ps -o command,vsize,rss,%mem,size <PID>`

This is likely a library bug or a python bug or something but needs something to track the issue:

```
[stieg@lucious scudcloud]$ rpm -qi python3
Name        : python3
Version     : 3.5.2
Release     : 4.fc25
```

```
[stieg@lucious scudcloud]$ rpm -qi qt
Name        : qt
Epoch       : 1
Version     : 4.8.7
Release     : 18.fc25
```

**Comment by CubeTheThird** [comment]
I too have been experiencing massive memory usage with the client. I've started using Rambox as an alternative until it can be addressed here.

**Comment by raelgc** [comment]
@CubeTheThird are you using Fedora too? Can you, please, paste the output for `scudcloud --version`?

**Comment by raelgc** [comment]
By the way, the original issue talks about the Qt4 version, no more available. Can you, please, open a new issue with all details requested?

**Comment by CubeTheThird** [comment]
I am on Arch Linux, but as of updating to version 1.62 (or perhaps a library update) the memory usage seems to be more stable. I'll create a separate ticket should this change.
