### ISSUE TITLE
Sidebar (flexpane) doesn't disappear when trying to close it 

### ISSUE THREAD

**Issue by bstein-clever** [raelgc/scudcloud#515]
## ScudCloud Version

Paste the output for `scudcloud --version` below:
`
~$ scudcloud --version
/usr/lib/python3/dist-packages/scudcloud/notifier.py:3: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python3/dist-packages/scudcloud/scudcloud.py:27: PyGIWarning: Unity was imported without specifying a version first. Use gi.require_version('Unity', '7.0') before import to ensure that the right version gets loaded.
  from gi.repository import Unity, Dbusmenu
ScudCloud 1.37
Python 3.5.2
Qt 4.8.7
PyQt 4.11.4
SIP 4.17
`

## Distro and Desktop info

  - Distribution: Ubuntu
  - Version/Release: Xenial
  - Desktop environment: Unity

## Expected behavior

After opening the sidebar and trying to close it, it should close completely.

## Actual behavior

When clicking the 'x', it reduces in size, but doesn't close completely, like so:
![image](https://cloud.githubusercontent.com/assets/11928921/21206409/939d356a-c216-11e6-9201-270f8ccbe8c2.png)

Compare to the fullly opened size, like so: 
![image](https://cloud.githubusercontent.com/assets/11928921/21206416/a381c4fa-c216-11e6-8ab6-0ef3bcdc4354.png)

The only solution I've found to close it is to restart scudcloud.

## Steps to reproduce
 1.  Open the sidebar
 2. Try to close the sidebar
 3. Voila

**Comment by raelgc** [comment]
@bstein-clever yeap, I've noticed that today too. The flexpane is just shrinking but not disappearing when closed. Wondering if with some CSS we can fix this.

**Comment by raelgc** [comment]
The workaround is right click and select `reload`.

**Comment by cajogos** [comment]
Any updates on this? It seems to still be happening, and now with threads opening on this pane this is going to cause some problems.

**Comment by jaxad0127** [comment]
`reload` isn't working for me. Even restarting the app doesn't clear the sidebar.

**Comment by raelgc** [comment]
@jaxad0127 I think you're confusing the left pane with the flexpane (the one at the right side that appears when you click on "What's New", by example).

**Comment by jaxad0127** [comment]
I mean the one on the right.

**Comment by raelgc** [comment]
I just tested and right clicking and selecting "reload" made it disappear.

**Comment by jaxad0127** [comment]
Not for me. Though Slack does keep restarting the search I did, before partially closing the flexpane, leaving the X button inaccessible. I've repeatedly tried clearing the search, restarting the app, reloading the pane, without any success.

**Comment by jaxad0127** [comment]
Seems Slack was keeping some partially broken state. After I somehow opened up more search options, the flex pane changed to a different one, and I was able to close and reload. It's gone now. Weird stuff.

**Comment by raelgc** [comment]
No problem. I'm working a fix for this.

**Comment by bstein-clever** [comment]
I've experienced this mixed responsiveness, as well.
Some types of sidebars (files, people, etc) have an 'x' to close them, some (what's new, threads, probably others) don't seem to.
There's also a problem, as suggested, that some try to expand too far, so the 'x' is hidden, and the only way to get to it is to full-screen scudcloud.

Once you've hit the 'x', and the sidebar goes into "semi-closed" mode, then it'll go away after a restart. But if the sidebar is open, restarting will keep it there; I believe that's by design.

**Comment by raelgc** [comment]
This do not happens on qt5 branch. Soon, I'll merge the qt5 branch to master.

**Comment by loonies** [comment]
Yeah, it works with qt5-webkit

**Comment by raelgc** [comment]
Finally I got able to fix this in qt4 version. Packages published for Ubuntu. Please, update and upgrade.
