### ISSUE TITLE
Can only have 2 team tabs open on scudcloud

### ISSUE THREAD

**Issue by alfredopalhares** [raelgc/scudcloud#517]
## ScudCloud Version

```
-> % scudcloud --version
/usr/lib/python3.6/site-packages/scudcloud/notifier.py:3: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python3.6/site-packages/scudcloud/scudcloud.py:27: PyGIWarning: Unity was imported without specifying a version first. Use gi.require_version('Unity', '7.0') before import to ensure that the right version gets loaded.
  from gi.repository import Unity, Dbusmenu
ScudCloud 1.37
Python 3.6.0
Qt 4.8.7
PyQt 4.12
SIP 4.19
```
## Distro and Desktop info

  - Distribution: ArchLinux
  - Version/Release: Rolling Release (up to date)
  - Desktop environment: Gnome 3

## Expected behavior

Have as many teams as desired. 

## Actual behavior

Cannot have more than 2 teams on scudcloud, the login process works correctly and I see the 3rd team, but not the tab, once I switch to another of the previous 2 teams, i cannot access the 3rd one.

## Steps to reproduce
 1. Have 2 teams
 2. Login to another team
 3. Switch back to one of the 2 other teams
 4. Cannot go back

**Comment by raelgc** [comment]
Please, update to latest version (which is 1.56).
