### ISSUE TITLE
Missing sidebar/leftbar team switcher (no other teams loading)

### ISSUE THREAD

**Issue by loonies** [raelgc/scudcloud#518]
## ScudCloud Version

```
ScudCloud 1.37
Python 3.6.0
Qt 4.8.7
PyQt 4.12
SIP 4.19
```

## Distro and Desktop info

  - Distribution: Arch Linux
  - Version/Release: -
  - Desktop environment: Xfce

## Expected behavior

When signed in with multiple teams, I'm expecting the sidebar team switcher on the left.

## Actual behavior

There is no sidebar team switcher.

If you go to "Sign in to another team..." you'll be prompted to enter domain and after that a team is opened. If logged in, you can also click on "You’re already signed in to these teams" and a team will be opened, but no there will be no team switcher.

## Steps to reproduce
 1. Quit Scudcloud
 2. Start Scudcloud
 3. Sign in to at least 2 teams

**Comment by raelgc** [comment]
Slack removed the previous JavaScript method used to retrieve the teams (`TS.getAllTeams()`). Working on a fix.

**Comment by alfredopalhares** [comment]
:+1: This also happens to me.

**Comment by raelgc** [comment]
Packages for Ubuntu are published. Please update.

**Comment by alfredopalhares** [comment]
Rebuilt the AUR package to the newest version, I can confirm this bug is fixed.

**Comment by maiatoday** [comment]
I can confirm updating from ubuntu packages fixes it for ubuntu 16.04 using Unity. Thanks for super quick response.

**Comment by raelgc** [comment]
@maiatoday Welcome and thank YOU for the quick issue reporting! :)

**Comment by enj** [comment]
Any timeline for Fedora?

**Comment by dtsallas** [comment]
Can also confirm it's working on Ubuntu 16.04. Thanks for the quick fix, this was a critical issue for me.

**Comment by rvanlaar** [comment]
There is a regression. It had this problem and it was fixed after the update last week.

Now I'm having the same problem again. 
I'm using ubuntu 16.10 with scudcloud 1.40-1

Extra information:
Restarting scudcloud didn't help, selecting another team did help. 
The bar is back.

**Comment by loonies** [comment]
Works for me. TY

**Comment by tdgroot** [comment]
I got the update on Fedora 24, bug is fixed now :).
