### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by umpirsky** [raelgc/scudcloud#52]
I have installed it like described in [README](https://github.com/raelgc/scudcloud#install) on Ubuntu 14.04.2 LTS.

When I run it I get:

```
$ scudcloud 
Segmentation fault (core dumped)
```

![ubuntu_001](https://cloud.githubusercontent.com/assets/208957/7001631/840c8bc0-dc3d-11e4-833c-a0ee890d3e21.png)

**Comment by raelgc** [comment]
Hi @umpirsky, thank you for reporting this issue.

Can you, please, perform a system update? Usually this is fixed after it.

**Comment by umpirsky** [comment]
Thanks for fast answer @raelgc!

My system is up to date.

**Comment by raelgc** [comment]
Right. Thanks for double check that.

Can you, please, paste here the stack trace of the segfault?

**Comment by umpirsky** [comment]
@raelgc I submitted crash report. I would like to post trace, just tell me how.

All I can see in syslog is `Apr  6 14:35:16 zenbook kernel: [ 1153.213719] python3[11172]: segfault at 7f855a3ec140 ip 00007f855a3ec140 sp 00007fffcf20ef68 error 15`.

**Comment by raelgc** [comment]
I'm not sure if under CoreDump or Disassembly (I cannot remember). The submitted crash report is not sent to me (I think aport sends to Canonical).

The easiest way is open ScudCloud from terminal, then copy and paste the outputs.

**Comment by umpirsky** [comment]
@raelgc But nothing is dumped in terminal:

```
$ scudcloud
Segmentation fault (core dumped)
```

**Comment by raelgc** [comment]
Interesting, it's a crash in the python3 interpreter. Is `zenbook kernel` a different kernel then vanilla Ubuntu one?

**Comment by umpirsky** [comment]
@raelgc No, I use regular Ubuntu kernel.

**Comment by raelgc** [comment]
Thanks for the quick reply, @umpirsky.

I can think in 2 possible causes here: 

1 - A missing dependency in ScudCloud (probably a package that most people installed ScudCloud until now already has installed).

2 - A specific situation for your team that ScudCloud code is broken, but instead of return the typical python3 stack trace, is just crashing the interpreter. In this case, probably I'll need your help to try a deep investigation like describe here: http://jodal.no/post/5779178001/log-from-the-debugging-of-a-segfault/

**Comment by umpirsky** [comment]
@raelgc Can I debug somehow? To get more trace?

**Comment by raelgc** [comment]
Yes, but it's a bit hard. This guy described how to perform it: http://jodal.no/post/5779178001/log-from-the-debugging-of-a-segfault/

**Comment by umpirsky** [comment]
@raelgc Thanks.

**Comment by raelgc** [comment]
Closing by inactivity. Please, re-open if required.
