### ISSUE TITLE
ScudCloud fail to open (pyQt4 webkit bindings removed from Arch)

### ISSUE THREAD

**Issue by filhocodes** [raelgc/scudcloud#520]
## ScudCloud Version

I can't run `scudcloud --version`, but via `pacman -Qi` the indicated version is `2:1.39-1`.

## Distro and Desktop info

  - Distribution: Arch Linux
  - Version/Release: -
  - Desktop environment: XFCE

## Expected behavior

Scudcloud opens, slack chat, emoji fight, `/gifs everywhere`, `:partyparrot:` etc.

## Actual behavior

Via the applications menu, when I click to open Scudcloud nothing happens.
When run `scudcloud` via terminal, I got:

```
$ scudcloud
Traceback (most recent call last):
  File "/usr/bin/scudcloud", line 11, in <module>
    load_entry_point('scudcloud==1.39', 'gui_scripts', 'scudcloud')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2642, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2296, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2302, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/scudcloud/__main__.py", line 16, in <module>
    import scudcloud.scudcloud as sca
  File "/usr/lib/python3.6/site-packages/scudcloud/scudcloud.py", line 2, in <module>
    from scudcloud.leftpane import LeftPane
  File "/usr/lib/python3.6/site-packages/scudcloud/leftpane.py", line 5, in <module>
    from PyQt4.QtWebKit import QWebView, QWebSettings
ModuleNotFoundError: No module named 'PyQt4.QtWebKit'
```

I just updated via AUR (with `yaourt -Sua`).

## Steps to reproduce
 1. Run `scudcloud` on terminal

**Comment by alfredopalhares** [comment]
I get this exact same error.

**Comment by raelgc** [comment]
Some days ago, Arch removed support for PyQt4. I remember someone saying they restored. Can you, please, update and check if it was really restored?

**Comment by raelgc** [comment]
If not, anyone able to create a AUR package should use the Qt5 branch to package it: https://github.com/raelgc/scudcloud/tree/254-port-to-qt5

**Comment by filhocodes** [comment]
@raelgc [They dropped it again](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/pyqt4&id=8cbe3c19635ab35860a5c479c3a93e8994c2a811).

Will the Qt5 port be merged into the master? If so, I can just install from source for now. Or I can ask the `scudcloud` maintainer to create a `scudcloud-qt5` package.

**Comment by raelgc** [comment]
Well, you can install it from source using git (clone it, then switch to branch `254-port-to-qt5`).

Then install or run from devtree with `python3 -m scudcloud`.

**Comment by raelgc** [comment]
qt5 branch will be merged to master, but not in the next week.

**Comment by ghost** [comment]
Hi, all. Until the qt5 branch is merged into master, I've based the scudcloud package off of that branch. Perform an upgrade and scudcloud should work again. Sorry for the delay!

**Comment by filhocodes** [comment]
@ainola thx

**Comment by filhocodes** [comment]
@raelgc I changed the title again because the pyqt4 was not removed from Arch, just the webkit bindings

**Comment by raelgc** [comment]
Thanks guys, for all the support and info!

**Comment by alfredopalhares** [comment]
@ainola Thanks. I am rolling that update,

**Comment by ghost** [comment]
With the latest 1.50 release, qt5 is now enabled. This can be closed.

Thanks for all of your hard work, @raelgc
