### ISSUE TITLE
Keep me signed in is not working

### ISSUE THREAD

**Issue by filhocodes** [raelgc/scudcloud#521]
## ScudCloud Version

```
ScudCloud 1.40
Python 3.6.0
Qt 5.8.0
PyQt 5.7.1
SIP 4.19
```

## Distro and Desktop info

  - Distribution: Arch Linux
  - Version/Release: -
  - Desktop environment: XFCE

## Expected behavior

When I launch Scudcloud, the teams that I checked _Keep me signed in_ should be listed.

## Actual behavior

When I launch Scudcloud, I need to sign in again to each team. I also noticed that I happens when I start my PC (if I quit Scudcloud now, and open it again, without powering off the PC, all my teams are loaded).

## Informations

This is the Qt5 port (installed after #520). This also may be related to #482. And I already executed `chmod -R 0755 ~/.config/scudcloud/scudcloud_qt5.cfg`.

## Steps to reproduce
 1. Use Scudcloud
 2. Turn off the PC
 3. Turn it on again
 4. When you launch Scudcloud, no teams are saved

**Comment by raelgc** [comment]
@marcossffilho, sorry for the late response, I was fixing several minor issues.

Is this still an issue? If yes, re-open, please.
