### ISSUE TITLE
Direct Messages crashes the app on XFCE

### ISSUE THREAD

**Issue by raffraffraff** [raelgc/scudcloud#523]
## ScudCloud Version
1.39-1
Paste the output for `scudcloud --version` below:
``
ScudCloud 1.39
Python 3.5.2
Qt 4.8.7
PyQt 4.11.4
SIP 4.17
``
## Distro and Desktop info

  - Distribution: Ubuntu
  - Version/Release: 16.04
  - Desktop environment: XFCE

## Expected behavior
Click on 'Direct Messages' should work

## Actual behavior
Click on 'Direct Messages' immediately crashes with error on terminal: "Segmentation fault (core dumped)"

## Steps to reproduce
 1. Launch scudcloud
 2. Click on 'Direct Messages'

**Comment by raffraffraff** [comment]
If you want a core dump let me know and I can create one

**Comment by raelgc** [comment]
Hi @raffraffraff, thanks for reporting this.

Do you have other desktop environments installed?

The stacktrace will be useful.

**Comment by raelgc** [comment]
Let me know if this is still an issue.
