### ISSUE TITLE
Fail to another another team on python3.6

### ISSUE THREAD

**Issue by alfredopalhares** [raelgc/scudcloud#527]
## ScudCloud Version

```
ScudCloud 1.40
Python 3.6.0
Qt 5.8.0
PyQt 5.8
SIP 4.19.1
```

## Distro and Desktop info

  - Distribution: Arch Linux
  - Version/Release: Rolling Release (updated today)
  - Desktop environment: Gnome 3

## Expected behavior

A new team tab should appear

## Actual behavior

Scudcloud  crashes when addding another team.

```
-> % scudcloud
QSocketNotifier: Can only be used with threads started with QThread
QSocketNotifier: Can only be used with threads started with QThread
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/scudcloud/leftpane.py", line 63, in switchTo
    self.window.switchTo(url)
  File "/usr/lib/python3.6/site-packages/scudcloud/scudcloud.py", line 358, in switchTo
    self.quicklist(self.current().listChannels())
  File "/usr/lib/python3.6/site-packages/scudcloud/scudcloud.py", line 433, in quicklist
    if hasattr(c, '__getitem__') and c['is_member']:
TypeError: string indices must be integers
[1]    14568 abort (core dumped)  scudcloud
```

## Steps to reproduce
 1. Add another team
 2. Insert Url / email / password

**Comment by alfredopalhares** [comment]
ping

**Comment by raelgc** [comment]
Hi @masterkorp. Unfortunatelly I cannot reproduce this under Ubuntu, because it's using python3.5. 

I renamed the issue title to be clear about the python version.

I'll need to install python3.6 to try to fix this under it.

**Comment by raelgc** [comment]
I believe this is no more an issue with several fixes in Qt5 version. Let me know if this is still happens.
