### ISSUE TITLE
ScudCloud crashes if notification recipient crashes

### ISSUE THREAD

**Issue by RyanDwyer** [raelgc/scudcloud#528]
## ScudCloud Version

Paste the output for `scudcloud --version` below:

    ScudCloud 1.41
    Python 3.6.0
    Qt 5.8.0
    PyQt 5.8
    SIP 4.19.1

## Distro and Desktop info

  - Distribution: Arch Linux
  - Version/Release: N/A (rolling release - all packages up to date)
  - Desktop environment: N/A - running i3 with dunst

## Expected behavior

Dunst (a notification displayer daemon) crashes because it's a terrible, unmaintained piece of software. Then ScudCloud crashes. I expect ScudCloud to not crash when dunst crashes because ScudCloud is a maintained, well built piece of software.

## Actual behavior

The dunst crash triggers a ScudCloud crash.

    Traceback (most recent call last):
    File "/usr/lib/python3.6/site-packages/scudcloud/wrapper.py", line 259, in sendMessage
        self.window.notify(title, str(message), self.icon)
    File "/usr/lib/python3.6/site-packages/scudcloud/scudcloud.py", line 446, in notify
        self.notifier.notify(title, message, icon)
    File "/usr/lib/python3.6/site-packages/scudcloud/notifier.py", line 37, in notify
        notice.show()
    GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying (4)

## Steps to reproduce

I can't reproduce this reliably, as I can't reproduce dunst's crash reliably.

You could try running `dunst -print` which causes it to run in the foreground, then use Ctrl + C to kill it immediately after you receive a ScudCloud notification.

But really, I assume you can use the trace above to wrap the notification part in a try/catch and just ignore any error that might occur.

**Comment by raelgc** [comment]
Hi @RyanDwyer and thanks for raising this.

This is a nice issue, indeed, mainly the idea of keep Scudcloud running.

I'm just wondering if after `dunst` got back, Scudcloud will be able to send notifications again automatically.

**Comment by RyanDwyer** [comment]
Python isn't my primary programming language, so forgive me if my code is wrong. I'm guessing you could test it using something like this (in notifier.py):

    try:
        if "crash" in message:
            raise Exception("test")
        notice.show()
    except Exception:
        print("Caught exception")

Then have someone send you a message containing the word "crash" to generate the exception, followed by another message without the word "crash" to see if the notifications still work.

EDIT: On second thought, the exception has to be triggered by the notice module in order to test if it's still usable, so my code above isn't very useful :-\

**Comment by raelgc** [comment]
@RyanDwyer Yes, my idea was to use an exception. Can you try this locally?

**Comment by RyanDwyer** [comment]
I replaced notice.show() with this:

    try:
        notice.show()
    except:
        pass

Then when dunst crashes, ScudCloud continues to run and notifications continue to work.

I don't know if you'd want to accept this as is or catch a more specific exception? I'll leave it with you.

**Comment by raelgc** [comment]
@RyanDwyer I'm fine with this exception handling, we don't want info about what happened, just continue working. 

Had you tested this locally?

**Comment by RyanDwyer** [comment]
Yes. It works fine.

**Comment by raelgc** [comment]
@RyanDwyer Please, can you open a pull request with this change?
