### ISSUE TITLE
Can't log into slack with scudcloud

### ISSUE THREAD

**Issue by chris48s** [raelgc/scudcloud#529]
## ScudCloud Version

Paste the output for `scudcloud --version` below:
```
ScudCloud 1.41
Python 3.5.2
Qt 4.8.7
PyQt 4.11.4
SIP 4.17
```

## Distro and Desktop info

  - Distribution: Ubuntu
  - Version/Release: 16.04
  - Desktop environment: MATE

## Expected behavior

Log in successfully

## Actual behavior

Stuck on loading screen after posting login details

Tried running ScudCloud in debug mode. Last error logged is `TypeError: 'null' is not an object (evaluating 'TS.model.user.is_restricted')`. Can login fine using a web browser.

## Steps to reproduce
 1. Start ScudCloud
 2. Attempt to log in

**Comment by hackel** [comment]
Something seems to have changed just today.  It was working fine yesterday.  Official client still working fine, of course.

**Comment by raelgc** [comment]
Indeed guys, I just closed and restarted after your report and I can see lot of JS errors from Slack side related to `makeComparableVersion`. Need to investigate.

**Comment by raelgc** [comment]
I found a fix. I'll publish in next minutes.

**Comment by raelgc** [comment]
Ok, fixed. Published for Ubuntu. Please, update and upgrade your Ubuntu install.

**Comment by mtb-xt** [comment]
Could you make a release with this fix?

**Comment by chris48s** [comment]
Just updated to 1.43 and it is sorted - amazing :+1:

**Comment by raelgc** [comment]
@mtb-xt I just made the release. Sorry for the delay.

**Comment by alexeikh-promon** [comment]
I am still experiencing the issue. Here is my output of "scudcloud --version":

ScudCloud 1.44
Python 3.5.3
Qt 5.7.1
PyQt 5.7
SIP 4.18.1

**Comment by macedigital** [comment]
@raelgc Thanks for the fast response 👍  

For all affected Fedora users out there, I made a package from the latest release. (Unzip and run `dnf install <path/to/package>`)

[scudcloud-1.43-1.fc25.noarch.zip](https://github.com/raelgc/scudcloud/files/833910/scudcloud-1.43-1.fc25.noarch.zip)

**Comment by jdowner** [comment]
Wow! Thanks for the fast turn around on this issue +1

**Comment by linux-modder** [comment]
CAN confirm working on Fedora 25, still a little lag but not too sure that is not local network side, much appreciated on the fast turn around  Just Curious why not just shipping the .rpm and zipping it tho?

**Comment by gvenegas-1aauto** [comment]
I Still can't log in. i'm using ubuntu 15.10  is anyone else still unable to login? here is my version info:
scudcloud --version
ScudCloud 1.37
Python 3.4.3+
Qt 4.8.6
PyQt 4.11.4
SIP 4.16.9

**Comment by raelgc** [comment]
@gvenegas-1aauto Version `1.37` is an old version. Unfortunately, Ubuntu 15.10 is no more supported, so I cannot publish packages for it.

Anyway, you can manually fix this: locate, edit file `scudcloud/__main__.py` and change:

```python
app.setApplicationName(Resources.APP_NAME+' Slack_SSB')
```

by this:

```python
app.setApplicationName(Resources.APP_NAME+' Slack')
```

**Comment by gvenegas-1aauto** [comment]
@raelgc Thanks a lot for letting me know. i just changed it and works fine now. thank you.

**Comment by vectorsigma** [comment]
Can confirm 1.43 works in Fedora 25.  Per the Fedora maintainer of scudcloud, an easy fix (for now):
`dnf --enablerepo=updates-testing update scudcloud`

**Comment by cirulls** [comment]
I'm still having this issue since 13th March 2017 despite having upgraded to the latest version. I have the feeling my issue may be related to  proxy settings (I'm behind a corporate proxy).

I'm on Ubuntu 16.04 and this is the output on my ```scudcloud --version``` (note the warnings):

```
/usr/lib/python3/dist-packages/scudcloud/notifier.py:3: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python3/dist-packages/scudcloud/scudcloud.py:27: PyGIWarning: Unity was imported without specifying a version first. Use gi.require_version('Unity', '7.0') before import to ensure that the right version gets loaded.
  from gi.repository import Unity, Dbusmenu
ScudCloud 1.43
Python 3.5.2
Qt 4.8.7
PyQt 4.11.4
SIP 4.17
```
When I launch scudcloud it can't connect and get stuck at the daily slack message. When I connect via Firefox, it works and I get all the tests passing on the [Slack Test Your Connection page](https://slack.com/help/test). Note that I had to set up Firefox to auto-detect proxy settings (in Firefox is under Preferences -> Advanced -> Network -> Connection -> Settings). This is what let me think that there may be an issue with the proxy settings for scudcloud but I may be completely wrong. Note that my proxy environment variables are all set correctly as I can verify with ```env | grep proxy```. 

Is there a way to configure scudcloud to auto-detect proxy settings as I did with Firefox? I tried with proxychains as suggest in #102 but with no luck.

**Comment by raelgc** [comment]
Hi @cirulls. In the latest days, Slack published several changes to their JS internals (as expected, they're always moving forward), and this current issue is just one of them. I think you're facing same as #532

**Comment by cirulls** [comment]
Thanks for the quick reply. I have 3 teams set up and my ```__main__.py``` does not contain the ```Slack_SSB``` configuration (I tried it and relaunch scudcloud but got exactly the same behaviour). Running scudcloud in debug mode gives me the aforementioned warnings. 

I guess I have to wait, I can use the web interface in the meantime. Please keep us posted when this is resolved or if you want me to test any workaround you may have. Thanks.

**Comment by raelgc** [comment]
@cirulls A new version was released few hours ago. Please, update and upgrade.

**Comment by cirulls** [comment]
Thanks for the swift turnaround. I confirm it works with scudcloud v1.47 on Ubuntu 16.04. Thanks!
