### ISSUE TITLE
Slack UI for 1 of 3 teams won't load

### ISSUE THREAD

**Issue by rsyring** [raelgc/scudcloud#532]
## ScudCloud Version

```
scudcloud --version
ScudCloud 1.43
Python 3.4.3
Qt 4.8.6
PyQt 4.10.4
SIP 4.15.5
```

## Distro and Desktop info

  - Distribution: Xubuntu
  - Version/Release: 14.04
  - Desktop environment: xfce

## Expected behavior

When switching to one of three teams I am logged into, I expect the slack UI to load normally. 

## Actual behavior

One of the three teams I'm logged into appears to be loading, but it's not actually loading.  It never finishes and is stuck on "Were all in this together.  - Your friends at Slack."

When in debug mode, I don't get a notification that I switched to a new URL when I click on this team.

I've tried:
- signing out of the team and signing back in.
- using a new cache directory

## Steps to reproduce
 1. Open ScudCloud
 2. Click on team icon

**Comment by MKV21** [comment]
Same for me since today (I have only one team at all).

```
scudcloud --version
ScudCloud 1.43
Python 3.5.2
Qt 4.8.7
PyQt 4.11.4
SIP 4.17
```
Ubuntu 16.04 with i3.

**Comment by raelgc** [comment]
Please, do a manual check for me:  locate, edit file `scudcloud/__main__.py` and replace:

```python
app.setApplicationName(Resources.APP_NAME+' Slack_SSB')
```

by this:

```python
app.setApplicationName(Resources.APP_NAME+' Slack')
```

Close ScudCloud and reopen it.

**Comment by rsyring** [comment]
"by this" in English is confusing.  I assume you mean that it should be set "to this":

```python
app.setApplicationName(Resources.APP_NAME+' Slack')
```

Mine was already set to that.  Just in case, I changed it to "Slack_SSB" and now none of my teams load (changing it back).

**Comment by raelgc** [comment]
The intention is to check if you're **not** using `Slack_SSB`. Sorry if I'm not clear.

**Comment by rsyring** [comment]
> The intention is to check if you're not using Slack_SSB. Sorry if I'm not clear.

Correct, "Slack_SSB" is not present.

No problem on clarity, I just wanted to let you know for future reference.  

And THANK YOU for your prompt response!

**Comment by raelgc** [comment]
It happens only for one of your teams, right? Please, can you tell me by email what is the team name? My email is rael.gc@gmail.com. I'm wondering if it's a bug due the team name breaking some bad logic.

**Comment by rsyring** [comment]
I've also noticed that, once I click on the team that is trying to load, scudcloud is a CPU hog using up about 40% CPU.  When I click to a different team scudcloud's CPU usage drops to around 10%.

**Comment by bstein-clever** [comment]
I'm experiencing this problem as well; I only have one team, so nothing loads.
I don't have the "_SSB", and the team name is pretty innocuous. No special characters or anything.

My workaround is the Web UI, which works fine, but it's not as nice as having a dedicated app.

**Comment by raelgc** [comment]
@bstein-clever I'm investigating the reason. It's hard because I cannot reproduce, so I'm trying to use info sent by @rsyring.

In this meanwhile, you can use the official app, it's really great.

**Comment by raelgc** [comment]
@rsyring Thank you for send me all the info by email. After investigate, I saw that, for some reason, the team failing is facing a JS issue (`can't find variable MutationServer`), which I don't see in teams loading normally.

Wondering why some teams are facing this and others not.

**Comment by rsyring** [comment]
I don't know if this is it, but this is the only account of the three that I use that uses Google OAuth for authentication against our Google Apps account.

**Comment by jdob** [comment]
The __main__.py hack worked for me, thanks :)

**Comment by raelgc** [comment]
@rsyring This is a good info! @MKV21 Is your team under Google OAuth too?

**Comment by wsgeorge** [comment]
Experiencing the same problem: loading screen with Google Auth. 
The first error in console is: 
TypeError: 'null' is not an object, (evaluating 'TS.model.user.is_restricted')

**Comment by MKV21** [comment]
No, we are not using Google OAuth. But I observe the same behavior as @rsyring, the CPU load goes up while scudcloud is trying to load (and never finishes to load). 'Slack' is set as application name.

**Comment by raelgc** [comment]
@wsgeorge The `'TS.model.user.is_restricted'` error is common and do not affect the team loading. Can you check if you can see the `can't find variable MutationServer` error?

**Comment by wsgeorge** [comment]
Yes. Looks like that:
`2017/3/14 14:06:34.356 logging e:ReferenceError: Can't find variable: MutationObserver e.stack:ScrollBlot@https://cdx.slack-edge.com/85db3/js/prebuilt/texty.js:2`

**Comment by bstein-clever** [comment]
I, too, am using Google OAuth for this account.
I certainly understand that it's difficult to debug if you can't reproduce.
But I'll also observe that there isn't actually an "official app" for Linux, just a web app, which isn't the same, and why I like scudcloud so much!

**Comment by rsyring** [comment]
@bstein-clever https://slack.com/downloads/linux

**Comment by raelgc** [comment]
@bstein-clever This is the same for all platforms: all Slack clients are just a wrapper around the web app. The oficial client is using Node+[electron](https://github.com/electron/electron) to render it, Scudcloud Qt+webkit.

**Comment by raelgc** [comment]
I just published a "half fix" for this issue for Ubuntu. But, unfortunately, it works properly only in the qt5 version.

I can promote it to be the main version now. But some stuff is not working on it yet, like the red marks under misspelled words and other minor issues.

**Comment by raelgc** [comment]
Ok, I fixed the second issue right now. There is an implementation of `MutationObserver` in webkit-qt4, but it's named `WebKitMutationObserver`. I'll publish in the next minutes.

**Comment by raelgc** [comment]
Just published new package version with the full fix. Please, update and upgrade (if you're under Ubuntu). For other distros, wait until your distro maintainer.

**Comment by rsyring** [comment]
Confirmed fixed on Ubuntu 14.04.  Thanks @raelgc!!

**Comment by raelgc** [comment]
@rsyring Welcome and thank YOU for all the efforts providing valuable feedback!

**Comment by bstein-clever** [comment]
Confirmed working for me, too. Thanks!
I had never noticed the official slack app before; last time I checked, they didn't even have a beta version out yet. I'll have to try it sometime.

**Comment by rsyring** [comment]
It seems like this bug is back.  Is anyone else having the same issue?  I can't troubleshoot immediately but will try and do a debug session over the weekend.

**Comment by raelgc** [comment]
@rsyring Still facing issues?

**Comment by rsyring** [comment]
No, they resolved on your their own.  Temporary glitch.  Thanks.

Randy Syring (sent from my mobile)
Chief Executive Developer
Direct: 502-276-0459
Office: 812-285-8766

Level 12 - Principled People | Software that Works
