### ISSUE TITLE
Opening a large text snippet makes scudcloud go 100% CPU utilization

### ISSUE THREAD

**Issue by zerthimon** [raelgc/scudcloud#535]
## ScudCloud Version

Paste the output for `scudcloud --version` below:
```
zerth@liasus:~$ scudcloud --version
/usr/lib/python3/dist-packages/scudcloud/notifier.py:3: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python3/dist-packages/scudcloud/scudcloud.py:27: PyGIWarning: Unity was imported without specifying a version first. Use gi.require_version('Unity', '7.0') before import to ensure that the right version gets loaded.
  from gi.repository import Unity, Dbusmenu
ScudCloud 1.43
Python 3.5.2
Qt 4.8.7
PyQt 4.11.4
SIP 4.17
```

## Distro and Desktop info

  - Distribution: ubuntu
  - Version/Release: 16.04
  - Desktop environment: unity

## Expected behavior
A large text snippet should expand without hanging scudcloud

## Actual behavior
When a large text snippet is expanded scudcloud utilizes 100% CPU becoming very slow to respond, only restart helps.

## Steps to reproduce
 1. Ask someone to send you a large (100 lines ?) text snippet
 2. Expand it
 3. Observe 100% CPU utilization
 4. Restart

**Comment by raelgc** [comment]
This is a known behavior of qt4. But you can force snippets being opened in default browser. Please see https://github.com/raelgc/scudcloud#9-viewing-snippets-consumes-too-much-resources

**Comment by zerthimon** [comment]
@raelgc Thanks for the info.
Is there an upstream issue in qt4 that I can take a look at ?

**Comment by zerthimon** [comment]
@raelgc so I've disabled the snippets in config. After doing that the chat doesn't show snippet (just a message), but when I click on it I don't get it in browser (nothing happens)

**Comment by raelgc** [comment]
Unfortunately, you have to click directly in the blue hyperlink to open it in browser. If you click in any blank space, it'll not open.
