### ISSUE TITLE
Native File Manager isn't used anymore?

### ISSUE THREAD

**Issue by simonsaysforcepush** [raelgc/scudcloud#539]
## ScudCloud Version

Paste the output for `scudcloud --version` below:
ScudCloud 1.44
Python 3.6.0
Qt 5.8.0
PyQt 5.8
SIP 4.19.1

## Distro and Desktop info

  - Distribution: Arch
  - Version/Release: N/A
  - Desktop environment: Openbox

## Expected behavior
When uploading a file from my computer, I expect thunar (my chosen file manager) to load.

## Actual behavior
Instead of thunar, I get some crappy windows-esque file manager that doesn't work the way I need it to.

## Steps to reproduce
 1. Attach a file
 2. Select "Your Computer" 
 3. ?????
4. PROFIT!!! (Actually no profit, just shitty file manager)

**Comment by raelgc** [comment]
This is automatically handled by `Qt` library. Few releases ago, Arch version of Scudcloud started to use the Qt5 version (instead of Qt4), because Arch dropped pyqt4 support.

**Comment by raelgc** [comment]
All versions now using the Qt5 branch. I'll close this as this is out of scope for this project (ScudCloud is just using Qt automatic handling for file manager).
