### ISSUE TITLE
Message list overlapped at the bottom

### ISSUE THREAD

**Issue by loonies** [raelgc/scudcloud#540]
## ScudCloud Version

```
ScudCloud 1.46
Python 3.6.0
Qt 5.8.0
PyQt 5.8
SIP 4.19.1
```

## Distro and Desktop info

  - Distribution: Arch Linux
  - Version/Release: N/A
  - Desktop environment: Xfce

## Expected / Actual behavior

A screenshot is worth a thousand words.

![scudcloud-message-list-overlap](https://cloud.githubusercontent.com/assets/109212/24242158/4104ca0e-0fb7-11e7-9d63-37e4dafe7b4f.png)

**Comment by raelgc** [comment]
Hi @loonies and thanks for raising this issue.

Indeed, yesterday I was working to promote this Qt5 version for other distros as the main version, and saw this issue. 

Slack changed their internal CSS, and for some reason Qt5 version is the only affected.

I'm working on a fix for it (probably overwrite Slack CSS for this element).

**Comment by ghost** [comment]
For now I'm going to update scudcloud to use revision a7736b04311f21328e24525f0d5976f84c6962d4, which does fix the issue. I'll keep an eye open and see if slack fixes the issue (as you mention that it might be their problem).

**Comment by loonies** [comment]
After manually applying aforementioned patch I can observe that the
message list is not overlapped by the message input element any more.

**Comment by raelgc** [comment]
The only downside of that fix is after you send a message, the messages list pane will get the correct size back and display a bottom padding :(

**Comment by ghost** [comment]
d'oh! There was a reason you reverted that commit..... I didn't notice that in my brief testing.

**Comment by onitake** [comment]
It seems Slack fixed the Problem in their CSS?
At least I'm not seeing it any more...

**Comment by loonies** [comment]
Looks like, I can observe that now the bottom padding is double in size.

**Comment by ghost** [comment]
Just bumped it to the latest revision that reverses it. I think this can be closed now.

**Comment by raelgc** [comment]
Thank you for sharing this good news, guys. I'm planning to roll out qt5 version as the unique version.

**Comment by ghost** [comment]
@loonies Is everything alright now? Can this be closed?

**Comment by loonies** [comment]
No issues so far. Thank you.
