### ISSUE TITLE
ScudCloud marked as deprecated by Slack

### ISSUE THREAD

**Issue by raelgc** [raelgc/scudcloud#541]
Slack is marking ScudCloud as deprecated client and asking to download the official app.

The workaround is to click on "Skip now" or download the official app.

The solution should be investigate how Slack clients reports version to Slack in the JS side. Opening the debug console will help to investigate it.

I'm moving to a new house, so I'll face a limited connection for some day. Anyhelp will be appreciated.

To open ScudCloud in debug mode, start with `scudcloud --debug=True &`, right click anywhere in the message pane, select Investigate, maximize the new window, select Console tab.

**Comment by raelgc** [comment]
Ok, I found a fix.

**Comment by loonies** [comment]
Super annoying

![bow](https://media.giphy.com/media/MUeQeEQaDCjE4/giphy.gif)

**Comment by raelgc** [comment]
Mama mia, let me go!
