### ISSUE TITLE
Latest Release 1.50 Places Unity Panel Indicator on Left Side of Screen in Ubuntu 14.04

### ISSUE THREAD

**Issue by stratigos** [raelgc/scudcloud#543]
## ScudCloud Version

`ScudCloud 1.50
Python 3.4.3
Qt 5.2.1
PyQt 5.2.1
SIP 4.15.5`

## Distro and Desktop info

  - Distribution: Ubuntu
  - Version/Release: 14.04
  - Desktop environment: Unity

## Expected behavior

Unity Panel Icon is placed right-justified, next to all the other panel icons. It doesnt cover application text or menus, and isnt placed left-justified. Panel icon also appears on redundant unity panels (i.e., 2nd monitor). 

## Actual behavior

Icon appears in left-most place in the Unity panel. It covers application names / text / and some dropdown menus. Also panel icon only appears once, and is missing from my 2nd unity panel (I have one on both of two monitors).

I actually cant close some applications with the mouse, and not all applications have a "Ctrl+W/Q" command. I either have to open terminal and kill an app's process, or shift it to another workspace which doesnt have the panel icon and close it there.

## Steps to reproduce
 1. Update to 1.50 on 03.29.2017
 2. Launch scudcloud
 3. Observe panel with scudcloud icon floated to the left

**Comment by raelgc** [comment]
Thank you @stratigos for opening this issue.

Are you using Close to Tray?

Can you, please, attach a screenshot?

**Comment by stratigos** [comment]
@raelgc Thanks for the response, and thanks for Scudcloud as well :)

I use Scudcloud every day, on two different machines, and am very appreciative of your work bringing this client to the Linux environment. I only noticed this problem immediately after updating this morning, it was not exhibiting this behavior yesterday or anytime before. 

> Are you using Close to Tray?

I am not sure where to find the preference/feature for "Close to Tray". In my `~/.config/scudcloud/scudcloud.cfg` file I do have: `Systray=True`. I noticed in the readme there is the `File > Close to Tray` option listed, but I dont seem to have any such "File" dropdown menu (or any other Scudcloud specific menus - Ive only ever used the config file). Any options that are given by the Unity Panel indicator/icon pertain to _Slack_ specific settings. 

> Can you, please, attach a screenshot?

![screenshot from 2017-03-29 11 59 52](https://cloud.githubusercontent.com/assets/3875361/24464509/1b6c03c8-1478-11e7-86d3-b673fbd9de1f.png)

The above is both of my monitors, with my redundant Unity panel and launcher. Note the Scudcloud panel indicator in the farthest topleft position - its usually just to the left of my dropbox panel indicator. Also note it is not on both screens, it only appears on the left screen.

Let me know if I can be of further assistance, thanks.

**Comment by raelgc** [comment]
Thank you for the feedback, @stratigos!

Yes, you're using Close to Tray enabled. Just to share: you can activate Close to Tray, just opening the standard app menu and select File > Close to Tray.

I found this is a Qt bug (several opened issues in Qt side for it), and appears to be fixed in Qt 5.5 (i.e., do not affects Xenial)..

The fix on 14.04 appears to be create a notification entry, similar to [viber-wrapper indicator](https://github.com/karas84/viberwrapper-indicator/blob/master/viberwrapper-indicator.py)

**Comment by stratigos** [comment]
@raelgc Ok thanks, I could either experiment with that, or upgrade my system. Was hoping I could hold out until 18.04 is released but Ill treat this as the first sign that an upgrade is imminent. This can be closed. Thanks! 

----

FWIW there is no app menu on my 14.04 desktop for scudcloud, none appears. I can check on my 16.04 machine sometime later.
