### ISSUE TITLE
ScudCloud crash which invokes apport results in two instances running

### ISSUE THREAD

**Issue by shevek** [raelgc/scudcloud#545]
## ScudCloud Version

Paste the output for `scudcloud --version` below:
`ScudCloud 1.50
Python 3.5.2
Qt 5.5.1
PyQt 5.5.1
SIP 4.17
`

## Distro and Desktop info

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

  - Distribution:
  - Version/Release:
  - Desktop environment: XFCE

## Expected behavior

It either runs, or exits, but not both. If a thread causes a crash and invokes apport, exit the app entirely, don't leave me with a half broken instance running and a second full instance running.

## Actual behavior

A crash on one thread which invokes apport seems to trigger some app-restart mechanism which I can't seem to disable AND the version which triggered the apport crash doesn't exit, so I end up with two.

## Steps to reproduce
 1.  Nothing special.
 2. 
 3.

**Comment by raelgc** [comment]
Yeap, I know this is odd, but it's something I cannot control due the nature of some Qt GUI objects automatically living in other threads.

The workaround is just uncheck the option to restart the app.
