### ISSUE TITLE
Recent scudcloud stopped remembering zoom levels on restart

### ISSUE THREAD

**Issue by josephlbarnett** [raelgc/scudcloud#547]
## ScudCloud Version

Paste the output for `scudcloud --version` below:
``
ScudCloud 1.50
Python 3.5.3
Qt 5.7.1
PyQt 5.7
SIP 4.18.1

## Distro and Desktop info

  - Distribution: Ubuntu
  - Version/Release: zesty
  - Desktop environment: Gnome

## Expected behavior
Until recently (sometime last week?), scudcloud would remember zoom levels between restarts.

## Actual behavior
I need to re-zoom in (hidpi screen) every time I restart

## Steps to reproduce
 1. Start scudcloud
 2. change zoom
 3.  restart scudcloud

**Comment by raelgc** [comment]
Thank you for reporting this, @jbarnettwomply.

I'll investigate it and fix.

**Comment by raelgc** [comment]
Please, update and upgrade.

**Comment by josephlbarnett** [comment]
confirmed fixed, thanks!
