### ISSUE TITLE
login/password is not remembered

### ISSUE THREAD

**Issue by zerthimon** [raelgc/scudcloud#549]
latest version
Have to sign up to team every time I start scudcloud  ("Keep me signed in" checkbox is checked)

**Comment by raelgc** [comment]
Hi @zerthimon and thanks for raising this issue.

Can you, please, check if you have these file and folder? `~/.config/scudcloud/scudcloud_qt5.cfg`

**Comment by zerthimon** [comment]
@raelgc yep I do have this file.
I'm working with 3 teams in scud, one of the teams doesn't keep the login across restarts, while other teams do.

**Comment by shevek** [comment]
I just lost 8 teams on a scudcloud restart.

**Comment by raelgc** [comment]
You don't lost them. They're just not being properly loaded. It's related to #554
