### ISSUE TITLE
Spell check not working?

### ISSUE THREAD

**Issue by kspears** [raelgc/scudcloud#55]
Maybe I'm the only one having issues with getting spell check working. I've got scudcloud and the hunspell-en-us packages installed and scudcloud seems to be working fine. Just can't get it to correct my spelling. When i right click on a red underlined word, there are no options presented to me. Wondering if I just missed something?

**Comment by raelgc** [comment]
Hi @kspears, thank you for reporting this issue.

Unfortunately, this is how the spell checker plugin from QupZilla works: it'll mark words in red, but not suggest correct ones on right click.

What got me wondering that I should add this info in the README.

**Comment by mcg** [comment]
Readme might be a good idea. I just came here to file that bug :-) Also booo for no suggestion support.

**Comment by raelgc** [comment]
@mcg Indeed, that will be awesome. I'm just searching the web to see if someone was able to get suggestions working with QupZilla spell corrector library.

**Comment by raelgc** [comment]
Found a way in the QupZilla project: https://github.com/QupZilla/qupzilla/blob/v1.8/src/lib/webkit/webview.cpp#L870

**Comment by boltronics** [comment]
I've got the latest build on Debian GNU/Linux (Jessie), with hunspell-en-us=20070829-6 installed. I ran `dpkg-buildpackage -uc -tc -b`, installed the deb, and I still have no spell checking support. I don't even get anything underlined. Any suggestions?

**Comment by raelgc** [comment]
@boltronics Sorry for my late response. Yeap, additionally to the hunspell package for your language, you need the hunspell plugin for Qt installed. Can you try install the package `libqtwebkit-qupzillaplugins_1.0-1_amd64.deb` available in https://launchpad.net/~rael-gc/+archive/ubuntu/scudcloud/+packages ?

**Comment by boltronics** [comment]
That seems to work, thanks! It would be great to have that in the documentation. Even better to have the package in Jessie backports. :)

**Comment by ngrennan-inflection** [comment]
Spell checking is not working for me on Fedora 22 x86_64 and scudcloud 1.0.50. I have libqtwebkitplugins.so in /usr/lib64/qt4/plugins/webkit. I can even see it loading it with strace. I have the hunspell packages. I have tried setting the environment variables mention at, https://github.com/QupZilla/qtwebkit-plugins . I get no underlined misspellings.

This is a big deal to me, because it was one of my main complaints with Skype. I am converting from Skype to Slack. It works in the browser client.

It would be nice if spell checking was handled via libraries that distributions commonly have instead of the Qupzilla qtwebkit plugin.

Packages:
hunspell-en-US-0.20140811.1-1.fc22.noarch
hunspell-1.3.3-4.fc22.x86_64
hunspell-devel-1.3.3-4.fc22.x86_64

**Comment by davidborrowman** [comment]
Hello. I have installed the hunspell plugin for Qt and ibqtwebkit-qupzillaplugins_1.0-1_amd64.deb as referenced above and still can't get any spelling suggestions within Scudcloud (fine elsewhere).
I use Kubuntu 14.04... KDELibs 4.1.3.3,  Qt 4.8.6, Kernel 3.16.0-38-generic x64... Please let me know if there is anything I can do to help diagnose the issue... Thank you for great software!

**Comment by tomchiverton** [comment]
I can ack @davidborrowman comment for Kubutnu 14.04, even with the extra libqtwebkit-qupzillaplugins package, there's no spell check at all, never mind right click support.
Correction: some times it highlights after a delay, but it's not consistent. Also, "my woord is woord" only has the first "woord" underlined. If I click away from the input box, the underline on the second one appears.

**Comment by davidborrowman** [comment]
Scud does spell check for me, but it only highlights (red squiggle line) misspelled words. Right clicking just doesn't bring up any spelling suggestions as it does in most other programs. It servers as a constant reminder of how stupid I am, and offers no help :)   I'm hoping this will make be a better speller, but I doubt it. Cheers!

Interesting side note: When I right click on a word, the red squiggles disappear for a moment like its thinking about doing something.

**Comment by raelgc** [comment]
Sorry for the long delay on tackle this one... but it's not easy. I've tried in several different ways...

But I think now I've finally made it! Please, upgrade and let me know if it works.

If not, please, re-open this issue.

**Comment by raelgc** [comment]
Guys, someone can port [libqtwebkit-qupzillaplugins](https://launchpad.net/~rael-gc/+archive/ubuntu/scudcloud/+packages) and [python3-hunspell](https://launchpad.net/ubuntu/trusty/+package/python3-hunspell) to `.rpm`? So we can offer a complete spell checking experience on Fedora and openSUSE.

**Comment by mbajor** [comment]
@raelgc I'll try to do it today or on friday

**Comment by rsyring** [comment]
I'm running Ubuntu 14.04.  I have the following packages installed:
- libqtwebkit-qupzillaplugins 1.0-1
- libhunspell-1.3.0 1.3.2-6ubuntu2
- hunspell-en-us 20070829-4ubuntu3
- python3-hunspell 0.1-1build2

I get spell checking errors as red squiggle lines, but I do not get spelling suggestions.

Let me know if there is any way I can help test this.

**Comment by tomchiverton** [comment]
WFM now on 14.04, red underline and right click correction popup. Win.

scudcloud 1.0-71
libqtwebkit-qupzillaplugins 1.0-1
libhunspell-1.3.0 1.3.2-6ubuntu2
hunspell-en-us 20070829-4ubuntu3
python3-hunspell 0.1-1build2

**Comment by boltronics** [comment]
Confirming it's working for me on Debian Jessie. Great stuff.

The only odd thing I noticed was when spellcheck automatically kicks in. If I type a mistyped word and press space, nothing happens. I only get an underline if I start typing a new word. This is in contrast to the way other programs behave, such as LibreOffice which spell check immediately after a white-space character is pressed.

In an instant messaging program, ideally the spellcheck would be even more aggressive in when it kicks in, as the last character in a line may not have any trailing white-space, for example. But it would be good to at least make the behaviour more consistent with other software.

**Comment by raelgc** [comment]
@boltronics I totally agree that the red marking behavior is a bit weird (like you said, it's not displayed immediately after the blank space).

The problem is: the way this works is internal to QtWebKit (the HTML rendering engine). It pass the word to the speller plugin, which will just say if the word is fine or not, and then QtWebKit itself mark the word in red.

Probably this is improved in newest versions of Qt (in case, Qt5). We have plans to upgrade it in the future, anyway.

**Comment by boltronics** [comment]
Makes sense. Thanks @raelgc.

**Comment by ghost** [comment]
sudo apt-get install libqtwebkit-qupzillaplugins
sudo apt-get install python3-hunspell
sudo apt-get install hunspell-en-us
sudo apt-get update

I did those commands in terminal to get spellcheck working but it doesnt work. I somehow managed to get it working on my other computer (with Ubuntu also) but I don't know what I've not done to make it work.

**Comment by tadas-s** [comment]
Can confirm, on Linux Mint 17, Linux Mint 18.1 this did the trick:

```
sudo apt-get install hunspell hunspell-en-us libqtwebkit-qupzillaplugins
```

Also, don't forget to install appropriate dictionary if your locale is not en-us.

**Comment by raelgc** [comment]
Thank you for the feedback, @tadas-s!

**Comment by rghvdberg** [comment]
~~Can't get it to work in Mint 18 compatible with Ubunutu 16.04 xenial) 
Installed Scudcloud via ppa, check if the packages above were installed 
No red wavy line :-(
Any suggestions ?~~

~~btw, It worked on Mint 17.3~~

edit : never mind ... it works
