### ISSUE TITLE
ScudCloud fails to upgrade/install due to libqt5 related library conflicts

### ISSUE THREAD

**Issue by rsyring** [raelgc/scudcloud#550]
## ScudCloud Version

Paste the output for `scudcloud --version` below:
```
ScudCloud 1.48
Python 3.4.3
Qt 4.8.6
PyQt 4.10.4
SIP 4.15.5
```

## Distro and Desktop info

  - Distribution: Ubuntu 
  - Version/Release: 14.04
  - Desktop environment: XFCE

Also using the LTS Enablement Stack to get updates to the kernel and X: https://wiki.ubuntu.com/Kernel/LTSEnablementStack

## Expected behavior

I want to update to the latest ScudCloud 1.5.x version.  I expect Synaptic to update ScudCloud.

## Actual behavior

Synaptic requires an **upgrade** not an update.  But, when upgrading, I get warnings that a lot of core packages would be removed in the process:

![image](https://cloud.githubusercontent.com/assets/109467/24714308/226c46be-19f6-11e7-8bc1-02884515fbbf.png)

![image](https://cloud.githubusercontent.com/assets/109467/24714330/34506400-19f6-11e7-98c1-2b05309bdc47.png)

![image](https://cloud.githubusercontent.com/assets/109467/24714351/3cdb5cc4-19f6-11e7-9d51-7e2a3410ed51.png)

Why is the upgrade of ScudCloud affecting other core parts of my system?

**Comment by raelgc** [comment]
Hi @rsyring!

No, ScudCloud has no requirements in specific X version. 

Requires packages are (like described in [`/debian/control`](https://github.com/raelgc/scudcloud/blob/master/debian/control) file):

         python3,
         python3-setuptools,
         python3-dbus,
         python3-dbus.mainloop.qt,
         gir1.2-notify-0.7,
         python3-pyqt5,
         python3-pyqt5.qtsvg,
         python3-pyqt5.qtwebkit,
         xdg-utils,
         notification-daemon

As you're running an upgrade after several days without run one, you'll have a ton to upgrade.

**Comment by rsyring** [comment]
So, I tried a bunch of googling and ran lots of apt related commands but nothing worked.  In the end, it seems there is a problem with the way QT dependencies are specified on Ubuntu.  The command that finally got me moving forward was:

`$ sudo apt-get install libqt5gui5`

A full terminal session showing the problem, error messages, and eventual resolution is posted here for posterity's sake: https://gist.github.com/rsyring/74654ef6b97386354e7377bb350c635f

**Comment by raelgc** [comment]
Thanks for sharing the solution. Wondering if we should add this package as a requirement.

**Comment by rsyring** [comment]
Maybe change the title of this issue to be more reflective of the underlying problem:

> ScudCloud fails to upgrade/install due to libqt5 related library conflicts

and leave it open to see if anyone else runs into the issue and comments on it?

**Comment by aschosser** [comment]
I have the same issue on ubuntu 14.04.
'apt-get install scudcloud' fails, because missing dependcy qt5-style-plugins cannot be installed.

**Comment by raelgc** [comment]
I'll move this package to `recommends` section.

**Comment by raelgc** [comment]
@aschosser Can you try update and upgrade again, please?

**Comment by aschosser** [comment]
@raelgc Now I could install with apt-get. Thank you.
