### ISSUE TITLE
scudcloud doesnt keep me online anymore

### ISSUE THREAD

**Issue by fabiofranco85** [raelgc/scudcloud#556]
## ScudCloud Version

Paste the output for `scudcloud --version` below:
`ScudCloud 1.50
Python 3.4.2
Qt 5.3.2
PyQt 5.3.2
SIP 4.16.4`

## Distro and Desktop info

  - Distribution: Debian
  - Version/Release: Debian GNU/Linux 8.7 (jessie)
  - Desktop environment: KDE KWin: 4.11.13

## Expected behavior

In previous versions scudcloud was keeping me always online

## Actual behavior

After a few minutes it will set my status as _away_

## Steps to reproduce
 1. Open scudcloud
 2. Keep the focus out of scudcloud (or do nothing on your computer) for a few minutes
 3. Check the status and it will be set as _away_

**Comment by raelgc** [comment]
I've made several fixes in the last days. This should be working now (if you upgraded to the latest version). Let me know if still an issue.
