### ISSUE TITLE
Typing is very slow on Ubuntu 14.04.2 / KDE 4.13.3

### ISSUE THREAD

**Issue by feoh** [raelgc/scudcloud#56]
The client works (well in fact) but typing input to send a message is incredibly slow - easily 3 seconds behind the actual keystrokes.

It's still usable but just barely.

Happy to provide any additional debugging info I can.

(I installed from the repo using the apt-get instructions on Github)

**Comment by jake-minted** [comment]
I'm facing the same issue on ArchLinux. There is some reasoning to believe that it is related to spell checking

**Comment by grubernaut** [comment]
I'm seeing the same issues on ArchLinux. There is some reasoning to suggest it's from spell checking.

**Comment by raelgc** [comment]
I think you guys can try remove the spell checker package (`libqtwebkit-qupzillaplugins`), if exists in Arch, it's just recommended, not required. Other possible candidate to make program slow can be `gi` stuff, but I'll need to check which lines of code to disable.

**Comment by raelgc** [comment]
Other stuff easy to check: using `sudo` or `root`, edit `/opt/scudcloud/lib/wrapper.py` and comment this line: 

`# QWebSettings.globalSettings().setAttribute(QWebSettings.PluginsEnabled, True)`

It'll start Flash, maybe Java, and I think they're not required at all.

**Comment by feoh** [comment]
@raelgc Thanks for the suggestions.  I tried commenting that line out but with no luck.  I also tried disabling "Spell check input" in the preferences, still no dice.

I tried removing the hunspell-en-us package using apt-get, still no change.

Happy to try anything else you'd care to suggest!

**Comment by raelgc** [comment]
@feoh Please, try my last suggestion (disable the webkit browser plugins).

**Comment by feoh** [comment]
@raelgc Thanks but as I mentioned previously commenting out that line had zero net effect.  Is there something I need to do after editing that file other than quitting and restarting the app?

**Comment by raelgc** [comment]
@feoh Oh, sorry, I missed that. Any luck removing the `libqtwebkit-qupzillaplugins` package?

**Comment by feoh** [comment]
@raelgc No worries at all, but sadly, no joy, again I apt-get removed that package and restarted scudcloud, and still slower than molasses going uphill in February :)

Do I perhaps need to reboot or something?

**Comment by raelgc** [comment]
@feoh No, just close and re-open the app will be enough.

As you mentioned slowness while typing, maybe one worth test is to disable the eventfilter that watchs for `Ctrl`+`#` to switch between teams.

Please, open as `sudo` or `root` this file: `/opt/scudcloud/lib/scudcloud.py` and disable this line (probably line 58):

`# self.installEventFilter(self)`

Then close and restart ScudCloud.

**Comment by feoh** [comment]
@raelgc Thanks a bunch tried that and yet still no joy :) Still incredibly slow. @grubernaut I'd be curious to hear if you've tried any of these workarounds and whether you had any success either.

**Comment by feoh** [comment]
Turns out things are much better for @grubernaut - but he's not running KDE.  I wonder if my issue is KDE specific? I should try logging in with Unity and see if it goes away.

**Comment by raelgc** [comment]
Closing by inactivity. Please, re-open if required.

**Comment by emichael** [comment]
I'm having similar issues with unity, no success after disabling/uninstalling spellcheck etc.

**Comment by raelgc** [comment]
Hi @emichael, thanks for raising this and sorry for the inconvenience.

Which Ubuntu version are you using? Is it updated with `sudo apt-get update && sudo apt-get dist-upgrade`?

**Comment by emichael** [comment]
I'm using Ubuntu 14.04.2 with the vivid kernel (version 3.19.0-41), everything is up to date.

**Comment by raelgc** [comment]
Right, same as me. Are you facing any hard time with CPU or RAM usage while using ScudCloud?

**Comment by grubernaut** [comment]
@emichael I switched to the official slack app, and it's been working so far

**Comment by emichael** [comment]
RAM is fine (under <1GB being used total on my system with 16GB, after I shut Chrome down of course), but one of my cores is spiking at 100% when I'm experiencing the typing lag. The lag seems to come and go, though, which is weird.

@grubernaut There's an official app?? Where?

**Comment by raelgc** [comment]
@emichael You can download the official client at https://slack.com/downloads

**Comment by raelgc** [comment]
@emichael and @grubernaut Sorry for not being able to reproduce this issue (so, not being able to fix it). At least now we have 3 Slack clients to use on Linux in case of problems :)
