### ISSUE TITLE
Ubuntu Matte 16.04 unmet dependencies qt5-styleplugins

### ISSUE THREAD

**Issue by nathanpw** [raelgc/scudcloud#560]
Hi, Thanks for the great software. This maybe more of a question then an issue. I have been using scudcloud for a couple months now and it's been great. However recently I can't update anymore because of a missing dependency (see below in actual behavior). After a little research I see you have added dependecy for [qt5-styleplugins](https://github.com/raelgc/scudcloud/commit/c1bdb9a3f0a82c1cc98f5f544399a3b589102f3c), however in the ubuntu package manager I believe it is listed as qt5-style-plugins (extra hyphen). Not sure if this is the case or maybe I need a different version of QT. Any help would be appreciated.

## ScudCloud Version

Paste the output for `scudcloud --version` below:
`ScudCloud 1.50
Python 3.5.2
Qt 5.5.1
PyQt 5.5.1
SIP 4.17
`

## Distro and Desktop info

  - Distribution: Ubuntu Matte
  - Version/Release: 16.04
  - Desktop environment: Matte

## Expected behavior
To be able to update to the next version.

## Actual behavior
When updating I get a message stating: 
The following packages have unmet dependencies:
 scudcloud : Depends: qt5-styleplugins but it is not installable
E: Unable to correct problems, you have held broken packages.

## Steps to reproduce
 1. run sudo apt-get install scudcloud on Ubuntu 16.04 Matte

**Comment by raelgc** [comment]
Sorry for that. I was in a hurry to fix several minor issues and made this typo. I'm already uploading the fix.

Really thank you for reporting this quickly!
