### ISSUE TITLE
Creating a "Post" doesn't open a new window.

### ISSUE THREAD

**Issue by rsyring** [raelgc/scudcloud#568]
## ScudCloud Version

Paste the output for `scudcloud --version` below:
```
ScudCloud 1.57
Python 3.4.3
Qt 5.2.1
PyQt 5.2.1
SIP 4.15.5
```

## Distro and Desktop info

  - Distribution: Xubuntu
  - Version/Release: 14.04
  - Desktop environment: XFCE

## Expected behavior

1. Click "+" icon to the left of the message area
2. Click New...Post
3. Have window open to create a Post

## Actual behavior

On step #3 above, nothing happens.

**Comment by raelgc** [comment]
Hi @rsyring and thanks for raising this.

In the paste, I've made a fix for it in #225, which was a random issue.

I'm investigating this and will publish a fix soon.

**Comment by raelgc** [comment]
Fix published for Ubuntu. Thank you again for reporting this issue, @rsyring
