### ISSUE TITLE
Cannot save more than 2 teams between restarts

### ISSUE THREAD

**Issue by alfredopalhares** [raelgc/scudcloud#569]
## ScudCloud Version

```
ScudCloud 1.57
Python 3.6.1
Qt 5.8.0
PyQt 5.8
SIP 4.19.1
```
## Distro and Desktop info

  - Distribution: Arch Linux
  - Version/Release: Rolling Release updated today
  - Desktop environment: Gnome 3

## Expected behavior

All the teams should be stored between restarts.

## Actual behavior

Only the first 2 teams are saved.

## Steps to reproduce
 1. Delete scudcloud cache
 2. Log in to more than 2 teams (in my case 5), marking "Keep Login"
 3. Restart scudcloud
 4. Only the first 2 teams will be available.

**Comment by raelgc** [comment]
Hi @masterkorp and thanks for raising this issue.

If you start Scudcloud by terminal, is there any output with stack errors?

**Comment by alfredopalhares** [comment]
I just upgraded to 1.58 and this stopped being an issue!

Closing for the meantime.
