### ISSUE TITLE
HiDPI Support

### ISSUE THREAD

**Issue by efuquen** [raelgc/scudcloud#57]
I'm running Ubuntu 14.10 on a Macbook pro with a retina display.  When using scudcloud the embedded QtWebkit browser runs at the native resolution without any scaling.  I can imagine the app either having a scaling option in preferences or picking up the scale ratio set up via the Display settings on the OS.

This bug report here seems to be relevant:

https://bugs.webkit.org/show_bug.cgi?id=104574#c19

**Comment by efuquen** [comment]
This blog post seems to describe step by step what would be necessary:

http://blog.davidedmundson.co.uk/blog/kde_apps_high_dpi

This project looks to be based on Qt4, so upgrading to Qt5 would seem to be the biggest blocker.

**Comment by raelgc** [comment]
Hi @efuquen, thanks for reporting this issue.

I'll check the links you provided.

In this meanwhile, you can try zoom in pressing `Ctrl`+`=` and zoom out with `Ctrl`+`-`

The zoom level will be preserved between sessions.

**Comment by efuquen** [comment]
@raelgc ah that works just fine, definitely should have thought to try that.  Thanks!

**Comment by angrycamel** [comment]
+1 for hidpi support
found that ctrl+= doesn't work, but also found that shift+ctrl+= DOES work (!) - good workaround

**Comment by raelgc** [comment]
@angrycamel I'm using the default Qt shortcuts, and unfortunately, on Linux, zoom is `ctrl`+`=`.

So to get the `=`, you need to press `shit`+`+`. 

Then, to get the complete shortcut you need to press, like you noted, `ctrl`+`shift`+`=`.
