### ISSUE TITLE
scudcloud started dumping core

### ISSUE THREAD

**Issue by shevek** [raelgc/scudcloud#572]
## ScudCloud Version

Paste the output for `scudcloud --version` below:
```
ScudCloud 1.58
Python 3.5.2
Qt 5.5.1
PyQt 5.5.1
SIP 4.17
```

## Distro and Desktop info

  - Distribution: 
  - Version/Release:
  - Desktop environment:
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```
XFCE4

## Expected behavior

Does not crash

## Actual behavior

```
QThread: Destroyed while thread is still running
Segmentation fault (core dumped)
```

## Steps to reproduce
 1.  Dunno
 2.  Did you get the core via apport?
 3.  If not, I guess I'll hunt you one down.

**Comment by raelgc** [comment]
@shevek Can you check if you have another process with `scudcloud` running?

**Comment by shevek** [comment]
System crashed and rebooted since then. Will keep eyes open.

**Comment by raelgc** [comment]
In case this is back, re-open this issue, please.
