### ISSUE TITLE
Login through google account is broken

### ISSUE THREAD

**Issue by dtsallas** [raelgc/scudcloud#576]
## ScudCloud Version

Paste the output for `scudcloud --version` below:
ScudCloud 1.58
Python 3.5.2
Qt 5.5.1
PyQt 5.5.1
SIP 4.17

## Distro and Desktop info

  - Distribution: Ubuntu
  - Version/Release: 16.04
  - Desktop environment: Unity

## Expected behavior

Google password input field should be visible after username has been entered

## Actual behavior

Google password input field is not visible, login page is greyed out. If user attempts to reload page (right click on page -> Reload) then password input field is visible but an error page is served by Google after pressing Next.

## Steps to reproduce
 1. Attempt to login to a slack team using your Google account
![google_sign_in](https://cloud.githubusercontent.com/assets/1235988/26202054/a8fc5660-3bde-11e7-8a2e-a286023c3dc5.png)

 2. Enter username
![email_log_in](https://cloud.githubusercontent.com/assets/1235988/26202005/7674f6f2-3bde-11e7-97ff-2496f98dd1e0.png)

 3. Click "Next"

![password_input_fail](https://cloud.githubusercontent.com/assets/1235988/26202110/d252a8e8-3bde-11e7-8d6d-ad45156d6242.png)
![password_reload_fail](https://cloud.githubusercontent.com/assets/1235988/26202118/db849192-3bde-11e7-96b8-b0b6c1094df4.png)

**Comment by vectorsigma** [comment]
confirming on Fedora 25, scudcloud 1.55 and 1.58 google login flow is broken.  After removing all settings and trying to reset my account logins, I saw what OP saw.

May or may not be related to Google's new sign-in thing they wouldn't shut up about for months before it happened.  Also, not sure if OP has 2FA enabled for their account, but it's enabled for ours.

For me, been broken for a month, switched to "official" client just to get back to work and forgot to file a bug.

```
$ scudcloud --version
ScudCloud 1.58
Python 3.5.3
Qt 5.7.1
PyQt 5.7
SIP 4.18.1
```

**Comment by raelgc** [comment]
Thank you, guys.

Can you check if there are error messages in the webkit console? 

Start scudcloud with `scudcloud --debug=True &` and after it loads, right click, select `Inspect`. Maximize this new window and select the `Console` tab.

**Comment by dtsallas** [comment]
No luck with the console, once the google page loads the console goes blank no matter what actions I go through (username, password, reloading page). FWIW I'm attaching the output from the slack login page (one screen previous to loading the google login):

![screenshot from 2017-05-23 10-28-42](https://cloud.githubusercontent.com/assets/1235988/26343046/2a6a3aa6-3fa3-11e7-9f41-9ac3cee7ea3e.png)

I'm also using 2FA in case it's relevant.

**Comment by dtsallas** [comment]
Not sure if it's relevant but there's this webkit issue which might apply here: https://bugs.webkit.org/show_bug.cgi?id=171770

**Comment by raelgc** [comment]
Thank you @dtsallas, yes, totally related. ScudCloud doesn't have code to directly handle the Google auth process. We just rely on webkit.

**Comment by supertunaman** [comment]
Looks like the upstream fix was to [disable the Firefox UA string specifically for Google Apps](https://trac.webkit.org/changeset/216343/webkit/trunk/Source/WebCore/platform/UserAgentQuirks.cpp). This is unlikely to be backported to QtWebKit at any point, since there's quite a lag between upstream WebKit and QtWebKit (like, years).

I was able to get logged in by commenting out the USER_AGENT line in scudcloud/resources.py, signing in via Google, then closing the app, uncommenting the line, and relaunching. I will experiment with different user-agents later.

**Comment by raelgc** [comment]
@supertunaman Nice find! Let me know if switching to Chrome user agent will make this work again.

**Comment by supertunaman** [comment]
@raelgc PR submitted ☝️

**Comment by raelgc** [comment]
I'm just waiting for a new PR to get merged this night. Then I'll publish new version.

**Comment by raelgc** [comment]
Published for Ubuntu. Thank you all for reporting this and special thanks to @supertunaman to find a fix and submit a PR!
