### ISSUE TITLE
Drag and drop support

### ISSUE THREAD

**Issue by mcg** [raelgc/scudcloud#58]
Would love if you could drag/drop files as you can in the regular browser interface.

**Comment by raelgc** [comment]
Hi @mcg and thanks for reporting this issue.

Actually drag and drop works fine (under Unity on 14.04, not sure under other DEs).

Which one are you using?

**Comment by mcg** [comment]
Using Unity and strangely it works now. When I tried previously, instead of the Slack dialog I expected to see for the dropped image, the image replace Slack completely.  Will try to get it to fail again.

**Comment by raelgc** [comment]
@mcg Drop the file in the text input. I didn't test drop the file in any window area, but probably it'll behave like you said.

Sometimes, then the CPU got hanging during ScudCloud startup, ScudCloud JavaScript will not perform in time, so probably drop any file will perform like you said too.

**Comment by mcg** [comment]
I use Shutter for screen captures. If I do a capture, save and immediately try to drop the image into Scud, it renders the image instead of the drop. The URL is "file:///.... path to image". If I instead, close the capture screen in Shutter, reopen, then drop. It works.

**Comment by mcg** [comment]
I can't 100% reproduce this, feel free to close it.

**Comment by raelgc** [comment]
@mcg In case you find reproducible steps, please, feel free to re-open it :)
