### ISSUE TITLE
Segfault immediately after startup

### ISSUE THREAD

**Issue by Alveel** [raelgc/scudcloud#582]
## ScudCloud Version

```
ScudCloud 1.60
Python 3.6.1
Qt 5.9.0
PyQt 5.8.2
SIP 4.19.2
```

## Distro and Desktop info

  - Distribution: ArchLinux
  - Version/Release: latest
  - Desktop environment: none (i3wm)

## Expected behavior

scudcloud loads properly

## Actual behavior

As soon as it passes the loading message scudcloud crashes with
`[1]    1998 segmentation fault (core dumped)  scudcloud`

## Steps to reproduce
 1. start scudcloud
 2. ???
 3. crash

I wish I had more details but the error above is all I get, I can't find a log file in any of the scudcloud directories or a core file.

**Comment by raelgc** [comment]
Hi @Alveel and thanks for raising this.

Can you start scudcloud by the command line and paste here the output?

**Comment by Alveel** [comment]
@raelgc this is the full output.

```
alwyn@aristotle ~ % scudcloud
[1]    4965 segmentation fault (core dumped)  scudcloud
```

**Comment by raelgc** [comment]
I can see our Python version is different. Mine is 3.5.2. Wondering if this is the problem or any missing library in your system.

**Comment by Alveel** [comment]
Perhaps but a bit doubtful. The last update to my python package was in April, scudcloud just stopped working today.

In an update today the PyQt5 package and other Qt5 packages got updated though.

**Comment by raelgc** [comment]
Indeed, this is my output:

```
ScudCloud 1.60
Python 3.5.2
Qt 5.7.0
PyQt 5.7
SIP 4.18.1
```

**Comment by janikarki** [comment]
I am also affected by this issue since today or yesterday. Same exact `--version` output as @Alveel. Feel free to ask for additional information.

EDIT: I am also using Arch Linux.

**Comment by vsund** [comment]
Same for me, I'm on Arch (+i3) too. Same versions.

**Comment by TimoKramer** [comment]
Same for me. journalctl outputs:
[scudcloud_log.txt](https://github.com/raelgc/scudcloud/files/1065830/scudcloud_log.txt)
Scudcloud from arch repo and antergos repo have same behaviour
antergos/scudcloud 1.60-4
aur/scudcloud 2:1.60-1
Python 3.6.1
extra/python-pyqt5 5.8.2-3
extra/qt5-base 5.9.0-2

**Comment by raelgc** [comment]
Is there a way to downgrade pyqt5? This is really hard to debug as the output is only a segfault. Wondering if other pyqt5 apps were affected in Arch.

**Comment by janikarki** [comment]
I have two other pyqt5 apps and they seem to be working just fine.

**Comment by Alveel** [comment]
@raelgc I can potentially send a core dump so you can analyse it. I have no idea how to do so myself unfortunately. Or point me in the right direction to do so :)

**Comment by ghost** [comment]
I get a similar problem, but for me scudcloud windows hangs in blank state.
I tried to downgrade `python-qt5` to 5.7.3 and `python` to 3.5.2 successively. Then, I stumble upon the same problem:
```
[1]    12110 segmentation fault (core dumped)  scudcloud
```

**Comment by K5HV** [comment]
It seems that qt5 upgrade from 5.8.0 to 5.9.0 broke scudcloud. (Archlinux)
Downgrading Qt to older versions:
```
warning: downgrading package qt5-base (5.9.0-2 => 5.8.0-12)
warning: downgrading package qt5ct (0.33-2 => 0.33-1)
warning: downgrading package qt5-declarative (5.9.0-1 => 5.8.0-2)
warning: downgrading package qt5-location (5.9.0-1 => 5.8.0-1)
warning: downgrading package qt5-sensors (5.9.0-1 => 5.8.0-1)
warning: downgrading package qt5-svg (5.9.0-1 => 5.8.0-1)
warning: downgrading package qt5-webchannel (5.9.0-1 => 5.8.0-1)
warning: downgrading package qt5-webkit (5.9.0-1 => 5.8.0-3)
warning: downgrading package qt5-xmlpatterns (5.9.0-1 => 5.8.0-1)
warning: downgrading package pyqt5-common (5.8.2-3 => 5.8.2-2)
warning: downgrading package python-pyqt5 (5.8.2-3 => 5.8.2-2)
```
fixed the issue.

Before downgrade (non-working):
```
ScudCloud 1.60
Python 3.6.1
Qt 5.9.0
PyQt 5.8.2
SIP 4.19.2
```

After downgrade (working):
```
ScudCloud 1.60
Python 3.6.1
Qt 5.8.0
PyQt 5.8.2
SIP 4.19.2
```

**Comment by klemmster** [comment]
I'm seeing the same issue and have uploaded coredumpctl captured stacktraces here:
https://gist.github.com/klemmster/f13b1d0d87701020c9638bb3b5448ae6

(Also latest Arch)

**Comment by raelgc** [comment]
@K5HV Thank you for the workaround.

@klemmster It's a bit hard to debug a python segfault. The expected is a python stack with error, including the line error.

But, for some reason, python itself is breaking.

**Comment by schplat** [comment]
Hit on this as well.
```
ScudCloud 1.60
Python 3.6.1
Qt 5.9.0
PyQt 5.8.2
SIP 4.19.2
```
More info on the segfault:
```
[  548.390483] traps: scudcloud[1299] general protection ip:7f637f2f7d84 sp:7ffc52bb8ad0 error:0 in libQt5WebKit.so.5.9.0[7f637d6d3000+2384000]

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f637f2f7d84 in JSC::JSRopeString::resolveRope(JSC::ExecState*) const () from /usr/lib/libQt5WebKit.so.5

```

So scudcloud is definitely finding some breakage between 5.8 and 5.9

**Comment by raelgc** [comment]
Is there any distro using Qt 5.9 that I can easy install in virtualbox? So, maybe I can debug step by step on this until hit the crash.

**Comment by raelgc** [comment]
Anyway, like I commented in other webkit-qt5 issue: wondering if we should change to other web container, like Electron.

**Comment by schplat** [comment]
I'm running Arch.

Also, I'd really prefer to avoid electron.  I use scudcloud because it *doesn't* use electron.  Electron gets into being a huge memory hog, and has a large foot print.

**Comment by TimoKramer** [comment]
@raelgos I am using antergos, you can install it easily. Please don't switch to electron.

**Comment by raelgc** [comment]
@TimoKramer thanks for the tip! I'm installing Artegos in a VM now to check.

**Comment by kotelnik** [comment]
Since Arch upgrade of qt5-webkit package to version 5.212.0alpha2-1 (in official "extra" repository), scudcloud no longer crashes :).

**Comment by TimoKramer** [comment]
seems to be solved

**Comment by klemmster** [comment]
Same here. Since the update to 5.212.0alpha2-1 it's working again.
This ticket can most likely be closed.
Thanks for the extra effort to look into it anyway :)
