### ISSUE TITLE
Slack CSS is no more working on webkit 5.5.1 (default on Ubuntu 16.04)

### ISSUE THREAD

**Issue by shevek** [raelgc/scudcloud#584]
## ScudCloud Version

Paste the output for `scudcloud --version` below:
```
ScudCloud 1.60
Python 3.5.2
Qt 5.5.1
PyQt 5.5.1
SIP 4.17
```

## Distro and Desktop info

  - Distribution: Ubuntu
  - Version/Release: something recent
  - Desktop environment: xfce

## Expected behavior
It works

## Actual behavior
Rendering is completely AFU'd, ti's all white, the input box is at the top, the main screen is half off the bottom, ...

Affects all teams, all channels.

## Steps to reproduce
 1. Open scudcloud 
 2. 
 3.

**Comment by novalu** [comment]
Same here with these: `scudcloud --version`

```
ScudCloud 1.60
Python 3.5.2
Qt 5.6.1
PyQt 5.5.1
SIP 4.17
```

## Distro and desktop info

- Distribution: Kubuntu
- Version/Release: 16.04
- Desktop environment: KDE

![Fragment of screen](https://www.novaklukas.cz/files/scudcloud-bug.png)

**Comment by tadas-s** [comment]
Same here:

![selection_033](https://user-images.githubusercontent.com/840454/27122154-ce021bf8-50e1-11e7-9910-baecf1f8a212.png)

```
$ scudcloud --version
ScudCloud 1.60
Python 3.5.2
Qt 5.5.1
PyQt 5.5.1
SIP 4.17
```

**Comment by jbrocher** [comment]
Same here  : 
```
ScudCloud 1.60
Python 3.5.2
Qt 5.5.1
PyQt 5.5.1
SIP 4.17
```

![image](https://user-images.githubusercontent.com/16919118/27122864-445726a4-50ec-11e7-9164-7284d2eea873.png)

**Comment by raelgc** [comment]
Thank all for reporting this issue.

I remember a [similar issue](https://github.com/raelgc/scudcloud/issues/540) in the past. Usually this breaks other clients too, so they revert the change in some hours.

I restarted Scudcloud here, and I'm not seeing this issue.

Still an issue for you?

**Comment by phlegx** [comment]
@raelgc I just started scudcloud again and yes it is still an issue (or maybe an issue again) for me.

**Comment by jbrocher** [comment]
Still broken here too ! =/

**Comment by smunaut** [comment]
Still broken here too.

**Comment by hungry** [comment]
Still broken here as well.

**Comment by pfogel** [comment]
Same for me as well - broken after restarting.  Not sure if this is relevant but I applied some updates this morning before opening Scudcloud.  Yesterday everything was fine.  The updates were: 
```
Upgrade: libqt5test5:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+dfsg-16ubuntu7.5), libqt5dbus5:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+dfsg-16ubu
ntu7.5), libqt5sql5-sqlite:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+dfsg-16ubuntu7.5), libqt5widgets5:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+d
fsg-16ubuntu7.5), libqt5xml5:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+dfsg-16ubuntu7.5), libqt5printsupport5:amd64 (5.5.1+dfsg-16ubuntu7.2, 
5.5.1+dfsg-16ubuntu7.5), libqt5gui5:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+dfsg-16ubuntu7.5), libqt5core5a:amd64 (5.5.1+dfsg-16ubuntu7.2, 
5.5.1+dfsg-16ubuntu7.5), libqt5opengl5:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+dfsg-16ubuntu7.5), libqt5network5:amd64 (5.5.1+dfsg-16ubuntu
7.2, 5.5.1+dfsg-16ubuntu7.5), libqt5sql5:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+dfsg-16ubuntu7.5)
```

**Comment by guibueno** [comment]
Broken here too.

ScudCloud 1.54
Python 3.5.2
Qt 5.5.1
PyQt 5.5.1
SIP 4.17

**Comment by skelband** [comment]
Same here with 1.60 on Linux Mint.
All White, with the formatting all over the place.

**Comment by raelgc** [comment]
Hm, I think I've found the reason why it's not broken in my system: I've installed (to test) KDE Neon some days ago. So my `Qt` and `PyQt` was upgraded to 5.7.

**Comment by raelgc** [comment]
There is a package to update only the qt-webkit in Ubuntu 16.04: http://repo.paretje.be/pool/universe/q/qtwebkit-ng/libqt5webkit5_0.0.0+tp5-1~ubuntu16.04.1_amd64.deb

**Comment by guibueno** [comment]
It worked for me, @raelgc

**Comment by cajogos** [comment]
Yep, installing that package fixed it for me on Ubuntu 16.04 @raelgc

**Comment by raelgc** [comment]
I'll try get the source package and try to build it on Launchpad, in order to get everyone using the PPA receive it as automatic upgrade.

**Comment by raelgc** [comment]
Hm, this package has some deep Qt dependencies. Works fine with Ubuntu and Unity (and probably all other GTK desktop environments). But I'm wondering if, forcing the upgrade using the PPA can break Qt environments dependencies using other versions.

**Comment by raelgc** [comment]
Hm, finally I got able to build it for xenial-backports. Are you guys all in 16.04.2?

**Comment by n8willis** [comment]
Has anyone tried dropping in the qtwebkit update on Ubuntu 16.10?  Because this certainly is affecting my 16.10 system; I'm not super excited about the idea of plugging in a standalone .deb for a single package (too many bad memories of RPM hell), but if there's no other way and Slack isn't reverting the change ....

@raelgc — as implied, I at least am on 16.10 :)

**Comment by raelgc** [comment]
@n8willis What is great about the solution proposed package is it's only an update for qtwebkit.

You can find zesty version here: http://repo.paretje.be/pool/universe/q/qtwebkit-ng/libqt5webkit5_5.212.0-alpha-1~ubuntu17.04.1_amd64.deb

But I was not able to find a yakkety version.

Anyway, sometimes I wonder if we should change to an Electron base. Sure, more memory usage, but at least, an updated and more stable web container.

**Comment by vinsgithub** [comment]
thanks very much @raelgc . updating qt-webkit on my Ubuntu 16.04 fixed the problem.

**Comment by n8willis** [comment]
@raelgc I'm clear on what the proposed solution is; what I don't like is dropping in a single DEB acquired from outside the repository, because that has a tendency to interfere with smooth repo-based updates of dependent packages & libraries further down the line.

Are you saying there's no hope of it building for yakkety?

**Comment by raelgc** [comment]
@n8willis yeap, I suffered from bad packages in the past too.

There is no built package for yakkety, but I think I can install yakkety in a VM and build it using the sources.

**Comment by n8willis** [comment]
@raelgc Cool; happy to test it if it builds. A yakkety DEB is far preferable to a Xenial or Zesty one, that's for sure!

**Comment by tigerand** [comment]
this is really not a great solution.  the package for a particular release should be built against, and depend upon, libraries available for/from that release.  how could i have installed scudcloud package for xenial release when it should depend on libraries i don't have and aren't available?  the install should have failed with unmet dependencies.  having to download (and trust!) some arbitrary package off the web, then install it with `dpkg -i`, well, that's no way to go through life, son!  -from _Animal House_

**Comment by raelgc** [comment]
@tigerand To explain: Slack updated their internal CSS and webkit (the HTML engine Scudcloud uses) include in Xenial cannot handle this new CSS properly.

I'm pointing, for now, for a package that has builds for xenial and zeist. This package will update the webkit in your system.

I'm balancing the pros and cons about put it in the PPA. I'm afraid that, while I can fix Scudcloud for some users, I can break other systems relying in the same technology.

I'm totally open for other ideas.

**Comment by smunaut** [comment]
Upgrading to Qt 5.7.1 fixed it for me as well on Gentoo ( from Qt 5.6.x were it was broken ).

**Comment by skelband** [comment]
I can report that installing the DEB package does the trick for me on Linux Mint 18 (Sarah).
Many thanks.

**Comment by TragicWarrior** [comment]
@raelgc , Is there a suitable qtwebkit package for 16.04.2?  I see the one posted for 16.04.1 and 17.04.1.

**Comment by raelgc** [comment]
@TragicWarrior You can use it on 16.04.2 too.

**Comment by hajderr** [comment]
Same problem here on Debian Jessie. Not sure if it'd be wise for me to upgrade the Qt lib though.

**Comment by Richard-ES** [comment]
Solved the issue on Linux Mint 18.1 Serena (Ubuntu 16.1) by installing the 16.04 DEB package (!): http://repo.paretje.be/pool/universe/q/qtwebkit-ng/libqt5webkit5_0.0.0+tp5-1~ubuntu16.04.1_amd64.deb  Got a slightly odd message that implied I'd already installed it, but it worked!  Thanks to everyone who's been commenting on this as the "white screen" issue has been bugging me for a couple of weeks now.

**Comment by raelgc** [comment]
@Richard-ES Thanks for sharing that the package worked on Debian too. Maybe it'd be a good idea build it to the PPA.

**Comment by guillaumeparis2000** [comment]
@raelgc the package given by @Richard-ES doesn't work on Debian, it need more dependencies that doesn't exist in Debian.

**Comment by raelgc** [comment]
Dependencies are an issue for the long chain in qt-webkit. Wondering if we should try build a flatpak/snappy version of it.

**Comment by DanMossa** [comment]
The package given by @raelgc  worked for me on ubuntu 16.04

**Comment by raelgc** [comment]
Ok, finally I got able to create a source package for the updated webkit and upload it to the PPA. For those who didn't install the deb file, this will fix:

    sudo apt update && sudo apt dist-upgrade
