### ISSUE TITLE
ScudCloud takes 100% CPU when doing nothing

### ISSUE THREAD

**Issue by neokore** [raelgc/scudcloud#59]
After a pair of days using ScudCloud in my laptop I realized that it uses 100% of one of the CPU cores from the application start without doing nothing.
I'm logged into one team and I deleted the config file to restart from zero and tried again updating to v1.0.26, but I get the same behavior. 
Besides this bug, everything seems to work OK.

Here comes the log:

```
"sni-qt/9075" WARN  10:16:10.880 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
No bp log location saved, using default.
[000:000] Cpu: 6.58.9, x8, 3300Mhz, 11901MB
[000:000] Computer model: Not available
[000:000] Browser XEmbed support present: 1
[000:000] Browser toolkit is not Gtk2 (0).
[000:000] Using Xt toolkit
No bp log location saved, using default.
[000:000] Cpu: 6.58.9, x8, 3300Mhz, 11901MB
[000:000] Computer model: Not available

(npviewer.bin:9104): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(npviewer.bin:9104): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(npviewer.bin:9104): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(npviewer.bin:9104): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
openjdk version "1.8.0_40"
OpenJDK Runtime Environment (build 1.8.0_40-b25)
OpenJDK 64-Bit Server VM (build 25.40-b25, mixed mode)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
```

Cheers!

**Comment by raelgc** [comment]
Hi @neokore, thanks for reporting this issue!

Can you, please, as `sudo`, edit `/opt/scudcloud/lib/wrapper.py` file and comment the above line (line 19)?

`QWebSettings.globalSettings().setAttribute(QWebSettings.PluginsEnabled, True)`

Then close and start ScudCloud again.

**Comment by neokore** [comment]
This works, by now it uses no CPU, and features like native notifications works, but in-window Youtube videos player (not a problem for me by now).
I'll test if hangouts integration works, but it seems to be ok.

Thank you!

**Comment by raelgc** [comment]
Maybe I should disable browser plugins by default and enable them only if a command line options is passed.

**Comment by lalomartins** [comment]
@raelgc, I'm still getting tons of CPU usage, with the latest version :crying_cat_face: my laptop has been overheating the last few weeks, it started to bother me so I went checking and htop tells me it's ScudCloud's fault. I quit it and indeed it's not so hot anymore. (Although now with Slack running on Firefox, it's FF eating CPU, albeit less than ScudCloud. Maybe it's at least partially Slack's fault?)

**Comment by lalomartins** [comment]
oh and I don't think it's Flash, as I have that blocked by default on FF

**Comment by raelgc** [comment]
@lalomartins I noted some CPU usage in Slack too (browser or inside ScudCloud) when I browser in history, search in archives, etc.

**Comment by michaelherold** [comment]
I actually see less CPU usage in scudcloud than I do in Chromium. It's about 1.5% constant in scudcloud and 2.5% in Chromium.

@lalomartins Since you're having an issue with overheating, you could look into using Slack's IRC gateway with something like weechat as an alternative. It doesn't have the amount of integration, but it would save your overheating issue.
