### ISSUE TITLE
Hangs when starting

### ISSUE THREAD

**Issue by ghost** [raelgc/scudcloud#590]
## ScudCloud Version

```
ScudCloud 1.61
Python 3.6.1
Qt 5.9.1
PyQt 5.8.2
SIP 4.19.2
```

## Distro and Desktop info

  - Distribution: Archlinux
  - Desktop environment: GNOME on Xorg/Wayland

## Steps to reproduce
 1. Start scudcloud, from GNOME GUI or with CLI
 2. Scudcloud hangs
 3. Popup: “This app does not respond”

## More info

- On wayland it makes the entire desktop freeze.
- I have absolutely no logs or debug info at all, with `--debug 1` or in systemd journal
- I tried to remove all my config files : `rm -r ~/.config/scudcloud`. Before, GUI was totally blank. Now I get the slack login page, but it hangs anyway.
- It started with `QT 5.9`
- I tried to reinstall all the packages.
- Network is very stable and very fast.

**Comment by raelgc** [comment]
Hi @gui-don and thanks for reporting this. Please, check #582. This problem is caused due the qtwebkit upgrade not supporting Slack internal JS/CSS.

**Comment by ghost** [comment]
Hi @raelgc! Thank you for your scudcloud!

Actually, on #582 , I read that the update `qt5-webkit  5.212.0alpha2-1`  solved the issue for everyone. Not for me :/ I use `qt5-webkit 5.212.0alpha2-4`, but it still hangs.

I thought I did something wrong, that’s why I tried to clear the conf. Maybe I can clear some qt cache or something the like that could fix the problem?

**Comment by raelgc** [comment]
Thanks for the additional info, @gui-don. I just re-opened the issue.

**Comment by ghost** [comment]
I think I fixed the issue.
I guess scudcloud has use qutebrowser or at least the same dependencies than this soft.
So, according to this source: https://github.com/qutebrowser/qutebrowser/issues/357, the problem could be related to mozplugger.

If the lib is present in user directory, but package absent it makes scudcloud hangs. Maybe I installed the package and remove it afterwards. So I guess it’s a bug in one of the dependencies related to HTML rendering/web browsing stuff, making a test on the presence of the lib to determine if mozplugger is installed or not.

Anyway, either install `mozplugger` or make sure the lib is absent: `rm ~/.mozilla/plugins/mozplugger*.so` solved the issue.

**Comment by raelgc** [comment]
Thanks for sharing your resolution @gui-don.

You're right, `qutebrowser` uses the same web engine as Scudcloud, `qtwebkit`.
