### ISSUE TITLE
Mangled sidebar UI 

### ISSUE THREAD

**Issue by michaelmior** [raelgc/scudcloud#591]
## ScudCloud Version

Paste the output for `scudcloud --version` below:
``
ScudCloud 1.61
Python 3.5.2
Qt 5.5.1
PyQt 5.5.1
SIP 4.17

## Distro and Desktop info

  - Distribution: Ubuntu
  - Version/Release: 16.04.2 LTS
  - Desktop environment: MATE

## Expected behavior
Correct UI display

## Actual behavior
See screenshot below
![scudcloud](https://user-images.githubusercontent.com/82501/28022099-1dbdad8a-6558-11e7-9298-74c1f4538ac7.png)

## Steps to reproduce
 1. Start ScudCloud
 2. Log in to a channel

**Comment by raelgc** [comment]
Hi @michaelmior and thanks for raising this issue.

This is a duplicate of #584.

Default 16.04 included `webkit` is no more able to handle Slack internal CSS. You can upgrade it installing this package: http://repo.paretje.be/pool/universe/q/qtwebkit-ng/libqt5webkit5_0.0.0+tp5-1%7Eubuntu16.04.1_amd64.deb

**Comment by michaelmior** [comment]
Thanks for the quick reply and the fix! This does indeed solve my problem :)
