### ISSUE TITLE
Sign in with LDAP ID opens in browser instead of in the app

### ISSUE THREAD

**Issue by maciex** [raelgc/scudcloud#592]
## ScudCloud Version
```
$ scudcloud --version
ScudCloud 1.60
Python 3.6.2
Qt 5.7.1
PyQt 5.8.1
SIP 4.19.1
```

## Distro and Desktop info

  - Distribution: Fedora
  - Version/Release: 26
  - Desktop environment: KDE

## Expected behavior
When starting ScudCloud the login page is shown. When I click the "Sign in using LDAP/Single Sign On" link I'm redirected to the browser. This causes inability to use Slack.

## Actual behavior
When opening the "Sign in using LDAP/Single Sing On" the login page should be opened in the ScudCloud to allow proper login.

## Steps to reproduce
 1. Start ScudCloud
 2. Click "Sign in with 'LDAP ID'"
 3. Browser window (Firefox) opens with LDAP/Single Sign On login page.

**Comment by raelgc** [comment]
Hi @maciex and thanks for reporting this issue. 

Scudcloud has a filter of some URLs that should be handled internally. I'm guessing Slack has changed the Single Sign On URL again.

Can you give an example of the URL used in your case? (Of course, replace sensitive words).

**Comment by maciex** [comment]
The URL shown at the start is:
```
scudcloud --debug True
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
URL Changed: https://xxx.enterprise.slack.com/?redir=xxxredir%3D%252Fmessages
```

The URL to be clicked is:
`https://xxx.enterprise.slack.com/sso/saml/start?redir=%2Fr-t1239467270%3Fredir%3D%2Fmessages`

I opened a pull request with proposed regexp.

**Comment by pyrho** [comment]
Hi,

I'm afraid this issue is back, `https://MY_COMPANY.slack.com/sso/saml/start` is not intercepted by Scudcloud and opens my default browser instead.

Here's my version:

```
➜ scudcloud --version
ScudCloud 1.63
Python 3.5.2
Qt 5.5.1
WebKit 602.1
PyQt 5.5.1
SIP 4.17
```

**Comment by Opfour** [comment]
same here:
$ scudcloud --version
ScudCloud 1.65
Python 3.7.0
Qt 5.11.1
WebKit 602.1
PyQt 5.11.2
SIP 4.19.12

$ strace -e open scudcloud 
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile

login just spins
