### ISSUE TITLE
Fails to connect to Slack service.

### ISSUE THREAD

**Issue by skelband** [raelgc/scudcloud#598]
## ScudCloud Version
ScudCloud 1.63
Python 3.5.2
Qt 5.5.1
WebKit 602.1
PyQt 5.5.1
SIP 4.17

## Distro and Desktop info
  - Distribution: Linux Mint
  - Version/Release: 18.2 Sonya
  - Desktop environment: Mate

## Expected behavior
Scudcloud should connect to service

## Actual behavior
Just sits in a waiting to connect loop.

I'm finding that I cannot connect to the Slack service at all. 
On the same network with my Android phone using the official Slack client I can connect no problem.
Up until around yesterday morning it was fine.
The app starts, but just sits with the introductory screen and the rotating blue graphic but just sits there indefinitely.

Tried the usual exit/restart, rebooting etc.

**Comment by skelband** [comment]
Checked with wireshark and I can confirm that there is TLS activity between Scudcloud and Slack services. It just stops after a while.

**Comment by raelgc** [comment]
Hi @skelband and thanks for reporting this issue.

The problem: Slack changed their internal JS and the code is returning JS errors in webkit:

    TypeError: undefined is not an object (evaluating 'a.id')

We saw this some days ago, but then they reverted and it started to work few hours later.

I'll see if I can work in a workaround in this meanwhile.

**Comment by skelband** [comment]
Looks like it might be a duplicate of #594.

**Comment by raelgc** [comment]
Yes, it's 594 back.
