### ISSUE TITLE
hanging on startup "Loading..." displayed

### ISSUE THREAD

**Issue by omiday** [raelgc/scudcloud#599]
## ScudCloud Version

Paste the output for `scudcloud --version` below:
```
pc96 ~ $ scudcloud --version
ScudCloud 1.63
Python 3.5.4
Qt 5.7.1
WebKit 602.1
PyQt 5.7
SIP 4.18.1

```

## Distro and Desktop info

  - Distribution: Fedora
  - Version/Release: 25
  - Desktop environment: XFCE

## Expected behavior
Open up the main window.

## Actual behavior
_Loading..._ page is displayed.

Here's the debug output:
```
pc96 ~ $ scudcloud --debug DEBUG
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
URL Changed: https://its-au.slack.com/messages
```

## Note
Reports as recent as today are logged in #594 (closed).

**Comment by raelgc** [comment]
I've reopened #594.
