### ISSUE TITLE
[ubuntu16.04] Stuck at loading screen

### ISSUE THREAD

**Issue by dvdn** [raelgc/scudcloud#600]
## ScudCloud Version

Paste the output for `scudcloud --version` below:

ScudCloud 1.63
Python 3.5.2
Qt 5.5.1
WebKit 602.1
PyQt 5.5.1
SIP 4.17

## Distro and Desktop info

`4.10.0-33-generic // #37~16.04.1-Ubuntu // x86_64 GNU/Linux`

## Expected behavior

Pass the loading screen and see messages

## Actual behavior

Stuck at loading screen

## Steps to reproduce
 1. Install it
 2. Launch it

Presicions:
It worked flawlessly the first time after installation
Then I logged out / logged in, restart the app and it didn't work no more.
I already purged it, remove related home config files and reinstall = same behaviour.

Related to #335 #294 
Merci

( closed as it clones #594 )

**Comment by djdevin** [comment]
Same as #594 

Seems to be an issue with new Slack, I see the same in Fedora as well

**Comment by addisonday** [comment]
Same issue!
