### ISSUE TITLE
Add Ubuntu 17.10 repo

### ISSUE THREAD

**Issue by vide** [raelgc/scudcloud#604]
Since Ubuntu 17.10 is almost ready for release, could you add the `artful` repo?
And thanks for your awesome work with ScudCloud!

**Comment by raelgc** [comment]
Done! Thank you for the reminder.

Just out of curiosity: are you already using 17.10?

**Comment by vide** [comment]
Yes, and previously installed scudcloud (1.60-1) can't connect at all, I'll try to update now

**Comment by vide** [comment]
Ok, stilldoesn't work, hangs on the "motivational quotes" at startup. I'll open another dedicated issue @raelgc

**Comment by raelgc** [comment]
It's duplicate of #594

**Comment by raelgc** [comment]
I.e., the current webkit is not properly running the Slack internal JS.

**Comment by vide** [comment]
uops, sorry, I was too quick opening the issue. will close it. Thanks!
