### ISSUE TITLE
Scudcloud crashes on execution

### ISSUE THREAD

**Issue by kyputer** [raelgc/scudcloud#607]
## ScudCloud Version
`ScudCloud 1.63`
`Python 3.6.3`
`Qt 5.9.2`
`WebKit 602.1`
`PyQt 5.9.1`
`SIP 4.19.5`

## Distro and Desktop info

  - Distribution: Arch Linux x86_64
  - Version/Release: 4.13.12-1-ARCH
  - Desktop environment: bspwm

## Expected behavior
Expected to start app when executed

## Actual behavior
![Alt text](https://imgur.com/Jeoqp9W.jpg)

## Steps to reproduce
 1. Open terminal
 2. Run scudcloud

**Comment by colinappnovation** [comment]
I found that I needed to install qt5-webkit which is listed as an optional dependency of pacman -Si python-pyqt5. Hope that helps!

**Comment by kyputer** [comment]
@colinappnovation Thanks for your input and assistance. Both of these packages were installed prior to execution!

**Comment by Miskamyasa** [comment]
+1

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
*** Error in `/usr/bin/python': free(): invalid pointer: 0x00007fbc817d33c0 ***

**Comment by kyputer** [comment]
No longer happening since my update to 1.64. Now my issue is the same as #594
