### ISSUE TITLE
Group notifications

### ISSUE THREAD

**Issue by Exoth** [raelgc/scudcloud#61]
If I enable desktop notifications for some group, I get both balloons and taskbar application triangle highlight.
But I need only triangle highlights without balloons. Is there a way to do this?

**Comment by raelgc** [comment]
Hi @Exoth, how are you?

Unfortunately ScudCloud just follows Slack notification scheme: balloons for Slack desktop notifications (in this case, you enable desktop notifications for the group), and taskbar highlight for any new message.

So, probably you need to, inside Slack, edit the group notification to no throw a desktop notification for any new message.

**Comment by Exoth** [comment]
The problem is that if desktop notifications are disabled for new messages, I don't get taskbar highlight as well.

**Comment by raelgc** [comment]
@Exoth You'll get the taskbar wobbling and with a border, just not the message counter (which exists only for direct messages).

**Comment by Exoth** [comment]
Nope, I'm getting absolutely no indication on a new message from a group without desktop notifications enabled. May be some OS version specific bug? I'm using Ubuntu 14.04 at the moment.

**Comment by raelgc** [comment]
I'm using Ubuntu 14.04 with Unity too. Maybe if you start ScudCloud from the command line, you can see any issues printed in the terminal.

**Comment by Exoth** [comment]
Getting this:

```
(npviewer.bin:23981): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "unity-gtk-module"

(acroread:24004): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",
```

**Comment by raelgc** [comment]
Hm, this one can be the reason for lack of icon wobbling: `Gtk-Message: Failed to load module "unity-gtk-module"`.

**Comment by raelgc** [comment]
Had you try to remove standard packages from 14.04?

**Comment by Exoth** [comment]
I haven't removed any standard packages as far as I remember.
I've just tried to install some i386 versions of gtk related packages, and I don't have unity-gtk-module error anymore, but I still don't get the taskbar notification.
In two weeks I'll install Ubuntu 15.04. I'll tell you if I have the problem there.

**Comment by raelgc** [comment]
@Exoth Please, re-open if still an issue.
