### ISSUE TITLE
Error with install instructions in Debian

### ISSUE THREAD

**Issue by nikolas** [raelgc/scudcloud#611]
Hi,
In the third step for your debian install instructions, you have:
```
sudo sed -i "s/${DISTRIB_CODENAME}/trusty/g" /etc/apt/sources.list.d/rael-gc-scudcloud-${DISTRIB_CODENAME}.list
```
But when I run that command I get the error:
```
sed: can't read /etc/apt/sources.list.d/rael-gc-scudcloud-buster.list: No such file or directory
```

I'm on Debian testing (buster).

**Comment by Kaffiend** [comment]
i'm on debian stretch and have the same error.
Whats actually sitting there is not what the documentation suggests.
```
4 -rw-r--r-- 1 root root 570 Mar 13 19:28 rael-gc-ubuntu-scudcloud-bionic.list
4 -rw-r--r-- 1 root root 498 Mar 13 19:28 rael-gc-ubuntu-scudcloud-bionic.list.save
```
this is what was placed there for me on debain stretch.
replaceing the env variable from lsb-release manually with the filename part thats in there in this case `bionic` and continuing on with the rest the instructions fixed it for me.

**Comment by raelgc** [comment]
@Kaffiend I just published for Bionic.
