### ISSUE TITLE
Keybinding support

### ISSUE THREAD

**Issue by mcg** [raelgc/scudcloud#62]
It would be great if it could respect the DE's currently configured keybinding setup or at least be configurable. I have Unity configured for Emacs bindings, but in Scudcloud, it's using something else.

**Comment by raelgc** [comment]
Hi @mcg. I'm using the QT keybindings. You can read more about it here: http://pyqt.sourceforge.net/Docs/PyQt4/qkeysequence.html

If you have any idea better about how to support it, you're welcome to contribute :)

**Comment by raelgc** [comment]
One possible solution is to try to configure QT keybinding. There is a question in SuperUser: http://superuser.com/questions/171925/enable-emacs-like-keybindings-scheme-for-all-qt-applications
