### ISSUE TITLE
END-USER LICENSE AGREEMENT FOR MICROSOFT SOFTWARE

### ISSUE THREAD

**Issue by asdfghjz** [raelgc/scudcloud#626]
So, I started the instalation for this FLOSS project however it asked me to agree to the "END-USER LICENSE AGREEMENT FOR MICROSOFT SOFTWARE", I couldn't find much info on it but it appears to be a proprietary font license. Why is this here? Is it possible to install only FLOSS software?

**Comment by raelgc** [comment]
It's not for scudcloud itself, it's for the MS fonts installer package, due the text fonts used by Slack.
