### ISSUE TITLE
Feature request: option for default team at start

### ISSUE THREAD

**Issue by OlivierBondu** [raelgc/scudcloud#64]
I was part of a team that has been now deleted, however it keeps being my default team when starting scudcloud, is there a way around this ?

**Comment by raelgc** [comment]
Hi @OlivierBondu, thanks for reporting this issue.

Please, edit your `~/.scudcloud` file and change the team inside it. Then restart ScudCloud.

**Comment by chazmo03** [comment]
What is the difference between `~/.scudcloud` and `~/.config/scudcloud/scudcloud.cfg`?

**Comment by michaelherold** [comment]
`~/.scudcloud` was the old name of the configuration file. We relocated it in #78 and Rael's comment is from prior to that change.
