### ISSUE TITLE
Unformatted Notifications

### ISSUE THREAD

**Issue by someben** [raelgc/scudcloud#65]
The notifications that popup when a new message is sent are not formatted correctly. For example code blocks with back ticks (```) are not monospaced.

**Comment by raelgc** [comment]
Hi @someben and thanks for reporting this issue.

This is, unfortunately, a specification from desktop notifications (i.e., outside of ScudCloud scope).

[Canonical NotifyOSD](https://wiki.ubuntu.com/NotifyOSD#text) supports only plain text ("should not contain any extra formatting"), while [Gnome Desktop Notifications](https://developer.gnome.org/notification-spec/#markup) can handle simple HTML tags (while not specified which ones).

I.e., markup and emojis are not supported by them.
