### ISSUE TITLE
Restore windows when trying to run again

### ISSUE THREAD

**Issue by draganshadow** [raelgc/scudcloud#66]
When clicking Scudcloud shortcut again from desktop or dock like Cairodock an error appear "Scudcloud is already running".
It would be more useful to just open the existing window instead.

**Comment by raelgc** [comment]
Hi @draganshadow and thanks for reporting this issue.

Yes, that should be a more friendly behaviour. I'll mark this as an improvement.

**Comment by zerthimon** [comment]
+1

**Comment by danielsanfr** [comment]
+1

**Comment by raelgc** [comment]
Sadly, this appears to be no that trivial as I initially thought.

Anyway, I'm trying some solutions.

**Comment by draganshadow** [comment]
Thanks for having a look !

**Comment by maksymov** [comment]
:+1:

**Comment by rahidelvi** [comment]
:+1:

**Comment by jupazave** [comment]
:+1:

**Comment by alexander-jiang** [comment]
+1

**Comment by collinpeters** [comment]
+1

**Comment by dorian-marchal** [comment]
:+1:

**Comment by komakino** [comment]
+1

**Comment by fabriciofreitag** [comment]
+1

**Comment by raelgc** [comment]
Guys, this is already implemented in #49 , so, it sounds like a bug.

Which is the state when you close, and which is when you open the window?

**Comment by zerthimon** [comment]
This happens when "Close to tray" is enabled and the window is "closed" to tray.
Then, you try running ScudCloud from the launcher and get a pop up window saying "Another instahce of ScudCloud is already running". The expected behaviour would be restoring the window which was "closed" to tray.

**Comment by raelgc** [comment]
Oh, right, this behaviour is really weird. I need to check why Unity thinks the program is not running when the window is just hidden to tray (the other behaviour, avoid a duplicate instance is expected).

**Comment by raelgc** [comment]
Ok guys, FINALLY I've just committed a fix (which worked locally).

In the next days I'll be able to publish a new version with it.

Thank you for your patience!

**Comment by raelgc** [comment]
New version with fix released. Let me know if it doesn't work and re-open this issue in this case.

**Comment by mou55** [comment]
:+1:

**Comment by dorian-marchal** [comment]
Thanks :+1:

**Comment by raelgc** [comment]
Welcome and thank you guys for wait so long for this.

**Comment by zerthimon** [comment]
It works, great job Rael.
