### ISSUE TITLE
No sound (notifications, embedded YouTube)

### ISSUE THREAD

**Issue by JonathanHarford** [raelgc/scudcloud#68]
Mint 17.1 Cinnamon 64-bit
Scudcloud 1.0-26

When I have Mint's Sound > Applications window open and I preview the notification sound, "python3" gets added to the list briefly before disappearing.
![screenshot from 2015-04-15 17 05 14](https://cloud.githubusercontent.com/assets/3912650/7169254/c0ce0a4c-e391-11e4-88b0-02109aca3d78.jpg)

Sound in Firefox, Clementine, etc. is working without a problem.

**Comment by JonathanHarford** [comment]
Oh and I'm using libqtwebkit4 version 2.3.2-0ubuntu7.

**Comment by raelgc** [comment]
Hi @JonathanHarford and thanks for reporting this issue.

This is really odd. Maybe some dependency is missing in the package (and then this dependency is automatically installed on default Ubuntu with Unity).

**Comment by raelgc** [comment]
@JonathanHarford, just to double-check: is your system updated?

If yes, can you run ScudCloud from the command-line and check if errors are printed?

**Comment by JonathanHarford** [comment]
I generally keep it updated but just was invited by Mint to update it now.
I did so, and I've also been messing with the sound settings.

And now it works.

It's possible that switching from Analog Output/Built-In Audio to Analog
Output/Logitech USB Headset fixed it, though now switching back to the
former I can't get the computer to make any sound. I am puzzled, but
pleased that it's now working.

PS: Great application! If we'd never gotten it working it would definitely
not have been a dealbreaker!

**Comment by raelgc** [comment]
I'm glad it worked now!

Just to share the pain: I have a Logitech USB Headset too. Interesting as all operating systems doesn't handle very well a USB Headset :(
