### ISSUE TITLE
Ubuntu: Pop up the application window when using "Show" from scudcloud's tray icon.

### ISSUE THREAD

**Issue by zerthimon** [raelgc/scudcloud#69]
The current behaviour is to activate scudcloud's icon in unity launcher.

**Comment by raelgc** [comment]
Hi @zerthimon and thanks for reporting this issue.

But this is actually the current behaviour: you click in Show, and the window application is opened and focused. At least in 14.04.

Which Ubuntu version are you running?

**Comment by zerthimon** [comment]
Hi @raelgc !
I'm running Trusty 14.04

When scudcloud is running normally (app window behind other windows) and I choose "show" in tray icon - the window doesn't pop up on top, but instead the unity launcher icon shivers. When scudcloud is closed (to tray) - the icon in the unity launcher looks inactive; Then, when I choose "show" in tray icon - the unity launcher icon activates (like the program is running), however, the app window doesn't pop up so I have to click the launcher icon to pop up scudcloud.

**Comment by raelgc** [comment]
@zerthimon thank you for the detailed description, I think I found the reason.

Appears that you have marked the ScudCloud to be "locked" (always present) in the Unity Launcher. I'll test this today later.

**Comment by zerthimon** [comment]
@raelgc thanks a lot, that was the reason!
Unlocked from the launcher and it works well!

**Comment by raelgc** [comment]
@zerthimon I'll investigate later how I can fix this problem when the app is locked to the launcher :)

**Comment by raelgc** [comment]
This was fixed in the past.
