### ISSUE TITLE
key shortcut for close

### ISSUE THREAD

**Issue by richey-v** [raelgc/scudcloud#70]
I like the "Close to Tray" feature, but would like it better if ctrl-W was close, instead of quit, and maybe ctrl-Q was quit.

**Comment by JonathanHarford** [comment]
Yeah, I keep accidentally exiting.

**Comment by raelgc** [comment]
In the next package build, this will be fixed :)

**Comment by raelgc** [comment]
@richey-v and @JonathanHarford, I just updated ScudCloud version. Please, run a `sudo apt-get update && sudo apt-get upgrade` and let me know if it works now.

**Comment by richey-v** [comment]
Sent you a pull-request for a change that worked better for me.

**Comment by raelgc** [comment]
@richey-v Right, so, based in your PR, I just changed a bit the code, to display `Close` only when `Close to Tray` is enabled.

**Comment by richey-v** [comment]
Thanks!  I like your solution best.
