### ISSUE TITLE
Keeping settings in ~/.config

### ISSUE THREAD

**Issue by cdysthe** [raelgc/scudcloud#71]
Hi,

This is a minor issue, but it would be good if Scudcloud could keep it's setting(s) in the ~/.config directory like most Linux applications do these days. ~/.config/scudclould would be the obvious candidate.

**Comment by michaelherold** [comment]
:+1: I agree with this.

It should also be aware of conventions, like following the [XDG Base Directory Specifications](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).
