### ISSUE TITLE
Open posts & files within Scudcloud

### ISSUE THREAD

**Issue by ghost** [raelgc/scudcloud#74]
It would be great to have the ability to edit posts within Scudcloud and not be forced into an external browser for the following URL locations:

`https://FOO.slack.com/files/`
`https://FOO.slack.com/files/USER/POST_ID/POST_NAME/edit`

Is this possible?

(BTW, super fantastic app!! :+1: :heart: )

**Comment by raelgc** [comment]
Hi @xHN35RQ, thanks for reporting this issue!

Just to try to reproduce: in which link should I click to get this `/files/` and `edit` URL?

**Comment by ghost** [comment]
If I click the Up Arrow at left of chat box and then click "Create Post" I immediately get sent to external browser. The URL is:

`https://FOO.slack.com/files/create/post`

Once a post is created, it's inserted into the chat stream, along with a link to edit the existing post. That link is the `edit` url:

`https://foo.slack.com/files/USER/POST_ID/POST_NAME/edit`

This also applied to any PDF files uploaded. They fall under the `/files/` URL scheme.

However viewing an individual PDF routes you to `https://slack-files.com/`

**Comment by raelgc** [comment]
@immerrr Can you, please, address this in the same way you fixed #60?

**Comment by ghost** [comment]
I'm closing this because I don't mind jumping out to the web browser to manage files and posts. Keeping Scudcloud a chat-only app is fine with me, and someone else can work on work on adding files/posts support if they want it badly enough.
