### ISSUE TITLE
The icon in the tray bar is not shown correctly under KDE

### ISSUE THREAD

**Issue by xdmx** [raelgc/scudcloud#77]
I'm using Arch with the last version of KDE and Scudcloud, the icon in the tray bar is not violet but gray/almost invisible. It changes the color to blue when there are new messages (without showing the unread messages)

![tray](https://cloud.githubusercontent.com/assets/115298/7259173/d0d34f4a-e861-11e4-8727-81321c6e912d.png)

Also, when I click on it it's not shown in front but under other windows

**Comment by raelgc** [comment]
Hi @xdmx, thanks for reporting this issue.

Interesting. Is that KDE5? I need to test and investigate. Weird is that ScudCloud works fine in other Qt environments.

**Comment by xdmx** [comment]
Hi @raelgc, yes, it's KDE5.

I've temporally fixed the icon downloading the zip from github and moving the mono-light icons into /usr/share/icons/hicolor/scalable/apps/, although it'll surely break again at the next update, maybe it's some kind of condition that must be added in the pkgbuild file itself. A way to change the icon directly from Scudcloud would be nice though

**Comment by raelgc** [comment]
@xdmx Are you using Arch?

**Comment by xdmx** [comment]
Yes

**Comment by michaelherold** [comment]
I'm updating the PKGBUILD to the new tagged version later today. I'll make sure those icons are copied.

**Comment by michaelherold** [comment]
@xdmx I have updated the PKGBUILDs on the AUR so you should be able to use them in the future and have all the icon themes copied over.

**Comment by xdmx** [comment]
Thank you @michaelherold, I see that icons are now copied in their folders. Now I'm trying to figure out how I can change them to use mono-light instead of hicolor under kde... is it maybe a setting in the cfg file?
