### ISSUE TITLE
Cache images

### ISSUE THREAD

**Issue by xdmx** [raelgc/scudcloud#82]
I've noticed that when images are posted in a channel and you switch between them they are downloaded again every time.

Would it be possible to add a caching system in order to avoid to download the same images every time?

**Comment by raelgc** [comment]
Reminder to myself or someone with coding skills reading this: check if http://stackoverflow.com/a/24504840/1604312 will works.

**Comment by raelgc** [comment]
Please, upgrade and test. Re-open the issue if not fixed.

**Comment by xdmx** [comment]
Using v1.0.46 (Arch) I see that images are still loaded each time I switch channels

**Comment by raelgc** [comment]
@xdmx I've researched about this, and it's a behaviour from webkit, unfortunately.

**Comment by raelgc** [comment]
@xdmx I'm trying to fix this again. Please upgrade to `1.0.65` and test :)

**Comment by xdmx** [comment]
Hi Rael, I've ugraded to 1.0.67 and it seems that it's caching them, awesome!
