### ISSUE TITLE
Proposal: Restructure code so it's more Pythonic

### ISSUE THREAD

**Issue by michaelherold** [raelgc/scudcloud#85]
Currently, ScudCloud expects to be found in `/opt/scudcloud`, which makes testing changes difficult (i.e. you have to build and install your package with the changes before you can test). I'd like to propose that we restructure into a more standard Python format using setuptools so that we can start writing tests and make development a little easier.

I know this is a big change, so I wanted to propose it before getting started.

**Comment by raelgc** [comment]
I totally agree with this @michaelherold!

And it's my fault. I just started the project without know Python and QT. Totally amateur. I just learned the basics.

**Comment by stieg** [comment]
@michaelherold are you working on this?  I have started work on this myself at https://github.com/stieg/scudcloud/tree/the_python_way

**Comment by michaelherold** [comment]
@stieg Nope, I'm not. I switched over to using the default Slack client.

**Comment by stieg** [comment]
Ok.  Thanks.
