### ISSUE TITLE
Icon error message in syslog.

### ISSUE THREAD

**Issue by cdysthe** [raelgc/scudcloud#86]
Hi,

I'm gettign a long entry in my syslog with this content:

fication-/opt/scudcloud/resources/scudcloud.png' not present in theme'loading icon 'notification-/opt/scudcloud/resources/scudcloud.png' caused error: 'Icon 'notification-/opt/scudcloud/resources/scudcloud.png' not present in theme'loading icon 'notification-/opt/scudcloud/resources/scudcloud.png' caused error: 'Icon 'notification-/opt/scudcloud/resources/scudcloud.png' not present in theme'loading icon 'notification-notification-audio-volume-high' caused error: 'Icon 'notification-notification-audio-volume-high' not present in theme'loading icon 'notification-notification-audio-volume-medium' caused error: 'Icon 'notification-notification-audio-volume-medium' not present in theme'loading icon 'notification-notification-audio-volume-low' caused error: 'Icon 'notification-notification-audio-volume-low' not present in theme'loading icon 'notification-notification-audio-volume-muted' caused error: 'Icon 'notification-notification-audio-volume-muted' not present in theme'loading icon 'notification-/opt/scudcloud/resources/scudcloud.png' caused error: 'Icon 'notification-/opt/scudcloud/resources/scudcloud.png' not present in theme'loading icon 'notification-/opt/scudcloud/resources/scudcloud.png' caused error: 'Icon 'notification-/opt/scudcloud/resources/scudcloud.png' not present in theme'loading icon 'notification-/opt/scudcloud/resources/scudcloud.png' caused error: 'Icon 'notification-/opt/scudcloud/resources/scudcloud.png' not present in theme'loading icon 'notification-/opt/scudcloud/resources/scudcloud.png' caused error: 'Icon 'notification-/opt/scudcloud/resources/scudcloud.png' not present in theme'loading icon 'notification-/opt/scudcloud/resources/scudcloud.png' caused error: 'Icon 'notification-/opt/scudcloud/resources/scudcloud.png' not present in theme'loading icon 'notification-/opt/scudcloud/resources/scudcloud.png' caused error: 'Icon 'notification-/opt/scudcloud/resources/scudcloud.png' not present in theme'loading icon 'notification-/opt/scudcloud/resources/scudcloud.png' caused error: 'Icon 'notifi

It goes on like that.

**Comment by michaelherold** [comment]
What OS are you? Ubuntu? Arch? etc.

**Comment by cdysthe** [comment]
Hi,

I'm on Ubuntu 15.04 x64

On 04/27/2015 10:07 AM, Michael Herold wrote:

> What OS are you? Ubuntu? Arch? etc.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/raelgc/scudcloud/issues/86#issuecomment-96667220.

## 

//Christian

Dropbox. Your files from anywhere: http://db.tt/U8MqkVR

**Comment by raelgc** [comment]
This is related to the `png` file used in the notification. I still didn't try 15.04. Anyway, ScudCloud is using the full path to the image, so this should not raise an issue.

Can you check if the image is present in expected location? Please run:

```
ls -la /opt/scudcloud/resources/scudcloud.png
```

**Comment by raelgc** [comment]
@cdysthe Any news on that?

**Comment by cdysthe** [comment]
Sorry, been on the road! :) Yes, it's there in that location

**Comment by raelgc** [comment]
Hi @cdysthe, is this still an issue?
