### ISSUE TITLE
The user isn't kept online

### ISSUE THREAD

**Issue by xdmx** [raelgc/scudcloud#87]
I've noticed a weird bug, this the steps to reproduce:
- open scudcloud
- close/minimize it to the tray
- wait some time (1-2 hours, I haven't found out the exact amount of time, it may be less)
- check with _another_ user the connected users

At this point you'll see that the user connected from scudcloud is offline.
- click on the icon in the tray to open scudcloud

Now the user is back online.

The bug is that the user was put offline even if the client has always been open. I guess it's a behaviour from slack web that doesn't see any activity from the user and so it thinks he disconnected. A ping to slack every in a while may solve this.

(Arch Linux, KDE 15.04/5.2)

**Comment by raelgc** [comment]
Hi @xdmx and thanks for reporting this issue!

Can you check if we can see the same behaviour in Slack running inside the browser?

**Comment by xdmx** [comment]
Yes, it also happens using Slack from the browser (Firefox). I had it in another window, and it set me as offline, once I went back to it I was back online.

**Comment by raelgc** [comment]
@xdmx So, if that happens in browser, probably is the default Slack behaviour. And I think we should follow the KISS principle and do not mess with Slack original behaviours.

**Comment by xdmx** [comment]
This is the reply I got from Amy at Slack:

> Thanks for writing in about this! I'm afraid that this is expected behaviour rather than a bug, and is connected with the way we measure presence in the app.
> 
> With our OSX app, your presence and whether or not we set you as 'away' is determined by computer activity rather than activity within Slack itself. When using Slack in the browser however, that presence is still determined by your activity within Slack, rather than on the computer as a whole.
> 
> Slack will automatically mark you as 'away' after 30 minutes of inactivity within Slack so if you're not interacting with Slack in the browser as frequently as every 30 minutes, you'll be shown as 'away'.
> 
> I'm afraid that there's no way to change this 30 minute interval or prevent it from being triggered, though I'll share your message with the team!

It'd be nice having the same OSX behaviour (computer activity) on Scudcloud as well

**Comment by raelgc** [comment]
@xdmx Cool man, I really like you asked the Slack team about it! :)

Ok, now I'll need to dig in the Slack JavaScript code, probably there is a trigger to disable the auto away/disconnect.

Stay tuned!

**Comment by raelgc** [comment]
@xdmx Can you test this again? In the last couple of changes, I tried to make ScudCloud work more closely to the OSX client.

**Comment by xdmx** [comment]
I've just upgraded to v1.0.46 (under Arch), but it seems that I'm still put offline after few minutes even while I use the laptop with scudcloud minimized in the tray bar

**Comment by ofavre** [comment]
Under Debian, I become away if I don't use the window for 1h.
I'd very much need that my away status reflects the fact that my computer is locked or not, and hence stays online as long as my computer is not locked.

How may I help on that issue? Any pointers?

**Comment by raelgc** [comment]
@xdmx and @ofavre: sorry for my long response on this.

After deep diging in Slack JS, I found a way to keep user online.

Now I'm just wondering how to read system status. 

My first thought was to check lockScreen activity. But we have some distros without lockScreen.

Other alternative is to rely in `libxss` (and some Python bindings for it) to use `XScreenSaverAllocInfo` (which provides time info about last user activity time), which is not present by default too.
