### ISSUE TITLE
Trouble with authentication inside the app

### ISSUE THREAD

**Issue by jclebreton** [raelgc/scudcloud#88]
Hello,

I have some trouble with authentication (Okta) inside the app.
- When i click on "Sign in with Okta" inside the app, a new page is open in my browser (Firefox),
- I fill the fields correctly (Login / Password) and the authentication is done correctly
- But i'm authenticate only inside my browser, not in the app.

I have this problem since i have update my ubuntu with apt-get this morning.
One of my colleagues have the same issue..

Do you have an idea ?

Thanks.

**Comment by raelgc** [comment]
Hi @jclebreton and thank you for reporting this issue.

Can you tell me which is the URL that is opened in the browser when you click to Sign in with Okta?

To explain: ScudCloud try to delegate external URLs to default programs. So, for some cases, it's required to add some white listed URLs to the code. If you can tell me the URL format, we can add an exception.

**Comment by jclebreton** [comment]
Hi,
Thank you for your reply.
ScudCloud open this URL in first : https://sch-chat.slack.com/sso/saml/start
In a second time, there is an automatic redirection to : https://schibsted.okta.com/login/login.htm
Thank you in advance.

**Comment by raelgc** [comment]
@jclebreton I just updated ScudCloud version (Trusty is built in PPA, others are building now). Please, run a `sudo apt-get update && sudo apt-get upgrade` and let me know if it works now.

**Comment by jclebreton** [comment]
Hey,
It seems to work, many thanks for your help.
I'll foward this to my colleagues.
have a nice weekend
