### ISSUE TITLE
Release and tag v1.0.28

### ISSUE THREAD

**Issue by michaelherold** [raelgc/scudcloud#91]
It looks like you make a new Ubuntu version but didn't push a tag or release up to Github. The Arch package can't be updated until those are done.

Also, I just wanted to take the chance to say you're doing a great job keeping up with this!

**Comment by raelgc** [comment]
Sorry @michaelherold, I just released v1.0.28.

Thank you and really need to say thanks to you, to contribute code and keep the Arch package!
