### ISSUE TITLE
Edit message doesn't work

### ISSUE THREAD

**Issue by alashkin** [raelgc/scudcloud#96]
Hello,

It seems, with last update "edit message" stops working.
When I press appropriate button (cogwheel) menu doesn't appear. 

Ubuntu 15.04/Unity

**Comment by raelgc** [comment]
@alashkin Thank you for reporting this issue!
Indeed, this stopped to work. Let me investigate!

**Comment by raelgc** [comment]
As workaround, `arrow+up` is still editing the last message.

**Comment by alashkin** [comment]
Thanks! I didn't know about this shortcut.
(Sometimes I forget English and "edit" is quite important for me).
And, thanx for great project.

**Comment by raelgc** [comment]
@alashkin Same for me (I use Edit a lot of times). Really weird Edit stopped to work. I'm still investigating, anyway.

**Comment by alashkin** [comment]
It started to work :)
May be slack.com changed something?
Or I miss update?

**Comment by raelgc** [comment]
@alashkin Thank you for sharing this!

No updates: It stopped to work and started to work again from the Slack side!

Cool!
