### ISSUE TITLE
Icon stretched in system tray

### ISSUE THREAD

**Issue by simonwjackson** [raelgc/scudcloud#97]
I am in on Gnome 3.16

![screenshot from 2015-05-06 17-01-14](https://cloud.githubusercontent.com/assets/189379/7496075/623c4976-f412-11e4-9f07-bf3b48e97e33.png)

**Comment by raelgc** [comment]
Hi @simonwjackson and thank you for reporting this issue.

This is really odd. This icon is just a `22x22px` SVG file. Wondering if 3.16 systray icons should be not squared.

**Comment by simonwjackson** [comment]
I checked again and aparently its not a scudcloud issue.
It's a gnome extention that moves icons back to the system tray and distorts them
