### ISSUE TITLE
The /hangout doesn't send credentials correctly to the browser

### ISSUE THREAD

**Issue by marcottedan** [raelgc/scudcloud#98]
Hey!

If you type /hangout in the web application, it'll correctly create a Google Hangout and automatically logs you in on Slack. If you do the same thing within the app, the Google Hangout is created but the credentials seems to not be passed. You have to log on Slack manually (and in case you're linked your account through a SSO, credentials won't work).

So, this prevent people from easily using the /hangout feature from within the application.

**Comment by raelgc** [comment]
Hi @marcottedan, thank you for reporting this issue!

In fact, ScudCloud will just open the URL created by Slack. 

When you're logged in browser by SSO, you'll be automatically logged to your Google account. When you're logged in ScudCloud by SSO, same user will be not shared with browser.

Anyway, if you got already logged in the account used by SSO in the browser, in the first Hangout screen, there is a bottom link (tiny one) entitled "switch account". You can click on it and then select which logged Google account you'll use.
