### ISSUE TITLE
Can't sign in to correct team

### ISSUE THREAD

**Issue by ajkay** [raelgc/scudcloud#99]
I'm an idiot and I tried to sign in to a team that I was not a member of (due to similar team names). I don't have access to that team so log in fails, but I cannot see any link on screen to select a different team and only "Close to tray" and "Quit" file menu options are available. I've tried uninstalling/reinstalling scudcloud through software centre but this hasn't helped.

Any ideas if this is a bug or if I'm still being an idiot?

**Comment by ajkay** [comment]
I found a workaround but will leave this issue open for someone else to look at and see if it needs addressing.

I noticed I could right-click on the "Sign up on the home page" link and open the link within scudcloud. That then gave me the option to sign in to the correct team

**Comment by raelgc** [comment]
Hi @alankay82 and thanks for reporting this issue.

ScudCloud configs are stored at `~/.config/scudcloud/scudcloud.cfg`.

You can delete this file or run `sudo apt-get purge scudcloud`.
